unpackaged/main/default/objects/Order/fields/PF_Location_Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>PF_Location_Number_of_Days__c</fullName>
    <description>This field calculates the number of days that the container has been rent</description>
    <formula>(EndDate__c  -  StartDate__c)+1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location (Number of Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <formula>TEXT(SBQQ__Quote__r.Type_de_location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/OrderSelector.cls
/**
* @Version: 1.0
* @Author: Remz Grges
* -----------------------------------------------------------------------------------------------
* Description: Selector class where all query operations for orders should be stored in methods.
* Created: 27/08/2021
** -----------------------------------------------------------------------------------------------
*/
public with sharing class OrderSelector implements IOrderSelector{
    /**
     * @param orderIds: Id of the orders to query
     *
     * @return queried orders mapped by there ID
     */
    public Map<Id, Order> getOrdersByIds(Set<Id> orderIds) {
        Map<Id, Order> mapOrderById = new Map<Id, Order>([SELECT Id,
                OrderNumber,
                EffectiveDate,
                EndDate,
                Status,
                Type_de_location__c,
                PF_Location_Number_of_Days__c
        FROM Order WHERE Id IN: orderIds]);
        return mapOrderById;
    }
}