unpackaged/main/default/objects/Order/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <formula>TEXT(SalesArea__r.BusinessLine__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ligne de produit</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Code_NACE__c.field-meta.xml
<CustomField>
    <fullName>Code_NACE__c</fullName>
    <formula>Account__r.DB_Code_Activite_NACE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code NACE</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Last_Batch_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Update__c</fullName>
    <label>Last Batch Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/PFRegion__c.field-meta.xml
<CustomField>
    <fullName>PFRegion__c</fullName>
    <label>Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segmentation</label>
    <referenceTo>Segmentation__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>Vues_Commerciales_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Verified__c.field-meta.xml
<CustomField>
    <fullName>Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Segmentation__c/Segmentation__c.object-meta.xml
<CustomObject>
    <label>Segmentation</label>
    <nameField>
        <displayFormat>Segmentation N°{0000}</displayFormat>
        <label>Nom de Segmentation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Segmentation__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessLine</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Segmentation__c/fields/CodeNACE__c.field-meta.xml
<CustomField>
    <fullName>CodeNACE__c</fullName>
    <label>Code NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Segmentation__c/fields/Notation__c.field-meta.xml
<CustomField>
    <fullName>Notation__c</fullName>
    <label>Notation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/BusinessLine.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Containers</fullName>
    </customValue>
    <customValue>
        <fullName>Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Frigorifiques</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Secs</fullName>
    </customValue>
    <customValue>
        <fullName>Cession</fullName>
    </customValue>
    <customValue>
        <fullName>Vente</fullName>
        <isActive>false</isActive>
        <label>Vente</label>
    </customValue>
    <customValue>
        <fullName>Véhicules</fullName>
        <isActive>false</isActive>
        <label>Véhicules</label>
    </customValue>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SADSegmentationSyncBatch.cls
global class SADSegmentationSyncBatch implements Database.Batchable<sObject>, Database.Stateful 
{
    private Integer retryCount; 
    private String filterPaysRegionPF;

    // Constructeur prenant le nombre de tentatives en paramètre
    global SADSegmentationSyncBatch(Integer retryCount, String filterPaysRegionPF) 
    {
        this.retryCount = retryCount;
        this.filterPaysRegionPF = filterPaysRegionPF;
    }
     
	global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator([
            SELECT Id, BusinessLine__c, CodeNACE__c, Notation__c, RecordTypeId
            FROM Segmentation__c
        ]);
    } 
    
    global void execute(Database.BatchableContext BC, List<Segmentation__c> scope) 
   	{
         Map<String, SalesAreaData__c> segmentationMap = new Map<String, SalesAreaData__c>();
         if(filterPaysRegionPF!=null && filterPaysRegionPF!='')
         {
            // Construire une carte de CodeNACE__c pour chaque enregistrement SalesAreaData__c
            for(SalesAreaData__c sad : [SELECT Id, Segmentation__c, BusinessLine__c, Code_NACE__c, Last_Batch_Update__c, Verified__c FROM SalesAreaData__c where   Verified__c = false AND Code_NACE__c !='' AND PFRegion__c = :filterPaysRegionPF   Order By Last_Batch_Update__c ASC limit 10000]) 
            {
                segmentationMap.put(sad.Id, sad);
            } 
         }
        else
        {
            for(SalesAreaData__c sad : [SELECT Id, Segmentation__c, BusinessLine__c, Code_NACE__c, Last_Batch_Update__c, Verified__c FROM SalesAreaData__c where   Verified__c = false AND Code_NACE__c !=''   Order By Last_Batch_Update__c ASC limit 10000]) 
            {
                segmentationMap.put(sad.Id, sad);
            } 
        }
        Set<SalesAreaData__c> sadToUpdate = new Set<SalesAreaData__c>();
        //create a map that will hold the values of the list 
        map<id,SalesAreaData__c> accmap = new map<id,SalesAreaData__c>();
        
        for(String sadRecordId  : segmentationMap.keySet()) 
        {
            // Récupérer l'enregistrement SalesAreaData__c correspondant à l'ID
    		SalesAreaData__c sadRecord = segmentationMap.get(sadRecordId);
            for(Segmentation__c seg : scope) 
            {
                if(sadRecord.Code_NACE__c == seg.CodeNACE__c && sadRecord.BusinessLine__c == seg.BusinessLine__c)
                {
                    sadRecord.Segmentation__c = seg.Id;
                    sadRecord.Verified__c = true;
                }
                DateTime currentDateTime = System.now();
                String formattedDateTime = currentDateTime.format('yyyy-MM-dd HH:mm:ss');
                sadRecord.Last_Batch_Update__c = formattedDateTime;
                if (!sadToUpdate.contains(sadRecord)) 
                {
                    sadToUpdate.add(sadRecord);
                }
            }
        }
        
        // Mettre à jour les enregistrements SalesAreaData__c
        if(!sadToUpdate.isempty())
        {
        	accmap.putall((new List<SalesAreaData__c>( sadToUpdate )));
        }

        if(accmap.size()>0)
        {
        	update accmap.values();
        }
    }

    global void finish(Database.BatchableContext BC) 
    {
        // Vérifier s'il existe encore des enregistrements SalesAreaData__c avec Segmentation__c vide
        Integer sadCount = [SELECT COUNT() FROM SalesAreaData__c WHERE  Verified__c = false AND Code_NACE__c !='' ];
        if (sadCount > 0 && retryCount < 50 ) 
        { 
            // Augmenter le compteur de tentative
            retryCount++;
            // Relancer le batch avec une nouvelle plage de données
        	Database.executeBatch(new SADSegmentationSyncBatch(retryCount, filterPaysRegionPF), 50);
        	//Database.executeBatch(new SADSegmentationSyncBatch(), 50);
        }
        else 
        {
            InitUpdateSalesAreaTerritoryDataBatch batchInitUpdateSalesAreaTerritoryData =new InitUpdateSalesAreaTerritoryDataBatch(); 
 			Database.executeBatch(batchInitUpdateSalesAreaTerritoryData, 100);
            // Préparer et envoyer l'email
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {'helachboura@petitforestier.fr'}; 
            mail.setToAddresses(toAddresses);
            mail.setSubject('Batch Process Completed: SADSegmentationSyncBatch => Note globale du secteur');
            
            // Construire le corps de l'email
            String emailBody = 'The batch SADSegmentationSyncBatch has finished:\n\n';
    
            mail.setPlainTextBody(emailBody);
            
            // Envoyer l'email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}