unpackaged/main/default/objects/blng__Invoice__c/blng__Invoice__c.object-meta.xml
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__Invoice__c/fields/blng__Account__c.field-meta.xml
<CustomField>
    <fullName>blng__Account__c</fullName>
    <inlineHelpText>Rechercher dans le compte la facturation de cette facture.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>AccountInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/blng__Invoice__c/fields/Facture_Genere__c.field-meta.xml
<CustomField>
    <fullName>Facture_Genere__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facture Généré</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/blng__Invoice__c/fields/templateId__c.field-meta.xml
<CustomField>
    <fullName>templateId__c</fullName>
    <formula>&#39;a2D7T000000TN7SUAW&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>templateId</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GenDocInvoicesFromAccount.cls
public class GenDocInvoicesFromAccount {
	public Account acc { get; set; }
    public List<blng__Invoice__c> invoices { get; set; }
    public Boolean allDocsAlreadyGenerated { get; set; }
    public GenDocInvoicesFromAccount(ApexPages.StandardController stdController) {
        allDocsAlreadyGenerated=false;
        String id = ApexPages.currentPage().getParameters().get('id');
        invoices = [SELECT id,blng__Account__c,templateId__c,Facture_Genere__c   FROM blng__Invoice__c where blng__Account__c=:id];
        integer nombreTotalDesFactureGenere=0;
        for(blng__Invoice__c invoice:invoices){
            system.debug('before condition');
            if(invoice.Facture_Genere__c){
                nombreTotalDesFactureGenere++;
            }
        }
        if(nombreTotalDesFactureGenere==invoices.size()){
            allDocsAlreadyGenerated=true;
        }
    }
}