unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/EntretienToDownloadController_TEST.cls
@isTest
public class EntretienToDownloadController_TEST {


    // Test the success (200) case of the the Post request
    
	static testMethod void GetEntretienWithSuccess()
    {
        //Mock
        Test.setMock(HttpCalloutMock.class, new EntretienToDownloadMock_TEST(200));
        WSParametreRequete__c wspr = new WSParametreRequete__c(Name='WS_Param_011',
                                                                   EndPoint__c = 'https://api-test.petitforestier.fr/api/services/SFDC/IGLOOPDFCommunity/GetEntretien',
                                                                   Methode__c = 'POST',
                                                                   UserName__c = 'mdm_sfdc',
                                                                   MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                                   ContentType__c = 'application/json',
                                                                   ApplicationName__c = 'SFDC',
                                                                   Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr;
		PageReference pref = Page.EntretienToDownload;
        pref.getParameters().put('id','PF-88590/PF-88590_ETALSON_20190212_1449896');
        Test.setCurrentPage(pref);
        Test.startTest();
        EntretienToDownloadController Page1 = new EntretienToDownloadController();
        Page1.getDocument();
        Test.stopTest();
    }
    
    // Test the unsuccess (404 or other Status) case of the the Post request
    
    static testMethod void GetEntretienWithUnsuccess()
    {
        //Mock
		Test.setMock(HttpCalloutMock.class, new EntretienToDownloadMock_TEST(404));
		WSParametreRequete__c wspr = new WSParametreRequete__c(Name='WS_Param_011',
                                                                   EndPoint__c = 'https://api-test.petitforestier.fr/api/services/SFDC/IGLOOPDFCommunity/GetEntretien',
                                                                   Methode__c = 'POST',
                                                                   UserName__c = 'mdm_sfdc',
                                                                   MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                                   ContentType__c = 'application/json',
                                                                   ApplicationName__c = 'SFDC',
                                                                   Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr;
        PageReference pref = Page.EntretienToDownload;
        pref.getParameters().put('id','PF-88590/PF-88590_ETALSON_20190212_1449896');
        Test.setCurrentPage(pref);
        Test.startTest();
        EntretienToDownloadController Page2 = new EntretienToDownloadController();
        Page2.getDocument();
        Test.stopTest();
    }
}