unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CarteGriseToDownloadController_TEST.cls
@isTest
public class CarteGriseToDownloadController_TEST {

    // Test the success (200) case of the the GET request
    
	static testMethod void GetCarteGriseWithSuccess()
    {
        //Mock
        Test.setMock(HttpCalloutMock.class, new CarteGriseToDownloadMock_TEST(200));
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_008',
                                                                   EndPoint__c = 'https://api.petitforestier.fr/api/services/SFDC/IGLOOPDFCommunity/GetCarteGrise/',
                                                                   Methode__c = 'GET',
                                                                   UserName__c = 'mdm_sfdc',
                                                                   MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                                   ContentType__c = 'application/xml',
                                                                   ApplicationName__c = 'SFCD',
                                                                   Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr1;
		PageReference pref = Page.CarteGriseToDownload;
        pref.getParameters().put('id','PF-88590');
        Test.setCurrentPage(pref);
        Test.startTest();
        CarteGriseToDownloadController MyCon = new CarteGriseToDownloadController();
        MyCon.getDocument();
        Test.stopTest();
    }
    
    // Test the unsuccess (404 or other Status) case of the the GET request
    
    static testMethod void GetCarteGriseWithUnsuccess()
    {
        //Mock
		Test.setMock(HttpCalloutMock.class, new CarteGriseToDownloadMock_TEST(404));
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_008',
                                                                   EndPoint__c = 'https://api.petitforestier.fr/api/services/SFDC/IGLOOPDFCommunity/GetCarteGrise/',
                                                                   Methode__c = 'GET',
                                                                   UserName__c = 'mdm_sfdc',
                                                                   MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                                   ContentType__c = 'application/xml',
                                                                   ApplicationName__c = 'SFCD',
                                                                   Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr1;
        Test.startTest();
        CarteGriseToDownloadController MyCon = new CarteGriseToDownloadController();
        MyCon.getDocument();
        Test.stopTest();
    }
}