unpackaged/main/default/objects/Contract/fields/Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Extension_Date__c</fullName>
    <label>Date de prolongation</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity from which this Contract was created.</description>
    <inlineHelpText>L&#39;opportunité à partir de laquelle ce contrat a été créé.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Tech_RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>Tech_RenewedContract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tech field used by the batch quote renewer and triggered short contract renewer</description>
    <label>Renewed contract</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <label>Type de location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
            </value>
            <value>
                <fullName>PRG</fullName>
            </value>
            <value>
                <fullName>RNV</fullName>
            </value>
            <value>
                <fullName>SUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <formula>TEXT(SBQQ__PrimaryQuote__r.Type_de_location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
                <color>#0B6FCE</color>
                <label>NCT</label>
            </value>
            <value>
                <fullName>SUP</fullName>
                <color>#A845DC</color>
                <label>SUP</label>
            </value>
            <value>
                <fullName>RNV</fullName>
                <color>#E27001</color>
                <label>RNV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <label>Type de location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifie le devis des quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Type_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Courte Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Moyenne Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Longue Durée</fullName>
    </customValue>
    <description>Type de Location (CD, CMD, LD)</description>
    <masterLabel>Type Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/BatchQuoteRenewerProcessor.cls
/**
 * Created by 4C on 03/03/2022.
 */

global class BatchQuoteRenewerProcessor implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {

    //data for batch job by date
    public Date renewDate;
    //data for unique contract processing
    public String contractId;
    public String ctNumber;
    public String userId;

    global BatchQuoteRenewerProcessor(Date searchDate) {
        this.renewDate = searchDate;
    }

    global BatchQuoteRenewerProcessor() {
        this.renewDate = Date.today();
    }

    global BatchQuoteRenewerProcessor(String contractId, String ctNumber, String userId) {
        this.contractId = contractId;
        this.ctNumber = ctNumber;
        this.userId = userId;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('Batch Contract renew start');

        //Query to select contracts matching conditions with related records RT
        String query;

        for (Contract c : [
                SELECT Id,
                        ContractNumber,
                        StartDate,
                        ContractTerm,
                        EndDate
                FROM Contract
                WHERE Status <> 'Résilié'
                AND SBQQ__Opportunity__r.Type_de_Location__c = 'Longue durée'
                AND Tech_RenewedContract__c = FALSE]) {
            System.debug('contract found for check: ');
            System.debug(c);
        }

        //Can be used for a batch of contracts or a specific contract
        if (String.isBlank(contractId) && renewDate != null) {
            query = 'SELECT Id, ContractNumber, EndDate, Extension_Date__c, TypeOpportunite__c, ' +
                    'SBQQ__Opportunity__r.RecordTypeId, SBQQ__Quote__r.RecordTypeId, SBQQ__Quote__r.Type_de_location__c ' +
                    'FROM Contract WHERE EndDate = ' + String.valueOf(this.renewDate).substring(0, 10) +
                    ' AND Status <> \'Résilié\' AND SBQQ__Opportunity__r.Type_de_Location__c = \'Longue durée\' ' +
                    'AND Tech_RenewedContract__c = FALSE';
        } else if (String.isNotBlank(contractId)) {
            query = 'SELECT Id, ContractNumber, ownerId, EndDate, Extension_Date__c, TypeOpportunite__c, ' +
                    'SBQQ__Opportunity__r.RecordTypeId, SBQQ__Quote__r.RecordTypeId, SBQQ__Quote__r.Type_de_location__c ' +
                    'FROM Contract WHERE Id = \'' + this.contractId + '\'';
//                    ' AND Status <> \'Résilié\' AND SBQQ__Opportunity__r.Type_de_Location__c = \'Longue durée\' ' +
//                    'AND Tech_RenewedContract__c = FALSE';
        }

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Contract> scope) {
        System.debug('Batch Contract renew execute');

        QuoteRenewer.runRenewalCalloutAndScheduleEvent(scope, false);
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Batch Contract renew end');
    }

}