unpackaged/main/default/objects/Contract/fields/Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Extension_Date__c</fullName>
    <label>Date de prolongation</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity from which this Contract was created.</description>
    <inlineHelpText>L&#39;opportunité à partir de laquelle ce contrat a été créé.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin prévisionnelle</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SBQQ__RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
    <inlineHelpText>Contrat renouvelé par cette opportunité de renouvellement. Si les contrats sont cumulés dans cette opportunité, il pointe vers le contrat principal.</inlineHelpText>
    <label>Renewed Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>RenewalOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début prévisionnelle</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>End date for subscriptions in this group.</description>
    <inlineHelpText>Date de fin des abonnements dans ce groupe.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunité associée à ce devis.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Date de début des abonnements de ce devis.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Devis auquel ce groupe appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this group.</description>
    <inlineHelpText>Date de début des abonnements de ce groupe.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifie le devis des quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AddDays_Helper.cls
public class AddDays_Helper {

    public static Map<String, Date> addDays_Order(List<String> RecordIdsList) {
        Map<String, Date> OrderEndDates = new Map<String, Date>();
        List<Order> Orders = [SELECT Id, EndDate__c, StartDate__c, Opportunity.SBQQ__RenewedContract__r.Extension_Date__c, Opportunity.SBQQ__RenewedContract__r.EndDate FROM Order WHERE Id in :RecordIdsList];
        
        if(!Orders.isEmpty()) {
            for (Order ord : Orders) {
                if (ord.Opportunity != null &&
                    ord.Opportunity.SBQQ__RenewedContract__r != null &&
                    ord.Opportunity.SBQQ__RenewedContract__r.EndDate != null) {
                    
                    Date OrderStartDate = ord.Opportunity.SBQQ__RenewedContract__r.EndDate.addDays(1);
                    ord.StartDate__c = OrderStartDate;
                    ord.EndDate__c = ord.Opportunity.SBQQ__RenewedContract__r.Extension_Date__c;
                    OrderEndDates.put(String.valueOf(ord.EndDate__c), ord.EndDate__c);
                }
            }
            update Orders;
        }
        
        return OrderEndDates;
    }

    public static Map<String, Date> addDays_Contract(List<String> RecordIdsList) {
        Map<String, Date> ContractEndDates = new Map<String, Date>();
        List<Contract> Contracts = [SELECT Id, SBQQ__Opportunity__r.SBQQ__RenewedContract__r.EndDate, SBQQ__Opportunity__r.SBQQ__RenewedContract__r.Extension_Date__c, EndDate, StartDate FROM Contract WHERE Id in :RecordIdsList];
        
        if(!Contracts.isEmpty()) {
            for (Contract cont : Contracts) {
                if (cont.SBQQ__Opportunity__r != null &&
                    cont.SBQQ__Opportunity__r.SBQQ__RenewedContract__r != null &&
                    cont.SBQQ__Opportunity__r.SBQQ__RenewedContract__r.EndDate != null) {
                    
                    Date ContractStartDate = cont.SBQQ__Opportunity__r.SBQQ__RenewedContract__r.EndDate.addDays(1);
                    cont.StartDate = ContractStartDate;
                    cont.EndDate = cont.SBQQ__Opportunity__r.SBQQ__RenewedContract__r.Extension_Date__c;
                    ContractEndDates.put(String.valueOf(cont.Id), cont.EndDate);
                }
            }
            update Contracts;
        }
        
        return ContractEndDates;
    }

    public static Map<String, Date> addDays_QuoteLineGroup(List<String> RecordIdsList) {
        Map<String, Date> QuoteLineGroupEndDates = new Map<String, Date>();
        List<SBQQ__QuoteLineGroup__c> QuoteLineGroups = [SELECT Id, SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Extension_Date__c, SBQQ__StartDate__c, SBQQ__EndDate__c, SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.EndDate FROM SBQQ__QuoteLineGroup__c WHERE Id in :RecordIdsList];
        
        if(!QuoteLineGroups.isEmpty()) {
            for (SBQQ__QuoteLineGroup__c qlg : QuoteLineGroups) {
                if (qlg.SBQQ__Quote__r != null &&
                    qlg.SBQQ__Quote__r.SBQQ__Opportunity2__r != null &&
                    qlg.SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r != null &&
                    qlg.SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.EndDate != null) {
                    
                    Date QuoteLineGroupStartDate = qlg.SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.EndDate.addDays(1);
                    qlg.SBQQ__StartDate__c = QuoteLineGroupStartDate;
                    qlg.SBQQ__EndDate__c = qlg.SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Extension_Date__c;
                    QuoteLineGroupEndDates.put(String.valueOf(qlg.SBQQ__EndDate__c), qlg.SBQQ__EndDate__c);
                }
            }
            update QuoteLineGroups;
        }
        
        return QuoteLineGroupEndDates;
    }

    @InvocableMethod(label='Add Days Helper Class. Objects Available : Order, Contract and QuoteLineGroup' description='AddDays_Helper for Objects : Order, Contract and QuoteLineGroup' )
    public static void AddDaysHelper_FromFlow(List<FlowParams> FlowParams) {
    if (FlowParams != null && !FlowParams.isEmpty()) {
        FlowParams params = FlowParams[0];

        if (params.IsOrderAction) {
            if (params.RecordIdsList != null && !params.RecordIdsList.isEmpty()) {
                addDays_Order(params.RecordIdsList);
            }
        }

        if (params.IsContractAction) {
            if (params.RecordIdsList != null && !params.RecordIdsList.isEmpty()) {
                addDays_Contract(params.RecordIdsList);
            }
        }

        if (params.IsQuoteLineGroupAction) {
            if (params.RecordIdsList != null && !params.RecordIdsList.isEmpty()) {
                addDays_QuoteLineGroup(params.RecordIdsList);
            }
        }
    }
}


    public class FlowParams {
        @InvocableVariable(label='Record Ids List' description='Record Ids List' required=true)
        public List<String> RecordIdsList;

        @InvocableVariable(label='If (IsContractAction) => Value = TRUE' description='Object : Contract' required=true)
        public Boolean IsContractAction;

        @InvocableVariable(label='If (IsOrderAction) => Value = TRUE' description='Object : Order' required=true)
        public Boolean IsOrderAction;

        @InvocableVariable(label='If (IsQuoteLineGroupAction) => Value = TRUE' description='Object : QuoteLineGroup' required=true)
        public Boolean IsQuoteLineGroupAction;
    }
}