unpackaged/main/default/objects/Contract/fields/Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Extension_Date__c</fullName>
    <label>Date de prolongation</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity from which this Contract was created.</description>
    <inlineHelpText>L&#39;opportunité à partir de laquelle ce contrat a été créé.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <label>Type de location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin prévisionnelle</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SBQQ__RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract being renewed by this renewal opportunity. In case opportunity rolls up several contracts this points at the master contract.</description>
    <inlineHelpText>Contrat renouvelé par cette opportunité de renouvellement. Si les contrats sont cumulés dans cette opportunité, il pointe vers le contrat principal.</inlineHelpText>
    <label>Renewed Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>RenewalOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début prévisionnelle</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <formula>TEXT(SBQQ__PrimaryQuote__r.Type_de_location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <formula>TEXT(SBQQ__Quote__r.Type_de_location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Saved_Quote_Line_Groups__c.field-meta.xml
<CustomField>
    <fullName>Saved_Quote_Line_Groups__c</fullName>
    <label>Saved Quote Line Groups</label>
    <summaryForeignKey>SBQQ__QuoteLineGroup__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>End date for subscriptions in this group.</description>
    <inlineHelpText>Date de fin des abonnements dans ce groupe.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunité associée à ce devis.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Date de début des abonnements de ce devis.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <label>Type de location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Devis auquel ce groupe appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this group.</description>
    <inlineHelpText>Date de début des abonnements de ce groupe.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifie le devis des quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Type_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Courte Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Moyenne Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Longue Durée</fullName>
    </customValue>
    <description>Type de Location (CD, CMD, LD)</description>
    <masterLabel>Type Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AddDays_Helper_Test.cls
@isTest (seealldata=true)
public class AddDays_Helper_Test {

    static testMethod void doAddDays() {
        Contract c = [SELECT Id, SBQQ__Opportunity__r.SBQQ__RenewedContract__r.EndDate, SBQQ__Opportunity__r.SBQQ__RenewedContract__r.Extension_Date__c, EndDate, StartDate FROM Contract WHERE SBQQ__Quote__r.Saved_Quote_Line_Groups__c > 0 AND SBQQ__Opportunity__r.SBQQ__RenewedContract__r.EndDate != NULL AND SBQQ__Quote__r.Type_de_location__c = 'Longue Durée' LIMIT 1];
        Order orderRecord = [SELECT Id, EndDate__c, StartDate__c, Opportunity.SBQQ__RenewedContract__r.Extension_Date__c, Opportunity.SBQQ__RenewedContract__r.EndDate FROM Order WHERE SBQQ__Quote__r.Saved_Quote_Line_Groups__c > 0 AND Opportunity.SBQQ__RenewedContract__r.EndDate != NULL AND SBQQ__Quote__r.Type_de_location__c = 'Longue Durée' LIMIT 1];
        SBQQ__QuoteLineGroup__c quoteLineGroup = [SELECT Id, SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Extension_Date__c, SBQQ__StartDate__c, SBQQ__EndDate__c, SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.EndDate FROM SBQQ__QuoteLineGroup__c WHERE SBQQ__Quote__r.Saved_Quote_Line_Groups__c > 0 AND SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.EndDate != NULL AND SBQQ__EndDate__c != NULL AND SBQQ__Quote__r.Type_de_location__c = 'Longue Durée' LIMIT 1];
 
        Test.startTest();

        List<String> contractIds = new List<String>{c.Id};
        Map<String, Date> contractEndDates = AddDays_Helper.addDays_Contract(contractIds);
        System.assert(!contractEndDates.isEmpty(), 'Contract end dates map should not be empty');

        List<String> orderIds = new List<String>{orderRecord.Id};
        Map<String, Date> orderEndDates = AddDays_Helper.addDays_Order(orderIds);
        System.assert(!orderEndDates.isEmpty(), 'Order end dates map should not be empty');

        List<String> quoteLineGroupIds = new List<String>{quoteLineGroup.Id};
        Map<String, Date> quoteLineGroupEndDates = AddDays_Helper.addDays_QuoteLineGroup(quoteLineGroupIds);
        System.assert(!quoteLineGroupEndDates.isEmpty(), 'QuoteLineGroup end dates map should not be empty');

        AddDays_Helper.FlowParams params = new AddDays_Helper.FlowParams();
        params.IsOrderAction = true;
        params.RecordIdsList = new List<String>{orderRecord.Id};

        List<AddDays_Helper.FlowParams> paramsList = new List<AddDays_Helper.FlowParams>{params};

        AddDays_Helper.AddDaysHelper_FromFlow(paramsList);

        params.IsOrderAction = false;
        params.IsContractAction = true;
        params.RecordIdsList = new List<String>{c.Id};
        AddDays_Helper.AddDaysHelper_FromFlow(paramsList);

        params.IsContractAction = false;
        params.IsQuoteLineGroupAction = true;
        params.RecordIdsList = new List<String>{quoteLineGroup.Id};
        AddDays_Helper.AddDaysHelper_FromFlow(paramsList);

        Test.stopTest();
    }
}