unpackaged/main/default/objects/Contract/fields/MasterContract__c.field-meta.xml
<CustomField>
    <fullName>MasterContract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsMasterContract</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ContentDocumentLink_Trigger_Test.cls
@isTest
public class ContentDocumentLink_Trigger_Test {
	 static testmethod void testmethod1(){
        Test.startTest();
        Account accA =new Account(Name='Demo');
        insert accA ;       
        SBQQ__Quote__c Q = New SBQQ__Quote__c();
        insert Q;  
        Contract C =new Contract(MasterContract__c=true,SBQQ__Quote__c=q.id,status='Draft',StartDate=system.Today(),AccountId=accA.Id);
        insert C;
        ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        //content.LinkedEntityId=sub.id;
        content.origin = 'H';
        insert content;
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=c.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
               
        insert contentlink;
        List<ContentDocumentLink> myList=[SELECT id,(SELECT ContentDocumentId  FROM ContentDocumentLinks) FROM SBQQ__Quote__c ].ContentDocumentLinks;
        system.assertEquals(1, myList.size());
        Test.stopTest();
        
    }
}