unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/templateId__c.field-meta.xml
<CustomField>
    <fullName>templateId__c</fullName>
    <formula>&#39;a2D7T000000TN7NUAW&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>templateId</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/templateId__c.field-meta.xml
<CustomField>
    <fullName>templateId__c</fullName>
    <formula>&#39;a2D7T000000TN6tUAG&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>templateId</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GenDocContractsFromQuote.cls
public class GenDocContractsFromQuote {
    public SBQQ__Quote__c quote { get; set; }
    public List<Contract> contracts { get; set; }
    public GenDocContractsFromQuote(ApexPages.StandardController stdController) {
        String id = ApexPages.currentPage().getParameters().get('id');
        system.debug('params');
        system.debug(id);
        contracts = [SELECT id,templateId__c  FROM Contract where SBQQ__Quote__c=:id];
    }
}