unpackaged/main/default/objects/Base_produit__c/Base_produit__c.object-meta.xml
<CustomObject>
    <label>Base produit</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Numéro de Base produit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Base produits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Base_produit__c/fields/Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Catalogue__c</fullName>
    <label>Catalogue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Base_produit__c/fields/Code_Pays__c.field-meta.xml
<CustomField>
    <fullName>Code_Pays__c</fullName>
    <label>Code Pays</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Base_produit__c/fields/Code_PF__c.field-meta.xml
<CustomField>
    <fullName>Code_PF__c</fullName>
    <label>Code PF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Base_produit__c/fields/Modele__c.field-meta.xml
<CustomField>
    <fullName>Modele__c</fullName>
    <label>Modèle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DependentPicklistGenerator_TEST.cls
@isTest(SeeAllData=true)
public class DependentPicklistGenerator_TEST 
{
    public static testMethod void fetchRecords()
    {
        String QueryPart_01 = 'Select  Code_Pays__c, Catalogue__c, Code_PF__c, Standard__c, Marque__c, Modele__c from Base_produit__c  ';
        Test.startTest();
        DependentPicklistGenerator.getCatalogDependentValues(QueryPart_01, 'CodePaysParam', 'CatalogueParam', 'CodePFParam', 'StandardPFParam', 'MarqueParam', 'ModeleParam');
        DependentPicklistGenerator.getAllBaseProduitRecords();
        Test.stopTest();
    }
    
}