unpackaged/main/default/objects/blng__BillingRule__c/blng__BillingRule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__FinanceBook__c/blng__FinanceBook__c.object-meta.xml
<CustomObject>
    <label>Finance Book</label>
    <nameField>
        <label>Finance Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__GLRule__c/blng__GLRule__c.object-meta.xml
<CustomObject>
    <label>GL Rule</label>
    <nameField>
        <label>GL Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__LegalEntity__c/blng__LegalEntity__c.object-meta.xml
<CustomObject>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__RevenueDistributionMethod__c/blng__RevenueDistributionMethod__c.object-meta.xml
<CustomObject>
    <customHelpPage>blng__revenueDistributionHelp</customHelpPage>
    <label>Revenue Distribution Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Distribution Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__RevenueRecognitionRule__c/blng__RevenueRecognitionRule__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognition Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognition Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__TaxRule__c/blng__TaxRule__c.object-meta.xml
<CustomObject>
    <label>Tax Rule</label>
    <nameField>
        <label>Tax Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__UsageSummary__c/blng__UsageSummary__c.object-meta.xml
<CustomObject>
    <label>Usage Summary</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>Usage Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usage Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassWorkflowRules__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflowRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/InterruptionDate__c.field-meta.xml
<CustomField>
    <fullName>InterruptionDate__c</fullName>
    <label>Date d&#39;Interruption</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/TechTerminated__c.field-meta.xml
<CustomField>
    <fullName>TechTerminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TechRésilié</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/blng__BillingRule__c.field-meta.xml
<CustomField>
    <fullName>blng__BillingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Recherche dans la règle de facturation attribuée à ce produit de commande.</inlineHelpText>
    <label>Billing Rule</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>blng__BillingRule__c.blng__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>blng__BillingRule__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/blng__TaxRule__c.field-meta.xml
<CustomField>
    <fullName>blng__TaxRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Recherche dans la règle fiscale attribuée à ce produit de commande.</inlineHelpText>
    <label>Tax Rule</label>
    <referenceTo>blng__TaxRule__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>TaxRuleOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Réservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OrderItem/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line where this order product is created from.</description>
    <inlineHelpText>La ligne du devis à partir de laquelle ce produit commandé est créé.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objet réservation de containers avec leurs options respectives.</description>
    <label>Réservation</label>
    <nameField>
        <displayFormat>RESA - {0}</displayFormat>
        <label>Numéro de réservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Devis auquel cet élément de ligne appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Devis auquel ce groupe appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/PF_UsageProcessor_Test.cls
/**
 * Created by 4C on 17/03/2022.
 */

@IsTest
public with sharing class PF_UsageProcessor_Test {

    @TestSetup
    public static void setupTests() {
        Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
        MyBypass.BypassValidationRules__c = true;
        MyBypass.BypassWorkflowRules__c = true;
        insert MyBypass;

        Account acc = TestDataFactory.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        TestDataFactory.createFinancialCond(acc.Id);
        TestDataFactory.createContact('contactTest', acc.Id);

        // billing rules creation
        blng__BillingRule__c blngR = TestDataFactory.createBillingRule();
        blng__RevenueRecognitionRule__c revRecRul = TestDataFactory.createRevenueRecognitionRule();
        blng__LegalEntity__c legEnt =  TestDataFactory.createLegalEntity();
        blng__FinanceBook__c finBook = TestDataFactory.createFinanceBook(legEnt.Id);
        blng__GLRule__c glrul = TestDataFactory.createGlRule(legEnt.Id);
        blng__RevenueDistributionMethod__c distMet = TestDataFactory.createDistribMethod();
        TestDataFactory.createRevenueRecognitionTreatment(legEnt.Id, finBook.Id, revRecRul.Id, glrul.Id, distMet.Id, 0);

        // tax rule
        blng__TaxRule__c taxRule = TestDataFactory.createTaxRule();
        TestDataFactory.createTaxTreatment(legEnt.Id, taxRule.Id);

        //product creation (with billing rule)
        Product2 p = TestDataFactory.createProduct('CF10', true, 'CF10', 'tst', blngR.Id, revRecRul.Id, taxRule.Id);
        PricebookEntry pbe = TestDataFactory.createPricebookEntry(true, Test.getStandardPricebookId(), p.Id, 10.0);

//        Account acc = Utils_TestMethods.createAccount('Account1',null,null, Label.CPT_RecordTypeId_CompteClient);
        Opportunity opp = TestDataFactory.createOpportunity('opp1', acc.Id, null, Label.OPP_StageName_OpportuniteCreee, null, legEnt.Id);
        SBQQ__Quote__c quote = TestDataFactory.createCPQQuote(opp.Id, true, acc.Id, Date.today(), 12);
        SBQQ__QuoteLineGroup__c qlg = TestDataFactory.createQuotelineGroup(quote.Id, Date.today(), Date.today().addMonths(12));
        SBQQ__QuoteLine__c ql = TestDataFactory.createQuoteLine(quote.Id, p.Id, 1, pbe.Id, qlg.Id);
        Order order = TestDataFactory.createOrder(acc.Id, Date.today(), Date.today().addMonths(12), quote.Id, opp.Id);
        OrderItem orderPrd = TestDataFactory.createOrderProduct(order.Id, p.Id, acc.Id, Date.today(), Date.today().addMonths(12), legEnt.Id, blngR.Id, finBook.Id, glrul.Id, revRecRul.Id, ql.Id, pbe.Id);
        Reservation__c reserv = TestDataFactory.createTransportToClientReservation(order.Id, orderPrd.Id, System.today());

        //create contract
        Date startDate = Date.today().addMonths(-4);
        Date startOfMonth = Date.newInstance(Date.today().year(), Date.today().month(), 1);

        SBQQ.TriggerControl.disable();
        Contract ct = TestDataFactory.createContract(acc.Id, quote.Id, 'Draft', startDate, 4, startDate.addMonths(4).addDays(1), order.Id, opp.Id);
        SBQQ.TriggerControl.enable();
        TestDataFactory.createSubscription(ct.Id, p.Id, ql.Id, acc.Id);

        blng__UsageSummary__c us = new blng__UsageSummary__c();
        us.blng__Account__c = acc.Id;
        us.blng__Order__c = order.Id;
        us.blng__OrderProduct__c = orderPrd.Id;
        us.blng__SummaryStartDate__c = startOfMonth;
        us.blng__SummaryEndDate__c = Date.today();
        us.blng__AppliedUnitPrice__c = 10.0;
        us.blng__MatchingId__c = 'test';
        insert us;
    }


    @IsTest
    public static void testUsageSummaryLDShortMonth() {
        Order o = [SELECT Id FROM Order LIMIT 1];
        o.Status = Label.orderStatus_processed;
        update o;

        //o = [SELECT Id, status FROM Order where Id =: o.Id];

        //System.debug('o = ' + o);

        Test.startTest();

        PF_UsageProcessor pfus = new PF_UsageProcessor(o.Id);
        Database.executeBatch(pfus,10);

        Test.stopTest();
        List<blng__Usage__c> usages = [
                SELECT
                        Id,
                        blng__StartDateTime__c,
                        blng__EndDateTime__c,
                        blng__PreratedAmount__c,
                        blng__PreratedQuantity__c,
                        blng__Quantity__c
                FROM blng__Usage__c
        ];

        System.assert(!usages.isEmpty(), 'No usages found');
    }

    @IsTest
    public static void testUsageSummaryLDFullMonth() {
        Order o = [SELECT Id FROM Order LIMIT 1];
        o.Status = Label.orderStatus_processed;
        update o;

        Test.startTest();

        PF_UsageProcessor pfus = new PF_UsageProcessor(o.Id);
        Database.executeBatch(pfus,10);

        Test.stopTest();
        List<blng__Usage__c> usages = [
                SELECT
                        Id,
                        blng__StartDateTime__c,
                        blng__EndDateTime__c,
                        blng__PreratedAmount__c,
                        blng__PreratedQuantity__c,
                        blng__Quantity__c
                FROM blng__Usage__c
        ];

        System.assert(!usages.isEmpty(), 'No usages found');
    }

    @IsTest
    public static void testUsageSummaryLDMidMonth() {
//        Date endOfMonth = Date.newInstance(Date.today().addMonths(1).year(), Date.today().addMonths(1).month(), 1).addDays(-1);
        Order o = [SELECT Id, Status FROM Order LIMIT 1];
        o.Status = Label.orderStatus_processed;
        update o;

        Contract ct = [SELECT Id, InterruptionDate__c, Status FROM Contract LIMIT 1];
        ct.TechTerminated__c = true;
        ct.InterruptionDate__c = Date.today();
//        ct.InterruptionDate__c = endMiddleMonth;
        ct.Status = Label.contractStatus_Resilie;
        update ct;

        Test.startTest();

        PF_UsageProcessor pfus = new PF_UsageProcessor(o.Id);
        Database.executeBatch(pfus,10);

        Test.stopTest();
        List<blng__Usage__c> usages = [
                SELECT
                        Id,
                        blng__StartDateTime__c,
                        blng__EndDateTime__c,
                        blng__PreratedAmount__c,
                        blng__PreratedQuantity__c,
                        blng__Quantity__c
                FROM blng__Usage__c
        ];

        System.assert(!usages.isEmpty(), 'No usages found');
    }

    @IsTest
    public static void testInvocableProcessor() {
        Order o = [SELECT Id, Status FROM Order LIMIT 1];
        o.Status = Label.orderStatus_processed;
        update o;

        Test.startTest();

        List<Order> orders = new List<Order>{o};
        InvocablePF_UsageProcessor.UsageProcessorUniqueOrder(new List<List<Order>>{orders});

        Test.stopTest();

        List<blng__Usage__c> usages = [
                SELECT
                        Id,
                        blng__StartDateTime__c,
                        blng__EndDateTime__c,
                        blng__PreratedAmount__c,
                        blng__PreratedQuantity__c,
                        blng__Quantity__c
                FROM blng__Usage__c
        ];

        System.assert(!usages.isEmpty(), 'No usages found');
    }
}