unpackaged/main/default/objects/blng__BillingRule__c/blng__BillingRule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__FinanceBook__c/blng__FinanceBook__c.object-meta.xml
<CustomObject>
    <label>Finance Book</label>
    <nameField>
        <label>Finance Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__GLRule__c/blng__GLRule__c.object-meta.xml
<CustomObject>
    <label>GL Rule</label>
    <nameField>
        <label>GL Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__LegalEntity__c/blng__LegalEntity__c.object-meta.xml
<CustomObject>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__RevenueDistributionMethod__c/blng__RevenueDistributionMethod__c.object-meta.xml
<CustomObject>
    <customHelpPage>blng__revenueDistributionHelp</customHelpPage>
    <label>Revenue Distribution Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Distribution Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__RevenueRecognitionRule__c/blng__RevenueRecognitionRule__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognition Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognition Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__TaxRule__c/blng__TaxRule__c.object-meta.xml
<CustomObject>
    <label>Tax Rule</label>
    <nameField>
        <label>Tax Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassWorkflowRules__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflowRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Extension_Date__c</fullName>
    <label>Date de prolongation</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Tech_RenewedContract__c.field-meta.xml
<CustomField>
    <fullName>Tech_RenewedContract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tech field used by the batch quote renewer and triggered short contract renewer</description>
    <label>Renewed contract</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/ContractRenewerEvent__e/ContractRenewerEvent__e.object-meta.xml
<CustomObject>
    <description>Event used to manage renewed quotes status for order and contract creation.</description>
    <label>ContractRenewerEvent</label>
    <pluralLabel>ContractRenewerEvents</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ContractRenewerEvent__e/fields/contractsToNotify__c.field-meta.xml
<CustomField>
    <fullName>contractsToNotify__c</fullName>
    <label>contractsToNotify</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ContractRenewerEvent__e/fields/quoteContractIdsMap__c.field-meta.xml
<CustomField>
    <fullName>quoteContractIdsMap__c</fullName>
    <description>List of old contract ids associated to new quote ids</description>
    <label>quoteContractIdsMap</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ContractRenewerEvent__e/fields/quoteIds__c.field-meta.xml
<CustomField>
    <fullName>quoteIds__c</fullName>
    <description>List of quotes to approve</description>
    <label>quoteIds</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>End date for subscriptions in this group.</description>
    <inlineHelpText>Date de fin des abonnements dans ce groupe.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunité associée à ce devis.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Date de début des abonnements de ce devis.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Statut indiquant la position du devis dans son cycle de vie.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rapport de visite</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>In Review</fullName>
                <label>En Cours</label>
            </value>
            <value>
                <fullName>En Attente d&#39;approbation</fullName>
            </value>
            <value>
                <fullName>Approuvé</fullName>
            </value>
            <value>
                <fullName>Quote Sent</fullName>
                <label>Devis Envoyé</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <label>Devis Refusé</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Devis Signé</label>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft (No Product)</fullName>
                <label>Brouillon (sans produits)</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Annulé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Tech_After_Calculate__c.field-meta.xml
<CustomField>
    <fullName>Tech_After_Calculate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech After Calculate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Tech_approval_unlock__c.field-meta.xml
<CustomField>
    <fullName>Tech_approval_unlock__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech approval unlock</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date à laquelle le service représenté par cet élément de ligne se termine (s&#39;applique uniquement sur le produit est un abonnement).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Devis auquel cet élément de ligne appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>La date à laquelle l&#39;abonnement à ce produit commence.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Devis auquel ce groupe appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this group.</description>
    <inlineHelpText>Date de début des abonnements de ce groupe.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ContractRenewerEventTriggerTest.cls
/**
 * Created by 4C on 06/04/2022.
 */

@IsTest
public class ContractRenewerEventTriggerTest {

    @TestSetup
    public static void setupTests() {
        Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
        MyBypass.BypassValidationRules__c = true;
        MyBypass.BypassWorkflowRules__c = true;
        insert MyBypass;

        Account acc = TestDataFactory.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        TestDataFactory.createFinancialCond(acc.Id);
        TestDataFactory.createContact('contactTest', acc.Id);

        // billing rules creation
        // blng__BillingRule__c blngR = TestDataFactory.createBillingRule();
        blng__RevenueRecognitionRule__c revRecRul = TestDataFactory.createRevenueRecognitionRule();
        blng__LegalEntity__c legEnt =  TestDataFactory.createLegalEntity();
        blng__FinanceBook__c finBook = TestDataFactory.createFinanceBook(legEnt.Id);
        blng__GLRule__c glrul = TestDataFactory.createGlRule(legEnt.Id);
        blng__RevenueDistributionMethod__c distMet = TestDataFactory.createDistribMethod();
        TestDataFactory.createRevenueRecognitionTreatment(legEnt.Id, finBook.Id, revRecRul.Id, glrul.Id, distMet.Id, 0);

        // tax rule
        blng__TaxRule__c taxRule = TestDataFactory.createTaxRule();
        TestDataFactory.createTaxTreatment(legEnt.Id, taxRule.Id);

        //product creation (with billing rule)
        // Product2 p = TestDataFactory.createProduct('CF10', true, 'CF10', 'tst', blngR.Id, revRecRul.Id, taxRule.Id);
        // PricebookEntry pbe = TestDataFactory.createPricebookEntry(true, Test.getStandardPricebookId(), p.Id, 10.0);

        //opty & quote creation
        Opportunity opp = TestDataFactory.createOpportunity('opp1', acc.Id, null, Label.OPP_StageName_OpportuniteCreee, null, legEnt.Id);
        SBQQ__Quote__c quote = TestDataFactory.createCPQQuote(opp.Id, true, acc.Id, Date.today(), 12);
        // SBQQ__QuoteLineGroup__c qlg = TestDataFactory.createQuotelineGroup(quote.Id, Date.today(), Date.today().addMonths(12));
        // SBQQ__QuoteLine__c ql = TestDataFactory.createQuoteLine(quote.Id, p.Id, 1, pbe.Id, qlg.Id);

        //create order
        Order order = TestDataFactory.createOrder(acc.Id, Date.today(), Date.today().addMonths(12), quote.Id, opp.Id);
        // TestDataFactory.createOrderProduct(order.Id, p.Id, acc.Id, Date.today(), Date.today().addMonths(12), legEnt.Id, blngR.Id, finBook.Id, glrul.Id, revRecRul.Id, ql.Id, pbe.Id);

        SBQQ.TriggerControl.disable();
        //create contract
        Contract ct = TestDataFactory.createContract(acc.Id, quote.Id, 'Draft', Date.today(), 12, Date.today().addMonths(12).addDays(2), order.Id, opp.Id);
        SBQQ.TriggerControl.enable();
        // TestDataFactory.createSubscription(ct.Id, p.Id, ql.Id, acc.Id);
        Opportunity renewOpp = TestDataFactory.createOpportunity('renewOpp', acc.Id, null, Label.OPP_StageName_OpportuniteCreee, null, legEnt.Id);
        SBQQ__Quote__c renewQuote = TestDataFactory.createCPQQuote(renewOpp.Id, false, acc.Id, Date.today().addMonths(12), 12);
    }

    @IsTest
    public static void testEventContractDraft() {
        Opportunity op = [SELECT Id FROM Opportunity WHERE Name = 'renewOpp'];
        SBQQ__Quote__c q = [SELECT Id, Tech_After_Calculate__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c = :op.Id LIMIT 1];
        Contract c = [SELECT Id, Extension_Date__c FROM Contract LIMIT 1];

        q.Tech_After_Calculate__c = true;
        // q.Tech_approval_unlock__c = true;
        update q;

        Test.startTest();

        List<ContractRenewerEvent__e> events = new List<ContractRenewerEvent__e>();
        events.add(new ContractRenewerEvent__e(quoteIds__c = q.Id,
                quoteContractIdsMap__c = q.Id+'#'+c.Id,
                contractsToNotify__c = c.Id + '#' + Userinfo.getUserId()));
        List<Database.SaveResult> pubResults = EventBus.publish(events);

        Test.stopTest();
        q = [SELECT Id, SBQQ__Status__c, SBQQ__StartDate__c, SBQQ__EndDate__c FROM SBQQ__Quote__c WHERE Id = :q.Id];
        //System.assertEquals(c.Extension_Date__c, q.SBQQ__EndDate__c);
    }/* */

    @IsTest
    public static void testEventContractSent() {
        Opportunity op = [SELECT Id FROM Opportunity WHERE Name = 'renewOpp'];
        SBQQ__Quote__c q = [SELECT Id, Tech_After_Calculate__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c = :op.Id LIMIT 1];
        Contract c = [SELECT Id, Extension_Date__c FROM Contract LIMIT 1];

        q.Tech_After_Calculate__c = true;
        q.SBQQ__Status__c = 'Quote Sent';
        // q.Tech_approval_unlock__c = true;

        Test.startTest();
        update q;

        List<ContractRenewerEvent__e> events = new List<ContractRenewerEvent__e>();
        events.add(new ContractRenewerEvent__e(quoteIds__c = q.Id,
                quoteContractIdsMap__c = q.Id+'#'+c.Id,
                contractsToNotify__c = c.Id + '#' + Userinfo.getUserId()));
        List<Database.SaveResult> pubResults = EventBus.publish(events);

        Test.stopTest();
        c = [SELECT Id, Tech_RenewedContract__c, Extension_Date__c FROM Contract WHERE Id = :c.Id];
        System.assertEquals(true, c.Tech_RenewedContract__c);
    }/* */

    @IsTest
    public static void testUncalculated() {
        Opportunity op = [SELECT Id FROM Opportunity WHERE Name = 'renewOpp'];
        SBQQ__Quote__c q = [SELECT Id, Tech_After_Calculate__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c = :op.Id LIMIT 1];
        Contract c = [SELECT Id, Extension_Date__c FROM Contract LIMIT 1];

        Test.startTest();

        List<ContractRenewerEvent__e> events = new List<ContractRenewerEvent__e>();
        events.add(new ContractRenewerEvent__e(quoteIds__c = q.Id,
                quoteContractIdsMap__c = q.Id+'#'+c.Id,
                contractsToNotify__c = c.Id + '#' + Userinfo.getUserId()));
        List<Database.SaveResult> pubResults = EventBus.publish(events);

        Test.stopTest();
        q = [SELECT Id, SBQQ__Status__c, SBQQ__StartDate__c, SBQQ__EndDate__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c = :op.Id LIMIT 1];
        System.assertEquals(null, q.SBQQ__EndDate__c);
    }/* */
}