unpackaged/main/default/objects/MonitoringDB__c/MonitoringDB__c.object-meta.xml
<CustomObject>
    <label>Historique D&amp;B</label>
    <nameField>
        <displayFormat>Modif N-{00000}</displayFormat>
        <label>Nom de Monitoring - D&amp;B</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitoring - D&amp;B</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MonitoringDB__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Monitoring_D_B</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/MonitoringDB__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>Nom du Champ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MonitoringDB__c/fields/ModificationDate__c.field-meta.xml
<CustomField>
    <fullName>ModificationDate__c</fullName>
    <label>Date de Modification</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/MonitoringDB__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>Nouvelle Valeur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/MonitoringDB__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <label>Ancienne Valeur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MonitoringDBHandler.cls
public class MonitoringDBHandler {
    public static void handleUpdatedAccounts(Map<Id, Account> oldMap, Map<Id, Account> newMap) {
        List<MonitoringDB__c> monitoringRecords = new List<MonitoringDB__c>();
        List<MonitoringDB__c> monitoringRecordsToUpdate = new List<MonitoringDB__c>();
        Map<Id, Set<String>> accountToModifiedFields = new Map<Id, Set<String>>();
        
        // Vérifier chaque Account pour les champs modifiés et créer des MonitoringDB__c records
        for (Account newAcc : newMap.values()) {
            Account oldAcc = oldMap.get(newAcc.Id);
            Set<String> modifiedFields = new Set<String>();
            
            // Liste des champs à surveiller
            String fieldsToCheckStr = System.Label.MonitoringDB_Fields; 
    		List<String> fieldsToCheck = fieldsToCheckStr.split(',');
            
         for (String field : fieldsToCheck) {
    		if (newAcc.get(field) != oldAcc.get(field)) {
        		// Vérification du duplicata
       		 List<MonitoringDB__c> duplicates = [SELECT Id, Account__c, FieldName__c, OldValue__c, NewValue__c 
                                            FROM MonitoringDB__c 
                                            WHERE Account__c = :newAcc.Id 
                                            AND FieldName__c = :field 
                                            LIMIT 1];

        // Créer un nouvel enregistrement si aucun duplicata n'existe
        if (duplicates.isEmpty()) {
            monitoringRecords.add(new MonitoringDB__c(
                Account__c = newAcc.Id,
                FieldName__c = field,
                ModificationDate__c = System.now(),
                OldValue__c = String.valueOf(oldAcc.get(field)),
                NewValue__c = String.valueOf(newAcc.get(field))
            ));
            modifiedFields.add(field);
        } 
        // Mettre à jour le champ existant s'il existe un duplicata
        else {
            MonitoringDB__c duplicate = duplicates[0];
            duplicate.OldValue__c = String.valueOf(oldAcc.get(field));
            duplicate.NewValue__c = String.valueOf(newAcc.get(field));
            duplicate.ModificationDate__c = System.now();
            monitoringRecordsToUpdate.add(duplicate);
            modifiedFields.add(field);
        }
    }
}//End for
            
            if (!modifiedFields.isEmpty()) {
                accountToModifiedFields.put(newAcc.Id, modifiedFields);
            }
        }
        
        if (!monitoringRecords.isEmpty()) {
            insert monitoringRecords;
        }
        if(!monitoringRecordsToUpdate.isEmpty())
        {
            Update monitoringRecordsToUpdate;
        }
        
        // Envoi des e-mails après la création des enregistrements MonitoringDB__c
        if (!accountToModifiedFields.isEmpty()) {
            EmailDBManager.sendModificationEmails(accountToModifiedFields, oldMap, newMap);
        }
    }
    
    //GC
    public static void handleUpdatedAccountsGC(Map<Id, Account> oldMap, Map<Id, Account> newMap) {
        List<MonitoringDB__c> monitoringRecords = new List<MonitoringDB__c>();
        List<MonitoringDB__c> monitoringRecordsToUpdate = new List<MonitoringDB__c>();
        Map<Id, Set<String>> accountToModifiedFields = new Map<Id, Set<String>>();
        
        // Vérifier chaque Account pour les champs modifiés et créer des MonitoringDB__c records
        for (Account newAcc : newMap.values()) {
            Account oldAcc = oldMap.get(newAcc.Id);
            Set<String> modifiedFields = new Set<String>();
            
            // Liste des champs à surveiller
            String fieldsToCheckStr = System.Label.MonitoringDB_Fields_GC; 
    		List<String> fieldsToCheck = fieldsToCheckStr.split(',');
            
         for (String field : fieldsToCheck) {
    		if (newAcc.get(field) != oldAcc.get(field)) {
        		// Vérification du duplicata
       		 List<MonitoringDB__c> duplicates = [SELECT Id, Account__c, FieldName__c, OldValue__c, NewValue__c 
                                            FROM MonitoringDB__c 
                                            WHERE Account__c = :newAcc.Id 
                                            AND FieldName__c = :field 
                                            LIMIT 1];

        // Créer un nouvel enregistrement si aucun duplicata n'existe
        if (duplicates.isEmpty()) {
            monitoringRecords.add(new MonitoringDB__c(
                Account__c = newAcc.Id,
                FieldName__c = field,
                ModificationDate__c = System.now(),
                OldValue__c = String.valueOf(oldAcc.get(field)),
                NewValue__c = String.valueOf(newAcc.get(field))
            ));
            modifiedFields.add(field);
        } 
        // Mettre à jour le champ existant s'il existe un duplicata
        else {
            MonitoringDB__c duplicate = duplicates[0];
            duplicate.OldValue__c = String.valueOf(oldAcc.get(field));
            duplicate.NewValue__c = String.valueOf(newAcc.get(field));
            duplicate.ModificationDate__c = System.now();
            monitoringRecordsToUpdate.add(duplicate);
            modifiedFields.add(field);
        }
    }
}//End for
            
            if (!modifiedFields.isEmpty()) {
                accountToModifiedFields.put(newAcc.Id, modifiedFields);
            }
        }
        
        if (!monitoringRecords.isEmpty()) {
            insert monitoringRecords;
        }
        if(!monitoringRecordsToUpdate.isEmpty())
        {
            Update monitoringRecordsToUpdate;
        }
        
        // Envoi des e-mails après la création des enregistrements MonitoringDB__c
        //if (!accountToModifiedFields.isEmpty()) {
           // EmailDBManager.sendModificationEmails(accountToModifiedFields, oldMap, newMap);
       // }
    }
}