unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassWorkflowRules__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflowRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Extension_Date__c</fullName>
    <label>Date de prolongation</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity from which this Contract was created.</description>
    <inlineHelpText>L&#39;opportunité à partir de laquelle ce contrat a été créé.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
            </value>
            <value>
                <fullName>PRG</fullName>
            </value>
            <value>
                <fullName>RNV</fullName>
            </value>
            <value>
                <fullName>SUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
                <color>#0B6FCE</color>
                <label>NCT</label>
            </value>
            <value>
                <fullName>SUP</fullName>
                <color>#A845DC</color>
                <label>SUP</label>
            </value>
            <value>
                <fullName>RNV</fullName>
                <color>#E27001</color>
                <label>RNV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
            </value>
            <value>
                <fullName>PRG</fullName>
            </value>
            <value>
                <fullName>RNV</fullName>
            </value>
            <value>
                <fullName>SUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>End date for subscriptions in this group.</description>
    <inlineHelpText>Date de fin des abonnements dans ce groupe.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunité associée à ce devis.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Date de début des abonnements de ce devis.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date à laquelle le service représenté par cet élément de ligne se termine (s&#39;applique uniquement sur le produit est un abonnement).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Devis auquel cet élément de ligne appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>La date à laquelle l&#39;abonnement à ce produit commence.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Devis auquel ce groupe appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this group.</description>
    <inlineHelpText>Date de début des abonnements de ce groupe.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifie le devis des quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchQuoteRenewerTest.cls
/**
 * Created by 4C on 03/03/2022.
 */

@IsTest
global class BatchQuoteRenewerTest {

    @TestSetup
    public static void setupTests() {
        Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
        MyBypass.BypassValidationRules__c = true;
        MyBypass.BypassWorkflowRules__c = true;
        insert MyBypass;

        Account acc = TestDataFactory.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        TestDataFactory.createFinancialCond(acc.Id);
        TestDataFactory.createContact('contactTest', acc.Id);

        // billing rules creation
        blng__BillingRule__c blngR = TestDataFactory.createBillingRule();
        blng__RevenueRecognitionRule__c revRecRul = TestDataFactory.createRevenueRecognitionRule();
        blng__LegalEntity__c legEnt =  TestDataFactory.createLegalEntity();
        blng__FinanceBook__c finBook = TestDataFactory.createFinanceBook(legEnt.Id);
        blng__GLRule__c glrul = TestDataFactory.createGlRule(legEnt.Id);
        blng__RevenueDistributionMethod__c distMet = TestDataFactory.createDistribMethod();
        TestDataFactory.createRevenueRecognitionTreatment(legEnt.Id, finBook.Id, revRecRul.Id, glrul.Id, distMet.Id, 0);

        // tax rule
        blng__TaxRule__c taxRule = TestDataFactory.createTaxRule();
        TestDataFactory.createTaxTreatment(legEnt.Id, taxRule.Id);

        //product creation (with billing rule)
        Product2 p = TestDataFactory.createProduct('CF10', true, 'CF10', 'tst', blngR.Id, revRecRul.Id, taxRule.Id);
        PricebookEntry pbe = TestDataFactory.createPricebookEntry(true, Test.getStandardPricebookId(), p.Id, 10.0);

        //opty & quote creation
        Opportunity opp = TestDataFactory.createOpportunity('opp1', acc.Id, null, Label.OPP_StageName_OpportuniteCreee, null, legEnt.Id);
        SBQQ__Quote__c quote = TestDataFactory.createCPQQuote(opp.Id, true, acc.Id, Date.today(), 12);
        SBQQ__QuoteLineGroup__c qlg = TestDataFactory.createQuotelineGroup(quote.Id, Date.today(), Date.today().addMonths(12));
        SBQQ__QuoteLine__c ql = TestDataFactory.createQuoteLine(quote.Id, p.Id, 1, pbe.Id, qlg.Id);

        //create order
        Order order = TestDataFactory.createOrder(acc.Id, Date.today(), Date.today().addMonths(12), quote.Id, opp.Id);
        TestDataFactory.createOrderProduct(order.Id, p.Id, acc.Id, Date.today(), Date.today().addMonths(12), legEnt.Id, blngR.Id, finBook.Id, glrul.Id, revRecRul.Id, ql.Id, pbe.Id);

        //create contract
        Contract ct = TestDataFactory.createContract(acc.Id, quote.Id, 'Draft', Date.today(), 12, Date.today().addMonths(12).addDays(2), order.Id, opp.Id);
        TestDataFactory.createSubscription(ct.Id, p.Id, ql.Id, acc.Id);
    }

    @IsTest
    public static void testBatch() {
        Test.startTest();

        BatchQuoteRenewerProcessor qr = new BatchQuoteRenewerProcessor(Date.today().addMonths(12));
        Database.executeBatch(qr, 5);

        Test.stopTest();

        Contract ct = [
                SELECT
                        Id,
                        StartDate,
                        EndDate,
                        ContractTerm,
                        Extension_Date__c,
                        SBQQ__Opportunity__r.RecordTypeId,
                        SBQQ__Quote__r.RecordTypeId,
                        SBQQ__Quote__c
                FROM Contract LIMIT 1
        ];
        List<SBQQ__Quote__c> renewQuote = [
                SELECT Id,
                        SBQQ__Opportunity2__r.TypeOpportunite__c,
                        SBQQ__StartDate__c,
                        SBQQ__EndDate__c,
                        SBQQ__Status__c,
                        SBQQ__Ordered__c
                FROM SBQQ__Quote__c
                WHERE Id <> :ct.SBQQ__Quote__c
        ];
        System.assertNotEquals(null, renewQuote, 'Renewed quote not found');
        System.assert(!renewQuote.isEmpty(), 'Renewed quote not found');
        System.assertEquals(ct.EndDate.addDays(1), renewQuote.get(0).SBQQ__StartDate__c, 'Wrong start date');
//        System.assertEquals(ct.StartDate.addMonths(ct.ContractTerm), renewQuote.get(0).SBQQ__StartDate__c, 'Wrong start date');
    }

    @IsTest
    public static void testBatchDefault() {
        Test.startTest();

        BatchQuoteRenewerProcessor qr = new BatchQuoteRenewerProcessor();
        Database.executeBatch(qr, 5);

        Test.stopTest();
    }

    @IsTest
    public static void testBatchPreprocessor() {
        Test.startTest();

        BatchQuoteRenewerPreprocessor qr = new BatchQuoteRenewerPreprocessor(Date.today().addMonths(12));
        Database.executeBatch(qr, 5);

        Test.stopTest();

        Contract ct = [
                SELECT
                        Id,
                        EndDate,
                        Extension_Date__c,
                        SBQQ__Opportunity__r.RecordTypeId,
                        SBQQ__Quote__r.RecordTypeId,
                        SBQQ__Quote__c,
                        TypeOpportunite__c
                FROM Contract LIMIT 1
        ];

        System.assertEquals('PRG', ct.TypeOpportunite__c, 'Contract opp type not updated');
    }

    @IsTest
    public static void testBatchPreprocessorDefault() {
        Test.startTest();

        BatchQuoteRenewerPreprocessor qr = new BatchQuoteRenewerPreprocessor();
        Database.executeBatch(qr, 5);

        Test.stopTest();
    }

    @IsTest
    public static void testBatchPreprocessorContract() {
        Contract ct = [SELECT Id FROM Contract LIMIT 1];
        Test.startTest();

        BatchQuoteRenewerPreprocessor qr = new BatchQuoteRenewerPreprocessor(ct.Id, 'ABC', UserInfo.getUserId());
        Database.executeBatch(qr, 5);

        Test.stopTest();

        ct = [
                SELECT
                        Id,
                        EndDate,
                        Extension_Date__c,
                        SBQQ__Opportunity__r.RecordTypeId,
                        SBQQ__Quote__r.RecordTypeId,
                        SBQQ__Quote__c,
                        TypeOpportunite__c
                FROM Contract LIMIT 1
        ];

        System.assertEquals('PRG', ct.TypeOpportunite__c, 'Contract opp type not updated');
    }

    @IsTest
    private static void testScheduler() {
        String CRON_EXP = '0 0 0 ' + Date.today().addMonths(1).day() + ' ' + Date.today().addMonths(1).month() +' ? ' + Date.today().year();
        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest', CRON_EXP, new BatchQuoteRenewerScheduler());
        Test.stopTest();

        CronTrigger trig = [SELECT Id, CronExpression, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals(CRON_EXP, trig.CronExpression);
        System.assertEquals(Datetime.newInstance(Date.today().addMonths(1), Time.newInstance(0,0,0,0)), trig.NextFireTime);
    }

    @IsTest
    private static void testTestBatch() {
        Contract ct = [SELECT Id, ContractNumber FROM Contract LIMIT 1];

        Test.startTest();

        List<Contract> insideList = new List<Contract> {ct};
        List<List<Contract>> lst = new List<List<Contract>> {insideList};
        BatchQuoteRenewerTestAction.testBatchQuoteRenewerUnitary(lst);

        Test.stopTest();

        ct = [SELECT Id, TypeOpportunite__c FROM Contract WHERE Id = :ct.Id];

        System.assertEquals('PRG', ct.TypeOpportunite__c);
    }

    @IsTest
    public static void testBatchContract() {
        Contract ct = [SELECT Id FROM Contract LIMIT 1];
        Test.startTest();

        BatchQuoteRenewerProcessor qr = new BatchQuoteRenewerProcessor(ct.Id, 'ABC', UserInfo.getUserId());
        Database.executeBatch(qr, 5);

        Test.stopTest();

        ct = [
                SELECT
                        Id,
                        EndDate,
                        Extension_Date__c,
                        SBQQ__Opportunity__r.RecordTypeId,
                        SBQQ__Quote__r.RecordTypeId,
                        SBQQ__Quote__c
                FROM Contract LIMIT 1
        ];
        List<SBQQ__Quote__c> renewQuote = [
                SELECT Id,
                        SBQQ__Opportunity2__r.TypeOpportunite__c,
                        SBQQ__StartDate__c,
                        SBQQ__EndDate__c,
                        SBQQ__Status__c,
                        SBQQ__Ordered__c
                FROM SBQQ__Quote__c
                WHERE Id <> :ct.SBQQ__Quote__c
        ];
        System.assertNotEquals(null, renewQuote, 'Renewed quote not found');
        System.assert(!renewQuote.isEmpty(), 'Renewed quote not found');
        System.assertEquals(ct.EndDate.addDays(1), renewQuote.get(0).SBQQ__StartDate__c, 'Wrong start date');
    }

}