unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassWorkflowRules__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflowRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Extension_Date__c</fullName>
    <label>Date de prolongation</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity from which this Contract was created.</description>
    <inlineHelpText>L&#39;opportunité à partir de laquelle ce contrat a été créé.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <label>Type de location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
            </value>
            <value>
                <fullName>PRG</fullName>
            </value>
            <value>
                <fullName>RNV</fullName>
            </value>
            <value>
                <fullName>SUP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/SBQQ__Ordered__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Internal flag that drives automatic order creation.</description>
    <inlineHelpText>Sélectionnez cette case pour créer automatiquement une commande à partir du devis principal.</inlineHelpText>
    <label>Ordered</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <formula>TEXT(SBQQ__PrimaryQuote__r.Type_de_location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <formula>TEXT(SBQQ__Quote__r.Type_de_location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Type_de_Location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_Location__c</fullName>
    <label>Type de Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunité associée à ce devis.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Ordered__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Internal flag to drive automatic order creation.</description>
    <inlineHelpText>Sélectionnez cette case pour créer automatiquement une commande à partir de ce devis, s&#39;il s&#39;agit d&#39;un devis principal.</inlineHelpText>
    <label>Ordered</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Statut indiquant la position du devis dans son cycle de vie.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rapport de visite</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>In Review</fullName>
                <label>En Cours</label>
            </value>
            <value>
                <fullName>En Attente d&#39;approbation</fullName>
            </value>
            <value>
                <fullName>Approuvé</fullName>
            </value>
            <value>
                <fullName>Quote Sent</fullName>
                <label>Devis Envoyé</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <label>Devis Refusé</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Devis Signé</label>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft (No Product)</fullName>
                <label>Brouillon (sans produits)</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <label>Annulé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <label>Type de location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Devis auquel cet élément de ligne appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <label>Type de location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Devis auquel ce groupe appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__SubscribedQuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the quote for the quoteLines.</description>
    <inlineHelpText>Identifie le devis des quoteLines.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Type_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Courte Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Moyenne Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Longue Durée</fullName>
    </customValue>
    <description>Type de Location (CD, CMD, LD)</description>
    <masterLabel>Type Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/QuoteRenewerTest.cls
/**
 * Created by 4C on 01/03/2022.
 */
@IsTest
public class QuoteRenewerTest {

    @TestSetup
    public static void setupTests() {
        Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
        MyBypass.BypassValidationRules__c = true;
        MyBypass.BypassWorkflowRules__c = true;
        insert MyBypass;

        Account acc = TestDataFactory.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        TestDataFactory.createFinancialCond(acc.Id);
        TestDataFactory.createContact('contactTest', acc.Id);

        // billing rules creation
        blng__BillingRule__c blngR = TestDataFactory.createBillingRule();
        blng__RevenueRecognitionRule__c revRecRul = TestDataFactory.createRevenueRecognitionRule();
        blng__LegalEntity__c legEnt =  TestDataFactory.createLegalEntity();
        blng__FinanceBook__c finBook = TestDataFactory.createFinanceBook(legEnt.Id);
        blng__GLRule__c glrul = TestDataFactory.createGlRule(legEnt.Id);
        blng__RevenueDistributionMethod__c distMet = TestDataFactory.createDistribMethod();
        TestDataFactory.createRevenueRecognitionTreatment(legEnt.Id, finBook.Id, revRecRul.Id, glrul.Id, distMet.Id, 0);

        // tax rule
        blng__TaxRule__c taxRule = TestDataFactory.createTaxRule();
        TestDataFactory.createTaxTreatment(legEnt.Id, taxRule.Id);

        //product creation (with billing rule)
        Product2 p = TestDataFactory.createProduct('CF10', true, 'CF10', 'tst', blngR.Id, revRecRul.Id, taxRule.Id);
        PricebookEntry pbe = TestDataFactory.createPricebookEntry(true, Test.getStandardPricebookId(), p.Id, 10.0);

        //opty & quote creation
        Opportunity opp = TestDataFactory.createOpportunity('opp1', acc.Id, null, Label.OPP_StageName_OpportuniteCreee, null, legEnt.Id);
        SBQQ__Quote__c quote = TestDataFactory.createCPQQuote(opp.Id, true, acc.Id, Date.today(), 12);
        SBQQ__QuoteLineGroup__c qlg = TestDataFactory.createQuotelineGroup(quote.Id, Date.today(), Date.today().addMonths(12));
        SBQQ__QuoteLine__c ql = TestDataFactory.createQuoteLine(quote.Id, p.Id, 1, pbe.Id, qlg.Id);

        //update quote to generate order/contract
        // quote.SBQQ__Status__c = 'Devis Signé';
        // quote.SBQQ__Ordered__c = true;
        // update quote;

        //create order
        Order order = TestDataFactory.createOrder(acc.Id, Date.today(), Date.today().addMonths(12), quote.Id, opp.Id);
        TestDataFactory.createOrderProduct(order.Id, p.Id, acc.Id, Date.today(), Date.today().addMonths(12), legEnt.Id, blngR.Id, finBook.Id, glrul.Id, revRecRul.Id, ql.Id, pbe.Id);

        SBQQ.TriggerControl.disable();
        //create contract
        Contract ct = TestDataFactory.createContract(acc.Id, quote.Id, 'Draft', Date.today(), 12, Date.today().addMonths(12).addDays(2), order.Id, opp.Id);
        SBQQ.TriggerControl.enable();

        TestDataFactory.createSubscription(ct.Id, p.Id, ql.Id, acc.Id);
        // ct.Status = 'Activated';
        // update ct;
    }

    @IsTest
    public static void testRenewer() {
        Contract ct = [
                SELECT
                        Id,
                        ContractNumber,
                        EndDate,
                        Extension_Date__c,
                        SBQQ__Opportunity__r.RecordTypeId,
                        SBQQ__Quote__r.RecordTypeId,
                        SBQQ__Quote__r.Type_de_location__c
                FROM Contract LIMIT 1
        ];
        System.debug(ct);

        Test.startTest();

        QuoteRenewer.QuoteRenewerOutputContext newQuoteIds = QuoteRenewer.renewContracts(new List<Contract>{ct});
        Test.stopTest();

        SBQQ__Quote__c renewQuote = [
                SELECT Id,
                        SBQQ__Opportunity2__r.TypeOpportunite__c,
                        SBQQ__StartDate__c,
                        SBQQ__EndDate__c,
                        SBQQ__Status__c,
                        SBQQ__Ordered__c
                FROM SBQQ__Quote__c
                WHERE Id = :newQuoteIds.quoteIds.get(0)
        ];
        System.assertNotEquals(null, renewQuote, 'Renewed quote not found');
        System.assertEquals(ct.EndDate.addDays(1), renewQuote.SBQQ__StartDate__c, 'Wrong start date');
        // System.assertEquals(ct.Extension_Date__c, renewQuote.SBQQ__EndDate__c, 'Wrong end date');
        // System.assertEquals('Devis Signé', renewQuote.SBQQ__Status__c, 'Wrong status');
        // System.assert(renewQuote.SBQQ__Ordered__c, 'Wrong ordered value');
    }/* */

    @IsTest
    public static void testRenewerRunRenewalCallout() {
        Contract ct = [
                SELECT
                        Id,
                        ContractNumber,
                        EndDate,
                        Extension_Date__c,
                        SBQQ__Opportunity__r.RecordTypeId,
                        SBQQ__Quote__r.RecordTypeId,
                        SBQQ__Quote__r.Type_de_location__c,
                        TypeOpportunite__c
                FROM Contract LIMIT 1
        ];
        SBQQ__Quote__c q = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        System.debug(ct);

        Test.startTest();

        QuoteRenewer.runRenewalCalloutAndScheduleEvent(new List<Contract>{ct}, false);
        Test.stopTest();

        SBQQ__Quote__c renewQuote = [
                SELECT Id,
                        SBQQ__Opportunity2__r.TypeOpportunite__c,
                        SBQQ__StartDate__c,
                        SBQQ__EndDate__c,
                        SBQQ__Status__c,
                        SBQQ__Ordered__c
                FROM SBQQ__Quote__c
                WHERE Id <> :q.Id LIMIT 1
        ];
        System.assertNotEquals(null, renewQuote, 'Renewed quote not found');
        System.assertEquals(ct.EndDate.addDays(1), renewQuote.SBQQ__StartDate__c, 'Wrong start date');
        // System.assertEquals(ct.Extension_Date__c, renewQuote.SBQQ__EndDate__c, 'Wrong end date');
        // System.assertEquals('Devis Signé', renewQuote.SBQQ__Status__c, 'Wrong status');
        // System.assert(renewQuote.SBQQ__Ordered__c, 'Wrong ordered value');
    }/* */

    @IsTest
    public static void testRenewerCustomEnd() {
        Contract ct = [
                SELECT Id,
                        ContractNumber,
                        EndDate,
                        Extension_Date__c,
                        SBQQ__Opportunity__r.RecordTypeId,
                        SBQQ__Quote__r.RecordTypeId,
                        SBQQ__Quote__r.Type_de_location__c,
                        TypeOpportunite__c
                FROM Contract LIMIT 1
        ];
        ct.Extension_Date__c = null;
        update ct;
        List<Contract> ctlist = new List<Contract>{ct};
        List<List<Contract>> invInput = new List<List<Contract>>{ctlist};

        ByPass__c byPass = ByPass__c.getInstance();
        if(bypass == null){
                bypass = new Bypass__c(
                        SetupOwnerId = UserInfo.getUserId()
                );
        }
        byPass.BypassTriggers__c = 'AP04Opportunite';
        upsert bypass;

        Test.startTest();

        QuoteRenewer.renewContractAction(invInput);
        QuoteRenewer.QuoteRenewerOutputContext out = QuoteRenewer.renewContracts(ctlist);
        QuoteApprovalScheduler sc = new QuoteApprovalScheduler(out);
        sc.execute(null);

        Test.stopTest();

        /*
        // START - DISABLE TESTS --> TO FIX
        Contract renewCt = [SELECT Id, StartDate, EndDate FROM Contract WHERE Id <> :ct.Id LIMIT 1];
        System.assertNotEquals(null, renewCt, 'Renewed contract not found');
        // END - DISABLE TESTS --> TO FIX
        */
        // System.assertEquals(Date.today().addMonths(5), renewCt.EndDate, 'Wrong end date');
    }
}