unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Relation__c/Relation__c.object-meta.xml
<CustomObject>
    <label>Relation</label>
    <nameField>
        <displayFormat>GF-RES-{0000000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relation__c/fields/ContactPrincipal__c.field-meta.xml
<CustomField>
    <fullName>ContactPrincipal__c</fullName>
    <label>Le contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Réseau du contact</relationshipLabel>
    <relationshipName>ContactsRelies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Relation__c/fields/ContactRelie__c.field-meta.xml
<CustomField>
    <fullName>ContactRelie__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>est en relation avec</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un contact ne peut pas être en relation avec lui-même.</errorMessage>
        <filterItems>
            <field>$Source.ContactPrincipal__c</field>
            <operation>notEqual</operation>
            <valueField>Contact.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Réseau du contact (2)</relationshipLabel>
    <relationshipName>ContactsPrincipaux</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relation__c/fields/TypeRelation__c.field-meta.xml
<CustomField>
    <fullName>TypeRelation__c</fullName>
    <label>Type de relation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Ami</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Concurrent</fullName>
            </value>
            <value>
                <fullName>Famille</fullName>
            </value>
            <value>
                <fullName>Fournisseur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AP01Relation_TEST.cls
/*
* CON-RG-011: "Si un contact A est ajouté au réseau d’un contact B, le contact B est automatiquement ajouté au réseau du contact A. 
	* 				Le type de la relation AB reste le même que celui de la relation BA, sauf si le type est « Client » ou « Fournisseur »:
	* 				- « Client » (AB) devient « Fournisseur » (BA)
	* 				- « Fournisseur » (AB) devient « Client »  (BA)"
* @Author Ali Naji
* @TestClass for AP01Relation
*/
@isTest
    private class AP01Relation_TEST {

    static testMethod void MirrorRelationTest() {

		Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
		MyBypass.BypassValidationRules__c = true;
		insert MyBypass;
		
		Account Account1 = Utils_TestMethods.createAccount('Account1',null,null,Label.CPT_RecordTypeId_CompteClient	);
		insert Account1;
		
		Contact Contact1 = Utils_TestMethods.createContact('Contact1',Account1.Id);
		Contact Contact2 = Utils_TestMethods.createContact('Contact2',Account1.Id);
		Contact Contact3 = Utils_TestMethods.createContact('Contact3',Account1.Id);
        Contact Contact4 = Utils_TestMethods.createContact('Contact4',Account1.Id);
		insert new List<Contact>{Contact1,Contact2,Contact3,Contact4};
		
		Relation__c Relation1 = Utils_TestMethods.createRelation(Contact1.Id,Contact2.Id,Label.REL_TypeRelation_Ami);
		insert Relation1;
		
		Relation__c Relation2 = [	SELECT TypeRelation__c 
									FROM Relation__c
									WHERE ContactPrincipal__c=:Contact2.Id
										AND ContactRelie__c=:Contact1.Id LIMIT 1];
		System.AssertEquals(Relation2.TypeRelation__c, Label.REL_TypeRelation_Ami);
		
		Relation1.ContactRelie__c = Contact3.Id;
		Relation1.TypeRelation__c = Label.REL_TypeRelation_Client;
		update Relation1;
		
		integer Relation2Count = [	SELECT COUNT()
									FROM Relation__c
									WHERE Id=:Relation2.Id];
		Relation__c Relation3 = [	SELECT TypeRelation__c
									FROM Relation__c
									WHERE ContactPrincipal__c=:Contact3.Id
										AND ContactRelie__c=:Contact1.Id LIMIT 1];
		System.AssertEquals(Relation2Count,0);
		System.AssertEquals(Relation3.TypeRelation__c,Label.REL_TypeRelation_Fournisseur);
		
		Relation1.TypeRelation__c = Label.REL_TypeRelation_Fournisseur;
		update Relation1;
		
		Relation3 = [	SELECT TypeRelation__c
						FROM Relation__c
						WHERE ContactPrincipal__c=:Contact3.Id
							AND ContactRelie__c=:Contact1.Id LIMIT 1];

		System.AssertEquals(Relation3.TypeRelation__c,Label.REL_TypeRelation_Client);
		
		delete Relation1;
		
		integer Relation3Count = [	SELECT COUNT()
									FROM Relation__c
									WHERE Id=:Relation3.Id];
		System.AssertEquals(Relation3Count,0);
        
        
    }
}