unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassAllTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassAllTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass All Triggers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Bypass.cls
public class Bypass{
    
    public static boolean canTrigger(string triggerClassName){
        
        if(String.isBlank(triggerClassName)){
            return true;
        }
        
        Bypass__c byPassOrg = Bypass__c.getOrgDefaults();
        if(byPassOrg!=null){
            
            if(byPassOrg.BypassAllTriggers__c){
                return false;
            }
            
            else if(!String.isBlank(byPassOrg.BypassTriggers__c) && byPassOrg.BypassTriggers__c.contains(triggerClassName)){
                return false;
            }
        }
        
        ByPass__c byPass = ByPass__c.getInstance(); // current user
        if(byPass != null){
            if(byPass.BypassAllTriggers__c)
                return false;
            else if(!String.isBlank(byPass.BypassTriggers__c) && byPass.BypassTriggers__c.contains(triggerClassName))
                return false;
        }
        
        return true;
    }
}