unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/CodePF__c.field-meta.xml
<CustomField>
    <fullName>CodePF__c</fullName>
    <label>Code PF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quantite__c.field-meta.xml
<CustomField>
    <fullName>Quantite__c</fullName>
    <label>Quantité</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SousCategorie__c.field-meta.xml
<CustomField>
    <fullName>SousCategorie__c</fullName>
    <label>Sous-catégorie</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Categorie__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>V1M</fullName>
            </value>
            <value>
                <fullName>V3M</fullName>
            </value>
            <value>
                <fullName>V3X</fullName>
            </value>
            <value>
                <fullName>V3E</fullName>
            </value>
            <value>
                <fullName>V3P</fullName>
            </value>
            <value>
                <fullName>V3I</fullName>
            </value>
            <value>
                <fullName>V3S</fullName>
            </value>
            <value>
                <fullName>V5M</fullName>
            </value>
            <value>
                <fullName>V5E</fullName>
            </value>
            <value>
                <fullName>V5X</fullName>
            </value>
            <value>
                <fullName>V5P</fullName>
            </value>
            <value>
                <fullName>V5I</fullName>
            </value>
            <value>
                <fullName>V5S</fullName>
            </value>
            <value>
                <fullName>V9M</fullName>
            </value>
            <value>
                <fullName>V9MH</fullName>
            </value>
            <value>
                <fullName>V9X</fullName>
            </value>
            <value>
                <fullName>V9XH</fullName>
            </value>
            <value>
                <fullName>V9E</fullName>
            </value>
            <value>
                <fullName>V9P</fullName>
            </value>
            <value>
                <fullName>V9I</fullName>
            </value>
            <value>
                <fullName>V9IH</fullName>
            </value>
            <value>
                <fullName>V9S</fullName>
            </value>
            <value>
                <fullName>V11M</fullName>
            </value>
            <value>
                <fullName>V11MH</fullName>
            </value>
            <value>
                <fullName>V11X</fullName>
            </value>
            <value>
                <fullName>V11XH</fullName>
            </value>
            <value>
                <fullName>V11E</fullName>
            </value>
            <value>
                <fullName>V11P</fullName>
            </value>
            <value>
                <fullName>V11PH</fullName>
            </value>
            <value>
                <fullName>V11I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
                <color>#0B6FCE</color>
                <label>NCT</label>
            </value>
            <value>
                <fullName>SUP</fullName>
                <color>#A845DC</color>
                <label>SUP</label>
            </value>
            <value>
                <fullName>RNV</fullName>
                <color>#E27001</color>
                <label>RNV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AP04Opportunite_TEST.cls
@istest
public class AP04Opportunite_TEST 
{
     public static testMethod void AP04Opportunite_t() 
    {
    
        Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
        MyBypass.BypassValidationRules__c = true;
        MyBypass.BypassTriggers__c = 'AP01Opportunite';//validation du  compte ayant au mois 1 contact..
        insert MyBypass;
        account acc= Utils_TestMethods.createAccount('4563gddfh',null,null  ,Label.CPT_RecordTypeId_CompteClient	);
        insert acc;
        
        opportunity opp= Utils_TestMethods.createOpportunity('add',label.OPP_StageName_Gagnee,Date.today(),acc);
        opp.accountid=acc.id;
        opp.TypeOpportunite__c='NCT';
        opp.Quantite__c=6;
        opp.CodePF__c='vm';
        //opp.SousCategorie__c='V11M';
        opp.recordtypeid=label.OPP_RecordType_Vehicule_DRAFT;
        
        opportunity opp1= Utils_TestMethods.createOpportunity('add',label.OPP_StageName_Gagnee,Date.today(),acc);
        opp1.accountid=acc.id;
        opp1.TypeOpportunite__c='NCT';
        opp1.Quantite__c=6;
       // opp.CodePF__c='vm';
        opp1.SousCategorie__c='V11M';  
        opp1.recordtypeid=label.OPP_RecordType_Vehicule_DRAFT; 
      
        opportunity opp2= Utils_TestMethods.createOpportunity('add',label.OPP_StageName_Gagnee,Date.today(),acc);
        opp2.accountid=acc.id;
       // opp1.TypeOpportunite__c='NCT';
        opp2.Quantite__c=6;
       // opp.CodePF__c='vm';
        opp2.SousCategorie__c='V11M'; 
        opp2.recordtypeid=label.OPP_RecordType_Vehicule_DRAFT;   
             
        opportunity opp3= Utils_TestMethods.createOpportunity('add',label.OPP_StageName_Gagnee,Date.today(),acc);
        opp3.accountid=acc.id;
        opp3.TypeOpportunite__c='NCT';
        opp3.Quantite__c=6;
       // opp.CodePF__c='vm';
        opp3.SousCategorie__c='V11M';  
        opp3.recordtypeid=label.OPP_RecordType_Vehicule_DRAFT; 
      
        insert new  list<Opportunity> {opp,opp1,opp2,opp3};     
        map<string,Opportunity> ResultsMap = new map<string,Opportunity>([SELECT Name FROM Opportunity WHERE Id in (:opp.Id,:opp1.Id,:opp2.Id,:opp3.Id)]);
            
        system.assertequals(ResultsMap.get(opp.Id).Name,'NCT_6_vm_GDDFH');
        system.assertequals(ResultsMap.get(opp1.Id).Name,'NCT_6_V11M_GDDFH');
        system.assertequals(ResultsMap.get(opp2.Id).name,'add');
        system.assertequals(ResultsMap.get(opp3.Id).name,'NCT_6_V11M_GDDFH');
          
        opp1.TypeOpportunite__c='RNV';
        update(opp1);
        opportunity test5= [select name from opportunity where id=:opp1.id];
        system.assertequals(test5.name,'RNV_6_V11M_GDDFH');
       
    
    }
}