unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassAllTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassAllTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass All Triggers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Bypass_TEST.cls
/**
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Bypass_TEST {

    static testMethod void BypassTest() {
        
        Bypass.canTrigger('');
        
        Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
        insert MyBypass;
        Bypass.canTrigger('AP01Compte');
        
        MyBypass.BypassAllTriggers__c=TRUE;
        update MyBypass;
        Bypass.canTrigger('AP01Compte');
        
        MyBypass.BypassAllTriggers__c=FALSE;
        MyBypass.BypassTriggers__c = 'AP01Compte';
        update MyBypass;
        Bypass.canTrigger('AP01Compte');
        
        
        MyBypass.setupOwnerId = UserInfo.getOrganizationId();        
        MyBypass.BypassAllTriggers__c=TRUE;
        update MyBypass;
        Bypass.canTrigger('AP01Compte');
        
        MyBypass.BypassAllTriggers__c=FALSE;
        MyBypass.BypassTriggers__c = 'AP01Compte';
        update MyBypass;
        Bypass.canTrigger('AP01Compte');
        
        
    }
}