unpackaged/main/default/objects/Account/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <label>Agence PF</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/IdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantNational__c</fullName>
    <label>Identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IDEulerHermes__c.field-meta.xml
<CustomField>
    <fullName>IDEulerHermes__c</fullName>
    <label>ID Euler Hermes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/VFC20_AccountBatches.cls
public class VFC20_AccountBatches {
    
    public Account accIdEH{get;set;}
    public Account accIdNat{get;set;}
    public string numberOfAccounts_IdEH{get;set;}
    public string numberOfAccounts_IdNat{get;set;}
    
    public void act(){
        accIdEH=new account();
        accIdNat=new account();
        numberOfAccounts_IdEH='Nombre de comptes';
        numberOfAccounts_IdNat='Nombre de comptes';
    }
    
    public void denombrerIdEH(){
        string queryIdEH='select Id '
                         +'from Account '
                         +'where IDEulerHermes__c!=null and IDEulerHermes__c!=\'\' ' 
            			 
                        
                         +'and Statut__c=\''+Label.CPT_Statut_Draft+'\' ';
                        
        if(accIdEH.PaysRegionPF__c!=null && accIdEH.PaysRegionPF__c!=''){
            queryIdEH+='and PaysRegionPF__c=\''+accIdEH.PaysRegionPF__c+'\' ';
        }
        if(accIdEH.AgencePF__c!=null && accIdEH.AgencePF__c!=''){
            queryIdEH+='and AgencePF__c=\''+accIdEH.AgencePF__c+'\' ';
        }
        
        integer numAccsIdEH=Database.query(queryIdEH).size();
        numberOfAccounts_IdEH=string.valueOf(numAccsIdEH)+' comptes';
    }
    public void denombrerIdNat(){
        string queryIdNat='select Id '
                         +'from Account WHERE Statut__c=\''+Label.CPT_Statut_Draft+'\' '
                         +'and IdentifiantNational__c!=null and IdentifiantNational__c!=\'\' ';
        if(accIdNat.PaysRegionPF__c!=null && accIdNat.PaysRegionPF__c!=''){
            queryIdNat+='and PaysRegionPF__c=\''+accIdNat.PaysRegionPF__c+'\' ';
        }
        if(accIdNat.AgencePF__c!=null && accIdNat.AgencePF__c!=''){
            queryIdNat+='and AgencePF__c=\''+accIdNat.AgencePF__c+'\' ';
        }
        integer numAccsIdNat=Database.query(queryIdNat).size();
        numberOfAccounts_IdNat=string.valueOf(numAccsIdNat)+' comptes';
        
    }
    
    public void executeBatchIdEHNotNull(){
        AP14Compte_BATCH batch_IdEHNotNull=new AP14Compte_BATCH('IDEulerHermes__c', accIdEH.PaysRegionPF__c, accIdEH.AgencePF__c); 
        Database.executeBatch(batch_IdEHNotNull, 1);
    }
    
    public void executeBatchIdNatNotNull(){
        AP14Compte_BATCH batch_IdNatNotNull=new AP14Compte_BATCH('IdentifiantNational__c', accIdNat.PaysRegionPF__c, accIdNat.AgencePF__c); 
        Database.executeBatch(batch_IdNatNotNull, 1);
    }
}