unpackaged/main/default/objects/Account/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <label>Agence PF</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ListeNoire__c.field-meta.xml
<CustomField>
    <fullName>ListeNoire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refus</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ModeCreation__c.field-meta.xml
<CustomField>
    <fullName>ModeCreation__c</fullName>
    <inlineHelpText>Define</inlineHelpText>
    <label>Mode de création</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Création manuelle</fullName>
                <default>true</default>
                <label>Création manuelle</label>
            </value>
            <value>
                <fullName>Import en masse</fullName>
            </value>
            <value>
                <fullName>Piste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassAllTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassAllTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass All Triggers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <description>Une seule agence PF utilisée pour afficher les missions en cours de cette agence sur Service cloud</description>
    <inlineHelpText>Une seule agence PF utilisée pour afficher les missions en cours de cette agence sur Service cloud</inlineHelpText>
    <label>Agence PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/VFE11_CompteReload_TEST.cls
/**
 * Test Class pour VFE11_CompteReload
 */
@isTest

private class VFE11_CompteReload_TEST {

    static testMethod void TestCompteWarning() {

        
        //User userOpTech = Utils_TestMethods.createUser('OP_TECH', 'OP_TECH', Label.USR_ProfileId_PFAdministrateurSysteme);
        //userOpTech.LanguageLocaleKey='fr';
        //insert userOpTech;
        
        
       //system.runAs(userOpTech)
       
        Test.startTest();
        //Bypass__c MyBypass = Utils_TestMethods.createBypass(userOpTech.Id);
        //MyBypass.BypassValidationRules__c=true;
        //MyBypass.BypassAllTriggers__c=true;
        //MyBypass.BypassTriggers__c='UtilisateurAfterUpdate,AP02Utilisateur';
        //insert MyBypass;
        Account Account1 = Utils_TestMethods.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        Account1.Statut__c = Label.CPT_Statut_Draft;
        Account1.ModeCreation__c = Label.CPT_ModeCreation_ImportEnMasse;
        Account1.PaysRegionPF__c='DO1B';
        Account1.AgencePF__c = '001 - VILLEPINTE';
        Account1.ListeNoire__c = true;
        
        Account Account1_bloque = Utils_TestMethods.createAccount('Account1_bloque', null, null, Label.CPT_RecordTypeId_CompteClient);
        Account1_bloque.PaysRegionPF__c='DO1B';
        Account1_bloque.AgencePF__c = '001 - VILLEPINTE';
        Account1_bloque.Statut__c = Label.CPT_Statut_Bloque;
        
        Account Account1_erreurEH = Utils_TestMethods.createAccount('Account1_erreurEH', null, null, Label.CPT_RecordTypeId_CompteClient);
        Account1_erreurEH.Statut__c = Label.CPT_Statut_Erreur_EH;
         Account1_erreurEH.PaysRegionPF__c='DO1B';
        Account1_erreurEH.AgencePF__c = '001 - VILLEPINTE';
        
        insert new list<Account>{Account1, Account1_bloque, Account1_erreurEH};
        
        ApexPages.StandardController controller = new ApexPages.StandardController(Account1);
        VFE11_CompteReload r = new VFE11_CompteReload(controller);
        r.reload();
        r.validateAccount();
        
        ApexPages.StandardController controller_bloque = new ApexPages.StandardController(Account1_bloque);
        VFE11_CompteReload r_bloque = new VFE11_CompteReload(controller_bloque);
        r_bloque.reload();
        r_bloque.validateAccount();
        
        ApexPages.StandardController controller_erreurEH = new ApexPages.StandardController(Account1_erreurEH);
        VFE11_CompteReload r_erreurEH = new VFE11_CompteReload(controller_erreurEH);
        r_erreurEH.reload();
        r_erreurEH.validateAccount();
        
       
            
            Account Account2 = Utils_TestMethods.createAccount('Account2', null, null, Label.CPT_RecordTypeId_CompteClient);
            Account2.Statut__c = Label.CPT_Statut_Draft;
            Account2.ModeCreation__c = Label.CPT_ModeCreation_ImportEnMasse;
            Account2.PaysRegionPF__c='DO1B';
        	Account2.AgencePF__c = '001 - VILLEPINTE';
            insert Account2;
            
            ApexPages.StandardController controller2 = new ApexPages.StandardController(Account2);
            VFE11_CompteReload r2 = new VFE11_CompteReload(controller2);
            r2.reload();
            r2.validateAccount();
        
        
			Test.stopTest();}
        
    
}