unpackaged/main/default/objects/Account/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <label>Agence PF</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ModeCreation__c.field-meta.xml
<CustomField>
    <fullName>ModeCreation__c</fullName>
    <inlineHelpText>Define</inlineHelpText>
    <label>Mode de création</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Création manuelle</fullName>
                <default>true</default>
                <label>Création manuelle</label>
            </value>
            <value>
                <fullName>Import en masse</fullName>
            </value>
            <value>
                <fullName>Piste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ModeCreation__c.field-meta.xml
<CustomField>
    <fullName>ModeCreation__c</fullName>
    <label>Mode de création</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Création manuelle</fullName>
                <default>true</default>
                <label>Création manuelle</label>
            </value>
            <value>
                <fullName>Import en masse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <inlineHelpText>Pays ou Région (FR) selon l&#39;implémentation des agences PF</inlineHelpText>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
            <value>
                <fullName>PIND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CatalogueAPI_TEST.cls
@isTest
private class CatalogueAPI_TEST {
	
    static testMethod void testPostCallout_200() {

        Test.setMock(HttpCalloutMock.class, new CatalogueAPIMock_200());
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_006',
                                                               EndPoint__c = 'https://api.petitforestier.fr/services/PFCore/produits',
                                                               Methode__c = 'POST',
                                                               UserName__c = 'ftgo_google',
                                                               MotDePasse__c = 'E_@h3D3r!7',
                                                               ContentType__c = 'application/json',
                                                               ApplicationName__c = 'SFCD',
                                                               Authorization__c = 'Basic ZnRnb19nb29nbGU6RV9AaDNEM3IhNw==');
        insert wspr1;
       
        Account Account1 = Utils_TestMethods.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        Account1.Statut__c = Label.CPT_Statut_Valide;
        Account1.ModeCreation__c = Label.CPT_ModeCreation_ImportEnMasse;
        Account1.PaysRegionPF__c='DO1B';
        Account1.AgencePF__c = '001 - VILLEPINTE';
        Account1.RecordTypeId = Label.ACC_RecordTypeId_CompteClient;
              insert Account1;
		
        Contact CON = Utils_TestMethods.createContact('conName', Account1.Id);
               insert CON;

        Opportunity OPP = Utils_TestMethods.createOpportunity('Nouvelle Opportunité 1',Label.OPP_StageName_OpportuniteCreee,system.today(),Account1);
        OPP.RecordTypeId = Label.OPP_RecordType_Vehicule_ENCOURS;
        OPP.Amount = 500000;
        OPP.DateClotureEffective__c = system.today();
           insert OPP;

        Quote Q = new Quote();
        Q.Name = 'TEST';
        Q.OpportunityId = OPP.Id;
        Q.RecordTypeId = Label.Quote_RecordTypeId_HorsStandard	;
                   insert Q;
        
        test.startTest();
        //CatalogueAPI.WSCallCatalogue('FR', '100E19 20CH', 'HY_ST', '01', Q.Id);
        CatalogueAPI.WSCallCatalogue('FR', '100E19 20CH', 'HY_ST', '01', Q.Id, '', '');
        test.stopTest();
      
    }
     static testMethod void testPostCallout_201() {

        Test.setMock(HttpCalloutMock.class, new CatalogueAPIMock_201());
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_006',
                                                               EndPoint__c = 'https://api.petitforestier.fr/services/PFCore/produits',
                                                               Methode__c = 'POST',
                                                               UserName__c = 'ftgo_google',
                                                               MotDePasse__c = 'E_@h3D3r!7',
                                                               ContentType__c = 'application/json',
                                                               ApplicationName__c = 'SFCD',
                                                               Authorization__c = 'Basic ZnRnb19nb29nbGU6RV9AaDNEM3IhNw==');
        insert wspr1;
       
        Account Account1 = Utils_TestMethods.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        Account1.Statut__c = Label.CPT_Statut_Valide;
        Account1.ModeCreation__c = Label.CPT_ModeCreation_ImportEnMasse;
        Account1.PaysRegionPF__c='DO1B';
        Account1.AgencePF__c = '001 - VILLEPINTE';
        Account1.RecordTypeId = Label.ACC_RecordTypeId_CompteClient;
              insert Account1;
		
        Contact CON = Utils_TestMethods.createContact('conName', Account1.Id);
               insert CON;

        Opportunity OPP = Utils_TestMethods.createOpportunity('Nouvelle Opportunité 1',Label.OPP_StageName_OpportuniteCreee,system.today(),Account1);
        OPP.RecordTypeId = Label.OPP_RecordType_Vehicule_ENCOURS;
        OPP.Amount = 500000;
        OPP.DateClotureEffective__c = system.today();
           insert OPP;

        Quote Q = new Quote();
        Q.Name = 'TEST';
        Q.OpportunityId = OPP.Id;
        Q.RecordTypeId = Label.Quote_RecordTypeId_HorsStandard	;
                   insert Q;
        
        test.startTest();
        //CatalogueAPI.WSCallCatalogue('FR', '100E19 20CH', 'HY_ST', '01', Q.Id);
        CatalogueAPI.WSCallCatalogue('FR', '100E19 20CH', 'HY_ST', '01', Q.Id, '', '');
        test.stopTest();
      
    }
     static testMethod void testPostCallout_404() {

        Test.setMock(HttpCalloutMock.class, new CatalogueAPIMock_404());
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_006',
                                                               EndPoint__c = 'https://api.petitforestier.fr/services/PFCore/produits',
                                                               Methode__c = 'POST',
                                                               UserName__c = 'ftgo_google',
                                                               MotDePasse__c = 'E_@h3D3r!7',
                                                               ContentType__c = 'application/json',
                                                               ApplicationName__c = 'SFCD',
                                                               Authorization__c = 'Basic ZnRnb19nb29nbGU6RV9AaDNEM3IhNw==');
        insert wspr1;
       
        Account Account1 = Utils_TestMethods.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        Account1.Statut__c = Label.CPT_Statut_Valide;
        Account1.ModeCreation__c = Label.CPT_ModeCreation_ImportEnMasse;
        Account1.PaysRegionPF__c='DO1B';
        Account1.AgencePF__c = '001 - VILLEPINTE';
        Account1.RecordTypeId = Label.ACC_RecordTypeId_CompteClient;
              insert Account1;
		
        Contact CON = Utils_TestMethods.createContact('conName', Account1.Id);
               insert CON;

        Opportunity OPP = Utils_TestMethods.createOpportunity('Nouvelle Opportunité 1',Label.OPP_StageName_OpportuniteCreee,system.today(),Account1);
        OPP.RecordTypeId = Label.OPP_RecordType_Vehicule_ENCOURS;
        OPP.Amount = 500000;
        OPP.DateClotureEffective__c = system.today();
           insert OPP;

        Quote Q = new Quote();
        Q.Name = 'TEST';
        Q.OpportunityId = OPP.Id;
        Q.RecordTypeId = Label.Quote_RecordTypeId_HorsStandard	;
                   insert Q;
        
        test.startTest();
        //CatalogueAPI.WSCallCatalogue('FR', '100E19 20CH', 'HY_ST', '02', Q.Id);
        CatalogueAPI.WSCallCatalogue('FR', '100E19 20CH', 'HY_ST', '01', Q.Id, '', '');
        test.stopTest();
      
    }
     static testMethod void testPostCallout_500() {

        Test.setMock(HttpCalloutMock.class, new CatalogueAPIMock_500());
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_006',
                                                               EndPoint__c = 'https://api.petitforestier.fr/services/PFCore/produits',
                                                               Methode__c = 'POST',
                                                               UserName__c = 'ftgo_google',
                                                               MotDePasse__c = 'E_@h3D3r!7',
                                                               ContentType__c = 'application/json',
                                                               ApplicationName__c = 'SFCD',
                                                               Authorization__c = 'Basic ZnRnb19nb29nbGU6RV9AaDNEM3IhNw==');
        insert wspr1;
       
        Account Account1 = Utils_TestMethods.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        Account1.Statut__c = Label.CPT_Statut_Valide;
        Account1.ModeCreation__c = Label.CPT_ModeCreation_ImportEnMasse;
        Account1.PaysRegionPF__c='DO1B';
        Account1.AgencePF__c = '001 - VILLEPINTE';
        Account1.RecordTypeId = Label.ACC_RecordTypeId_CompteClient;
              insert Account1;
		
        Contact CON = Utils_TestMethods.createContact('conName', Account1.Id);
               insert CON;

        Opportunity OPP = Utils_TestMethods.createOpportunity('Nouvelle Opportunité 1',Label.OPP_StageName_OpportuniteCreee,system.today(),Account1);
        OPP.RecordTypeId = Label.OPP_RecordType_Vehicule_ENCOURS;
        OPP.Amount = 500000;
        OPP.DateClotureEffective__c = system.today();
           insert OPP;

        Quote Q = new Quote();
        Q.Name = 'TEST';
        Q.OpportunityId = OPP.Id;
        Q.RecordTypeId = Label.Quote_RecordTypeId_HorsStandard	;
                   insert Q;
        
        test.startTest();
        //CatalogueAPI.WSCallCatalogue('FR', '100E19 20CH', 'HY_ST', '01', Q.Id);
        CatalogueAPI.WSCallCatalogue('FR', '100E19 20CH', 'HY_ST', '01', Q.Id, '', '');

        test.stopTest();
      
    }
}