unpackaged/main/default/objects/Account/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <label>Agence PF</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <label>Agence de location</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <inlineHelpText>Pays ou Région (FR) selon l&#39;implémentation des agences PF</inlineHelpText>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
            <value>
                <fullName>PIND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence PF</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commandes (Agence PF)</relationshipLabel>
    <relationshipName>Commande_Agence</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/VFE12_OpportunityPrefill.cls
/*
* Les champs Pays / Région PF et Agence PF d'une opportunité doivent être préremplis par les valeurs du compte, mais restent modifiables.
* @Author Natasha Maalouf
* @TestClass VFE12_OpportunityPrefill_TEST
* @CodeCoverage 100%
*/

public class VFE12_OpportunityPrefill{

    public string RecordType {get;set;}
    public boolean isOppEnfant=FALSE;
    public string theme{get;set;}
    public Opportunity a{get;set;}
    public list<RecordType> RecordTypes{get;set;}
    public boolean isBrowser{
        get
        {
            if(theme == 'Theme4t')
            {
                return false;
            }
            return true;
        }
        set;
   }
    public VFE12_OpportunityPrefill(ApexPages.StandardSetController controller) {
       theme = UserInfo.getUiTheme();
       a = new Opportunity();
   }

    
    public VFE12_OpportunityPrefill(ApexPages.StandardController controller) {
        theme = UserInfo.getUiTheme();
        a = new Opportunity();
        //Recordtype = a.RecordTypeId;
        RecordTypes = [SELECT Name, Description 
                        FROM RecordType 
                        WHERE sObjectType = 'Opportunity'
                        AND (Id = :label.OPP_RecordTypeId_OppMonoProduit15 or Id = :label.OPP_RecordTypeId_OppMultiProduits15)
                        ORDER BY Name];
    }

    public PageReference prefillOpportunity(){
        PageReference p;

        Id accId=ApexPages.currentPage().getParameters().get('accId');
        Id parentOppId=ApexPages.currentPage().getParameters().get('parentOppId');
        string pageRefURL='/'+Label.OPP_CreateNew_Id+'/e?retURL=%2F'+Label.OPP_CreateNew_Id+'%2Fo'+'&nooverride=1';
        Recordtype = a.RecordTypeId;
        boolean Mono = FALSE;
        if(Recordtype!=null)
        {
            Mono = Recordtype.substring(0,15) == Label.OPP_RecordTypeId_OppMonoProduit15;
        }
        
        //Si on crée l'opportunité à partir de la liste associée sur un compte
        if(!isOppEnfant){
            
            pageRefURL=pageRefURL+'&RecordType='+Recordtype ;
            if(accId!=NULL){
                pageRefURL=pageRefURL+'&accid='+accId;
                Account acc=[select PaysRegionPF__c, AgencePF__c
                             from account
                             where id=:accId];
                //Si le compte a une valeur de Pays / Région
                if(acc.PaysRegionPF__c!='' && acc.PaysRegionPF__c!=NULL){
                    pageRefURL=pageRefURL+'&'+Label.OPP_PaysRegionPF_Id+'='+acc.PaysRegionPF__c;
                    //Si le compte a une valeur d'Agence PF (en plus de la valeur Pays / Région)
                    if(acc.AgencePF__c!='' && acc.AgencePF__c!=NULL){
                        pageRefURL=pageRefURL+'&'+Label.OPP_AgencePF_Id+'='+acc.AgencePF__c;
                    }
                }
            }
        }
        
        //Si on crée l'opportunité à partir de la liste associée d'une opportunité multi-produits
        else{
            pageRefURL=pageRefURL+'&RecordType='+Label.OPP_RecordTypeId_OppMonoProduit15;
            Mono = true;
            if(parentOppId!=NULL){
                pageRefURL=pageRefURL+'&CF'+Label.OPP_FieldID_OpportuniteParent+'_lkid='+parentOppId;
                Opportunity parentOpp=[select Name, AccountId, PaysRegionPF__c, AgencePF__c
                                       from Opportunity
                                       where id=:parentOppId];
                pageRefURL=pageRefURL+'&CF'+Label.OPP_FieldID_OpportuniteParent+'='+parentOpp.Name;
                if(parentOpp.AccountId!=NULL){
                    pageRefURL=pageRefURL+'&accid='+parentOpp.AccountId;
                }
                //Si l'opportunité mère a une valeur de Pays / Région
                if(parentOpp.PaysRegionPF__c!='' && parentOpp.PaysRegionPF__c!=NULL){
                    pageRefURL=pageRefURL+'&'+Label.OPP_PaysRegionPF_Id+'='+parentOpp.PaysRegionPF__c;
                    //Si l'opportunité mère a une valeur d'Agence PF (en plus de la valeur Pays / Région)
                    if(parentOpp.AgencePF__c!='' && parentOpp.AgencePF__c!=NULL){
                        pageRefURL=pageRefURL+'&'+Label.OPP_AgencePF_Id+'='+parentOpp.AgencePF__c;
                    }
                }
            }
        }
                
        //Préremplir le nom d'une opportunité mono-produit par "Nouvelle Opportunité XX..X"
        if(Mono)
        {
            string NewOppName = Label.OPP_Name_NewOpp + '%';
            list<Opportunity> NouvellesOpps = [ SELECT Name
                                                FROM Opportunity
                                                WHERE Name like :NewOppName];
            list<integer> Numbers = new list<integer>();
            for(Opportunity o : NouvellesOpps)
            {
                string digits = o.Name.substring(o.Name.lastindexof(' ')+1);
                if(digits.isNumeric())
                {
                    Numbers.add((integer.valueof(digits)));
                }
            }
            Numbers.sort();
            if(Numbers.size()>0)
            {   pageRefURL += '&opp3=' + Label.OPP_Name_NewOpp + ' ' + (Numbers[Numbers.size()-1]+1); }
            else
            {   pageRefURL += '&opp3=' + Label.OPP_Name_NewOpp + ' 1'; }
        }
        
        //pageRefURL=pageRefURL+'&save_new=1';
        p=new PageReference(pageRefURL);
        p.setRedirect(true);
        return p;
    }
    
    public PageReference prefillChildOpportunity(){       
        isOppEnfant=TRUE;
        PageReference p1=prefillOpportunity();
        return p1;
        }
}