unpackaged/main/default/objects/Account/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <label>Agence PF</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <formula>IF(
    BEGINS(TEXT(PaysRegionPF__c), &quot;DRO&quot;), 
    &#39;FR&#39;,
    IF(
        BEGINS(TEXT(PaysRegionPF__c), &quot;STFR&quot;),
        &#39;FR&#39;,
        CASE(
            TEXT(PaysRegionPF__c),
            &#39;PFUK&#39;, &#39;GB&#39;,
            &#39;PIRL&#39;, &#39;IE&#39;,
            &#39;PIMA&#39;, &#39;MA&#39;,
            &#39;PITA&#39;, &#39;IT&#39;,
            &#39;PIND&#39;, &#39;NL&#39;,
            &#39;PIAT&#39;, &#39;AT&#39;,
            &#39;PIPL&#39;, &#39;PL&#39;,
            &#39;PIPT&#39;, &#39;PT&#39;,
            &#39;PILU&#39;, &#39;LU&#39;,
            &#39;PIES&#39;, &#39;ES&#39;,
            &#39;PIDE&#39;, &#39;DE&#39;,
            &#39;PIBE&#39;, &#39;BE&#39;,
            &#39;PICZ&#39;, &#39;SK&#39;,
            &#39;PICH&#39;, &#39;CH&#39;,
            &#39;PIAE&#39;, &#39;AE&#39;,
            &#39;PIBU&#39;, &#39;BU&#39;,
            &#39;PIZA&#39;, &#39;ZA&#39;,


            &#39;-&#39;
        )
    )
)</formula>
    <label>CodePays</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantNational__c</fullName>
    <label>Identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TypeIdentifiantNational__c</fullName>
    <label>Type d&#39;identifiant national</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CNIE</fullName>
            </value>
            <value>
                <fullName>COC</fullName>
            </value>
            <value>
                <fullName>COCCH</fullName>
            </value>
            <value>
                <fullName>COCCHE</fullName>
            </value>
            <value>
                <fullName>COFIS</fullName>
            </value>
            <value>
                <fullName>CRO</fullName>
            </value>
            <value>
                <fullName>DELTA</fullName>
            </value>
            <value>
                <fullName>HRB</fullName>
            </value>
            <value>
                <fullName>HRM</fullName>
            </value>
            <value>
                <fullName>IBLC</fullName>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
            <value>
                <fullName>KVK</fullName>
            </value>
            <value>
                <fullName>NIPC</fullName>
            </value>
            <value>
                <fullName>P.IVA</fullName>
            </value>
            <value>
                <fullName>RCLU</fullName>
            </value>
            <value>
                <fullName>RNMA</fullName>
            </value>
            <value>
                <fullName>RNPL</fullName>
            </value>
            <value>
                <fullName>RNPT</fullName>
            </value>
            <value>
                <fullName>SIREN</fullName>
            </value>
            <value>
                <fullName>TVABE</fullName>
            </value>
            <value>
                <fullName>TVADE</fullName>
            </value>
            <value>
                <fullName>TVAPL</fullName>
            </value>
            <value>
                <fullName>En création</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>PRISMA</fullName>
            </value>
            <value>
                <fullName>RNHU</fullName>
                <label>RNHU (cégjegyzékszám)</label>
            </value>
            <value>
                <fullName>VATHU</fullName>
                <label>VATHU (Adoszam)</label>
            </value>
            <value>
                <fullName>TVAIT</fullName>
            </value>
            <value>
                <fullName>ICOSK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CodeAgence__c/CodeAgence__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Code Agence</label>
</CustomObject>

unpackaged/main/default/objects/CodeAgence__c/fields/Numero_Agence__c.field-meta.xml
<CustomField>
    <fullName>Numero_Agence__c</fullName>
    <label>Numero_Agence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CodesPays__c/CodesPays__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CodesPays</label>
</CustomObject>

unpackaged/main/default/objects/CodesPays__c/fields/Code_Pays2__c.field-meta.xml
<CustomField>
    <fullName>Code_Pays2__c</fullName>
    <label>Code_Pays2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CodesPays__c/fields/Code_Pays__c.field-meta.xml
<CustomField>
    <fullName>Code_Pays__c</fullName>
    <label>Code_Pays</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TypeIdentifiantNational__c/TypeIdentifiantNational__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Type Identifiant National</label>
</CustomObject>

unpackaged/main/default/objects/TypeIdentifiantNational__c/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TypeIdentifiantNational__c/fields/Libelle_fr__c.field-meta.xml
<CustomField>
    <fullName>Libelle_fr__c</fullName>
    <label>Libelle_fr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AP14Compte_BATCH_TEST.cls
/**
 * Classe de test pour AP14Compte_BATCH
 */

@isTest
public class AP14Compte_BATCH_TEST {

    public static testMethod void launchBatchTest() {
        Bypass__c myBypass=Utils_TestMethods.createBypass(UserInfo.getUserId());
        myBypass.BypassValidationRules__c = true;
        myBypass.BypassTriggers__c = 'AP09Compte';
        
        User userOpTech=[select Name from User where Name=:Label.USR_OPTECH][0];
        Bypass__c opTechBypass=Utils_TestMethods.createBypass(userOpTech.Id);
        opTechBypass.BypassValidationRules__c = true;
        opTechBypass.BypassTriggers__c = 'AP09Compte';
        
        insert new list<Bypass__c>{myBypass, opTechBypass};
        
        //set up custom settings
        TypeIdentifiantNational__c tin1 = new TypeIdentifiantNational__c(Name = '011',
                                                                        Code__c = 'SIREN',
                                                                        CodePays__c = 'FR',
                                                                        Libelle_fr__c = 'SIREN-FRA');
        insert tin1;
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_000',
                                                               EndPoint__c = 'https://api-test.petitforestier.fr/api/services/PFCustomersRepository/Account',
                                                               Methode__c = 'POST',
                                                               UserName__c = 'mdm_sfdc',
                                                               MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                               ContentType__c = 'application/xml',
                                                               ApplicationName__c = 'SFCD',
                                                               Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr1;
        CodesPays__c cp1 = new CodesPays__c(Name = '053',
                                           Code_Pays__c = 'FRA',
                                           Code_Pays2__c = 'FR',
                                           Libelle_fr__c = 'France');
        insert cp1;
        CodeAgence__c ca1 = new CodeAgence__c(Name = '001',
                                           Numero_Agence__c = '001',
                                           Libelle_fr__c = '001 - VILLEPINTE');
        insert ca1;
        
        System.runAs(userOpTech){
            Account accIdNat = new Account(Name='AccountTest', RecordTypeId=Label.CPT_RecordTypeId_CompteClient,
                                       PaysRegionPF__c = 'RPF1', AgencePF__c = '001 - VILLEPINTE',
                                       ModeCreation__c=Label.CPT_ModeCreation_ImportEnMasse,
                                       Statut__c = Label.CPT_Statut_Bloque,
                                       IdentifiantNational__c = '343134763',
                                       TypeIdentifiantNational__c = 'SIREN-FRA',
                                       Ligne1Exploitation__c = '42 avenue de Friedland',
                                       VilleExploitation__c = 'PARIS',
                                       CodePostalExploitation__c = '75008',
                                       PaysExploitation__c = 'France');
            Account accIdEH = new Account(Name='AccountTest2', RecordTypeId=Label.CPT_RecordTypeId_CompteClient,
                                       PaysRegionPF__c = 'RPF1', AgencePF__c = '001 - VILLEPINTE',
                                       Statut__c = Label.CPT_Statut_Bloque,
                                       ModeCreation__c=Label.CPT_ModeCreation_ImportEnMasse,
                                       IDEulerHermes__c = '343134763',
                                       TypeIdentifiantNational__c = 'SIREN-FRA',
                                       Ligne1Exploitation__c = '42 avenue de Friedland',
                                       VilleExploitation__c = 'PARIS',
                                       CodePostalExploitation__c = '75008',
                                       PaysExploitation__c = 'France');
            insert new list<Account>{accIdNat, accIdEH};
            
            VFC20_AccountBatches controller=new VFC20_AccountBatches();
            controller.act();
            controller.accIdEH=accIdEH;
            controller.accIdNat=accIdNat;
            controller.denombrerIdEH();
            controller.denombrerIdNat();
            
            Test.startTest();
            /*AP14Compte_BATCH batchIdEH = new AP14Compte_BATCH('IDEulerHermes__c', accIdEH.PaysRegionPF__c, accIdEH.AgencePF__c);
            ID batchprocessid_IdEH = Database.executeBatch(batchIdEH);
            
            AP14Compte_BATCH batchIdNat = new AP14Compte_BATCH('IdentifiantNational__c', accIdNat.PaysRegionPF__c, accIdNat.AgencePF__c);
            ID batchprocessid_IdNat = Database.executeBatch(batchIdNat);*/
            
            controller.executeBatchIdEHNotNull();
            controller.executeBatchIdNatNotNull();
            Test.stopTest();
        }
    }
}