unpackaged/main/default/objects/Account/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <label>Agence PF</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
            <value>
                <fullName>113 - LEEDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AgencePF__c.field-meta.xml
<CustomField>
    <fullName>AgencePF__c</fullName>
    <label>Agence de location</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>000 - SIEGE</fullName>
            </value>
            <value>
                <fullName>001 - VILLEPINTE</fullName>
            </value>
            <value>
                <fullName>002 - BORDEAUX</fullName>
            </value>
            <value>
                <fullName>003 - ROUEN</fullName>
            </value>
            <value>
                <fullName>004 - RUNGIS</fullName>
            </value>
            <value>
                <fullName>005 - TOULOUSE</fullName>
            </value>
            <value>
                <fullName>006 - NANTES</fullName>
            </value>
            <value>
                <fullName>007 - PAU</fullName>
            </value>
            <value>
                <fullName>008 - DIJON</fullName>
            </value>
            <value>
                <fullName>009 - TOURS</fullName>
            </value>
            <value>
                <fullName>010 - LYON</fullName>
            </value>
            <value>
                <fullName>011 - PLAISIR</fullName>
            </value>
            <value>
                <fullName>012 - CAEN</fullName>
            </value>
            <value>
                <fullName>014 - LILLE</fullName>
            </value>
            <value>
                <fullName>015 - NIORT</fullName>
            </value>
            <value>
                <fullName>016 - NÎMES</fullName>
            </value>
            <value>
                <fullName>017 - ANGERS</fullName>
            </value>
            <value>
                <fullName>018 - METZ</fullName>
            </value>
            <value>
                <fullName>019 - ORLEANS</fullName>
            </value>
            <value>
                <fullName>020 - REIMS</fullName>
            </value>
            <value>
                <fullName>021 - RENNES</fullName>
            </value>
            <value>
                <fullName>022 - CLERMONT-FERRAND</fullName>
            </value>
            <value>
                <fullName>023 - LE HAVRE</fullName>
            </value>
            <value>
                <fullName>024 - MARSEILLE</fullName>
            </value>
            <value>
                <fullName>025 - ANNECY</fullName>
            </value>
            <value>
                <fullName>026 - MULHOUSE</fullName>
            </value>
            <value>
                <fullName>027 - LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>028 - BEZONS</fullName>
            </value>
            <value>
                <fullName>029 - PERPIGNAN</fullName>
            </value>
            <value>
                <fullName>030 - LIÈGE</fullName>
            </value>
            <value>
                <fullName>113 - LEEDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <inlineHelpText>Pays ou Région (FR) selon l&#39;implémentation des agences PF</inlineHelpText>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
            <value>
                <fullName>PIND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/VFE12_OpportunityPrefill_TEST.cls
/**
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class VFE12_OpportunityPrefill_TEST{

    static testMethod void TestOpportunityPrefill() {

    Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
    MyBypass.BypassValidationRules__c = true;
    MyBypass.BypassTriggers__c = 'AP09Compte,AP03Opportunite,AP01Opportunite';
    insert MyBypass;
    
    Account Account1 = Utils_TestMethods.createAccount('Account1',null,null, Label.CPT_RecordTypeId_CompteClient); 
    Account1.PaysRegionPF__c = 'PFUK';
    Account1.AgencePF__c = '113 - LEEDS';
    insert Account1;
        
    Opportunity Opportunity1 = Utils_TestMethods.createOpportunity('Nouvelle Opportunité 1',Label.OPP_StageName_OpportuniteCreee,system.today(),Account1);
    Opportunity1.AccountId = Account1.Id;
    Opportunity1.PaysRegionPF__c = 'PFUK';
    Opportunity1.AgencePF__c = '113 - LEEDS';
    insert Opportunity1;
    
    ApexPages.StandardController controller;
    VFE12_OpportunityPrefill r = new VFE12_OpportunityPrefill(controller);
    ApexPages.currentPage().getparameters().put('accid', Account1.Id);
    ApexPages.currentPage().getparameters().put('parentOppId', Opportunity1.Id);
    r.prefillOpportunity();
    r.prefillChildOpportunity();
    boolean sf1 = r.isBrowser;
    r.theme = label.VFP_Theme4t_SF1;
    boolean sf2 = r.isBrowser;
    }
}