unpackaged/main/default/objects/Account/fields/AgrementSFAC__c.field-meta.xml
<CustomField>
    <fullName>AgrementSFAC__c</fullName>
    <label>Agrément</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal (-Facturation-)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CodePostalExploitation__c.field-meta.xml
<CustomField>
    <fullName>CodePostalExploitation__c</fullName>
    <label>Code Postal (-Exploitation-)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CotationPF__c.field-meta.xml
<CustomField>
    <fullName>CotationPF__c</fullName>
    <description>Grade de 1 à 10</description>
    <label>Grade Allianz</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DateAgrementEH__c.field-meta.xml
<CustomField>
    <fullName>DateAgrementEH__c</fullName>
    <label>Date d&#39;agrément</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DateCotationPF__c.field-meta.xml
<CustomField>
    <fullName>DateCotationPF__c</fullName>
    <label>Date de grade Allianz</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne1__c.field-meta.xml
<CustomField>
    <fullName>Ligne1__c</fullName>
    <label>Ligne 1 (-Facturation-)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne1Exploitation__c.field-meta.xml
<CustomField>
    <fullName>Ligne1Exploitation__c</fullName>
    <label>Ligne 1 (-Exploitation-)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne2__c.field-meta.xml
<CustomField>
    <fullName>Ligne2__c</fullName>
    <label>Ligne 2 (-Facturation-)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne2Exploitation__c.field-meta.xml
<CustomField>
    <fullName>Ligne2Exploitation__c</fullName>
    <label>Ligne 2 (Exploitation)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne3__c.field-meta.xml
<CustomField>
    <fullName>Ligne3__c</fullName>
    <label>Ligne 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne3Exploitation__c.field-meta.xml
<CustomField>
    <fullName>Ligne3Exploitation__c</fullName>
    <label>Ligne 3 (Exploitation)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne4Exploitation__c.field-meta.xml
<CustomField>
    <fullName>Ligne4Exploitation__c</fullName>
    <label>Ligne 4 (Exploitation)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ListeNoire__c.field-meta.xml
<CustomField>
    <fullName>ListeNoire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refus</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysExploitation__c.field-meta.xml
<CustomField>
    <fullName>PaysExploitation__c</fullName>
    <label>Pays (-Exploitation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FINLANDE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>GUADELOUPE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MARTINIQUE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TECHIdentifiantNational__c</fullName>
    <label>TECH Identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHTypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TECHTypeIdentifiantNational__c</fullName>
    <label>TECH Type d&#39;identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville (-Facturation-)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/VilleExploitation__c.field-meta.xml
<CustomField>
    <fullName>VilleExploitation__c</fullName>
    <label>Ville (-Exploitation-)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AP09Compte_BATCH.cls
/*
* Automatically sends a web service callout for Accounts with a callout counter superior to 0
* 
* @Author Kévin Melliand
* @TestClass AP09Compte_BATCH_TEST
* @CodeCoverage 0%
*/

global class AP09Compte_BATCH implements Database.Batchable<sObject>, Database.Stateful, 
Database.AllowsCallouts{

    global UtilsBatch__c u;
    
    global dateTime batchStartDateTime;
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        System.Debug('>>>> AP09Compte_BATCH Start start <<<<');
                
        String query = 'SELECT Id, Name, RecordTypeId, OwnerId, PaysRegionPF__c, TECHIdentifiantNational__c,'
                              + 'Ligne1__c, Ligne2__c, Ligne3__c, Ligne4__c, Pays__c, CodePostal__c, Ville__c,'
                              +'TECHTypeIdentifiantNational__c, Ligne1Exploitation__c, Ligne2Exploitation__c,'
                              +'DateCotationPF__c, CotationPF__c, DateAgrementEH__c, AgrementSFAC__c, ListeNoire__c,'
                              +'Ligne3Exploitation__c, Ligne4Exploitation__c, VilleExploitation__c, Parent.TECHIdentifiantNational__c, Parent.TECHTypeIdentifiantNational__c, '
                              +'CodePostalExploitation__c, PaysExploitation__c, LastModifiedById, ParentId, '
                              +'Statut__c, AgencePF__c, TECHCompteurAppelsWS__c, TECHWS__c, CategorieCompte__c, IrreductibleVIP__c, RecopierAdressePrincipale__c, TECHIdNatCPExp__c '
                              +'FROM Account WHERE ((RecordTypeID = \''
                                                    + Label.CPT_RecordTypeId_CompteProspectClient 
                                                    + '\' OR RecordTypeID = \''
                                                   // + Label.CPT_RecordTypeId_Administration15 
                                                    + '\' OR RecordTypeID = \''
                                                   // + Label.CPT_RecordTypeId_MultiNiveau 
                                                    + '\' OR RecordTypeID = \''
                                                   // + Label.CPT_RecordTypeId_GrandCompte 
                                                    + '\' OR RecordTypeID = \''
                                                    + Label.CPT_RecordTypeId_CompteClient 
                                                    + '\') AND Statut__c = \''+ Label.CPT_Statut_Erreur_EH +'\' AND TECHCompteurAppelsWS__c > 0)';
                               
        u=[select id, TECHTodayAP09Compte__c from UtilsBatch__c where Name = 'ERG 1'];
        
        if(u.TECHTodayAP09Compte__c != system.today())
        {
            query += ' OR ( (Statut__c = \'' + Label.CPT_Statut_Bloque+'\' OR Statut__c = \''+ Label.CPT_Statut_Erreur_EH + '\') AND (RecordTypeId = \''                                                                                                                                                                                             + '\' OR RecordTypeId = \'' 
            //+ Label.CPT_RecordTypeId_Administration15
            + '\' OR RecordTypeId = \'' 
           // + Label.CPT_RecordTypeId_MultiNiveau
            + '\' OR RecordTypeId = \'' 
           // + Label.CPT_RecordTypeId_GrandCompte
            + '\' OR RecordTypeId = \'' 
            + Label.CPT_RecordTypeId_CompteClient
            + '\'))';
            u.TECHTodayAP09Compte__c = system.today();
            update u;
        }
                               
        System.Debug(query);
        System.Debug('>>>> AP09Compte_BATCH End start <<<<');
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, list<sObject> scope){
        System.Debug('>>>> AP09Compte_BATCH Start execute <<<<');
        
        list<Account> listAccounts=(list<Account>)scope;
        AP09Compte.processCreation2(listAccounts,false,false);
        
    }
    
    global void finish(Database.BatchableContext bc){
        System.Debug('>>>> AP09Compte_BATCH Start finish <<<<');
        
       // System.scheduleBatch(new AP09Compte_BATCH(), 'Web Service Batch', 5);
        
        System.Debug('>>>> AP09Compte_BATCH End finish <<<<');
    }
}