unpackaged/main/default/objects/Account/fields/AgrementSFAC__c.field-meta.xml
<CustomField>
    <fullName>AgrementSFAC__c</fullName>
    <label>Agrément</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CotationPF__c.field-meta.xml
<CustomField>
    <fullName>CotationPF__c</fullName>
    <description>Grade de 1 à 10</description>
    <label>Grade Allianz</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ListeNoire__c.field-meta.xml
<CustomField>
    <fullName>ListeNoire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refus</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHDateListeNoire__c.field-meta.xml
<CustomField>
    <fullName>TECHDateListeNoire__c</fullName>
    <description>CPT-RG-021 et CPT-RG-022</description>
    <label>TECH Date Liste Noire</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <formula>if
(
OR(
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusSiteAccount,
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusUltimateAccount,
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusClientAccount)
,
IF
(AND(ISPICKVAL(Status,&quot;Nouvelle&quot;), Requete_en_attente__c ==FALSE),IMAGE(&quot;/client/resource/1556207842000/Case_Nouvelle_V2?&quot;,&quot;Nouvelle&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;Nouvelle&quot;), Requete_en_attente__c ==TRUE),IMAGE(&quot;/client/resource/1556207856000/Case_Nouvelle_Attente_V2?&quot;,&quot;Attente&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;En_Cours&quot;), Requete_en_attente__c ==FALSE),IMAGE(&quot;/client/resource/1561547731000/Case_EnCours_V2?&quot;,&quot;En Cours&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;En_Cours&quot;), Requete_en_attente__c == TRUE),IMAGE(&quot;/client/resource/1556207885000/Case_EnCours_Attente_V2?&quot;,&quot;Attente&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;Terminee&quot;),IMAGE(&quot;/client/resource/1556207905000/Case_Ferme_V2?&quot;,&quot;Terminée&quot;,20,130),&#39;&#39;)))))
,
IF
(AND(ISPICKVAL(Status,&quot;Nouvelle&quot;), Requete_en_attente__c ==FALSE),IMAGE(&quot;/resource/1556207842000/Case_Nouvelle_V2?&quot;,&quot;Nouvelle&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;Nouvelle&quot;), Requete_en_attente__c ==TRUE),IMAGE(&quot;/resource/1556207856000/Case_Nouvelle_Attente_V2?&quot;,&quot;Attente&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;En_Cours&quot;), Requete_en_attente__c ==FALSE),IMAGE(&quot;/resource/1561547731000/Case_EnCours_V2?&quot;,&quot;En Cours&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;En_Cours&quot;), Requete_en_attente__c == TRUE),IMAGE(&quot;/resource/1556207885000/Case_EnCours_Attente_V2?&quot;,&quot;Attente&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;Terminee&quot;),IMAGE(&quot;/resource/1556207905000/Case_Ferme_V2?&quot;,&quot;Terminée&quot;,20,130),&#39;&#39;)))))
)</formula>
    <label>Statut</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/OpportunityWarningHeader.cls
public class OpportunityWarningHeader {
    public Opportunity currentOpp;
    @AuraEnabled
    public Boolean DisplayWarning {get;set;}
    
	public OpportunityWarningHeader (ApexPages.StandardController controller) {
        this.currentOpp= (Opportunity) controller.getRecord();
        this.currentOpp= [SELECT AccountId,Account.ListeNoire__c, Account.TECHDateListeNoire__c, Account.Statut__c,StageName  FROM Opportunity WHERE Id =: this.currentOpp.Id][0];
        Account acc= [SELECT  CotationPF__c,AgrementSFAC__c,Statut__c from Account where id =:this.currentOpp.AccountId];
        System.debug('##Cotation PF : '+String.valueOf(acc.CotationPF__c));
        decimal statutOpp=decimal.valueOf(this.currentOpp.StageName.substring(0,1));
        //Affichage du message d'avertissement cotation seulement si l'opportunité a un statut inférieur à 5
       
        	//this.DisplayWarning=acc.CotationPF__c>7?true:false;
        	if((statutOpp<5 && acc.Statut__c ==Label.OPP_Statut_Attente_Validation_CM) )
            {
                this.DisplayWarning = true;
               
            }
        	else
        	{
            this.DisplayWarning=false;
        	}
        System.debug('DisplayWarning : '+String.valueOf(this.DisplayWarning));	
    }
    @AuraEnabled
    public static boolean IsDisplayWarning(String opportunityId){
        boolean displayWarning=false;
        System.debug('##TEST :'+String.valueOf(opportunityId));
        Opportunity currOpp= [SELECT AccountId,Account.ListeNoire__c, Account.TECHDateListeNoire__c,Account.AgrementSFAC__c, Account.Statut__c,StageName  FROM Opportunity WHERE Id =: opportunityId][0];
        Account acc= [SELECT  CotationPF__c,AgrementSFAC__c,Statut__c, ListeNoire__c from Account where id =:currOpp.AccountId];
        System.debug('##Cotation PF : '+String.valueOf(acc.CotationPF__c));
        decimal statutOpp=decimal.valueOf(currOpp.StageName.substring(0,1));
        //Affichage du message d'avertissement cotation seulement si l'opportunité a un statut inférieur à 5
        if((statutOpp<5 && acc.Statut__c == Label.OPP_Statut_Attente_Validation_CM) )
            {
                displayWarning = true;
            }
        //Affichage du message d'avertissement cotation seulement lorsqu'un client a un grade 9 avec case à cocher "Refus"
        else if(acc.CotationPF__c == 9 && acc.ListeNoire__c == true  )
            {
            	displayWarning = true;
            }
        else
        {
            displayWarning=false;
        }
        return displayWarning;
    }
}