unpackaged/main/default/objects/Account/fields/Ancestor__c.field-meta.xml
<CustomField>
    <fullName>Ancestor__c</fullName>
    <label>Ancestor</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Empreinte_Geographique__c.field-meta.xml
<CustomField>
    <fullName>Empreinte_Geographique__c</fullName>
    <label>Empreinte Géographique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Is_Parent__c.field-meta.xml
<CustomField>
    <fullName>Is_Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Parent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Flow_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Flow_Update__c</fullName>
    <label>Last Flow Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ClearAncestorFieldBatch.cls
// Batch pour vider le champ Ancestor__c des enregistrements Account
global class ClearAncestorFieldBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //return Database.getQueryLocator([SELECT Id, Ancestor__c, Is_Parent__c FROM Account ]);
        return Database.getQueryLocator([SELECT Id, Is_Parent__c,Ancestor__c, Empreinte_Geographique__c,Last_Flow_Update__c FROM Account ]);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
                    List<Account> ancestors = new List<Account>();

        for(Account acc : scope) {
            acc.Ancestor__c = '';
            acc.Is_Parent__c = false;
            acc.Empreinte_Geographique__c = '';
            acc.Last_Flow_Update__c = '';
            
            
            ancestors.add(acc);
        }
        update ancestors;
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Champ Ancestor__c vidé pour tous les enregistrements Account.');
    }
}