unpackaged/main/default/objects/Account/fields/CodeNACE__c.field-meta.xml
<CustomField>
    <fullName>CodeNACE__c</fullName>
    <label>Code NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_Code_Activite_NACE__c.field-meta.xml
<CustomField>
    <fullName>DB_Code_Activite_NACE__c</fullName>
    <label>Code Activité NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_DU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_DU__c</fullName>
    <label>DUNS# DU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Note_Nombre_employe__c.field-meta.xml
<CustomField>
    <fullName>Note_Nombre_employe__c</fullName>
    <label>Note Nombre d’employé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pourcentage_effectif__c.field-meta.xml
<CustomField>
    <fullName>Pourcentage_effectif__c</fullName>
    <label>Pourcentage d&#39;effectif</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EmployeeNoteRule__c/EmployeeNoteRule__c.object-meta.xml
<CustomObject>
    <label>Employee Note Rule</label>
    <nameField>
        <label>EmployeeNoteRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Note Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EmployeeNoteRule__c/fields/Code_Nace__c.field-meta.xml
<CustomField>
    <fullName>Code_Nace__c</fullName>
    <label>Code Nace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EmployeeNoteRule__c/fields/Maximum_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Percentage__c</fullName>
    <label>Maximum Percentage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EmployeeNoteRule__c/fields/Minimum_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Percentage__c</fullName>
    <label>Minimum Percentage</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EmployeeNoteRule__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/EmployeeCountNoteUpdateBatch.cls
global class EmployeeCountNoteUpdateBatch implements Database.Batchable<sObject>, Database.Stateful 
{
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = 'SELECT Id, DB_Code_Activite_NACE__c, CodeNACE__c, DB_DUNS_DU__c, Pourcentage_effectif__c, Note_Nombre_employe__c FROM Account ';
		return Database.getQueryLocator(query);
    }
    
     
    global void execute(Database.BatchableContext BC, List<Account> scope) 
    {
        List<Account> accountToUpdate = new List<Account>();

        // Créer un ensemble pour stocker les ID des enregistrements déjà ajoutés
		Set<Id> existingIds = new Set<Id>();
        for (Account acc : scope) 
        {
            for (EmployeeNoteRule__c rule : [SELECT Code_Nace__c, Minimum_Percentage__c, Maximum_Percentage__c, Note__c FROM EmployeeNoteRule__c where Code_Nace__c =:acc.DB_Code_Activite_NACE__c]) 
            {
                if (acc.Pourcentage_effectif__c != null && acc.Pourcentage_effectif__c >= rule.Minimum_Percentage__c && acc.Pourcentage_effectif__c < rule.Maximum_Percentage__c) 
                {
                    // Vérifier si l'ID de l'enregistrement n'est pas déjà dans l'ensemble existingIds
                    if (!existingIds.contains(acc.Id)) 
                    {
                        // Ajouter l'ID de l'enregistrement à l'ensemble existingIds
                        existingIds.add(acc.Id);
                        // Ajouter l'enregistrement à la liste accountToUpdate
                        acc.Note_Nombre_employe__c = rule.Note__c;
                        accountToUpdate.add(acc);
                    }
           		 }
        	}
        }
 
		if(!accountToUpdate.isEmpty())
        {
        	update accountToUpdate;
        }  
    }
    
    global void finish(Database.BatchableContext BC) 
    {
		// Préparer et envoyer l'email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'helachboura@petitforestier.fr'}; 
        mail.setToAddresses(toAddresses);
        mail.setSubject('Batch Process Completed: EmployeeCountNoteUpdateBatch');
        
        // Construire le corps de l'email
        String emailBody = 'The batch EmployeeCountNoteUpdateBatch has finished:\n\n';

        mail.setPlainTextBody(emailBody);
        
        // Envoyer l'email
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });    
    }

}