unpackaged/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <formula>IF(
    BEGINS(TEXT(PaysRegionPF__c), &quot;DRO&quot;), 
    &#39;FR&#39;,
    IF(
        BEGINS(TEXT(PaysRegionPF__c), &quot;STFR&quot;),
        &#39;FR&#39;,
        CASE(
            TEXT(PaysRegionPF__c),
            &#39;PFUK&#39;, &#39;GB&#39;,
            &#39;PIRL&#39;, &#39;IE&#39;,
            &#39;PIMA&#39;, &#39;MA&#39;,
            &#39;PITA&#39;, &#39;IT&#39;,
            &#39;PIND&#39;, &#39;NL&#39;,
            &#39;PIAT&#39;, &#39;AT&#39;,
            &#39;PIPL&#39;, &#39;PL&#39;,
            &#39;PIPT&#39;, &#39;PT&#39;,
            &#39;PILU&#39;, &#39;LU&#39;,
            &#39;PIES&#39;, &#39;ES&#39;,
            &#39;PIDE&#39;, &#39;DE&#39;,
            &#39;PIBE&#39;, &#39;BE&#39;,
            &#39;PICZ&#39;, &#39;SK&#39;,
            &#39;PICH&#39;, &#39;CH&#39;,
            &#39;PIAE&#39;, &#39;AE&#39;,
            &#39;PIBU&#39;, &#39;BU&#39;,
            &#39;PIZA&#39;, &#39;ZA&#39;,


            &#39;-&#39;
        )
    )
)</formula>
    <label>CodePays</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantNational__c</fullName>
    <label>Identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IDEulerHermes__c.field-meta.xml
<CustomField>
    <fullName>IDEulerHermes__c</fullName>
    <label>ID Euler Hermes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ModeCreation__c.field-meta.xml
<CustomField>
    <fullName>ModeCreation__c</fullName>
    <inlineHelpText>Define</inlineHelpText>
    <label>Mode de création</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Création manuelle</fullName>
                <default>true</default>
                <label>Création manuelle</label>
            </value>
            <value>
                <fullName>Import en masse</fullName>
            </value>
            <value>
                <fullName>Piste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TypeIdentifiantNational__c</fullName>
    <label>Type d&#39;identifiant national</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CNIE</fullName>
            </value>
            <value>
                <fullName>COC</fullName>
            </value>
            <value>
                <fullName>COCCH</fullName>
            </value>
            <value>
                <fullName>COCCHE</fullName>
            </value>
            <value>
                <fullName>COFIS</fullName>
            </value>
            <value>
                <fullName>CRO</fullName>
            </value>
            <value>
                <fullName>DELTA</fullName>
            </value>
            <value>
                <fullName>HRB</fullName>
            </value>
            <value>
                <fullName>HRM</fullName>
            </value>
            <value>
                <fullName>IBLC</fullName>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
            <value>
                <fullName>KVK</fullName>
            </value>
            <value>
                <fullName>NIPC</fullName>
            </value>
            <value>
                <fullName>P.IVA</fullName>
            </value>
            <value>
                <fullName>RCLU</fullName>
            </value>
            <value>
                <fullName>RNMA</fullName>
            </value>
            <value>
                <fullName>RNPL</fullName>
            </value>
            <value>
                <fullName>RNPT</fullName>
            </value>
            <value>
                <fullName>SIREN</fullName>
            </value>
            <value>
                <fullName>TVABE</fullName>
            </value>
            <value>
                <fullName>TVADE</fullName>
            </value>
            <value>
                <fullName>TVAPL</fullName>
            </value>
            <value>
                <fullName>En création</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>PRISMA</fullName>
            </value>
            <value>
                <fullName>RNHU</fullName>
                <label>RNHU (cégjegyzékszám)</label>
            </value>
            <value>
                <fullName>VATHU</fullName>
                <label>VATHU (Adoszam)</label>
            </value>
            <value>
                <fullName>TVAIT</fullName>
            </value>
            <value>
                <fullName>ICOSK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TypeIdentifiantNational__c/TypeIdentifiantNational__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Type Identifiant National</label>
</CustomObject>

unpackaged/main/default/objects/TypeIdentifiantNational__c/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/VFE11_CompteReload.cls
public class VFE11_CompteReload {

    public Account currentAcc{get;set;}
    public boolean spaces{get;set;}
    public boolean showValidationButton{get;set;}
    public set<Id> creditManagementUsers{get;set;}
    public Boolean refreshPage {get; set;}
    
    public VFE11_CompteReload (ApexPages.StandardController controller) {
        this.currentAcc= (Account) controller.getRecord();
        System.debug('currentAcc : '+ currentAcc);
        currentAcc= [SELECT Statut__c, ModeCreation__c, CreatedBy.LastName
                     FROM Account
                     WHERE Id =: currentAcc.Id][0];
        refreshPage=FALSE;
        showValidationButton=FALSE;
        
        creditManagementUsers=new set<Id>();
        for(GroupMember gm: [select UserOrGroupId
                             from GroupMember
                             where Group.Name=:Label.GRP_CreditManagement_Name]){
            creditManagementUsers.add(gm.UserOrGroupId);
        }
    }
    
    public void reload() {
        spaces = !Utils_Methods.isSF1();
        
        if(currentAcc.Statut__c == Label.CPT_Statut_Draft) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING, Label.CPT_Alert_RefreshPageDraft);
            ApexPages.addMessage(myMsg);
        }
        if(
           //Le bouton Validation EH est visible pour les utilisateurs du Credit Management (groupe public) si le compte est en statut Draft, Bloqué ou Erreur EH.
           ((currentAcc.Statut__c == Label.CPT_Statut_Draft
            || currentAcc.Statut__c == Label.CPT_Statut_Bloque
            || currentAcc.Statut__c == Label.CPT_Statut_Erreur_EH)
           &&
            creditManagementUsers.contains(UserInfo.getUserId())
           )
           ||
           //Le bouton Validation EH est visible pour tous les utilisateurs sur les comptes en statut "Draft", en mode de création "Import en masse" et créés par OP_TECH.
           (currentAcc.Statut__c==Label.CPT_Statut_Draft
            && currentAcc.ModeCreation__c==Label.CPT_ModeCreation_ImportEnMasse
           )
          ){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.CPT_Alert_CliquerBoutonEH));
            showValidationButton=true;
        }
    }
    
    public PageReference validateAccount(){
        Account acc = [select id,CodePays__c,IdentifiantNational__c,TypeIdentifiantNational__c,BillingCountryCode,Statut__c,IDEulerHermes__c from account where id=:currentAcc.id];
        if(acc.Statut__c != 'Validé') {
            Account accValidated = AllianzWebServiceRest.validateCompany(acc);
            acc.IDEulerHermes__c = accValidated.IDEulerHermes__c;
            acc.Statut__c = accValidated.Statut__c;
            update acc;
        }
        refreshPage=TRUE;
        return null;
        
    }
}