unpackaged/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal (-Facturation-)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IDEulerHermes__c.field-meta.xml
<CustomField>
    <fullName>IDEulerHermes__c</fullName>
    <label>ID Euler Hermes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne1__c.field-meta.xml
<CustomField>
    <fullName>Ligne1__c</fullName>
    <label>Ligne 1 (-Facturation-)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville (-Facturation-)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ligne1__c.field-meta.xml
<CustomField>
    <fullName>Ligne1__c</fullName>
    <label>Ligne 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BOLIVIE</fullName>
            </value>
            <value>
                <fullName>BOSNIE HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>BURKINA FASO</fullName>
            </value>
            <value>
                <fullName>CAMBODGE</fullName>
            </value>
            <value>
                <fullName>CAMEROUN</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILI</fullName>
            </value>
            <value>
                <fullName>CHINE</fullName>
            </value>
            <value>
                <fullName>CHYPRE</fullName>
            </value>
            <value>
                <fullName>CISJORDANIE</fullName>
            </value>
            <value>
                <fullName>COLOMBIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/TypeProduits__c.field-meta.xml
<CustomField>
    <fullName>TypeProduits__c</fullName>
    <inlineHelpText>Famille</inlineHelpText>
    <label>Type de Produit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Carrosseries</fullName>
            </value>
            <value>
                <fullName>Containers</fullName>
                <color>#FF9900</color>
                <label>Containers</label>
            </value>
            <value>
                <fullName>Meubles</fullName>
                <color>#33CCFF</color>
                <label>Meubles</label>
            </value>
            <value>
                <fullName>Véhicules Frigorifiques</fullName>
                <color>#33CC00</color>
                <label>Véhicules Frigorifiques</label>
            </value>
            <value>
                <fullName>Véhicules Secs</fullName>
                <color>#FF0000</color>
                <label>Véhicules Secs</label>
            </value>
            <value>
                <fullName>Refrigerated vehicle</fullName>
            </value>
            <value>
                <fullName>Dry vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>Objet utilisé pour recueillir les devis SAP CPQ</description>
    <label>Devis SAP CPQ</label>
    <nameField>
        <label>Numéro du devis</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devis SAP CPQ</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <formula>text(Account__r.Pays__c)</formula>
    <label>Pays</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
            </value>
            <value>
                <fullName>En attente approbation</fullName>
            </value>
            <value>
                <fullName>Autorisé</fullName>
            </value>
            <value>
                <fullName>Non Autorisé</fullName>
            </value>
            <value>
                <fullName>Devis Envoyé</fullName>
            </value>
            <value>
                <fullName>Devis annulé</fullName>
            </value>
            <value>
                <fullName>Devis refusé</fullName>
            </value>
            <value>
                <fullName>Devis validé</fullName>
            </value>
            <value>
                <fullName>Contrat envoyé</fullName>
            </value>
            <value>
                <fullName>Contrat signé</fullName>
            </value>
            <value>
                <fullName>Contrat validé</fullName>
            </value>
            <value>
                <fullName>Devis échu</fullName>
            </value>
            <value>
                <fullName>Brouillon - étude HS en cours</fullName>
            </value>
            <value>
                <fullName>Brouillon - étude HS validée</fullName>
            </value>
            <value>
                <fullName>Création de contrat en cours</fullName>
            </value>
            <value>
                <fullName>Echec de la création du contrat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/TypeProduits__c.field-meta.xml
<CustomField>
    <fullName>TypeProduits__c</fullName>
    <formula>text( SBQQ__Opportunity2__r.TypeProduits__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CopyFiles_QuoteTest.cls
@isTest

public class CopyFiles_QuoteTest {
    @isTest static void TestCopyFileFicheRenseignement()
    {
        test.startTest();
        Account acc = TestDataFactory.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        acc.Statut__c='Validé CM';acc.IDEulerHermes__c='123';acc.Ligne1__c='Ligne1';acc.CodePostal__c='93420';acc.ville__c='Villepinte';acc.Pays__c='France';
        update acc;
         TestDataFactory.createFinancialCond(acc.Id);
        Contact Cont = TestDataFactory.createContact('Test', acc.id);
        blng__LegalEntity__c legEnt =  TestDataFactory.createLegalEntity();
        Opportunity opp = TestDataFactory.createOpportunity('opp1', acc.Id, null, Label.OPP_StageName_OpportuniteCreee, 'PRG', legEnt.Id);
        opp.TypeProduits__c='Containers';Update opp;
        SBQQ__Quote__c quote = TestDataFactory.createCPQQuote(opp.Id, true, acc.Id, Date.today(), 12);
		Information_Sheet__c Fiche = new Information_Sheet__c();
        Fiche.Quote__c = quote.id;
        insert Fiche;
        ContentVersion cv = new ContentVersion();
        cv.Title = 'FR-TEST-ttile';
        cv.PathOnClient = 'FR-TEST.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
       
      	///
        ContentDocumentLink NewCDL = new ContentDocumentLink();
        NewCDL.ContentDocumentId = [select contentdocumentid from contentversion where id =: cv.id].contentdocumentid;
        NewCDL.LinkedEntityId = quote.id;
        NewCDL.ShareType='I';
        NewCDL.Visibility='InternalUsers';
        insert NewCDL;
        
        //test
        list<ContentDocumentLink> L = [select id from ContentDocumentLink where LinkedEntityId=:fiche.id];
        system.debug('L='+L);
        system.assertEquals(1, L.size());
        test.stopTest();
    }
    
     @isTest static void TestCopyFileContratMA()
    {
        test.startTest();
        Account acc = TestDataFactory.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        acc.Statut__c='Validé CM';acc.IDEulerHermes__c='123';acc.Ligne1__c='Ligne1';acc.CodePostal__c='93420';acc.ville__c='Villepinte';acc.Pays__c='France';
        update acc;
         TestDataFactory.createFinancialCond(acc.Id);
        Contact Cont = TestDataFactory.createContact('Test', acc.id);
        blng__LegalEntity__c legEnt =  TestDataFactory.createLegalEntity();
        Opportunity opp = TestDataFactory.createOpportunity('opp1', acc.Id, null, Label.OPP_StageName_OpportuniteCreee, 'PRG', legEnt.Id);
        opp.TypeProduits__c='Containers';Update opp;
        SBQQ__Quote__c quote = TestDataFactory.createCPQQuote(opp.Id, true, acc.Id, Date.today(), 12);
		//Information_Sheet__c Fiche = new Information_Sheet__c();
		Order order = TestDataFactory.createOrder(acc.Id, Date.today(), Date.today().addMonths(12), quote.Id, opp.Id); 
        
		//Contract ct = TestDataFactory.createContract(acc.Id, quote.Id, 'Draft', Date.today(), 12, Date.today().addMonths(12).addDays(2), order.Id, opp.Id);
		//Contract ct = TestDataFactory.createContract(acc.Id, quote.Id, 'Draft', Date.today(), 12, Date.today().addMonths(12).addDays(2), order.Id, opp.Id);
          Contract ct = new Contract();
        ct.AccountId = acc.id;
        ct.Status = 'Draft';
        ct.StartDate = Date.today();
        ct.EndDate =  Date.today().addMonths(12).addDays(2);
        ct.ContractTerm = 12;
        ct.SBQQ__Quote__c = quote.Id;
        ct.SBQQ__Order__c = order.Id;
        ct.SBQQ__Opportunity__c = opp.Id;
        insert ct;
		String ContractNumber = [select ContractNumber from Contract where id=:ct.id].ContractNumber;
        system.debug('ct.ContractNumber:'+ContractNumber);
        ContentVersion cv = new ContentVersion();
        cv.Title = 'MA container_'+ContractNumber+'_2022-12-19_completed';
        cv.PathOnClient = 'MA Container_'+ContractNumber+'_2022-12-19_completed.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
       
        ContentDocumentLink NewCDL = new ContentDocumentLink();
        NewCDL.ContentDocumentId = [select contentdocumentid from contentversion where id =: cv.id].contentdocumentid;
        NewCDL.LinkedEntityId = quote.id;
        NewCDL.ShareType='I';
        NewCDL.Visibility='InternalUsers';
        insert NewCDL;
        
        //test
        list<ContentDocumentLink> L = [select id from ContentDocumentLink where LinkedEntityId=:ct.id];
        system.debug('L='+L);
        system.assertEquals(1, L.size());
        test.stopTest();
    }
      @isTest static void TestCopyFileContract()
    {
        test.startTest();
        Account acc = TestDataFactory.createAccount('Account1', null, null, Label.CPT_RecordTypeId_CompteClient);
        acc.Statut__c='Validé CM';acc.IDEulerHermes__c='123';acc.Ligne1__c='Ligne1';acc.CodePostal__c='93420';acc.ville__c='Villepinte';acc.Pays__c='France';
        update acc;
         TestDataFactory.createFinancialCond(acc.Id);
        Contact Cont = TestDataFactory.createContact('Test', acc.id);
        blng__LegalEntity__c legEnt =  TestDataFactory.createLegalEntity();
        Opportunity opp = TestDataFactory.createOpportunity('opp1', acc.Id, null, Label.OPP_StageName_OpportuniteCreee, 'PRG', legEnt.Id);
        opp.TypeProduits__c='Containers';Update opp;
        SBQQ__Quote__c quote = TestDataFactory.createCPQQuote(opp.Id, true, acc.Id, Date.today(), 12);
		
		Order order = TestDataFactory.createOrder(acc.Id, Date.today(), Date.today().addMonths(12), quote.Id, opp.Id); 
       
		//Contract ct = TestDataFactory.createContract(acc.Id, quote.Id, 'Draft', Date.today(), 12, Date.today().addMonths(12).addDays(2), order.Id, opp.Id);
        Contract ct = new Contract();
        ct.AccountId = acc.id;
        ct.Status = 'Draft';
        ct.StartDate = Date.today();
        ct.EndDate =  Date.today().addMonths(12).addDays(2);
        ct.ContractTerm = 12;
        ct.SBQQ__Quote__c = quote.Id;
        ct.SBQQ__Order__c = order.Id;
        ct.SBQQ__Opportunity__c = opp.Id;
        insert ct;
        
        String ContractNumber = [select ContractNumber from Contract where id=:ct.id].ContractNumber;
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Contrat simplifié_'+ContractNumber+'_2022-12-19_completed';
        cv.PathOnClient = 'Contrat simplifié_'+ContractNumber+'_2022-12-19_completed.pdf';system.debug('ContractNumber: '+ContractNumber);
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
       
      	///
        ContentDocumentLink NewCDL = new ContentDocumentLink();
        NewCDL.ContentDocumentId = [select contentdocumentid from contentversion where id =: cv.id].contentdocumentid;
        NewCDL.LinkedEntityId = quote.id;
        NewCDL.ShareType='I';
        NewCDL.Visibility='InternalUsers';
        insert NewCDL;
        
        //test
        list<ContentDocumentLink> L = [select id from ContentDocumentLink where LinkedEntityId=:ct.id];
        system.debug('L='+L);
        system.assertEquals(1, L.size());
        test.stopTest();
    }
}