unpackaged/main/default/objects/Account/fields/CodeNACE__c.field-meta.xml
<CustomField>
    <fullName>CodeNACE__c</fullName>
    <label>Code NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_Code_Activite_NACE__c.field-meta.xml
<CustomField>
    <fullName>DB_Code_Activite_NACE__c</fullName>
    <label>Code Activité NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Batch_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Update__c</fullName>
    <label>Last Batch Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segmentation</label>
    <referenceTo>Segmentation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <formula>TEXT(SalesArea__r.BusinessLine__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ligne de produit</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Last_Batch_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Update__c</fullName>
    <label>Last Batch Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segmentation</label>
    <referenceTo>Segmentation__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>Vues_Commerciales_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Verified__c.field-meta.xml
<CustomField>
    <fullName>Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Segmentation__c/Segmentation__c.object-meta.xml
<CustomObject>
    <label>Segmentation</label>
    <nameField>
        <displayFormat>Segmentation N°{0000}</displayFormat>
        <label>Nom de Segmentation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Segmentation__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <label>Business Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessLine</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Segmentation__c/fields/CodeNACE__c.field-meta.xml
<CustomField>
    <fullName>CodeNACE__c</fullName>
    <label>Code NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Segmentation__c/fields/Notation__c.field-meta.xml
<CustomField>
    <fullName>Notation__c</fullName>
    <label>Notation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Segmentation__c/fields/NotationPotentielExtension__c.field-meta.xml
<CustomField>
    <fullName>NotationPotentielExtension__c</fullName>
    <label>Notation de Potentiel d&#39;Extension</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/BusinessLine.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Containers</fullName>
    </customValue>
    <customValue>
        <fullName>Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Frigorifiques</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Secs</fullName>
    </customValue>
    <customValue>
        <fullName>Cession</fullName>
    </customValue>
    <customValue>
        <fullName>Vente</fullName>
        <isActive>false</isActive>
        <label>Vente</label>
    </customValue>
    <customValue>
        <fullName>Véhicules</fullName>
        <isActive>false</isActive>
        <label>Véhicules</label>
    </customValue>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountSegmentationSyncBatch.cls
global class AccountSegmentationSyncBatch implements Database.Batchable<sObject>, Database.Stateful 
{
    private Integer retryCount; // Variable de classe statique pour compter les tentatives
    private String filterPaysRegionPF;

    // Constructeur prenant le nombre de tentatives en paramètre
    global AccountSegmentationSyncBatch(Integer retryCount, String filterPaysRegionPF) 
    {
        this.retryCount = retryCount;
        this.filterPaysRegionPF = filterPaysRegionPF;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator([
            SELECT Id, BusinessLine__c, CodeNACE__c, Notation__c, RecordTypeId, NotationPotentielExtension__c	
            FROM Segmentation__c
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Segmentation__c> scope) 
   	{
        
         Map<String, Account> accountMap = new Map<String, Account>();
        Set<String> codeNACESet = new Set<String>();
        for (Segmentation__c segmentationRec : scope) 
        {
            codeNACESet.add(segmentationRec.CodeNACE__c);
        }
        
        List<Account> accList = new List<Account>();
        if(filterPaysRegionPF!=null && filterPaysRegionPF!='')
        {
            accList = [SELECT ID,Segmentation__c, Verified__c, DB_Code_Activite_NACE__c	, CodeNACE__c, Last_Batch_Update__c FROM Account where Segmentation__c = '' AND DB_Code_Activite_NACE__c IN :codeNACESet AND PaysRegionPF__c = :filterPaysRegionPF AND Verified__c = false  ORDER BY LastModifiedDate ASC limit 150];  
        }
        else   
        {
            accList = [SELECT ID,Segmentation__c, Verified__c, DB_Code_Activite_NACE__c	, CodeNACE__c, Last_Batch_Update__c FROM Account where Segmentation__c = '' AND DB_Code_Activite_NACE__c IN :codeNACESet AND Verified__c = false ORDER BY LastModifiedDate ASC limit 150];  
        } 
           
        // Construire une carte de CodeNACE__c pour chaque enregistrement SalesAreaData__c
        for(Account acc : accList)  
        { 
            accountMap.put(acc.Id, acc);
        } 

        List<Account> accToUpdate = new List<Account>();
        
        for(String accRecordId  : accountMap.keySet()) 
        {
            // Récupérer l'enregistrement SalesAreaData__c correspondant à l'ID
    		Account accRecord = accountMap.get(accRecordId);
            for(Segmentation__c segmentationRec : scope) 
            {
                if(accRecord.DB_Code_Activite_NACE__c == segmentationRec.CodeNACE__c && accRecord.DB_Code_Activite_NACE__c != '')
                {
                    accRecord.Segmentation__c = segmentationRec.Id;
                    DateTime currentDateTime = System.now();
                    String formattedDateTime = currentDateTime.format('yyyy-MM-dd HH:mm:ss');
                    accRecord.Last_Batch_Update__c = formattedDateTime;
                    accRecord.Verified__c = true;
                    accToUpdate.add(accRecord); 
                }
            }
        }
        
        // Mettre à jour les enregistrements SalesAreaData__c
        update accToUpdate;        
    }

    global void finish(Database.BatchableContext BC) 
    {
        // Vérifier s'il existe encore des enregistrements SalesAreaData__c avec Segmentation__c vide
        Integer accCount = [SELECT COUNT() FROM Account WHERE Segmentation__c = '' AND PaysRegionPF__c = :filterPaysRegionPF];
        if (accCount > 0 && retryCount < 50) 
        {
            // Augmenter le compteur de tentative
            retryCount++;
            // Relancer le batch avec une nouvelle plage de données
        	Database.executeBatch(new AccountSegmentationSyncBatch(retryCount, filterPaysRegionPF), 50);
        }
        else 
        { 
            InitVerifiedAccountsBatch batchInitVerifiedAccountsBatch =new InitVerifiedAccountsBatch(); 
 			Database.executeBatch(batchInitVerifiedAccountsBatch, 100);
            // Préparer et envoyer l'email
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {'helachboura@petitforestier.fr'}; 
            mail.setToAddresses(toAddresses);
            mail.setSubject('Batch Process Completed: AccountSegmentationSyncBatch => Note Potentiel Extension');
            
            // Construire le corps de l'email
            String emailBody = 'The batch AccountSegmentationSyncBatch has finished:\n\n';
    
            mail.setPlainTextBody(emailBody);
            
            // Envoyer l'email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
    }
}