unpackaged/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal (-Facturation-)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IDEulerHermes__c.field-meta.xml
<CustomField>
    <fullName>IDEulerHermes__c</fullName>
    <label>ID Euler Hermes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ligne1__c.field-meta.xml
<CustomField>
    <fullName>Ligne1__c</fullName>
    <label>Ligne 1 (-Facturation-)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville (-Facturation-)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ligne1__c.field-meta.xml
<CustomField>
    <fullName>Ligne1__c</fullName>
    <label>Ligne 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BOLIVIE</fullName>
            </value>
            <value>
                <fullName>BOSNIE HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>BURKINA FASO</fullName>
            </value>
            <value>
                <fullName>CAMBODGE</fullName>
            </value>
            <value>
                <fullName>CAMEROUN</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILI</fullName>
            </value>
            <value>
                <fullName>CHINE</fullName>
            </value>
            <value>
                <fullName>CHYPRE</fullName>
            </value>
            <value>
                <fullName>CISJORDANIE</fullName>
            </value>
            <value>
                <fullName>COLOMBIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Duree_de_location__c.field-meta.xml
<CustomField>
    <fullName>Duree_de_location__c</fullName>
    <inlineHelpText>(Mois)</inlineHelpText>
    <label>Durée de location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>72</fullName>
            </value>
            <value>
                <fullName>84</fullName>
            </value>
            <value>
                <fullName>96</fullName>
            </value>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Kilom_trage__c.field-meta.xml
<CustomField>
    <fullName>Kilom_trage__c</fullName>
    <label>Kilométrage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Sous_famille__c.field-meta.xml
<CustomField>
    <fullName>Sous_famille__c</fullName>
    <label>Sous-famille</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_produit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>P (Frigo)</fullName>
            </value>
            <value>
                <fullName>P (Sec)</fullName>
            </value>
            <value>
                <fullName>S (Frigo)</fullName>
            </value>
            <value>
                <fullName>T (Frigo)</fullName>
            </value>
            <value>
                <fullName>T (Sec)</fullName>
            </value>
            <value>
                <fullName>V (Frigo)</fullName>
            </value>
            <value>
                <fullName>V (Sec)</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>V (Dry)</fullName>
            </value>
            <value>
                <fullName>L (Dry)</fullName>
            </value>
            <value>
                <fullName>C (Dry)</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>S (Dry)</fullName>
            </value>
            <value>
                <fullName>R (frigo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Type_de_produit__c.field-meta.xml
<CustomField>
    <fullName>Type_de_produit__c</fullName>
    <label>Type de produit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Véhicules Frigorifiques</fullName>
            </value>
            <value>
                <fullName>Véhicules Secs</fullName>
            </value>
            <value>
                <fullName>Refrigerated vehicle</fullName>
            </value>
            <value>
                <fullName>Dry vehicle</fullName>
            </value>
            <value>
                <fullName>Veicolo frigo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/QuoteClass_TEST.cls
@isTest
private class QuoteClass_TEST {
Static testMethod void generateTarificationsTest()
{
    Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
    MyBypass.BypassValidationRules__c = true;
    insert MyBypass;
  
    //OPP
    Account ACC = Utils_TestMethods.createAccount('accName', 'accCodeNAF', null, Label.CPT_RecordTypeId_CompteClient);
    Date dd = Date.newInstance(2020,9,1);
    Opportunity  OPP = Utils_TestMethods.createOpportunity('oppName', '2 - Opportunité qualifiée',dd , ACC);
    insert OPP;
  
    //Quote
    Quote Q = new Quote();
    Q.Name='TEST';
    Q.OpportunityId=OPP.Id;
    Q.CurrencyIsoCode = 'EUR';
    Q.Duree_de_location__c = '24;48';
    Q.Kilom_trage__c=2000;
    Q.RecordTypeId=Label.Quote_RecordTypeId_Parc;
    insert Q;
    
    //Générer les lignes de tarification à l'insertion
    QuoteClass.generateTarifications(Q.Id,Q.CurrencyIsoCode);
    //Générer les lignes de tarification à l'update
    Q.Duree_de_location__c = '36;69';
    Q.Kilom_trage__c=2300;
    update Q;
}
  Static testMethod void generateTarificationsTriggerTest()
  {
    Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
    MyBypass.BypassValidationRules__c = true;
    insert MyBypass;
      
    //Quote  
        Quote Q = new Quote();
        Account ACC = Utils_TestMethods.createAccount('accName', 'accCodeNAF', null, Label.ACC_RecordTypeId_CompteClient);
        ACC.statut__c = 'Validé';ACC.IDEulerHermes__c='12344';ACC.Ligne1__c='Rue';ACC.CodePostal__c='12345';ACC.Ville__c='Paris';ACC.Pays__c='France';
        insert ACC;
        Contact Cont = Utils_TestMethods.createContact('conName', ACC.id);
        insert Cont;
        Date dd = Date.newInstance(2020,9,1);
        Opportunity  OPP = Utils_TestMethods.createOpportunity('oppName', '2 - Opportunité qualifiée',dd , ACC);
        insert OPP;
        Q.Duree_de_location__c='24;48';
        Q.Kilom_trage__c=2000;
        Q.OpportunityId =OPP.id;
        Q.RecordTypeId=Label.Quote_RecordTypeId_Parc;
        Q.Name='TEST';
        Q.Type_de_produit__c='Véhicules Frigorifiques';
        Q.Sous_famille__c ='CF';
        Q.Categorie__c='CF10';
        Q.Sous_Categorie__c='CF10';
        Q.Quantite__c=1;
        Q.Duree__c=24;
        Q.Loyer__c =200;
        Q.KM__c = 3000;
        Q.Origine_de_produit__c='A';
    insert Q;
      
    //Second Quote
        Quote Q2 = new Quote();
        Q2.Duree_de_location__c='24;48';
        Q2.Kilom_trage__c=2000;
        Q2.OpportunityId =OPP.id;
        Q2.RecordTypeId=Label.Quote_RecordTypeId_Parc;
        Q2.Name='TEST2';
        Q2.Type_de_produit__c='Véhicules Frigorifiques';
        Q2.Sous_famille__c ='CF';
        Q2.Categorie__c='CF10';
        Q2.Sous_Categorie__c='CF10';
        Q2.Quantite__c=1;
        Q2.Duree__c=24;
        Q2.Loyer__c =200;
        Q2.KM__c = 3000;
        Q2.Origine_de_produit__c='A';
        //Q2.Synchronise__c=true;
        insert Q2;
        
        //Update Quote
        Q.Duree_de_location__c='24;48';
        Q.Kilom_trage__c=4800;
        update Q;
        //Q.Synchronise__c=true;
        update Q;
      
      //Third Quote
        Quote Q3 = new Quote();
        Q3.Duree_de_location__c='24;48';
        Q3.Kilom_trage__c=2000;
        Q3.OpportunityId =OPP.id;
        Q3.RecordTypeId=Label.Quote_RecordTypeId_Parc;
        Q3.Name='TEST2';
        Q3.Type_de_produit__c='Véhicules Frigorifiques';
        Q3.Sous_famille__c ='CF';
        Q3.Categorie__c='CF10';
        Q3.Sous_Categorie__c='CF10';
        Q3.Quantite__c=1;
        Q3.Duree__c=24;
        Q3.Loyer__c =200;
        Q3.KM__c = 3000;
        Q3.Origine_de_produit__c='A';
       // Q3.Synchronise__c=true;
        insert Q3;
        
        //Update Quote
        Q3.Duree_de_location__c='12;24';
        Q3.Kilom_trage__c=4800;
        update Q3;
        //Q3.Synchronise__c=true;
        //update Q3;
      
      //Forth Quote
        Quote Q4 = new Quote();
        Q4.Duree_de_location__c='24;48';
        Q4.Kilom_trage__c=2000;
        Q4.OpportunityId =OPP.id;
        Q4.RecordTypeId=Label.Quote_RecordTypeId_Parc;
        Q4.Name='TEST2';
        Q4.Type_de_produit__c='Véhicules Frigorifiques';
        Q4.Sous_famille__c ='CF';
        Q4.Categorie__c='CF10';
        Q4.Sous_Categorie__c='CF10';
        Q4.Quantite__c=1;
        Q4.Origine_de_produit__c='A';
        //Q4.Synchronise__c=true;
        insert Q4;
        
        //Update Quote
        
        update Q4;
        Q4.Duree__c=24;
        Q4.Loyer__c =200;
        Q4.KM__c = 3000;
        Q4.Synchronise__c=true;
        Q4.Prix_du_km_supplementaire_les_100_kms__c=10;
        //update Q4;
  }
}