unpackaged/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal (-Facturation-)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Territoire__c.field-meta.xml
<CustomField>
    <fullName>Territoire__c</fullName>
    <label>Territoire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANTILLES</fullName>
            </value>
            <value>
                <fullName>DO1A</fullName>
            </value>
            <value>
                <fullName>DO1B</fullName>
            </value>
            <value>
                <fullName>DO2A</fullName>
            </value>
            <value>
                <fullName>DO2B</fullName>
            </value>
            <value>
                <fullName>DO3A</fullName>
            </value>
            <value>
                <fullName>DO3B</fullName>
            </value>
            <value>
                <fullName>DO4A</fullName>
            </value>
            <value>
                <fullName>DO4B</fullName>
            </value>
            <value>
                <fullName>DO5A</fullName>
            </value>
            <value>
                <fullName>DO5B</fullName>
            </value>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>ILE MAURICE</fullName>
            </value>
            <value>
                <fullName>OCEAN INDIEN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/ManagerCommercial__c.field-meta.xml
<CustomField>
    <fullName>ManagerCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vues_Commerciales_Client1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/PFRegion__c.field-meta.xml
<CustomField>
    <fullName>PFRegion__c</fullName>
    <label>Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <formula>Account__r.CodePostal__c</formula>
    <label>PostalCode</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Secteur__c.field-meta.xml
<CustomField>
    <fullName>Secteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secteur</label>
    <referenceTo>Secteur__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Territoire__c.field-meta.xml
<CustomField>
    <fullName>Territoire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territoire</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>Vues_Commerciales_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/TerritorialCommercial__c.field-meta.xml
<CustomField>
    <fullName>TerritorialCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial / KAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>VuesCommercialesClientUserCommercial</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Secteur__c/Secteur__c.object-meta.xml
<CustomObject>
    <label>Secteur</label>
    <nameField>
        <label>Nom du Secteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Secteur__c/fields/Commercial__c.field-meta.xml
<CustomField>
    <fullName>Commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial / KAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Representants_Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Secteur__c/fields/Manager_Commercial__c.field-meta.xml
<CustomField>
    <fullName>Manager_Commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Secteurs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Secteur__c/fields/Organisation_Commerciale__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Commerciale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipName>Representants_Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Table référentielle pour l&#39;assignation des commerciaux aux S.A.D</description>
    <label>Territoire</label>
    <nameField>
        <displayFormat>TER-{000000000}</displayFormat>
        <label>Numéro de Territoire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territoires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Territory__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <externalId>true</externalId>
    <label>Code Postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Territory__c/fields/Organisation_Commerciale__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Commerciale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Territoires</relationshipLabel>
    <relationshipName>Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Territory__c/fields/Secteur__c.field-meta.xml
<CustomField>
    <fullName>Secteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secteur</label>
    <referenceTo>Secteur__c</referenceTo>
    <relationshipLabel>Territoire</relationshipLabel>
    <relationshipName>Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestUpdateSalesAreaTerritoryDataBatch.cls
@isTest
private class TestUpdateSalesAreaTerritoryDataBatch {

    static void setupTestData() {
        //Create account
        Account ac = new Account(Name='Compte test',PaysRegionPF__c='DRO IDF 1',CodePostal__c='12345');
        insert ac;
        // Create and insert SalesArea
        SalesArea__c sa = new SalesArea__c(Name = 'Test Sales Area');
        insert sa;
        
        // Create and insert Secteur with a link to SalesArea
        Secteur__c sect = new Secteur__c(Organisation_Commerciale__c = sa.Id, Commercial__c = UserInfo.getUserId(), Manager_Commercial__c = UserInfo.getUserId());
        insert sect;
        
        // Create and insert Territoire linked to SalesArea and Secteur
        Territory__c ter = new Territory__c(Organisation_Commerciale__c = sa.Id, Secteur__c = sect.Id, Code_Postal__c = '12345');
        insert ter;
        
        // Create SalesAreaData with matching SalesArea and PostalCode but null Secteur__c and Territoire__c
        SalesAreaData__c sad = new SalesAreaData__c(Name='SAD test',SalesArea__c = sa.Id,Account__c=ac.id,TerritorialCommercial__c=null,ManagerCommercial__c=null,PFRegion__c='DRO IDF 1');
        insert sad;
    }
    
    static testMethod void testUpdateSalesAreaTerritoryDataBatch() {
        Test.startTest();
        
        // Setup test data
        setupTestData();
        
        // Execute the batch class
        UpdateSalesAreaTerritoryDataBatch batch = new UpdateSalesAreaTerritoryDataBatch('DRO IDF 1');
        Database.executeBatch(batch, 200);
        
        Test.stopTest();
        
        // Retrieve the updated SalesAreaData__c record
        Account ACC = [select id from account where Name = 'Compte test' limit 1];
        SalesAreaData__c updatedSad = [SELECT Territoire__c, Secteur__c, TerritorialCommercial__c, ManagerCommercial__c,PostalCode__c FROM SalesAreaData__c WHERE Account__c =: ACC.id and name = 'SAD test'  LIMIT 1];
        system.debug('SAD Territoire : '+updatedSad.Territoire__c +' Secteur : '+updatedSad.Secteur__c +'Postal code : '+updatedSad.PostalCode__c);
        // Assert that the updates were made as expected
        System.assertNotEquals(null, updatedSad.Territoire__c, 'Territoire__c was not updated.');
        System.assertNotEquals(null, updatedSad.Secteur__c, 'Secteur__c was not updated.');
        System.assertNotEquals(null, updatedSad.TerritorialCommercial__c, 'Commercial__c was not updated.');
        System.assertNotEquals(null, updatedSad.ManagerCommercial__c, 'Manager__c was not updated.');
    }
}