unpackaged/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal (-Facturation-)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code Postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vue commerciale client sur la quelle le contrat a été créé.</description>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Contrats</relationshipLabel>
    <relationshipName>Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/Dero_Fi__c/Dero_Fi__c.object-meta.xml
<CustomObject>
    <label>Conditions Financières</label>
    <nameField>
        <displayFormat>Cond Fi - {0000}</displayFormat>
        <label>Dero. Financière Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions Financières</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dero_Fi__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Dero_Fi</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dero_Fi__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Conditions Financières</relationshipLabel>
    <relationshipName>Conditions_Financi_res</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dero_Fi__c/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use for specific financial condition</description>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Conditions Financières</relationshipLabel>
    <relationshipName>Conditions_Financieres</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Derogation__c/Derogation__c.object-meta.xml
<CustomObject>
    <label>Dérogation</label>
    <nameField>
        <displayFormat>DERO-{0000}</displayFormat>
        <label>Num de Dérogation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dérogations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Derogation__c/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Dérogations</relationshipLabel>
    <relationshipName>Derogations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Facture_vehicule__c/Facture_vehicule__c.object-meta.xml
<CustomObject>
    <label>Facture véhicule</label>
    <nameField>
        <displayFormat>FV-{0000}</displayFormat>
        <label>Numéro de Facture véhicule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factures véhicule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Facture_vehicule__c/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vue commerciale client sur la quelle la facture a été créé.</description>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Factures véhicules</relationshipLabel>
    <relationshipName>FacturesVehicules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <formula>SalesAreaData__r.BusinessLine__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ligne de produit</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <inlineHelpText>Pays ou Région (FR) selon l&#39;implémentation des agences PF</inlineHelpText>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
            <value>
                <fullName>PIND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vue commerciale client sur la quelle l&#39;opportunité a été créé.</description>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marque</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <label>Ligne de produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessLine</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <formula>TEXT(SalesArea__r.BusinessLine__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ligne de produit</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/ManagerCommercial__c.field-meta.xml
<CustomField>
    <fullName>ManagerCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vues_Commerciales_Client1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/TerritorialCommercial__c.field-meta.xml
<CustomField>
    <fullName>TerritorialCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial / KAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>VuesCommercialesClientUserCommercial</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Petit Forestier</fullName>
    </customValue>
    <customValue>
        <fullName>Stricher</fullName>
    </customValue>
    <customValue>
        <fullName>Zefirent</fullName>
    </customValue>
    <customValue>
        <fullName>Mendon Truck Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>MedFood</fullName>
    </customValue>
    <customValue>
        <fullName>Petit Forestier Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Reways</fullName>
    </customValue>
    <customValue>
        <fullName>NOLEGGIO</fullName>
    </customValue>
    <customValue>
        <fullName>Stricher Froid</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/BusinessLine.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Containers</fullName>
    </customValue>
    <customValue>
        <fullName>Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Frigorifiques</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Secs</fullName>
    </customValue>
    <customValue>
        <fullName>Cession</fullName>
    </customValue>
    <customValue>
        <fullName>Vente</fullName>
        <isActive>false</isActive>
        <label>Vente</label>
    </customValue>
    <customValue>
        <fullName>Véhicules</fullName>
        <isActive>false</isActive>
        <label>Véhicules</label>
    </customValue>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/RDD_SADController_Test.cls
@isTest
private class RDD_SADController_Test {
  
    
    // Test the init method
    @isTest
    static void testInit() {
        Test.startTest();
          // Setup specific test data if needed
        RDD_SADController controller = new RDD_SADController();
        //Account
        Account ac = new Account(Name='Compte test',PaysRegionPF__c='DRO IDF 1',CodePostal__c='12345',RecordtypeId= Label.ACC_RecordTypeId_CompteClient); insert ac;
        //SalesArea
        SalesArea__c sa = new SalesArea__c(Name = 'Test Sales Area',BusinessLine__c='Véhicules Frigorifiques',Brand__c='Petit Forestier');
        SalesArea__c saContainer = new SalesArea__c(Name = 'Test Sales Area 2',BusinessLine__c='Containers',Brand__c='Petit Forestier');
        insert sa;insert saContainer;
        //SalesAreaData
        SalesAreaData__c sad = new SalesAreaData__c(Name='SAD test',SalesArea__c = sa.Id,Account__c=ac.id,TerritorialCommercial__c=null,ManagerCommercial__c=null,PFRegion__c='DRO IDF 1'); 
        SalesAreaData__c sadContainer = new SalesAreaData__c(Name='SAD test',SalesArea__c = saContainer.Id,Account__c=ac.id,TerritorialCommercial__c=null,ManagerCommercial__c=null,PFRegion__c='DRO IDF 1'); 
        insert sad;insert sadContainer;
        //DeroFI
        Dero_Fi__c DeroFI1 = new Dero_Fi__c(Account__c=ac.Id,SalesArea__c=sa.Id,SalesAreaData__c=sad.Id,Product_Type__c='Véhicules Frigorifiques');
        Dero_Fi__c DeroFI2 = new Dero_Fi__c(Account__c=ac.Id,SalesArea__c=saContainer.Id,SalesAreaData__c=sadContainer.Id,Product_Type__c='Containers');
        insert DeroFI1;insert DeroFI2;
        
 
        controller.SADInit= sad; controller.accInit = ac ;controller.accInitAct = ac;controller.accInitCondFi = ac;controller.accInitCtr = ac;controller.accInitDERO = ac;controller.accInitFact = ac;controller.accInitOpp = ac;controller.accInitTerritoire = ac;
        controller.accInit.PaysRegionPF__c='DRO IDF 1';
        // Instantiate your controller and call the init method
        
        controller.init();
        controller.denombrerInitSAD();
        controller.denombrerStatutSAD();
        controller.denombrerCondFiSAD();
        controller.denombrerInitFacturesSAD();
        controller.denombrerContactsSAD();
		controller.denombrerInitOppSAD();
        controller.denombrerDEROSAD();
        controller.denombrerTerritoire();
        // Perform asserts to verify the initialization
        // 
        Test.stopTest();
        
        // Example assert
        System.assertNotEquals(null, controller.accInit, 'Account should be initialized');
        System.assertNotEquals(null, controller.accInitAct, 'Account should be initialized');
        System.assertNotEquals(null, controller.accInitCondFi, 'Account should be initialized');
        System.assertNotEquals(null, controller.accInitCtr, 'Account should be initialized');
        System.assertNotEquals(null, controller.accInitDERO, 'Account should be initialized');
        System.assertNotEquals(null, controller.accInitFact, 'Account should be initialized');
        System.assertNotEquals(null, controller.accInitOpp, 'Account should be initialized');
        System.assertNotEquals(null, controller.accInitTerritoire, 'Account should be initialized');

        
    }
    
    // test Controller
    @isTest
    static void testController() {
        Test.startTest();
        // Setup specific test data if needed
        RDD_SADController controller = new RDD_SADController();
        //Account
        Account ac = new Account(Name='Compte test',PaysRegionPF__c='DRO IDF 1',CodePostal__c='12345'); insert ac;
        //SalesArea
        SalesArea__c sa = new SalesArea__c(Name = 'Test Sales Area',BusinessLine__c='Véhicules Frigorifiques',Brand__c='Petit Forestier');
        SalesArea__c saContainer = new SalesArea__c(Name = 'Test Sales Area 2',BusinessLine__c='Containers',Brand__c='Petit Forestier');
        insert sa;insert saContainer;
        //SalesAreaData
        SalesAreaData__c sad = new SalesAreaData__c(Name='SAD test',SalesArea__c = sa.Id,Account__c=ac.id,TerritorialCommercial__c=null,ManagerCommercial__c=null,PFRegion__c='DRO IDF 1'); 
        SalesAreaData__c sadContainer = new SalesAreaData__c(Name='SAD test',SalesArea__c = saContainer.Id,Account__c=ac.id,TerritorialCommercial__c=null,ManagerCommercial__c=null,PFRegion__c='DRO IDF 1'); 
        insert sad;insert sadContainer;
        //DeroFI
        Dero_Fi__c DeroFI1 = new Dero_Fi__c(Account__c=ac.Id,SalesArea__c=sa.Id,SalesAreaData__c=sad.Id,Product_Type__c='Véhicules Frigorifiques');
        Dero_Fi__c DeroFI2 = new Dero_Fi__c(Account__c=ac.Id,SalesArea__c=saContainer.Id,SalesAreaData__c=sadContainer.Id,Product_Type__c='Containers');
        insert DeroFI1;insert DeroFI2;
        
 
        controller.SADInit= sad; controller.accInit = ac;controller.accInitAct = ac;controller.accInitCondFi = ac;controller.accInitCtr = ac;controller.accInitDERO = ac;controller.accInitFact = ac;controller.accInitOpp = ac;controller.accInitTerritoire = ac;
        
    
        
        // Execute the method to be tested
        controller.executeBatchIdInitSAD();
        controller.executeBatchIdInitCondFiSAD();
        controller.executeBatchIdInitCtsSAD();
        controller.executeBatchIdInitFactSAD();
        controller.executeBatchIdInitStatutSAD();
        controller.executeBatchIdInitDeroSAD();
        controller.executeBatchIdInitOppSAD();
        controller.executeBatchIdInitTerritoire();
        // method call
        Test.stopTest();
        
        // Asserts to verify method outcomes
       System.assertEquals(null, sad.Territoire__c, 'Territoire__c was not updated.');

    }
    
    
   // Template for testing other methods
    @isTest
    static void testMethods() {
        Test.startTest();
        // Setup specific test data if needed
        RDD_SADController controller = new RDD_SADController();
        Account ac = new Account(Name='Compte test',PaysRegionPF__c='DRO IDF 1',CodePostal__c='12345',Pays__c='FRANCE'); ac.Statut__c='Validé';
        insert ac;
        //Entité légale
        LegalEntity__c LegalEntity = new LegalEntity__c(Name='Petit Forestier Location',Active__c=true);
        insert LegalEntity;
        //SalesArea
        SalesArea__c sa = new SalesArea__c(Name = 'Test Sales Area',BusinessLine__c='Véhicules Frigorifiques',Brand__c='Petit Forestier',LegalEntity__c=LegalEntity.Id,Country__c='FRANCE');
        SalesArea__c saContainer = new SalesArea__c(Name = 'Test Sales Area 2',BusinessLine__c='Containers',Brand__c='Petit Forestier',LegalEntity__c=LegalEntity.Id,Country__c='FRANCE');
        insert sa;insert saContainer;
        //SalesAreaData
        SalesAreaData__c sad = new SalesAreaData__c(Name='SAD test',SalesArea__c = sa.Id,Account__c=ac.id,TerritorialCommercial__c=null,ManagerCommercial__c=null,PFRegion__c='DRO IDF 1'); 
        SalesAreaData__c sadContainer = new SalesAreaData__c(Name='SAD test',SalesArea__c = saContainer.Id,Account__c=ac.id,TerritorialCommercial__c=null,ManagerCommercial__c=null,PFRegion__c='DRO IDF 1'); 
        insert sad;insert sadContainer;
        	//Account SAD
      	List<SalesAreaData__c> ListeSADAccount = [select id,name,Account__c,BusinessLine__c,Pays_SA__c,PFRegion__c,SalesArea__c from SalesAreaData__c where Account__c=:Ac.id];
            //DeroFI
        Dero_Fi__c DeroFI1 = new Dero_Fi__c(Account__c=ac.Id,SalesArea__c=sa.Id,SalesAreaData__c=sad.Id,Product_Type__c='Véhicules Frigorifiques');
        Dero_Fi__c DeroFI2 = new Dero_Fi__c(Account__c=ac.Id,SalesArea__c=saContainer.Id,SalesAreaData__c=sadContainer.Id,Product_Type__c='Containers');
        insert DeroFI1;insert DeroFI2;
		//Contact Ct = Utils_TestMethods.createContact('conName', ac.id);
        Opportunity Opp = Utils_TestMethods.createOpportunityWithProduits('oppName', '1 - Opportunité créée	', Date.newInstance(2024,10,10), ac);
        Opp.PaysRegionPF__c='DO IDF 1';
        insert Opp;
		
        Contract Ct1 = new contract(RecordtypeId=Label.RecordtypeId_ContratVehicule,Accountid=ac.id);insert ct1;
        Contract Ct2 = new contract(RecordtypeId=Label.Master_Agreement_Contrat_RecordTypeId,Accountid=ac.id);insert ct2;
        controller.SADInit= sad; controller.accInit = ac;controller.accInitAct = ac;controller.accInitCondFi = ac;controller.accInitCtr = ac;controller.accInitDERO = ac;controller.accInitFact = ac;controller.accInitOpp = ac;controller.accInitTerritoire = ac;
       
        //Lists
        list<SalesAreaData__c> SADList = new list<SalesAreaData__c>();SADList.add(sad);SADList.add(sadContainer);
        list<Account> AccountsList = new list<Account>();AccountsList.add(ac);
        list<SalesArea__c> SAList = new list<SalesArea__c>();SAList.add(sa);SAList.add(saContainer);
        list<Opportunity> OPPList = new list<Opportunity>();OPPList.add(Opp);
        list<contract> ContractList = new list<Contract>();ContractList.add(ct1);ContractList.add(ct2);
        list<Derogation__c> DEROList = new list<Derogation__c>();
        list<Dero_Fi__c> DEROFIList = new list<Dero_Fi__c>();DEROFIList.add(DeroFI1);DEROFIList.add(DeroFI2);
        list<Facture_vehicule__c> FVList = new list<Facture_vehicule__c>();
        List<Id> ListIds = new list<id>();ListIds.Add(Opp.id);
        // Execute the method to be tested
        RDD_SADController.InitiateSADCreation(AccountsList, SAList);
        RDD_SADController.InitiateStatutSAD(ListeSADAccount);
        RDD_SADController.MigrateOppsSAD(OPPList, ListeSADAccount);
        RDD_SADController.MigrateContratsSAD(ContractList, ListeSADAccount);
        RDD_SADController.MigrateCondFiSAD(DEROFIList, ListeSADAccount);
        RDD_SADController.MigrateFacturesSAD(FVList, ListeSADAccount);
        RDD_SADController.MigrateDeroSAD(DEROList);
        RDD_SADController.MigrateOneOpportunity(ListIds);
        
        // method call
        Test.stopTest();
        
        // Asserts to verify method outcomes
//       System.assertEquals(null, sad.Territoire__c, 'Territoire__c was not updated.');

    }
    
    //Test batches
   @isTest
    static void testBatchs(){
        Test.startTest();

        
        RDD_InitSAD_Batch Batch1 = new RDD_InitSAD_Batch('DRO IDF 1');
        Database.executeBatch(Batch1,5);
        
        RDD_InitStatutSAD_Batch Batch2 = new RDD_InitStatutSAD_Batch('DRO IDF 1');
        Database.executeBatch(Batch2,5);
        
        RDD_InitOppSAD_Batch Batch3 = new RDD_InitOppSAD_Batch('DRO IDF 1');
        Database.executeBatch(Batch3,5);
        
        RDD_InitFactureSAD_Batch Batch4 = new RDD_InitFactureSAD_Batch('DRO IDF 1');
        Database.executeBatch(Batch4,5);
        
        RDD_InitDEROSAD_Batch Batch5 = new RDD_InitDEROSAD_Batch('DRO IDF 1');
        Database.executeBatch(Batch5,5);
        
        RDD_InitCondFiSAD_Batch Batch6 = new RDD_InitCondFiSAD_Batch('DRO IDF 1');
        Database.executeBatch(Batch6,5);
        
        RDD_InitContractsSAD_Batch Batch7 = new RDD_InitContractsSAD_Batch('DRO IDF 1');
        Database.executeBatch(Batch7,5);
		Test.stopTest();

    }
}