unpackaged/main/default/objects/Account/fields/CodeNACE__c.field-meta.xml
<CustomField>
    <fullName>CodeNACE__c</fullName>
    <label>Code NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_Code_Activite_NACE__c.field-meta.xml
<CustomField>
    <fullName>DB_Code_Activite_NACE__c</fullName>
    <label>Code Activité NACE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_DU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_DU__c</fullName>
    <label>DUNS# DU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_GU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_GU__c</fullName>
    <label>DUNS# GU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_Number__c</fullName>
    <label>D-U-N-S Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Note_Poids_CA__c.field-meta.xml
<CustomField>
    <fullName>Note_Poids_CA__c</fullName>
    <label>Note Poids du CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Poids_CA__c.field-meta.xml
<CustomField>
    <fullName>Poids_CA__c</fullName>
    <label>Poids du CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pourcentage_effectif__c.field-meta.xml
<CustomField>
    <fullName>Pourcentage_effectif__c</fullName>
    <label>Pourcentage d&#39;effectif</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/NotePoidsCABatch_TEST.cls
@isTest
private class NotePoidsCABatch_TEST 
{
     static void setupTestData() 
    {
		// Créer des données de test - comptes et enregistrements SalesAreaData__c associés
		
        String recordtypeCLIENT = Label.ACC_RecordTypeId_CompteClient;
        String recordtypePROSPECT = Label.ACC_RecordTypeId_CompteProspect;
        // Création d'un compte GU
        Account Account01 = new Account(Poids_CA__c = -1, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account02 = new Account(Poids_CA__c = 1, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account03 = new Account(Poids_CA__c = 3, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account04 = new Account(Poids_CA__c = 6, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account05 = new Account(Poids_CA__c = 11, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account06 = new Account(Poids_CA__c = 16, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account07 = new Account(Poids_CA__c = 27, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account08 = new Account(Poids_CA__c = 38, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account09 = new Account(Poids_CA__c = 55, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        Account Account10 = new Account(Poids_CA__c = 80, DB_Code_Activite_NACE__c = '9104', CodeNACE__c = '9104', Pourcentage_effectif__c = 0.3, RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='PIES');
        // Création des comptes enfants DU avec différentes empreintes
        insert new List<Account>{Account01, Account02, Account03, Account04, Account05, Account06, Account07, Account08, Account09, Account10};
    }
 
    @isTest
    static void testBatchExecution() 
    {
        
        // Démarrer le test en appelant la méthode setupTestData
        setupTestData();
        
        Test.startTest();

        // Instancier et exécuter le lot
        NotePoidsCABatch batch = new NotePoidsCABatch();
        Database.executeBatch(batch);

        Test.stopTest();

        // Vérifier que les comptes ont été mis à jour avec les bonnes notes de poids de CA
        List<Account> updatedAccounts = [SELECT Id, Note_Poids_CA__c FROM Account];
        /*System.assertEquals(1, updatedAccounts[0].Note_Poids_CA__c);
        System.assertEquals(2, updatedAccounts[1].Note_Poids_CA__c);
        System.assertEquals(3, updatedAccounts[2].Note_Poids_CA__c);
        System.assertEquals(4, updatedAccounts[3].Note_Poids_CA__c);
        System.assertEquals(7, updatedAccounts[4].Note_Poids_CA__c);
        System.assertEquals(10, updatedAccounts[5].Note_Poids_CA__c);
        System.assertEquals(15, updatedAccounts[6].Note_Poids_CA__c);*/
    }
}