unpackaged/main/default/objects/Account/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Libelle__c.field-meta.xml
<CustomField>
    <fullName>Libelle__c</fullName>
    <label>Libellé</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NomCommercial__c.field-meta.xml
<CustomField>
    <fullName>NomCommercial__c</fullName>
    <label>Raison Sociale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Région / Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DF1</fullName>
            </value>
            <value>
                <fullName>DF2</fullName>
            </value>
            <value>
                <fullName>DF3</fullName>
            </value>
            <value>
                <fullName>DF4</fullName>
            </value>
            <value>
                <fullName>DF5</fullName>
            </value>
            <value>
                <fullName>DIRECTION RESEAU DROM</fullName>
            </value>
            <value>
                <fullName>DIRECTION RESEAU IDF</fullName>
            </value>
            <value>
                <fullName>DIRECTION RESEAU NORD</fullName>
            </value>
            <value>
                <fullName>DIRECTION RESEAU SUD</fullName>
            </value>
            <value>
                <fullName>DO1A</fullName>
                <isActive>false</isActive>
                <label>DO1A</label>
            </value>
            <value>
                <fullName>DO1B</fullName>
                <isActive>false</isActive>
                <label>DO1B</label>
            </value>
            <value>
                <fullName>DO2A</fullName>
                <isActive>false</isActive>
                <label>DO2A</label>
            </value>
            <value>
                <fullName>DO2B</fullName>
                <isActive>false</isActive>
                <label>DO2B</label>
            </value>
            <value>
                <fullName>DO3A</fullName>
                <isActive>false</isActive>
                <label>DO3A</label>
            </value>
            <value>
                <fullName>DO3B</fullName>
                <isActive>false</isActive>
                <label>DO3B</label>
            </value>
            <value>
                <fullName>DO4A</fullName>
                <isActive>false</isActive>
                <label>DO4A</label>
            </value>
            <value>
                <fullName>DO4B</fullName>
                <isActive>false</isActive>
                <label>DO4B</label>
            </value>
            <value>
                <fullName>DO5A</fullName>
                <isActive>false</isActive>
                <label>DO5A</label>
            </value>
            <value>
                <fullName>DO5B</fullName>
                <isActive>false</isActive>
                <label>DO5B</label>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>EE</fullName>
                <isActive>false</isActive>
                <label>EE</label>
            </value>
            <value>
                <fullName>NCEE</fullName>
            </value>
            <value>
                <fullName>NEUS</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
                <isActive>false</isActive>
                <label>PFUK</label>
            </value>
            <value>
                <fullName>PIAE</fullName>
                <isActive>false</isActive>
                <label>PIAE</label>
            </value>
            <value>
                <fullName>PIAT</fullName>
                <isActive>false</isActive>
                <label>PIAT</label>
            </value>
            <value>
                <fullName>PIBE</fullName>
                <isActive>false</isActive>
                <label>PIBE</label>
            </value>
            <value>
                <fullName>PIBU</fullName>
                <isActive>false</isActive>
                <label>PIBU</label>
            </value>
            <value>
                <fullName>PICH</fullName>
                <isActive>false</isActive>
                <label>PICH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Societe_PF__c.field-meta.xml
<CustomField>
    <fullName>Societe_PF__c</fullName>
    <label>Société PF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PFLO</fullName>
            </value>
            <value>
                <fullName>STFR</fullName>
            </value>
            <value>
                <fullName>LECAPITAINE</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>FRIDENGO</fullName>
            </value>
            <value>
                <fullName>SV</fullName>
            </value>
            <value>
                <fullName>SVAD</fullName>
            </value>
            <value>
                <fullName>SVCC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Territoire__c.field-meta.xml
<CustomField>
    <fullName>Territoire__c</fullName>
    <label>Territoire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANTILLES</fullName>
            </value>
            <value>
                <fullName>DO1A</fullName>
            </value>
            <value>
                <fullName>DO1B</fullName>
            </value>
            <value>
                <fullName>DO2A</fullName>
            </value>
            <value>
                <fullName>DO2B</fullName>
            </value>
            <value>
                <fullName>DO3A</fullName>
            </value>
            <value>
                <fullName>DO3B</fullName>
            </value>
            <value>
                <fullName>DO4A</fullName>
            </value>
            <value>
                <fullName>DO4B</fullName>
            </value>
            <value>
                <fullName>DO5A</fullName>
            </value>
            <value>
                <fullName>DO5B</fullName>
            </value>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>ILE MAURICE</fullName>
            </value>
            <value>
                <fullName>OCEAN INDIEN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Calendrier_Astreinte__c/Calendrier_Astreinte__c.object-meta.xml
<CustomObject>
    <label>Calendrier Astreinte</label>
    <nameField>
        <label>Calendrier Astreinte Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendriers Astreintes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Calendrier_Astreinte__c/fields/Agence_PF__c.field-meta.xml
<CustomField>
    <fullName>Agence_PF__c</fullName>
    <label>Agence PF</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calendriers Astreintes</relationshipLabel>
    <relationshipName>Calendriers_Astreintes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Calendrier_Astreinte__c/fields/N_semaine__c.field-meta.xml
<CustomField>
    <fullName>N_semaine__c</fullName>
    <label>N° semaine</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/RCSC_GetCalendrierAstreinte_TEST.cls
@isTest
private class RCSC_GetCalendrierAstreinte_TEST {
    static testmethod void testcomponent(){
        //Agence
Account AgenceTest = new account();
    AgenceTest.Name = '000 - AgenceTest';
    AgenceTest.Code__c = '000';
    AgenceTest.NomCommercial__c = 'AgenceTest';
    AgenceTest.Libelle__c = 'AgenceTest';
    AgenceTest.Societe_PF__c = 'PFLO';
    AgenceTest.Region__c = 'DIRECTION RESEAU IDF';
    AgenceTest.Territoire__c = 'DRO IDF 1';
    AgenceTest.RecordTypeId = Label.CPT_RecordTypeId_AgencePF;
    insert AgenceTest;
//Calendrier
    Calendrier_Astreinte__c CalendrierAstreinteTEST1 = New Calendrier_Astreinte__c();
    CalendrierAstreinteTEST1.Name = '2019 - S36';
    CalendrierAstreinteTEST1.N_semaine__c = 36;
    CalendrierAstreinteTEST1.Agence_PF__c = AgenceTest.id;
    CalendrierAstreinteTEST1.Date_de_debut__c = system.today();
    CalendrierAstreinteTEST1.Date_de_fin__c = system.today() +7;
    insert CalendrierAstreinteTEST1;
        Test.startTest();
        List<Calendrier_Astreinte__c> Lst = RCSC_GetCalendrierAstreinte.listWeeks(CalendrierAstreinteTEST1.Id);
        
        Test.stopTest();
        system.assertNotEquals(Lst.size(), 1);
    }

}