unpackaged/main/default/objects/Account/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <formula>IF(
    BEGINS(TEXT(PaysRegionPF__c), &quot;DRO&quot;), 
    &#39;FR&#39;,
    IF(
        BEGINS(TEXT(PaysRegionPF__c), &quot;STFR&quot;),
        &#39;FR&#39;,
        CASE(
            TEXT(PaysRegionPF__c),
            &#39;PFUK&#39;, &#39;GB&#39;,
            &#39;PIRL&#39;, &#39;IE&#39;,
            &#39;PIMA&#39;, &#39;MA&#39;,
            &#39;PITA&#39;, &#39;IT&#39;,
            &#39;PIND&#39;, &#39;NL&#39;,
            &#39;PIAT&#39;, &#39;AT&#39;,
            &#39;PIPL&#39;, &#39;PL&#39;,
            &#39;PIPT&#39;, &#39;PT&#39;,
            &#39;PILU&#39;, &#39;LU&#39;,
            &#39;PIES&#39;, &#39;ES&#39;,
            &#39;PIDE&#39;, &#39;DE&#39;,
            &#39;PIBE&#39;, &#39;BE&#39;,
            &#39;PICZ&#39;, &#39;SK&#39;,
            &#39;PICH&#39;, &#39;CH&#39;,
            &#39;PIAE&#39;, &#39;AE&#39;,
            &#39;PIBU&#39;, &#39;BU&#39;,
            &#39;PIZA&#39;, &#39;ZA&#39;,


            &#39;-&#39;
        )
    )
)</formula>
    <label>CodePays</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantNational__c</fullName>
    <label>Identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TypeIdentifiantNational__c</fullName>
    <label>Type d&#39;identifiant national</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CNIE</fullName>
            </value>
            <value>
                <fullName>COC</fullName>
            </value>
            <value>
                <fullName>COCCH</fullName>
            </value>
            <value>
                <fullName>COCCHE</fullName>
            </value>
            <value>
                <fullName>COFIS</fullName>
            </value>
            <value>
                <fullName>CRO</fullName>
            </value>
            <value>
                <fullName>DELTA</fullName>
            </value>
            <value>
                <fullName>HRB</fullName>
            </value>
            <value>
                <fullName>HRM</fullName>
            </value>
            <value>
                <fullName>IBLC</fullName>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
            <value>
                <fullName>KVK</fullName>
            </value>
            <value>
                <fullName>NIPC</fullName>
            </value>
            <value>
                <fullName>P.IVA</fullName>
            </value>
            <value>
                <fullName>RCLU</fullName>
            </value>
            <value>
                <fullName>RNMA</fullName>
            </value>
            <value>
                <fullName>RNPL</fullName>
            </value>
            <value>
                <fullName>RNPT</fullName>
            </value>
            <value>
                <fullName>SIREN</fullName>
            </value>
            <value>
                <fullName>TVABE</fullName>
            </value>
            <value>
                <fullName>TVADE</fullName>
            </value>
            <value>
                <fullName>TVAPL</fullName>
            </value>
            <value>
                <fullName>En création</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>PRISMA</fullName>
            </value>
            <value>
                <fullName>RNHU</fullName>
                <label>RNHU (cégjegyzékszám)</label>
            </value>
            <value>
                <fullName>VATHU</fullName>
                <label>VATHU (Adoszam)</label>
            </value>
            <value>
                <fullName>TVAIT</fullName>
            </value>
            <value>
                <fullName>ICOSK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/objects/allianz_api__c/allianz_api__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Allianz API</label>
</CustomObject>

unpackaged/main/default/objects/allianz_api__c/fields/API_KEY__c.field-meta.xml
<CustomField>
    <fullName>API_KEY__c</fullName>
    <label>API KEY</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/CodeAgence__c/CodeAgence__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Code Agence</label>
</CustomObject>

unpackaged/main/default/objects/CodeAgence__c/fields/Numero_Agence__c.field-meta.xml
<CustomField>
    <fullName>Numero_Agence__c</fullName>
    <label>Numero_Agence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CodesPays__c/CodesPays__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CodesPays</label>
</CustomObject>

unpackaged/main/default/objects/CodesPays__c/fields/Code_Pays2__c.field-meta.xml
<CustomField>
    <fullName>Code_Pays2__c</fullName>
    <label>Code_Pays2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CodesPays__c/fields/Code_Pays__c.field-meta.xml
<CustomField>
    <fullName>Code_Pays__c</fullName>
    <label>Code_Pays</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TypeIdentifiantNational__c/TypeIdentifiantNational__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Type Identifiant National</label>
</CustomObject>

unpackaged/main/default/objects/TypeIdentifiantNational__c/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TypeIdentifiantNational__c/fields/Libelle_fr__c.field-meta.xml
<CustomField>
    <fullName>Libelle_fr__c</fullName>
    <label>Libelle_fr</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AP09Compte_BATCH_TEST.cls
@isTest
public class AP09Compte_BATCH_TEST {

    //@isTest
    public static testMethod void launchBatchTest() {
        List<allianz_api__c> customList = new List<allianz_api__c>();
        allianz_api__c customTest = new allianz_api__c();
        customTest.Name = 'Company grade';
        customTest.Endpoint__c = 'test';
        customTest.Method__c = 'test';
        customTest.API_KEY__c = 'test';
        customList.add(customTest);

        allianz_api__c customTest2 = new allianz_api__c();
        customTest2.Name = 'New access token';
        customTest2.Endpoint__c = 'test';
        customTest2.Method__c = 'test';
        customTest2.API_KEY__c = 'test';
        customList.add(customTest2);

        allianz_api__c customTest3 = new allianz_api__c();
        customTest3.Name = 'Company search';
        customTest3.Endpoint__c = 'test';
        customTest3.Method__c = 'test';
        customTest3.API_KEY__c = 'test';
        customList.add(customTest3);

        allianz_api__c customTest4 = new allianz_api__c();
        customTest4.Name = 'Covers search';
        customTest4.Endpoint__c = 'test';
        customTest4.Method__c = 'test';
        customTest4.API_KEY__c = 'test';
        customList.add(customTest4);

        allianz_api__c customTest5 = new allianz_api__c();
        customTest5.Name = 'Get jobId';
        customTest5.Endpoint__c = 'test';
        customTest5.Method__c = 'test';
        customTest5.API_KEY__c = 'test';
        customList.add(customTest5);

        allianz_api__c customTest6 = new allianz_api__c();
        customTest6.Name = 'Request grade';
        customTest6.Endpoint__c = 'test';
        customTest6.Method__c = 'test';
        customTest6.API_KEY__c = 'test';
        customList.add(customTest6);

        insert customList;
        
        User u1 = new User(UserName='kevin.test@petitforestier.dev',LastName='Mell',
                          Email='kevin.melliand@ei-tehnologies.com',Alias='kMel',
                           TimeZoneSidKey='Europe/Paris',
                           LocaleSidKey='fr_FR_EURO',
                          EmailEncodingKey='ISO-8859-1',
                           ProfileId=Label.USR_ProfileId_PFReseau,LanguageLocaleKey='fr',
                          DefaultCurrencyIsoCode='EUR');
        /*
         * (alias = 'kbra', email='kbrazi@noemail.com',
                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='fr',
                            localesidkey='fr_FR_EURO', profileid = p.Id, country='France',
                            timezonesidkey='Europe/Paris', username='KBrazi@noemail.com',
                            IsActive = true);
         * */
        
        //Bypass Validation Rules  or Trigger on Running User////////////////////////////
        Bypass__c bypassSetting=Bypass__c.getInstance(UserInfo.getUserId());
        if (bypassSetting==null){
            bypassSetting=new Bypass__c();
        }
       // bypassSetting.BypassTriggers__c = 'AP02Utilisateur'; //To bypass Class
        bypassSetting.BypassValidationRules__c = true; //To bypass Validation Rules
        upsert bypassSetting;
        /////////////////////////////////////////////////////////////////////
        
        UtilsBatch__c ub = new UtilsBatch__c(Name = 'ERG 1');
        insert ub;
        
        insert u1;
        TypeIdentifiantNational__c tin1 = new TypeIdentifiantNational__c(Name = '011',
                                                                        Code__c = 'SIREN',
                                                                        CodePays__c = 'FR',
                                                                        Libelle_fr__c = 'SIREN-FRA');
        insert tin1;
        /*RecordType rd1 = new RecordType(SObjectType='Account', Name = 'Compte Prospect / Client');
        insert rd1;*/
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_000',
                                                               EndPoint__c = 'https://api-test.petitforestier.fr/api/services/PFCustomersRepository/Account',
                                                               Methode__c = 'POST',
                                                               UserName__c = 'mdm_sfdc',
                                                               MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                               ContentType__c = 'application/xml',
                                                               ApplicationName__c = 'SFCD',
                                                               Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr1;
        CodesPays__c cp1 = new CodesPays__c(Name = '053',
                                           Code_Pays__c = 'FRA',
                                           Code_Pays2__c = 'FR',
                                           Libelle_fr__c = 'France');
        insert cp1;
        CodeAgence__c ca1 = new CodeAgence__c(Name = '001',
                                           Numero_Agence__c = '001',
                                           Libelle_fr__c = '001 - VILLEPINTE');
        insert ca1;
        Account acc1 = new Account(Name='AccountTest', RecordTypeId=Label.CPT_RecordTypeId_CompteClient,
                                   PaysRegionPF__c = 'DO1B', AgencePF__c = '001 - VILLEPINTE', Statut__c = Label.CPT_Statut_Erreur_EH,
                                  IdentifiantNational__c = '343134763',
                                  TypeIdentifiantNational__c = 'SIREN-FRA',
                                  Ligne1Exploitation__c = '42 avenue de Friedland',
                                  VilleExploitation__c = 'PARIS',
                                  CodePostalExploitation__c = '75008',
                                  PaysExploitation__c = 'France');
        insert acc1;
        
        acc1.statut__c = Label.CPT_Statut_Erreur_EH;
        update acc1;
        
        List<Account> accs = new List<Account>();
        accs.add(acc1);
        
        /*batch.start(null);
        batch.execute(null, accs);
        batch.finish(null);*/
        
        Test.startTest();
        AP09Compte_BATCH batch = new AP09Compte_BATCH();
        ID batchprocessid = Database.executeBatch(batch);
        Test.stopTest();
        
        ID batchprocessid_RDD = Database.executeBatch(new AP13Compte_BATCH());
    }
}