unpackaged/main/default/objects/Account/fields/Compte_Parent_legal__c.field-meta.xml
<CustomField>
    <fullName>Compte_Parent_legal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte Parent légal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Comptes (Compte Parent légal)</relationshipLabel>
    <relationshipName>LegalParent</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_DU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_DU__c</fullName>
    <label>DUNS# DU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_GU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_GU__c</fullName>
    <label>DUNS# GU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_Number__c</fullName>
    <label>D-U-N-S Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IDEulerHermes__c.field-meta.xml
<CustomField>
    <fullName>IDEulerHermes__c</fullName>
    <label>ID Euler Hermes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Id__c</fullName>
    <formula>IF( ISPICKVAL(PaysRegionPF__c, &#39;PIES&#39;), &#39;A0003414901&#39;,
  IF( ISPICKVAL(PaysRegionPF__c, &#39;PIBE&#39;), &#39;A0009271201&#39;,
    IF( ISPICKVAL(PaysRegionPF__c, &#39;PILU&#39;), &#39;A0009271401&#39;,
      IF( ISPICKVAL(PaysRegionPF__c, &#39;PIND&#39;), &#39;A0009271601&#39;,
        IF( ISPICKVAL(PaysRegionPF__c, &#39;PIPT&#39;), &#39;A0011913601&#39;,
          IF( ISPICKVAL(PaysRegionPF__c, &#39;PFUK&#39;), &#39;A0014354401&#39;,
            IF( ISPICKVAL(PaysRegionPF__c, &#39;PITA&#39;), &#39;A0017874001&#39;,
              IF( ISPICKVAL(PaysRegionPF__c, &#39;PIRL&#39;), &#39;A0018560801&#39;,
                IF( ISPICKVAL(PaysRegionPF__c, &#39;PIPL&#39;), &#39;A0022172401&#39;,
                  IF( ISPICKVAL(PaysRegionPF__c, &#39;PIDE&#39;), &#39;A0022707601&#39;,
                    IF( ISPICKVAL(PaysRegionPF__c, &#39;PICZ&#39;), &#39;A0025918801&#39;,
                      IF( ISPICKVAL(PaysRegionPF__c, &#39;PIAT&#39;), &#39;A0027311601&#39;,
                        IF( ISPICKVAL(PaysRegionPF__c, &#39;PIHU&#39;), &#39;A0027558601&#39;,
                          IF( 
                            AND(ISPICKVAL(PaysRegionPF__c, &#39;DROM&#39;), ISPICKVAL(Pays__c, &#39;REUNION&#39;)), 
                            &#39;A0033711801&#39;,
                            IF( 
                              AND(ISPICKVAL(PaysRegionPF__c, &#39;DROM&#39;), ISPICKVAL(Pays__c, &#39;ANTILLES&#39;)), 
                              &#39;A0033712001&#39;,
                              IF( 
                                OR(ISPICKVAL(PaysRegionPF__c, &#39;STFR1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;STFR2&#39;), 
                                   ISPICKVAL(PaysRegionPF__c, &#39;STFR3&#39;), ISPICKVAL(PaysRegionPF__c, &#39;STFR4&#39;), 
                                   ISPICKVAL(PaysRegionPF__c, &#39;STFR5&#39;)),
                                &#39;A0020436801&#39;,
                                IF( 
                                  OR(ISPICKVAL(PaysRegionPF__c, &#39;DRO IDF 1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO IDF 2&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 2&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 3&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 4&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 5&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 6&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 7&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 1&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 2&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 3&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 4&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 5&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 6&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 7&#39;)),
                                  &#39;A0019715001&#39;,
                                  NULL)))))  ))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/allianz_api__c/allianz_api__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Allianz API</label>
</CustomObject>

unpackaged/main/default/objects/allianz_api__c/fields/API_KEY__c.field-meta.xml
<CustomField>
    <fullName>API_KEY__c</fullName>
    <label>API KEY</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LegalEntity__c/LegalEntity__c.object-meta.xml
<CustomObject>
    <label>Entité Légale</label>
    <nameField>
        <label>Nom de l&#39;Entité Légale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités Légales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/PolicyId_Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Liste des différentes entités légale et la policy rattachée</description>
    <label>PolicyId By Legal Entity</label>
</CustomObject>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/Business_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Code__c</fullName>
    <label>Business Unit Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/policyId__c.field-meta.xml
<CustomField>
    <fullName>policyId__c</fullName>
    <description>Policy Allianz</description>
    <label>policyId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marque</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <label>Ligne de produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessLine</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liste_Pays</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité Légale</label>
    <referenceTo>LegalEntity__c</referenceTo>
    <relationshipName>SalesArea</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Agrement__c.field-meta.xml
<CustomField>
    <fullName>Agrement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agrément</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <formula>TEXT(SalesArea__r.BusinessLine__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ligne de produit</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Date_agrement__c.field-meta.xml
<CustomField>
    <fullName>Date_agrement__c</fullName>
    <label>Date agrément</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Montant_agrement__c.field-meta.xml
<CustomField>
    <fullName>Montant_agrement__c</fullName>
    <label>Montant agrément</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Petit Forestier</fullName>
    </customValue>
    <customValue>
        <fullName>Stricher</fullName>
    </customValue>
    <customValue>
        <fullName>Zefirent</fullName>
    </customValue>
    <customValue>
        <fullName>Mendon Truck Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>MedFood</fullName>
    </customValue>
    <customValue>
        <fullName>Petit Forestier Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Reways</fullName>
    </customValue>
    <customValue>
        <fullName>NOLEGGIO</fullName>
    </customValue>
    <customValue>
        <fullName>Stricher Froid</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/BusinessLine.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Containers</fullName>
    </customValue>
    <customValue>
        <fullName>Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Frigorifiques</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Secs</fullName>
    </customValue>
    <customValue>
        <fullName>Cession</fullName>
    </customValue>
    <customValue>
        <fullName>Vente</fullName>
        <isActive>false</isActive>
        <label>Vente</label>
    </customValue>
    <customValue>
        <fullName>Véhicules</fullName>
        <isActive>false</isActive>
        <label>Véhicules</label>
    </customValue>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Liste_Pays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AFRIQUE DU SUD</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANIE</fullName>
    </customValue>
    <customValue>
        <fullName>ALGERIE</fullName>
    </customValue>
    <customValue>
        <fullName>ALLEMAGNE</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRE</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLA</fullName>
    </customValue>
    <customValue>
        <fullName>ARABIE SAOUDITE</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINE</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIE</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIE</fullName>
    </customValue>
    <customValue>
        <fullName>AUTRICHE</fullName>
    </customValue>
    <customValue>
        <fullName>BAHREIN</fullName>
    </customValue>
    <customValue>
        <fullName>BELARUS</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIQUE</fullName>
    </customValue>
    <customValue>
        <fullName>BENIN</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDES</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIE HERZEGOVINE</fullName>
    </customValue>
    <customValue>
        <fullName>BOTSWANA</fullName>
    </customValue>
    <customValue>
        <fullName>BRESIL</fullName>
    </customValue>
    <customValue>
        <fullName>BULGARIE</fullName>
    </customValue>
    <customValue>
        <fullName>BURKINA FASO</fullName>
    </customValue>
    <customValue>
        <fullName>CAMBODGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAMEROUN</fullName>
    </customValue>
    <customValue>
        <fullName>CANADA</fullName>
    </customValue>
    <customValue>
        <fullName>CHILI</fullName>
    </customValue>
    <customValue>
        <fullName>CHINE</fullName>
    </customValue>
    <customValue>
        <fullName>CHYPRE</fullName>
    </customValue>
    <customValue>
        <fullName>CISJORDANIE</fullName>
    </customValue>
    <customValue>
        <fullName>COLOMBIE</fullName>
    </customValue>
    <customValue>
        <fullName>FRANCE</fullName>
    </customValue>
    <description>Liste de pays</description>
    <masterLabel>Liste Pays</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/BatchVCCAgrement_TEST.cls
@isTest
public class BatchVCCAgrement_TEST {

    static void setupTestData() {

        List<allianz_api__c> customList = new List<allianz_api__c>();
        allianz_api__c customTest = new allianz_api__c();
        customTest.Name = 'Company grade';
        customTest.Endpoint__c = 'test';
        customTest.Method__c = 'test';
        customTest.API_KEY__c = 'test';
        customList.add(customTest);

        allianz_api__c customTest2 = new allianz_api__c();
        customTest2.Name = 'New access token';
        customTest2.Endpoint__c = 'test';
        customTest2.Method__c = 'test';
        customTest2.API_KEY__c = 'test';
        customList.add(customTest2);

        allianz_api__c customTest3 = new allianz_api__c();
        customTest3.Name = 'Company search';
        customTest3.Endpoint__c = 'test';
        customTest3.Method__c = 'test';
        customTest3.API_KEY__c = 'test';
        customList.add(customTest3);

        allianz_api__c customTest4 = new allianz_api__c();
        customTest4.Name = 'Covers search';
        customTest4.Endpoint__c = 'test';
        customTest4.Method__c = 'test';
        customTest4.API_KEY__c = 'test';
        customList.add(customTest4);

        allianz_api__c customTest5 = new allianz_api__c();
        customTest5.Name = 'Get jobId';
        customTest5.Endpoint__c = 'test';
        customTest5.Method__c = 'test';
        customTest5.API_KEY__c = 'test';
        customList.add(customTest5);

        allianz_api__c customTest6 = new allianz_api__c();
        customTest6.Name = 'Request grade';
        customTest6.Endpoint__c = 'test';
        customTest6.Method__c = 'test';
        customTest6.API_KEY__c = 'test';
        customList.add(customTest6);

        insert customList;

        PolicyId_Legal_Entity__c customPolicy = new PolicyId_Legal_Entity__c();
        customPolicy.Name = 'Test';
        customPolicy.Legal_Entity__c = 'LegalEntity1';
        customPolicy.policyId__c = 'A0028307201';
        customPolicy.Business_Unit_Code__c = 'SFAC';
        insert customPolicy;


        // Créer des données de test - comptes et enregistrements SalesAreaData__c associés
		
        String recordtypeCLIENT = Label.ACC_RecordTypeId_CompteClient;
        String recordtypePROSPECT = Label.ACC_RecordTypeId_CompteProspect;
        // Création d'un compte GU
        Account guAccount = new Account(RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='DRO IDF 1');
        // Création des comptes enfants DU avec différentes empreintes
        Account child1 = new Account(RecordTypeId = recordtypePROSPECT, Name='Child DU 1', DB_DUNS_Number__c='DU1', DB_DUNS_GU__c='GU1', PaysRegionPF__c='DRO IDF 1',Compte_Parent_legal__c=guAccount.id, IDEulerHermes__c = 'companyIdTest');
        insert new List<Account>{child1, guAccount};
		LegalEntity__c LegalEntity1 = new LegalEntity__c(Name = 'LegalEntity1');
        insert LegalEntity1;

        SalesArea__c SalesArea1 = new SalesArea__c(Name = 'SalesArea1', BusinessLine__c = 'Containers' , Brand__c ='Petit Forestier' , Country__c ='FRANCE' , LegalEntity__c = LegalEntity1.Id );
		insert SalesArea1;
            
            
        SalesAreaData__c sad1 = new SalesAreaData__c(Account__c = child1.Id, SalesArea__c = SalesArea1.Id);
        
        insert sad1;
    }

    @isTest
    static void testBatchExecution() {
        // Démarrer le test en appelant la méthode setupTestData
        setupTestData();
        
        
        // Démarrer le batch
        Test.startTest();
        BatchVCCAgrementScheduler batch = new BatchVCCAgrementScheduler();
        batch.execute(null);
        Test.stopTest();

        SalesAreaData__c sadUpdated = [SELECT Id, Agrement__c, Montant_agrement__c, Date_agrement__c, Account__r.IDEulerHermes__c, Account__r.Policy_Id__c, SalesArea__r.LegalEntity__r.Name FROM SalesAreaData__c WHERE Account__r.Name = 'Child DU 1'];
        System.debug('sadUpdated :' + sadUpdated);
        System.assert(sadUpdated.Montant_agrement__c != null && sadUpdated.Agrement__c == true && sadUpdated.Date_agrement__c != null, 'Le montant de l\'agrement ainsi que la date ne devraient pas être vide');
    }
}