unpackaged/main/default/objects/Account/fields/CotationPF__c.field-meta.xml
<CustomField>
    <fullName>CotationPF__c</fullName>
    <description>Grade de 1 à 10</description>
    <label>Grade Allianz</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantNational__c</fullName>
    <label>Identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Id__c</fullName>
    <formula>IF( ISPICKVAL(PaysRegionPF__c, &#39;PIES&#39;), &#39;A0003414901&#39;,
  IF( ISPICKVAL(PaysRegionPF__c, &#39;PIBE&#39;), &#39;A0009271201&#39;,
    IF( ISPICKVAL(PaysRegionPF__c, &#39;PILU&#39;), &#39;A0009271401&#39;,
      IF( ISPICKVAL(PaysRegionPF__c, &#39;PIND&#39;), &#39;A0009271601&#39;,
        IF( ISPICKVAL(PaysRegionPF__c, &#39;PIPT&#39;), &#39;A0011913601&#39;,
          IF( ISPICKVAL(PaysRegionPF__c, &#39;PFUK&#39;), &#39;A0014354401&#39;,
            IF( ISPICKVAL(PaysRegionPF__c, &#39;PITA&#39;), &#39;A0017874001&#39;,
              IF( ISPICKVAL(PaysRegionPF__c, &#39;PIRL&#39;), &#39;A0018560801&#39;,
                IF( ISPICKVAL(PaysRegionPF__c, &#39;PIPL&#39;), &#39;A0022172401&#39;,
                  IF( ISPICKVAL(PaysRegionPF__c, &#39;PIDE&#39;), &#39;A0022707601&#39;,
                    IF( ISPICKVAL(PaysRegionPF__c, &#39;PICZ&#39;), &#39;A0025918801&#39;,
                      IF( ISPICKVAL(PaysRegionPF__c, &#39;PIAT&#39;), &#39;A0027311601&#39;,
                        IF( ISPICKVAL(PaysRegionPF__c, &#39;PIHU&#39;), &#39;A0027558601&#39;,
                          IF( 
                            AND(ISPICKVAL(PaysRegionPF__c, &#39;DROM&#39;), ISPICKVAL(Pays__c, &#39;REUNION&#39;)), 
                            &#39;A0033711801&#39;,
                            IF( 
                              AND(ISPICKVAL(PaysRegionPF__c, &#39;DROM&#39;), ISPICKVAL(Pays__c, &#39;ANTILLES&#39;)), 
                              &#39;A0033712001&#39;,
                              IF( 
                                OR(ISPICKVAL(PaysRegionPF__c, &#39;STFR1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;STFR2&#39;), 
                                   ISPICKVAL(PaysRegionPF__c, &#39;STFR3&#39;), ISPICKVAL(PaysRegionPF__c, &#39;STFR4&#39;), 
                                   ISPICKVAL(PaysRegionPF__c, &#39;STFR5&#39;)),
                                &#39;A0020436801&#39;,
                                IF( 
                                  OR(ISPICKVAL(PaysRegionPF__c, &#39;DRO IDF 1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO IDF 2&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 2&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 3&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 4&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 5&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 6&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 7&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 1&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 2&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 3&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 4&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 5&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 6&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 7&#39;)),
                                  &#39;A0019715001&#39;,
                                  NULL)))))  ))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TECHIdentifiantNational__c</fullName>
    <label>TECH Identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHTypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TECHTypeIdentifiantNational__c</fullName>
    <label>TECH Type d&#39;identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TypeIdentifiantNational__c</fullName>
    <label>Type d&#39;identifiant national</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CNIE</fullName>
            </value>
            <value>
                <fullName>COC</fullName>
            </value>
            <value>
                <fullName>COCCH</fullName>
            </value>
            <value>
                <fullName>COCCHE</fullName>
            </value>
            <value>
                <fullName>COFIS</fullName>
            </value>
            <value>
                <fullName>CRO</fullName>
            </value>
            <value>
                <fullName>DELTA</fullName>
            </value>
            <value>
                <fullName>HRB</fullName>
            </value>
            <value>
                <fullName>HRM</fullName>
            </value>
            <value>
                <fullName>IBLC</fullName>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
            <value>
                <fullName>KVK</fullName>
            </value>
            <value>
                <fullName>NIPC</fullName>
            </value>
            <value>
                <fullName>P.IVA</fullName>
            </value>
            <value>
                <fullName>RCLU</fullName>
            </value>
            <value>
                <fullName>RNMA</fullName>
            </value>
            <value>
                <fullName>RNPL</fullName>
            </value>
            <value>
                <fullName>RNPT</fullName>
            </value>
            <value>
                <fullName>SIREN</fullName>
            </value>
            <value>
                <fullName>TVABE</fullName>
            </value>
            <value>
                <fullName>TVADE</fullName>
            </value>
            <value>
                <fullName>TVAPL</fullName>
            </value>
            <value>
                <fullName>En création</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>PRISMA</fullName>
            </value>
            <value>
                <fullName>RNHU</fullName>
                <label>RNHU (cégjegyzékszám)</label>
            </value>
            <value>
                <fullName>VATHU</fullName>
                <label>VATHU (Adoszam)</label>
            </value>
            <value>
                <fullName>TVAIT</fullName>
            </value>
            <value>
                <fullName>ICOSK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TypeIdentifiantNational__c/TypeIdentifiantNational__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Type Identifiant National</label>
</CustomObject>

unpackaged/main/default/classes/UpdateGradeController.cls
public class UpdateGradeController {
private String recordId;
    public Boolean DisplayNull{get;set;}public Boolean DisplaySame{get;set;}public Boolean DisplayDifferent{get;set;}
    public Boolean DisplayInfo{get;set;}public Boolean DisplayRequested{get;set;}
public Account currentAcc{get;set;}
    
    public UpdateGradeController(ApexPages.StandardController controller) {
        DisplayInfo=true;
        this.currentAcc= (Account) controller.getRecord();
        currentAcc= [Select id,CotationPF__c,TECHTypeIdentifiantNational__c,TECHIdentifiantNational__c,Name,TypeIdentifiantNational__c,IdentifiantNational__c,Policy_Id__c,BillingCountryCode, RecordType.Name, Pays__c from account where id=:currentAcc.id];
    }
    
 	public void method() {
       
    String Result = AP09Compte.UpdateGrade(currentAcc);
        switch on Result {
            when 'null' {		
                DisplayNull = true;DisplayDifferent=false;DisplaySame=false;DisplayInfo=false;DisplayRequested=false;
            }
            when 'Different' {		
                DisplayDifferent = true;DisplayNull=false;DisplaySame=false;DisplayInfo=false;DisplayRequested=false;
            }
            when 'Same' {
                DisplaySame = true;DisplayDifferent=false;Displaynull=false;DisplayInfo=false;DisplayRequested=false;
            }
            when 'Requested' {
                DisplayRequested=true;DisplaySame=false;DisplayDifferent=false;Displaynull=false;DisplayInfo=false;
            }
           }
    }
}