unpackaged/main/default/objects/Account/fields/CotationPF__c.field-meta.xml
<CustomField>
    <fullName>CotationPF__c</fullName>
    <description>Grade de 1 à 10</description>
    <label>Grade Allianz</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ListeNoire__c.field-meta.xml
<CustomField>
    <fullName>ListeNoire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refus</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHDateListeNoire__c.field-meta.xml
<CustomField>
    <fullName>TECHDateListeNoire__c</fullName>
    <description>CPT-RG-021 et CPT-RG-022</description>
    <label>TECH Date Liste Noire</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/OldBypassTriggersValidationRules__c.field-meta.xml
<CustomField>
    <fullName>OldBypassTriggersValidationRules__c</fullName>
    <label>TECHOld Bypass Triggers Validation Rules</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/DateClotureEffective__c.field-meta.xml
<CustomField>
    <fullName>DateClotureEffective__c</fullName>
    <label>Date clôture effective</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/DateSignatureContrat__c.field-meta.xml
<CustomField>
    <fullName>DateSignatureContrat__c</fullName>
    <label>Date signature contrat</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/DNP_Statut__c.field-meta.xml
<CustomField>
    <fullName>DNP_Statut__c</fullName>
    <label>DNP Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approuvée</fullName>
                <color>#009900</color>
                <label>Approuvée</label>
            </value>
            <value>
                <fullName>Rejetée</fullName>
                <color>#CC0000</color>
                <label>Rejetée</label>
            </value>
            <value>
                <fullName>En attente</fullName>
                <color>#FF9900</color>
                <label>En attente</label>
            </value>
            <value>
                <fullName>Anuulé</fullName>
                <label>Annulé</label>
            </value>
            <value>
                <fullName>En attente DG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Probabilite_signature__c.field-meta.xml
<CustomField>
    <fullName>Probabilite_signature__c</fullName>
    <inlineHelpText>Indiquer selon votre feeling la probabilité de signer l&#39;opportunité</inlineHelpText>
    <label>Probabilité signature</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>0% (Perdu)</fullName>
            </value>
            <value>
                <fullName>20% (Peu probable)</fullName>
            </value>
            <value>
                <fullName>50% (Probable)</fullName>
            </value>
            <value>
                <fullName>80% (Très probable)</fullName>
            </value>
            <value>
                <fullName>100% (Signé)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sans_Concurrent__c.field-meta.xml
<CustomField>
    <fullName>Sans_Concurrent__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Aucun concurrent identifié sur cette oppportunité</description>
    <inlineHelpText>Cochez cette case si aucun concurrent n&#39;est identifié sur cette opportunité</inlineHelpText>
    <label>Aucun concurrent identifié</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/OpportunityWarningHeader_TEST.cls
@isTest
public class OpportunityWarningHeader_TEST {
    @isTest
    private static void OpportunityWarningHeaderTest(){
        /////////////////////////////////////////////////////////////
        Bypass__c bypassSetting=Bypass__c.getInstance(UserInfo.getUserId());
        if (bypassSetting==null){
            bypassSetting=new Bypass__c();
            bypassSetting.OldBypassTriggersValidationRules__c = 'false:';
        }
        else{
            if(bypassSetting.BypassValidationRules__c != true)
            {
                bypassSetting.OldBypassTriggersValidationRules__c = bypassSetting.BypassValidationRules__c+':'+bypassSetting.BypassTriggers__c;
            }
        }
       
        bypassSetting.BypassValidationRules__c = true;
        upsert bypassSetting;
        //////////////////////////////
        Account Acc = new Account();
        Acc.CotationPF__c=4;
        Acc.Name='Test';
        Acc.ListeNoire__c =false;
        Acc.TECHDateListeNoire__c =null;
        Acc.Statut__c='Validé';
        Acc.recordtypeId=Label.CPT_RecordTypeId_CompteClient;
        insert Acc;
        Contact Cont = new Contact();
        Cont.AccountId=Acc.Id;
        Cont.LastName='Test';
        insert Cont;
        Opportunity OPP = new Opportunity();
        OPP.AccountId=Acc.Id;
        OPP.StageName='1 - Opportunité créée';
        OPP.Name='Opp Test'; 
        OPP.CloseDate=date.today();
        OPP.Probabilite_signature__c= '50% (Probable)';
        OPP.DateClotureEffective__c = system.today();
        OPP.DNP_Statut__c='Approuvée';
		insert OPP;
       
        Opportunity OPP2 = new Opportunity();
        OPP2.AccountId=Acc.Id;
        OPP2.StageName='1 - Opportunité créée';
        OPP2.Name='Opp Test2'; 
        OPP2.CloseDate=date.today();
        OPP2.Probabilite_signature__c= '50% (Probable)';
        OPP2.DateClotureEffective__c = system.today();
        OPP2.DNP_Statut__c='Approuvée';
		insert OPP2;
        //////////////////////////////////////
        Test.startTest();

        ApexPages.StandardController sc = new ApexPages.StandardController(OPP);
        OpportunityWarningHeader contr = new OpportunityWarningHeader(sc);
       // String param = ApexPages.currentPage().getParameters().get('DisplayWarning');
        // system.assertEquals('false', param);
        OPP.Sans_Concurrent__c=true;
        OPP.DateSignatureContrat__c=system.today();
        OPP.DateClotureEffective__c=system.today();
        OPP.StageName='6 - Contrat Signé';
        String OppId = OPP.Id;
        update OPP;
        OpportunityWarningHeader.IsDisplayWarning(OPP.Id);
        
        OPP2.Sans_Concurrent__c=true;
        OPP2.DateSignatureContrat__c=system.today();
        OPP2.StageName='4 - Proposition remise';
        update OPP2;
        OpportunityWarningHeader.IsDisplayWarning(OPP2.Id);
		Acc.CotationPF__c=9;  
        update Acc;
        OPP2.StageName='5 - Gagnée';
        OpportunityWarningHeader.IsDisplayWarning(OPP2.Id);
        OpportunityWarningHeader.IsDisplayWarning(OPP.Id);
        Test.stopTest();
    }
    
}