unpackaged/main/default/objects/Account/fields/Count_nb_SAD__c.field-meta.xml
<CustomField>
    <fullName>Count_nb_SAD__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Count nombre des SAD par compte</description>
    <label>Count nb SAD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LegalEntity__c/LegalEntity__c.object-meta.xml
<CustomObject>
    <label>Entité Légale</label>
    <nameField>
        <label>Nom de l&#39;Entité Légale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités Légales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <label>Ligne de produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessLine</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liste_Pays</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité Légale</label>
    <referenceTo>LegalEntity__c</referenceTo>
    <relationshipName>SalesArea</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/BusinessLine.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Containers</fullName>
    </customValue>
    <customValue>
        <fullName>Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Frigorifiques</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Secs</fullName>
    </customValue>
    <customValue>
        <fullName>Cession</fullName>
    </customValue>
    <customValue>
        <fullName>Vente</fullName>
        <isActive>false</isActive>
        <label>Vente</label>
    </customValue>
    <customValue>
        <fullName>Véhicules</fullName>
        <isActive>false</isActive>
        <label>Véhicules</label>
    </customValue>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Liste_Pays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AFRIQUE DU SUD</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANIE</fullName>
    </customValue>
    <customValue>
        <fullName>ALGERIE</fullName>
    </customValue>
    <customValue>
        <fullName>ALLEMAGNE</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRE</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLA</fullName>
    </customValue>
    <customValue>
        <fullName>ARABIE SAOUDITE</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINE</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIE</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIE</fullName>
    </customValue>
    <customValue>
        <fullName>AUTRICHE</fullName>
    </customValue>
    <customValue>
        <fullName>BAHREIN</fullName>
    </customValue>
    <customValue>
        <fullName>BELARUS</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIQUE</fullName>
    </customValue>
    <customValue>
        <fullName>BENIN</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDES</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIE HERZEGOVINE</fullName>
    </customValue>
    <customValue>
        <fullName>BOTSWANA</fullName>
    </customValue>
    <customValue>
        <fullName>BRESIL</fullName>
    </customValue>
    <customValue>
        <fullName>BULGARIE</fullName>
    </customValue>
    <customValue>
        <fullName>BURKINA FASO</fullName>
    </customValue>
    <customValue>
        <fullName>CAMBODGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAMEROUN</fullName>
    </customValue>
    <customValue>
        <fullName>CANADA</fullName>
    </customValue>
    <customValue>
        <fullName>CHILI</fullName>
    </customValue>
    <customValue>
        <fullName>CHINE</fullName>
    </customValue>
    <customValue>
        <fullName>CHYPRE</fullName>
    </customValue>
    <customValue>
        <fullName>CISJORDANIE</fullName>
    </customValue>
    <customValue>
        <fullName>COLOMBIE</fullName>
    </customValue>
    <description>Liste de pays</description>
    <masterLabel>Liste Pays</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/RDD_InitSAD_Batch.cls
global class RDD_InitSAD_Batch implements Database.Batchable<sObject>, Database.Stateful {

    private string filterPaysRegionPF;
    
    
    
    public RDD_InitSAD_Batch(string filterPaysRegionPF)
    {
        this.filterPaysRegionPF = filterPaysRegionPF;
    }
    
	global Database.queryLocator start(Database.BatchableContext bc)    
    {
        System.Debug('>>>>> initSAD_BATCH start <<<<<');
        string Query = 'select Id,Name,Pays__c,OwnerId,PaysRegionPF__c,CurrencyIsoCode from Account where Count_NB_SAD__c=0 and (RecordtypeId=\'0123X00000041YvQAI\' OR RecordtypeId=\'0123G000002UKyQQAW\') ' ;
         if(filterPaysRegionPF!=null && filterPaysRegionPF!=''){
            Query+='AND PaysRegionPF__c=\''+filterPaysRegionPF+'\' ';
        }
        Query+= ' ORDER BY Id';
        return Database.getQueryLocator(Query);
    }
    
    
    
     global void execute(Database.BatchableContext bc, list<sObject> scope){
        System.Debug('>>>> initSAD_BATCH start execute <<<<');
        
         List<SalesArea__c> ListSA=[SELECT id,Name,Country__c,BusinessLine__c,LegalEntity__c,LegalEntity__r.Name from SalesArea__c];
        
         list<Account> listAccounts=(list<Account>)scope;
        RDD_SADController.InitiateSADCreation(listAccounts,ListSA);
        
        System.Debug('>>>> initSAD_BATCH End execute <<<<');
    }
    
    
     global void finish(Database.BatchableContext bc){
        System.Debug('>>>> initSAD_BATCH Start finish <<<<');
                
        
    }
}