unpackaged/main/default/objects/Account/fields/DB_Autre_Identifiant_National__c.field-meta.xml
<CustomField>
    <fullName>DB_Autre_Identifiant_National__c</fullName>
    <label>ID national 2 (Valeur)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_Valeur_Autre__c.field-meta.xml
<CustomField>
    <fullName>DB_Valeur_Autre__c</fullName>
    <label>ID autre (Valeur)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_Valeur_ID_Prefere__c.field-meta.xml
<CustomField>
    <fullName>DB_Valeur_ID_Prefere__c</fullName>
    <label>ID national 1 (Valeur)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_Valeur_Taxe__c.field-meta.xml
<CustomField>
    <fullName>DB_Valeur_Taxe__c</fullName>
    <label>ID Taxe (Valeur)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LatePayment__c.field-meta.xml
<CustomField>
    <fullName>LatePayment__c</fullName>
    <description>Alimenté par l&#39;app SF Labs - Roll up qui COUNT le nb de SAD ayant un retard de paiement &gt; 0
Utilisé pour la visibilité du bouton &quot;Nouvelle opportunité&quot; sur les SAD</description>
    <label>Retard de paiement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Encours__c.field-meta.xml
<CustomField>
    <fullName>Encours__c</fullName>
    <label>Encours</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/LatePayment__c.field-meta.xml
<CustomField>
    <fullName>LatePayment__c</fullName>
    <description>Alimenté par KWOTE</description>
    <label>Retard de paiement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/PFRegion__c.field-meta.xml
<CustomField>
    <fullName>PFRegion__c</fullName>
    <label>Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/Intf_WebserviceCalloutKwote.cls
/**
 * Created by Michael on 27-03-24.
 */


public with sharing class Intf_WebserviceCalloutKwote extends Intf_WebserviceCalloutAbstract implements Intf_WebserviceCallout {

    public static Map<String, String> headers;
    private List<String> fieldList = new List<String>{'DB_Valeur_ID_Prefere__c', 'DB_Valeur_Autre__c', 'DB_Valeur_Taxe__c', 'DB_Autre_Identifiant_National__c'};


    private String setInterfaceType() {
        return 'Kwote';
    }

    private String setNamedCredential() {
        return 'Intf_Kwote';
    }

    private String setCaller() {
        return 'Intf_WebserviceCalloutKwote';
    }

    private Boolean setQueueing() {
        return false;
    }

    private Integer setMode() {

        if (System.isBatch() || System.isFuture()) {
            return intf_WebserviceCalloutAbstract.MODE_DIRECT;
        } else {
            return Intf_WebserviceCalloutAbstract.MODE_FUTURE;
        }

    }

    private String setMethod() {
        return 'GET';
    }

    private Map<String, String> setHeaders() {

        return headers;
    }

    private Map<String, String> setTagRemap() {
        return new Map<String, String>();
    }

    public void executeCallout(List<Object> payloadObjects) {

        super.doCallout(payloadObjects);
    }

    public void handleResponse(Intf_ServiceResult serviceResult, String payload, Boolean technicalError) {

        List<KwoteMessage> kwoteMessages = (List<KwoteMessage>)JSON.deserialize(serviceResult.body, List<KwoteMessage>.class);
        System.debug('============================== Intf_WebserviceCalloutKwote handleResponse kwoteMessages#: ' + kwoteMessages.size());

        Map<String, List<SalesAreaData__c>> sadsByIdentifiers = new Map<String, List<SalesAreaData__c>>();
        Map<Id, SalesAreaData__c> sadsToUpdate = new Map<Id, SalesAreaData__c>();
        Map<String, KwoteMessage> kwoteMessagesByIndentifiantIds = new Map<String, KwoteMessage>();

        String legalEntityPayload = payload.remove('"');
        List<String> legalEntities = legalEntityPayload.split(',');
        System.debug('============================== Intf_WebserviceCalloutKwote handleResponse legalEntityPayload : ' + legalEntityPayload);

        for (KwoteMessage kwoteMessage : kwoteMessages) {
            System.debug('============================== Intf_WebserviceCalloutKwote handleResponse kwoteMessages: ' + kwoteMessage);
            if (String.isNotBlank(kwoteMessage.identifiantLegal)) {

                if (kwoteMessage.codePays != null) {
                    String code2Char = kwoteMessage.codePays.left(2);
//                    System.debug('============================== Intf_WebserviceCalloutKwote handleResponse code2Char: ' + code2Char);
                    if (kwoteMessage.identifiantLegal.contains(code2char)) {
                        kwoteMessagesByIndentifiantIds.put(kwoteMessage.identifiantLegal, kwoteMessage);
                    } else {
                        kwoteMessagesByIndentifiantIds.put(kwoteMessage.identifiantLegal, kwoteMessage);
                        kwoteMessagesByIndentifiantIds.put(code2Char + kwoteMessage.identifiantLegal, kwoteMessage);
                    }

                } else {
                    kwoteMessagesByIndentifiantIds.put(kwoteMessage.identifiantLegal, kwoteMessage);
                }
            }
        }

        Set<String> legalIdentifiers = kwoteMessagesByIndentifiantIds.keySet();

        for (SalesAreaData__c sad : [
                SELECT Id, LatePayment__c, Account__r.DB_Valeur_ID_Prefere__c, Account__r.DB_Valeur_Autre__c, Account__r.DB_Valeur_Taxe__c, Account__r.DB_Autre_Identifiant_National__c,
                        Encours__c, Score__c
                FROM SalesAreaData__c
                WHERE PFRegion__c in :legalEntities
                AND (Account__r.DB_Valeur_ID_Prefere__c in :legalIdentifiers
                    OR Account__r.DB_Valeur_Autre__c in :legalIdentifiers OR Account__r.DB_Valeur_Taxe__c in :legalIdentifiers OR Account__r.DB_Autre_Identifiant_National__c in :legalIdentifiers)]) {

            Account accountLink = sad.Account__r;
            for (String fieldNameApi :fieldList) {

                String value = (String)accountLink.get(fieldNameApi);
                    if (String.isNotBlank(value)) {
                         if(!sadsByIdentifiers.containsKey(value)) {
                             sadsByIdentifiers.put(value, new List<SalesAreaData__c>());
                         }

                        List<SalesAreaData__c> sads = sadsByIdentifiers.get(value);
                        sads.add(sad);
                    }
            }
        }

        System.debug('============================== Intf_WebserviceCalloutKwote handleResponse salesAreaDatas# : ' + sadsByIdentifiers.size());

        for (String legalIdentifier : sadsByIdentifiers.keySet()) {
//            System.debug('============================== Intf_WebserviceCalloutKwote handleResponse SAD legalIdentifier : ' + legalIdentifier);

            KwoteMessage kwoteMessage = kwoteMessagesByIndentifiantIds.get(legalIdentifier);

            if (kwoteMessage != null) {
                for (SalesAreaData__c sad : sadsByIdentifiers.get(legalIdentifier)) {
//                    System.debug('============================== Intf_WebserviceCalloutKwote handleResponse added kwoteMessage : ' + kwoteMessage);
                    if (!isSameInfo(sad, kwoteMessage)) {
                        sadsToUpdate.put(sad.Id, new SalesAreaData__c(
                                Id = sad.Id,
                                Encours__c = kwoteMessage.enCours,
                                Score__c = kwoteMessage.profilPayeur,
                                LatePayment__c = kwoteMessage.retard
                        ));
                    }
                }
            } else {
//                System.debug('============================== Intf_WebserviceCalloutKwote handleResponse no kwote message for  : ' + legalIdentifier);
            }
        }

        System.debug('============================== Intf_WebserviceCalloutKwote handleResponse sadsToUpdate# : ' + sadsToUpdate.size());
        if (!sadsToUpdate.isEmpty()) {
            List<Database.SaveResult> results = Database.update(sadsToUpdate.values(), false);
        }
    }

    public void registerMonitoningMessage(String method, String outgoingMessage, String responseMessage, String interfaceName, Integer statusCode, Boolean isError, Boolean isResponse) {

        System.debug('================================ Intf_WebserviceCalloutKwote registerMonitoningMessage method: ' + method);
        System.debug('================================ Intf_WebserviceCalloutKwote registerMonitoningMessage outgoingMessage: ' + outgoingMessage);
        System.debug('================================ Intf_WebserviceCalloutKwote registerMonitoningMessage interfaceName: ' + interfaceName);

        super.registerMonitoningMessage(method, outgoingMessage, responseMessage, interfaceName, statusCode, isError, Intf_GenerallntService.getUMessageId(), isResponse);

    }

    private Boolean isSameInfo(SalesAreaData__c sad, KwoteMessage kwoteMessage) {


        return (sad.Encours__c == kwoteMessage.enCours)
                && (sad.Score__c == kwoteMessage.profilPayeur)
                && (sad.LatePayment__c == kwoteMessage.retard);

    }

    public class KwoteMessage {

        public Decimal retard { get; set; }
        public Decimal enCours { get; set; }
        public Decimal retard30Jours { get; set; }
        public Decimal encoursDisponible { get; set; }
        public Decimal risque { get; set; }
        public Decimal profilPayeur { get; set; }
        public String identifiantLegal { get; set; }
        public String codePays { get; set; }

    }

}