unpackaged/main/default/objects/Account/fields/DB_DUNS_DU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_DU__c</fullName>
    <label>DUNS# DU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_GU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_GU__c</fullName>
    <label>DUNS# GU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_Number__c</fullName>
    <label>D-U-N-S Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Empreinte_Geographique__c.field-meta.xml
<CustomField>
    <fullName>Empreinte_Geographique__c</fullName>
    <label>Empreinte Géographique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/IS_Account_Child_of_DU__c.field-meta.xml
<CustomField>
    <fullName>IS_Account_Child_of_DU__c</fullName>
    <formula>IF( DB_DUNS_Number__c  &lt;&gt;  DB_DUNS_DU__c,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IS Account Child of DU</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IS_Account_Child_of_GU__c.field-meta.xml
<CustomField>
    <fullName>IS_Account_Child_of_GU__c</fullName>
    <formula>IF( DB_DUNS_Number__c  &lt;&gt;  DB_DUNS_GU__c,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IS Account Child of GU</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IS_Account_Child_of_Principal__c.field-meta.xml
<CustomField>
    <fullName>IS_Account_Child_of_Principal__c</fullName>
    <formula>IF( ParentId  &lt;&gt; NULL,TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IS Account Child of Principal</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Flow_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Flow_Update__c</fullName>
    <label>Last Flow Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Compte_Client.recordType-meta.xml
<RecordType>
    <fullName>Compte_Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/classes/ExportAccountListBatch.cls
global class ExportAccountListBatch implements Database.Batchable<sObject>, Database.Stateful
{
    
    
    // Déclaration de la liste globale
   // global   List<Account> allAccounts = new List<Account>();
            private   List<Account> allAccounts = new List<Account>();

    
     global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        // Récupérer les informations sur les Record Types
        List<RecordType> recordTypes = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName IN ('Compte_Client', 'Prospect')];
     
        // Vérifier si les Record Types sont valides avant de construire la requête
        if (!recordTypes.isEmpty()) 
        {
            Set<Id> recordTypeIds = new Set<Id>();
            for (RecordType rt : recordTypes) 
            {
                recordTypeIds.add(rt.Id);
            }

           return Database.getQueryLocator('SELECT Id, Name, DB_DUNS_GU__c, DB_DUNS_DU__c, DB_DUNS_Number__c, ParentId, IS_Account_Child_of_GU__c, IS_Account_Child_of_DU__c, IS_Account_Child_of_Principal__c, Last_Flow_Update__c, PaysRegionPF__c, BillingCountry, Pays__c, Empreinte_Geographique__c FROM Account WHERE RecordTypeId IN :recordTypeIds');
        } 
        else 
        {
            // Gérer le cas où les Record Types ne sont pas valides
            return null;
    	}
		

    }

        global void execute(Database.BatchableContext BC, List<Account> scope) 
    {
        

		

    // Ajouter chaque élément du scope à la liste globale
 // Initialiser la liste allAccounts si elle est vide

    
    // Ajouter chaque élément du scope à la liste globale
    allAccounts.addAll(scope);                
//List<Account> allAccounts2 = new List<Account>();
  //      allAccounts2.addAll(scope);    
        String jsonLogText1 = JSON.serializePretty(allAccounts);
        Blob content1 = Blob.valueOf(jsonLogText1);
        String fileName1 =  'ExecuteallAccounts.json';
        // Créer un nouveau contenu de fichier
        ContentVersion contentVersion1 = new ContentVersion();
        contentVersion1.Title = fileName1;
        contentVersion1.PathOnClient = fileName1;
        contentVersion1.VersionData = content1;
        insert contentVersion1;
        Id contentDocumentId1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion1.Id].ContentDocumentId;
        ContentDocument contentDocument1 = [SELECT Id, Title FROM ContentDocument WHERE Id = :contentDocumentId1];
        }

    global void finish(Database.BatchableContext BC) 
    {
        // Actions à effectuer après l'exécution du lot
		
//if (allAccounts == null || allAccounts.isEmpty()) 
  //      {
    //        return;
      //  }
		
        // Filtrer les comptes qui sont à la fois parents et enfants
       
        

    // Lancez la classe Queueable avec les données nécessaires
    System.enqueueJob(new GeographicFootprintComputeAccounts(allAccounts), 5);        
        //GeographicFootprintComputeAccounts.computeGeographicFootprint(allAccounts);

    }
}