unpackaged/main/default/objects/Account/fields/DB_DUNS_DU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_DU__c</fullName>
    <label>DUNS# DU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_GU__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_GU__c</fullName>
    <label>DUNS# GU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DB_DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DB_DUNS_Number__c</fullName>
    <label>D-U-N-S Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_SAP_Id__c</fullName>
    <label>Tech SAP Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AccountTriggerHandler_TEST.cls
@isTest
public class AccountTriggerHandler_TEST {
    @TestSetup
    static void setupTestData() {
        String recordtypeCLIENT = Label.CPT_RecordTypeId_CompteClient;
        String recordtypeSITE = Label.CPT_RecordTypeId_CompteSite;
        // Création d'un compte GU
        Account clientAccount = new Account(RecordTypeId = recordtypeCLIENT, Name='Global Ultimate', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='DRO IDF 1');
        Account siteAccount = new Account(RecordTypeId = recordtypeSITE, Name='Global Ultimate - SITE', DB_DUNS_Number__c='GU1', DB_DUNS_DU__c='GU1', DB_DUNS_GU__c='GU1',  PaysRegionPF__c='DRO IDF 1', ParentId=clientAccount.Id);
        System.debug('clientAccount : ' + clientAccount.Id);
        System.debug('siteAccount : ' + siteAccount.Id);
        insert new List<Account>{clientAccount, siteAccount};
        siteAccount.ParentId=clientAccount.Id;
        update siteAccount;
        
    }

    @isTest
    public static void updateSAPIdOfSiteAccountTEST() {
        
        // This code runs as the system user
        Test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='PF Administrateur Système'];
        User u = new User(Alias = 'standt', Email='PFTestTalend.integration@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='PFTestTalend.integration@testorg.com');
        //User u = [SELECT Id FROM User WHERE UserName = 'talend.integration@testorg.com'];
        System.runAs(u) {
            System.debug([SELECT Id, Name, RecordType.Name FROM Account]);
            Account siteAccount = [SELECT Id, Tech_SAP_Id__c FROM Account WHERE Name='Global Ultimate - SITE' LIMIT 1];
            siteAccount.Tech_SAP_Id__c = '123456789';
            update siteAccount;
            System.debug([SELECT Id, Name, RecordType.Name FROM Account WHERE Name='Global Ultimate - SITE']);
        }
        Test.stopTest();
        Account clientAccount = [SELECT Id, Tech_SAP_Id__c FROM Account WHERE Name='Global Ultimate' LIMIT 1];
        System.assert(clientAccount.Tech_SAP_Id__c == '123456789');
    }

    @IsTest
    public static void updateSAPIdOfClientAccountTEST() {
        
        // This code runs as the system user
        Test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='PF Administrateur Système'];
        User u = new User(Alias = 'standt', Email='PFTestTalend.integration@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='PFTestTalend.integration@testorg.com');
        //User u = [SELECT Id FROM User WHERE UserName = 'talend.integration@testorg.com'];
        System.runAs(u) {
            System.debug([SELECT Id, Name, RecordType.Name FROM Account]);
            Account clientAccount = [SELECT Id, Tech_SAP_Id__c FROM Account WHERE Name='Global Ultimate' LIMIT 1];
            clientAccount.Tech_SAP_Id__c = '123456789';
            update clientAccount;
            System.debug([SELECT Id, Name, RecordType.Name FROM Account WHERE Name='Global Ultimate']);
        }
        Test.stopTest();
        Account siteAccount = [SELECT Id, Tech_SAP_Id__c FROM Account WHERE Name='Global Ultimate - SITE' LIMIT 1];
        System.assert(siteAccount.Tech_SAP_Id__c == '123456789');
    }
}