unpackaged/main/default/objects/Account/fields/DB_Statut_Activite__c.field-meta.xml
<CustomField>
    <fullName>DB_Statut_Activite__c</fullName>
    <label>Status d&#39;activité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LegalEntity__c/LegalEntity__c.object-meta.xml
<CustomObject>
    <label>Entité Légale</label>
    <nameField>
        <label>Nom de l&#39;Entité Légale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités Légales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marque</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <label>Ligne de produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessLine</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liste_Pays</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité Légale</label>
    <referenceTo>LegalEntity__c</referenceTo>
    <relationshipName>SalesArea</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <formula>TEXT(SalesArea__r.BusinessLine__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ligne de produit</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/ManagerCommercial__c.field-meta.xml
<CustomField>
    <fullName>ManagerCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vues_Commerciales_Client1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/TerritorialCommercial__c.field-meta.xml
<CustomField>
    <fullName>TerritorialCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial / KAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>VuesCommercialesClientUserCommercial</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Petit Forestier</fullName>
    </customValue>
    <customValue>
        <fullName>Stricher</fullName>
    </customValue>
    <customValue>
        <fullName>Zefirent</fullName>
    </customValue>
    <customValue>
        <fullName>Mendon Truck Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>MedFood</fullName>
    </customValue>
    <customValue>
        <fullName>Petit Forestier Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Reways</fullName>
    </customValue>
    <customValue>
        <fullName>NOLEGGIO</fullName>
    </customValue>
    <customValue>
        <fullName>Stricher Froid</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/BusinessLine.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Containers</fullName>
    </customValue>
    <customValue>
        <fullName>Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Frigorifiques</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Secs</fullName>
    </customValue>
    <customValue>
        <fullName>Cession</fullName>
    </customValue>
    <customValue>
        <fullName>Vente</fullName>
        <isActive>false</isActive>
        <label>Vente</label>
    </customValue>
    <customValue>
        <fullName>Véhicules</fullName>
        <isActive>false</isActive>
        <label>Véhicules</label>
    </customValue>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Liste_Pays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AFRIQUE DU SUD</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANIE</fullName>
    </customValue>
    <customValue>
        <fullName>ALGERIE</fullName>
    </customValue>
    <customValue>
        <fullName>ALLEMAGNE</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRE</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLA</fullName>
    </customValue>
    <customValue>
        <fullName>ARABIE SAOUDITE</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINE</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIE</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIE</fullName>
    </customValue>
    <customValue>
        <fullName>AUTRICHE</fullName>
    </customValue>
    <customValue>
        <fullName>BAHREIN</fullName>
    </customValue>
    <customValue>
        <fullName>BELARUS</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIQUE</fullName>
    </customValue>
    <customValue>
        <fullName>BENIN</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDES</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIE</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIE HERZEGOVINE</fullName>
    </customValue>
    <customValue>
        <fullName>BOTSWANA</fullName>
    </customValue>
    <customValue>
        <fullName>BRESIL</fullName>
    </customValue>
    <customValue>
        <fullName>BULGARIE</fullName>
    </customValue>
    <customValue>
        <fullName>BURKINA FASO</fullName>
    </customValue>
    <customValue>
        <fullName>CAMBODGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAMEROUN</fullName>
    </customValue>
    <customValue>
        <fullName>CANADA</fullName>
    </customValue>
    <customValue>
        <fullName>CHILI</fullName>
    </customValue>
    <customValue>
        <fullName>CHINE</fullName>
    </customValue>
    <customValue>
        <fullName>CHYPRE</fullName>
    </customValue>
    <customValue>
        <fullName>CISJORDANIE</fullName>
    </customValue>
    <customValue>
        <fullName>COLOMBIE</fullName>
    </customValue>
    <description>Liste de pays</description>
    <masterLabel>Liste Pays</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/EmailDBManagerTest.cls
@IsTest
private class EmailDBManagerTest {
    @IsTest
    static void testSendModificationEmails() {
       Test.startTest();
       // Configuration - Création de records Account et SalesAreaData__c pour le test
        // Assurez-vous de remplacer les valeurs de champ et d'ID par des valeurs valides pour votre org Salesforce
        Account testAccount = new Account(Name='Test Account', DB_Statut_Activite__c='Old Value');
        insert testAccount;
        
        // Supposons que TerritorialCommercial__c et ManagerCommercial__c contiennent des adresses e-mail valides
        User Commercial = Utils_TestMethods.createUser('UserTest', 'UserT', system.Label.USR_ProfileId_PFReseau);
        Commercial.Email='hass.medsaid@gmail.com';Insert commercial;
        LegalEntity__c LegalEntity = new LegalEntity__c(Name='Legal entity test');insert LegalEntity;
        SalesArea__c SA = New SalesArea__c(Name='SA test',Businessline__c='Véhicules Frigorifiques',Brand__c='Petit Forestier',Country__c='France',LegalEntity__c=legalEntity.id);Insert SA;
        SalesAreaData__c salesAreaData = new SalesAreaData__c(Account__c=testAccount.Id, TerritorialCommercial__c=Commercial.id, ManagerCommercial__c=Commercial.id,SalesArea__c=SA.Id);
        insert salesAreaData;
        
        // Simuler la mise à jour de l'Account pour déclencher l'envoi d'un e-mail
        
        
        // Simuler la modification des champs surveillés
        testAccount.DB_Statut_Activite__c = 'New Value';
        update testAccount;
        
        // Appeler votre méthode pour envoyer les e-mails
        Map<Id, Account> oldMap = new Map<Id, Account>{testAccount.Id => testAccount.clone()};
        Map<Id, Account> newMap = new Map<Id, Account>{testAccount.Id => testAccount};
        Map<Id, Set<String>> accountToModifiedFields = new Map<Id, Set<String>>{
            testAccount.Id => new Set<String>{'DB_Statut_Activite__c'}
        };
        
        EmailDBManager.sendModificationEmails(accountToModifiedFields, oldMap, newMap);
        
        Test.stopTest();
        
        // Assertions - Salesforce ne permet pas de vérifier directement les e-mails envoyés dans les tests unitaires
        // Vous pouvez ici ajouter des assertions indirectes si votre méthode produit d'autres effets secondaires vérifiables
    }
}