unpackaged/main/default/objects/Account/fields/DB_Valeur_ID_Prefere__c.field-meta.xml
<CustomField>
    <fullName>DB_Valeur_ID_Prefere__c</fullName>
    <label>ID national 1 (Valeur)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/LatePayment__c.field-meta.xml
<CustomField>
    <fullName>LatePayment__c</fullName>
    <description>Alimenté par l&#39;app SF Labs - Roll up qui COUNT le nb de SAD ayant un retard de paiement &gt; 0
Utilisé pour la visibilité du bouton &quot;Nouvelle opportunité&quot; sur les SAD</description>
    <label>Retard de paiement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_SAP_Id__c</fullName>
    <label>Tech SAP Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Particulier_B2C.recordType-meta.xml
<RecordType>
    <fullName>Particulier_B2C</fullName>
    <active>true</active>
    <label>Particulier (B2C)</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Fonction__c.field-meta.xml
<CustomField>
    <fullName>Fonction__c</fullName>
    <inlineHelpText>Function as defined in the PF qualification</inlineHelpText>
    <label>Fonction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrateur</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Directeur</fullName>
            </value>
            <value>
                <fullName>Employé</fullName>
            </value>
            <value>
                <fullName>Gérant</fullName>
            </value>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Propriétaire</fullName>
            </value>
            <value>
                <fullName>Responsable</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Technicien</fullName>
            </value>
            <value>
                <fullName>Chef d&#39;atelier</fullName>
            </value>
            <value>
                <fullName>DIRECTEUR DE SITE</fullName>
            </value>
            <value>
                <fullName>AGENT D&#39;EXPLOITATION</fullName>
            </value>
            <value>
                <fullName>AIDE EXPLOITANT</fullName>
            </value>
            <value>
                <fullName>APPRENTI CARROSSIER</fullName>
            </value>
            <value>
                <fullName>APPRENTI CARROSSIER PEINTRE</fullName>
            </value>
            <value>
                <fullName>APPRENTI COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>APPRENTI EXPLOITANT</fullName>
            </value>
            <value>
                <fullName>APPRENTI FRIGORISTE</fullName>
            </value>
            <value>
                <fullName>APPRENTI MECANICIEN</fullName>
            </value>
            <value>
                <fullName>APPRENTIE SECRETAIRE</fullName>
            </value>
            <value>
                <fullName>ASSIST REGIONAL ASSURANCE RE</fullName>
            </value>
            <value>
                <fullName>ASSISTANCE DAGENCE</fullName>
            </value>
            <value>
                <fullName>ASSISTANT COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>ASSISTANT EXPLOITATION</fullName>
            </value>
            <value>
                <fullName>ASSISTANT REGIONAL ASSURANCE</fullName>
            </value>
            <value>
                <fullName>ASSISTANT REGIONAL EXPLOITATION</fullName>
            </value>
            <value>
                <fullName>ASSISTANTE ADMINISTRATIVE</fullName>
            </value>
            <value>
                <fullName>ASSISTANTE COMMERCIALE</fullName>
            </value>
            <value>
                <fullName>ASSISTANTE COMMERCIALE REGIONAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Particulier_B2C.recordType-meta.xml
<RecordType>
    <fullName>Particulier_B2C</fullName>
    <active>true</active>
    <description>Contact B2C</description>
    <label>Particulier (B2C)</label>
</RecordType>

unpackaged/main/default/objects/Intf_Kwote_Access_Mapping__mdt/Intf_Kwote_Access_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Intf Kwote Access Mapping</label>
    <pluralLabel>Intf Kwote Access Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Intf_Kwote_Access_Mapping__mdt/fields/api_access__c.field-meta.xml
<CustomField>
    <fullName>api_access__c</fullName>
    <label>api access</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Intf_Kwote_Access_Mapping__mdt/fields/api_key__c.field-meta.xml
<CustomField>
    <fullName>api_key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>api key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Intf_Kwote_Access_Mapping__mdt/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <description>List des entités PF liées à cette clé Kwote</description>
    <label>Legal Entity List</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Encours__c.field-meta.xml
<CustomField>
    <fullName>Encours__c</fullName>
    <label>Encours</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/LatePayment__c.field-meta.xml
<CustomField>
    <fullName>LatePayment__c</fullName>
    <description>Alimenté par KWOTE</description>
    <label>Retard de paiement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/PFRegion__c.field-meta.xml
<CustomField>
    <fullName>PFRegion__c</fullName>
    <label>Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/Intf_WebserviceCalloutKwote_Test.cls
/**
 * Created by Michael on 04-04-24.
 */

@IsTest
private class Intf_WebserviceCalloutKwote_Test {

    @TestSetup
    static void setupData() {

        SalesArea__c sa = new SalesArea__c(
                Name = 'test'
        );
        insert sa;

        Id acRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();

        Account account = new Account(
                Name = 'Agence Test',
                Tech_SAP_Id__c = 'SAP1234',
                RecordTypeId = acRecTypeId,
                DB_Valeur_ID_Prefere__c = 'BE0547562822'
        );
        insert account;

        SalesAreaData__c sad = new SalesAreaData__c(
                Account__c = account.Id,
                SalesArea__c = sa.Id,
                PFRegion__c = 'PIBE'
        );
        insert sad;

        Id coRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Particulier_B2C').getRecordTypeId();

        Contact contact = new Contact(
                FirstName = 'Monsieur',
                LastName = 'Test',
                MobilePhone = '063456884',
                AccountId = account.Id,
                RecordTypeId = coRecTypeId,
                Fonction__c = 'Particulier'
        );
        insert contact;

    }
    @IsTest
    static void testBehavior() {

        Intf_Kwote_Access_Mapping__mdt kwoteAccessMapping = [SELECT Id, api_key__c, api_access__c, Legal_Entity__c FROM Intf_Kwote_Access_Mapping__mdt WHERE DeveloperName = 'PIBE'];

        Map<String, String> headers = new Map<String, String>{
                'X-API-KEY' => kwoteAccessMapping.api_key__c,
                'X-API-PWD' => kwoteAccessMapping.api_access__c,
                'accept' => 'application/json'
        };

        Intf_WebserviceMock.status = 200;
        Intf_WebserviceMock.interfaceToTest = 'KWOTE';

        Test.startTest();
        Test.setMock(HttpCalloutMock.class,new Intf_WebserviceMock());

        Intf_WebserviceCalloutKwote.headers = headers;

        Intf_WebserviceCalloutKwote intfWebserviceCalloutWO = new Intf_WebserviceCalloutKwote();
        intfWebserviceCalloutWO.executeCallout(new List<Object>{kwoteAccessMapping.Legal_Entity__c});

        Test.stopTest();

        SalesAreaData__c sad = [SELECT Id, Encours__c, LatePayment__c, Score__c FROM SalesAreaData__c LIMIT 1];
        System.debug('========================== TEST Intf_WebserviceCalloutKwote_Test sad: ' + sad);
        System.assertEquals(1, sad.Encours__c);
        System.assertEquals(1, sad.LatePayment__c);

    }
}