unpackaged/main/default/objects/Account/fields/Grade_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Grade_Request_Date__c</fullName>
    <label>Grade Request Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut_du_grade__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_grade__c</fullName>
    <label>Statut du grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchAccountValidation_TEST.cls
@isTest
public class BatchAccountValidation_TEST {
    static void setupTestData() {
        List<Account> accounts = new List<Account>();
        accounts.add(new Account(Name='Test Account 1', Statut_du_grade__c='Processing', Grade_Request_Date__c=System.now().addMinutes(-1)));
        accounts.add(new Account(Name='Test Account 2', Statut_du_grade__c='Processing', Grade_Request_Date__c=System.now().addMinutes(-10)));
        insert accounts;
    }

    @isTest
    static void testBatchExecution() {
        // Démarrer le test en appelant la méthode setupTestData
        setupTestData();
        
        
        // Démarrer le batch
        Test.startTest();
        BatchAccountValidation batch = new BatchAccountValidation();
        Database.executeBatch(batch);
        Test.stopTest();

        List<Account> updatedAccounts = [SELECT Id, Statut__c, Statut_du_grade__c, Grade_Request_Date__c FROM Account WHERE Statut_du_grade__c = 'Error'];
        System.assert(updatedAccounts.size() == 1, 'Il devrait y avoir un seul account avec la valeur du statut du grade = Error');
    }
}