unpackaged/main/default/objects/Account/fields/Grade_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Grade_Request_Date__c</fullName>
    <label>Grade Request Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut_du_grade__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_grade__c</fullName>
    <label>Statut du grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchAccountValidation.cls
global class BatchAccountValidation implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Statut__c, Statut_du_grade__c, Grade_Request_Date__c FROM Account WHERE Statut_du_grade__c = \'Processing\' AND Grade_Request_Date__c != null';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
        List<Account> accountToUpdate = new List<Account>();
        for(Account account : scope) {
            if(account.Grade_Request_Date__c.addMinutes(5) < Datetime.now()) {
                account.Statut__c = 'Attente Validation CM';
                account.Statut_du_grade__c = 'Error';
                accountToUpdate.add(account);
            }
        }
        if(accountToUpdate.size() > 0) {
            update accountToUpdate;
        }
    }

    global void finish(Database.BatchableContext BC) {
    
        System.Debug('>>>> AccountGradesValidation End execute <<<<');
    }
}