unpackaged/main/default/objects/Account/fields/IDEulerHermes__c.field-meta.xml
<CustomField>
    <fullName>IDEulerHermes__c</fullName>
    <label>ID Euler Hermes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>Policy_Id__c</fullName>
    <formula>IF( ISPICKVAL(PaysRegionPF__c, &#39;PIES&#39;), &#39;A0003414901&#39;,
  IF( ISPICKVAL(PaysRegionPF__c, &#39;PIBE&#39;), &#39;A0009271201&#39;,
    IF( ISPICKVAL(PaysRegionPF__c, &#39;PILU&#39;), &#39;A0009271401&#39;,
      IF( ISPICKVAL(PaysRegionPF__c, &#39;PIND&#39;), &#39;A0009271601&#39;,
        IF( ISPICKVAL(PaysRegionPF__c, &#39;PIPT&#39;), &#39;A0011913601&#39;,
          IF( ISPICKVAL(PaysRegionPF__c, &#39;PFUK&#39;), &#39;A0014354401&#39;,
            IF( ISPICKVAL(PaysRegionPF__c, &#39;PITA&#39;), &#39;A0017874001&#39;,
              IF( ISPICKVAL(PaysRegionPF__c, &#39;PIRL&#39;), &#39;A0018560801&#39;,
                IF( ISPICKVAL(PaysRegionPF__c, &#39;PIPL&#39;), &#39;A0022172401&#39;,
                  IF( ISPICKVAL(PaysRegionPF__c, &#39;PIDE&#39;), &#39;A0022707601&#39;,
                    IF( ISPICKVAL(PaysRegionPF__c, &#39;PICZ&#39;), &#39;A0025918801&#39;,
                      IF( ISPICKVAL(PaysRegionPF__c, &#39;PIAT&#39;), &#39;A0027311601&#39;,
                        IF( ISPICKVAL(PaysRegionPF__c, &#39;PIHU&#39;), &#39;A0027558601&#39;,
                          IF( 
                            AND(ISPICKVAL(PaysRegionPF__c, &#39;DROM&#39;), ISPICKVAL(Pays__c, &#39;REUNION&#39;)), 
                            &#39;A0033711801&#39;,
                            IF( 
                              AND(ISPICKVAL(PaysRegionPF__c, &#39;DROM&#39;), ISPICKVAL(Pays__c, &#39;ANTILLES&#39;)), 
                              &#39;A0033712001&#39;,
                              IF( 
                                OR(ISPICKVAL(PaysRegionPF__c, &#39;STFR1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;STFR2&#39;), 
                                   ISPICKVAL(PaysRegionPF__c, &#39;STFR3&#39;), ISPICKVAL(PaysRegionPF__c, &#39;STFR4&#39;), 
                                   ISPICKVAL(PaysRegionPF__c, &#39;STFR5&#39;)),
                                &#39;A0020436801&#39;,
                                IF( 
                                  OR(ISPICKVAL(PaysRegionPF__c, &#39;DRO IDF 1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO IDF 2&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 1&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 2&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 3&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 4&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 5&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 6&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO NORD 7&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 1&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 2&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 3&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 4&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 5&#39;), 
                                     ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 6&#39;), ISPICKVAL(PaysRegionPF__c, &#39;DRO SUD 7&#39;)),
                                  &#39;A0019715001&#39;,
                                  NULL)))))  ))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LegalEntity__c/LegalEntity__c.object-meta.xml
<CustomObject>
    <label>Entité Légale</label>
    <nameField>
        <label>Nom de l&#39;Entité Légale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités Légales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/PolicyId_Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Liste des différentes entités légale et la policy rattachée</description>
    <label>PolicyId By Legal Entity</label>
</CustomObject>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/policyId__c.field-meta.xml
<CustomField>
    <fullName>policyId__c</fullName>
    <description>Policy Allianz</description>
    <label>policyId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité Légale</label>
    <referenceTo>LegalEntity__c</referenceTo>
    <relationshipName>SalesArea</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Agrement__c.field-meta.xml
<CustomField>
    <fullName>Agrement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agrément</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Date_agrement__c.field-meta.xml
<CustomField>
    <fullName>Date_agrement__c</fullName>
    <label>Date agrément</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Montant_agrement__c.field-meta.xml
<CustomField>
    <fullName>Montant_agrement__c</fullName>
    <label>Montant agrément</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchVCCAgrement.cls
global class BatchVCCAgrement implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {

    Map<String, Map<String, Object>> coversByIdEuler = new Map<String, Map<String, Object>>();

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.Debug('>>>> VCC agrement Batch Start start <<<<');
        
        String query = 'SELECT policyId__c FROM PolicyId_Legal_Entity__c';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<PolicyId_Legal_Entity__c> scope) {
        System.Debug('>>>> VCC agrement Batch Start Execute <<<<');
        List<String> policiesId = new List<String>();
        for(PolicyId_Legal_Entity__c policy : scope) {
            policiesId.add(policy.policyId__c.substringAfter('A'));
        }
        List<PolicyId_Legal_Entity__c> policies = PolicyId_Legal_Entity__c.getAll().values();
        coversByIdEuler.putAll(AllianzWebServiceRest.getLastUpdatedAgrement(AllianzWebServiceRest.getNewAccessToken(), policies));
    }

    global void finish(Database.BatchableContext BC) {
        System.Debug('>>>> VCC agrement Batch Start Finish <<<<');
        Map<String, String> legalEntityToPolicyIdMap = new Map<String,String>();
        List<PolicyId_Legal_Entity__c> policies = PolicyId_Legal_Entity__c.getAll().values();
        for(PolicyId_Legal_Entity__c ple : policies) {
            legalEntityToPolicyIdMap.put(ple.Legal_Entity__c, ple.policyId__c.substringAfter('A'));
        }
        if(coversByIdEuler.size() > 0) {
            List<SalesAreaData__c> sadsToUpdate = new List<SalesAreaData__c>();
            List<SalesAreaData__c> sads = [SELECT Id, Agrement__c, Montant_agrement__c, Date_agrement__c, Account__r.IDEulerHermes__c, Account__r.Policy_Id__c, SalesArea__r.LegalEntity__r.Name, CurrencyIsoCode FROM SalesAreaData__c WHERE  Account__r.IDEulerHermes__c IN: coversByIdEuler.keySet()];
            for(SalesAreaData__c sad : sads) {
                if(coversByIdEuler.containsKey(sad.Account__r.IDEulerHermes__c)){
                    Map<String, Object> coverInformationMap = ((Map<String, Map<String, Object>>)coversByIdEuler.get(sad.Account__r.IDEulerHermes__c)).get(legalEntityToPolicyIdMap.get(sad.SalesArea__r.LegalEntity__r.Name));
                    if(coverInformationMap !=null) {
                        sad.Agrement__c = true;
                        sad.Montant_agrement__c = sad.CurrencyIsoCode != 'EUR' ? AllianzWebServiceRest.convertCurrencyWithApexCode(sad.CurrencyIsoCode,(Decimal)coverInformationMap.get('totalAmount')) : (Decimal)coverInformationMap.get('totalAmount');
                        sad.Date_agrement__c = Date.valueOf((String)coverInformationMap.get('lastUpdateDate'));
                        sadsToUpdate.add(sad);
                    }
                }
            }
            if(sadsToUpdate.size() > 0) {
                update sadsToUpdate;
            }
        }
    }
}