unpackaged/main/default/objects/Account/fields/IDEulerHermes__c.field-meta.xml
<CustomField>
    <fullName>IDEulerHermes__c</fullName>
    <label>ID Euler Hermes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LegalEntity__c/LegalEntity__c.object-meta.xml
<CustomObject>
    <label>Entité Légale</label>
    <nameField>
        <label>Nom de l&#39;Entité Légale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités Légales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Agrement__c.field-meta.xml
<CustomField>
    <fullName>Agrement__c</fullName>
    <description>Agrément Sfac + Date Agrément</description>
    <formula>IF(ISBLANK(Account.AgrementSFAC__c),&quot;###&quot;,TEXT(ROUND(Account.AgrementSFAC__c,2) ))  &amp; &quot; // &quot; &amp; IF(ISBLANK(Account.DateAgrementEH__c),&quot;###&quot;,IF(LEN(TEXT(DAY(Account.DateAgrementEH__c))) &gt; 1 , TEXT(DAY(Account.DateAgrementEH__c)), &quot;0&quot; + TEXT(DAY(Account.DateAgrementEH__c)))+ &quot;-&quot; +IF(LEN(TEXT(MONTH(Account.DateAgrementEH__c))) &gt; 1 , TEXT(MONTH(Account.DateAgrementEH__c)), &quot;0&quot; + TEXT(MONTH(Account.DateAgrementEH__c)))+&quot;-&quot; +TEXT(YEAR(Account.DateAgrementEH__c)))</formula>
    <label>Agrément</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité Légale</label>
    <referenceTo>LegalEntity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vue commerciale client sur la quelle l&#39;opportunité a été créé.</description>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/PolicyId_Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Liste des différentes entités légale et la policy rattachée</description>
    <label>PolicyId By Legal Entity</label>
</CustomObject>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/Business_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Code__c</fullName>
    <label>Business Unit Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/PolicyId_Legal_Entity__c/fields/policyId__c.field-meta.xml
<CustomField>
    <fullName>policyId__c</fullName>
    <description>Policy Allianz</description>
    <label>policyId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité Légale</label>
    <referenceTo>LegalEntity__c</referenceTo>
    <relationshipName>SalesArea</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Agrement__c.field-meta.xml
<CustomField>
    <fullName>Agrement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agrément</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Date_agrement__c.field-meta.xml
<CustomField>
    <fullName>Date_agrement__c</fullName>
    <label>Date agrément</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Montant_agrement__c.field-meta.xml
<CustomField>
    <fullName>Montant_agrement__c</fullName>
    <label>Montant agrément</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/UpdateAgrementController.cls
public class UpdateAgrementController {

    @AuraEnabled
    public static String updateAgrement(String recordId){
        String successfulUpdate = '';
        String policyId;
        String businessUnitCode;
        Map<String, Object> coversByIdEuler = new Map<String, Object>();
        Map<String, String> legalEntityToPolicyIdMap = new Map<String,String>();
        Map<String, string> businessUnitCodeByLegalEntityMap = new Map<String, String>();
        List<SalesAreaData__c> sadToUpdate = new List<SalesAreaData__c>();

        try {
            Opportunity opp = [SELECT Id, SalesAreaData__c, AccountId FROM Opportunity WHERE Id =: recordId];
            Account acc = [SELECT Id, Pays__c FROM Account WHERE Id =: opp.AccountId];
            if(acc.Pays__c != 'FRANCE') {
                List<SalesAreaData__c> sadList = [SELECT Id, Agrement__c, Montant_agrement__c, Date_agrement__c, Account__r.IDEulerHermes__c, SalesArea__r.LegalEntity__r.Name, CurrencyIsoCode FROM SalesAreaData__c WHERE Account__c =:opp.AccountId];
                List<PolicyId_Legal_Entity__c> tempList = PolicyId_Legal_Entity__c.getAll().values();
                for(PolicyId_Legal_Entity__c ple : tempList) {
                    legalEntityToPolicyIdMap.put(ple.Legal_Entity__c, ple.policyId__c);
                    businessUnitCodeByLegalEntityMap.put(ple.Legal_Entity__c, ple.Business_Unit_Code__c);
                }
                policyId = legalEntityToPolicyIdMap.get(sadList[0].SalesArea__r.LegalEntity__r.Name);
                businessUnitCode = businessUnitCodeByLegalEntityMap.get(sadList[0].SalesArea__r.LegalEntity__r.Name);

                if(policyId != null && policyId != '') {
                    coversByIdEuler.putAll(AllianzWebServiceRest.getCoverInformation(businessUnitCode, policyId.substringAfter('A'), new List<String>{sadList[0].Account__r.IDEulerHermes__c}));
                    if(coversByIdEuler.containsKey(sadList[0].Account__r.IDEulerHermes__c)) {
                        Map<String, Object> coverInformationMap = (Map<String, Object>)coversByIdEuler.get(sadList[0].Account__r.IDEulerHermes__c);
                        for(SalesAreaData__c sad : sadList){
                            if(Date.valueOf((String)coverInformationMap.get('lastUpdateDate')) != sad.Date_agrement__c) {
                                sad.Agrement__c = true;
                                sad.Montant_agrement__c = sad.CurrencyIsoCode != 'EUR' ? AllianzWebServiceRest.convertCurrencyWithApexCode(sad.CurrencyIsoCode,(Decimal)coverInformationMap.get('totalAmount')) : (Decimal)coverInformationMap.get('totalAmount');
                                sad.Date_agrement__c = Date.valueOf((String)coverInformationMap.get('lastUpdateDate'));
                                sadToUpdate.add(sad);
                            } else {
                                successfulUpdate = 'No change';
                            }
                        }
                    } else {
                            successfulUpdate = 'Agrement not found';
                        }
                    } else {
                        successfulUpdate = 'Problem with policyId';
                    }
                    if(!sadToUpdate.isEmpty()) {
                        update sadToUpdate;
                        successfulUpdate = 'Done';
                    }
                return successfulUpdate;
            }
            else {
                SalesAreaData__c sad = [SELECT Id, Agrement__c, Montant_agrement__c, Date_agrement__c, Account__r.IDEulerHermes__c, SalesArea__r.LegalEntity__r.Name, CurrencyIsoCode FROM SalesAreaData__c WHERE Id =:opp.SalesAreaData__c];
                List<PolicyId_Legal_Entity__c> tempList = PolicyId_Legal_Entity__c.getAll().values();
                for(PolicyId_Legal_Entity__c ple : tempList) {
                    legalEntityToPolicyIdMap.put(ple.Legal_Entity__c, ple.policyId__c);
                    businessUnitCodeByLegalEntityMap.put(ple.Legal_Entity__c, ple.Business_Unit_Code__c);
                }
                policyId = legalEntityToPolicyIdMap.get(sad.SalesArea__r.LegalEntity__r.Name);
                businessUnitCode = businessUnitCodeByLegalEntityMap.get(sad.SalesArea__r.LegalEntity__r.Name);

                if(policyId != null && policyId != '') {
                    coversByIdEuler.putAll(AllianzWebServiceRest.getCoverInformation(businessUnitCode, policyId.substringAfter('A'), new List<String>{sad.Account__r.IDEulerHermes__c}));
                    if(coversByIdEuler.containsKey(sad.Account__r.IDEulerHermes__c)) {
                        Map<String, Object> coverInformationMap = (Map<String, Object>)coversByIdEuler.get(sad.Account__r.IDEulerHermes__c);
                        if(Date.valueOf((String)coverInformationMap.get('lastUpdateDate')) != sad.Date_agrement__c) {
                            sad.Agrement__c = true;
                            sad.Montant_agrement__c = sad.CurrencyIsoCode != 'EUR' ? AllianzWebServiceRest.convertCurrencyWithApexCode(sad.CurrencyIsoCode,(Decimal)coverInformationMap.get('totalAmount')) : (Decimal)coverInformationMap.get('totalAmount');
                            sad.Date_agrement__c = Date.valueOf((String)coverInformationMap.get('lastUpdateDate'));
                            update sad;
                            successfulUpdate = 'Done';
                        } else {
                            successfulUpdate = 'No change';
                        }
                    } else {
                        successfulUpdate = 'Agrement not found';
                    }
                } else {
                    successfulUpdate = 'Problem with policyId';
                }
                return successfulUpdate;
            }
        } catch (Exception e) {
            System.debug(e.getMessage());
            
            successfulUpdate = 'No Sales Area Data';
            return successfulUpdate;
        }
    }
}