unpackaged/main/default/objects/Account/fields/Intf_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Intf_Sync_Status__c</fullName>
    <label>Statut Synchronisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intf_Statut_Synchro</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Organisation_de_service_SAP__c.field-meta.xml
<CustomField>
    <fullName>Organisation_de_service_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Organisation de service SAP</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_SAP_Id__c</fullName>
    <label>Tech SAP Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville (-Facturation-)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120O0000003cw4QAA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>Contact_Chauffeur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact :
- Type d&#39;enregistrement : Chauffeur 
- Compte du contact = Compte Requête</description>
    <label>Contact - Chauffeur</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Chauffeur</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_responsable_parc__c.field-meta.xml
<CustomField>
    <fullName>Contact_responsable_parc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact - responsable parc</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) AND 5</booleanFilter>
        <errorMessage>Le type de contact ne correspond pas au type de la requête</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Responsable de parcs</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dépannage - Container</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Commercial, Contact - Chauffeur, Contact - Responsable de parcs</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Demande de service</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Agence_proprietaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requêtes (Contact)</relationshipLabel>
    <relationshipName>Requete</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Description_incident_client__c.field-meta.xml
<CustomField>
    <fullName>Description_incident_client__c</fullName>
    <label>Description incident client</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/N_Tel_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>N_Tel_Chauffeur__c</fullName>
    <label>N° Tel - Chauffeur</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Nom_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>Nom_Chauffeur__c</fullName>
    <label>Nom Chauffeur</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>SLOVAQUIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Precision__c.field-meta.xml
<CustomField>
    <fullName>Precision__c</fullName>
    <label>Précisions lieu panne</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Rue_Lieu__c.field-meta.xml
<CustomField>
    <fullName>Rue_Lieu__c</fullName>
    <label>Rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Intf_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Intf_Sync_Status__c</fullName>
    <label>Statut Synchronisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intf_Statut_Synchro</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BOLIVIE</fullName>
            </value>
            <value>
                <fullName>BOSNIE HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>BURKINA FASO</fullName>
            </value>
            <value>
                <fullName>CAMBODGE</fullName>
            </value>
            <value>
                <fullName>CAMEROUN</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILI</fullName>
            </value>
            <value>
                <fullName>CHINE</fullName>
            </value>
            <value>
                <fullName>CHYPRE</fullName>
            </value>
            <value>
                <fullName>CISJORDANIE</fullName>
            </value>
            <value>
                <fullName>COLOMBIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Intf_Activation__mdt/Intf_Activation__mdt.object-meta.xml
<CustomObject>
    <label>Intf Activation</label>
    <pluralLabel>Intf Activations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Intf_Activation__mdt/fields/Interface_Name__c.field-meta.xml
<CustomField>
    <fullName>Interface_Name__c</fullName>
    <label>Interface Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account_SAP</fullName>
                <default>true</default>
                <label>Account_SAP</label>
            </value>
            <value>
                <fullName>WorkOrder_SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordres de Travail</relationshipLabel>
    <relationshipName>Ordres_de_Travail</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Intf_Statut_Synchro.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sync</fullName>
        <label>Synchronisé</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <label>En Cours</label>
    </customValue>
    <customValue>
        <fullName>Notsync</fullName>
        <default>true</default>
        <label>Pas Synchro</label>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
        <label>Erreur</label>
    </customValue>
    <customValue>
        <fullName>Resend</fullName>
    </customValue>
    <customValue>
        <fullName>Resync</fullName>
        <isActive>false</isActive>
        <label>Resync</label>
    </customValue>
    <masterLabel>Intf Statut Synchro</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Intf_WorkOrderTriggerHandler.cls
/**
 * @description       :
 * @author            : Michaël Cabaraux
 * @group             :
 * @last modified on  : 05-05-2024
 * @last modified by  : Michaël Cabaraux
**/

public with sharing class Intf_WorkOrderTriggerHandler {

    private static final String INTERFACE_NAME = 'WorkOrder_SAP';

    public without sharing class sendWorkOrderToSAP implements Intf_Framework_Triggers.Handler {
        public void handle() {

            List<Intf_Activation__mdt> interfaceActivations = new List<Intf_Activation__mdt>([SELECT Id, Active__c FROM Intf_Activation__mdt WHERE Interface_Name__c = :INTERFACE_NAME]);

            if (!Test.isRunningTest() && (interfaceActivations.isEmpty() || interfaceActivations[0].Active__c == false)) { return; }

            List<WorkOrder> workOrderToSend = new List<WorkOrder>();

            if (Trigger.isInsert) {
                workOrderToSend = (List<WorkOrder>)Trigger.new;

            } else {
                for (WorkOrder wo: (List<WorkOrder>)Trigger.new) {
                    if (wo.Intf_Sync_Status__c == 'Resend') {
                        workOrderToSend.add(wo);
                    }
                }
            }

            System.debug('========================== WorkOrderTriggerHandler sendWorkOrderToSAP workOrderToSend#: ' + workOrderToSend.size());
            if (!workOrderToSend.isEmpty()) {
                sendWorkOrdersToSAP(workOrderToSend);
            }
        }
    }

    private static void sendWorkOrdersToSAP(List<WorkOrder> workOrders) {

        Set<Id> caseIds = new Set<Id>();
        Set<Id> agencesIds = new Set<Id>();

        for (WorkOrder wo : workOrders) {
            if (wo.CaseId != null) { caseIds.add(wo.CaseId); }
            if (wo.Agence_Intervenante__c != null) { agencesIds.add(wo.Agence_Intervenante__c); }
        }
        
        //if(caseIds.isEmpty()) return;

        Map<Id, Case> casesByIds = new Map<Id, Case>([
                SELECT Id, Asset.Name, Contact_Chauffeur__c, Contact_responsable_parc__c, Contact_Chauffeur__r.Name, Contact_Chauffeur__r.Email, Contact_Chauffeur__r.MobilePhone,
                        Contact_Chauffeur__r.Phone, Contact_responsable_parc__r.Name, Contact_responsable_parc__r.Email, Contact_responsable_parc__r.MobilePhone,
                        Contact_responsable_parc__r.Phone, Nom_Chauffeur__c, N_Tel_Chauffeur__c, Precision__c, Priority, Ville__c, Code_postal__c, Pays__c, Rue_Lieu__c, Description_incident_client__c,
                        Account.Tech_SAP_Id__c
                FROM Case WHERE Id = :caseIds
        ]);

        Map<Id, String> agenceSAPIdsByIds = new Map<Id, String>();
        for (Account account : [SELECT Id, Organisation_de_service_SAP__c FROM Account WHERE Id in :agencesIds]) {
            agenceSAPIdsByIds.put(account.Id, account.Organisation_de_service_SAP__c);
        }

        List<Intf_WorkOrderSchemaBuilder.WorkOrderMsg> woMessages = new List<Intf_WorkOrderSchemaBuilder.WorkOrderMsg>();

        for (WorkOrder wo : workOrders) {
            woMessages.add(new Intf_WorkOrderSchemaBuilder.WorkOrderMsg(wo, casesByIds.get(wo.CaseId), agenceSAPIdsByIds.get(wo.Agence_Intervenante__c)));
        }

        if (!woMessages.isEmpty()) {
            Intf_WebserviceCalloutWO intfWebserviceCalloutWO = new Intf_WebserviceCalloutWO();
            intfWebserviceCalloutWO.executeCallout(woMessages);
        }


    }

}