unpackaged/main/default/objects/Account/fields/Intf_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Intf_Sync_Status__c</fullName>
    <label>Statut Synchronisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intf_Statut_Synchro</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_SAP_Id__c</fullName>
    <label>Tech SAP Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Intf_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Intf_Sync_Status__c</fullName>
    <label>Statut Synchronisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intf_Statut_Synchro</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Rôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Détracteur</fullName>
            </value>
            <value>
                <fullName>Indifférent</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact_Chauffeur.recordType-meta.xml
<RecordType>
    <fullName>Contact_Chauffeur</fullName>
    <active>true</active>
    <label>Contact - Chauffeur</label>
</RecordType>

unpackaged/main/default/objects/Interface_Response__c/Interface_Response__c.object-meta.xml
<CustomObject>
    <label>Interface Response</label>
    <nameField>
        <label>Interface Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interface Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interface_Response__c/fields/CRM_Number__c.field-meta.xml
<CustomField>
    <fullName>CRM_Number__c</fullName>
    <label>CRM Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Interface_Name__c.field-meta.xml
<CustomField>
    <fullName>Interface_Name__c</fullName>
    <label>Interface Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intf_InterfaceName</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This is the status of the object create/update in the ERP : 
- &quot;S&quot; for the success creation/update in the ERP
- &quot;E&quot; for any error
- &quot;G&quot; to send contract after Price Sync</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Treatment_Message__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Message__c</fullName>
    <label>Treatment Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Treatment_Status__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Status__c</fullName>
    <label>Treatment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/InvolvedStakeholder__c/InvolvedStakeholder__c.object-meta.xml
<CustomObject>
    <label>Fonction partenaire</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Numéro Partie impliquée</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fonctions partenaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvolvedStakeholder__c/fields/InvolvedAccount__c.field-meta.xml
<CustomField>
    <fullName>InvolvedAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Prospect, Client, Particulier (B2C)</value>
        </filterItems>
        <filterItems>
            <field>$Source.Role__c</field>
            <operation>equals</operation>
            <value>Donneur d’ordre, Facturé, Payeur, PV</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>$Source.Role__c</field>
            <operation>equals</operation>
            <value>Livré</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fonctions partenaires</relationshipLabel>
    <relationshipName>Parties_impliquees_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/InvolvedStakeholder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Partie_impliquee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvolvedStakeholder__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Fonction partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Donneur d’ordre</fullName>
            </value>
            <value>
                <fullName>Facturé</fullName>
            </value>
            <value>
                <fullName>Livré</fullName>
                <default>true</default>
                <label>Livré</label>
            </value>
            <value>
                <fullName>Payeur</fullName>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/InvolvedStakeholder__c/fields/SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>SAP_Id__c</fullName>
    <formula>if (Contact_B2C__c&lt;&gt;null, Contact_B2C__r.SAP_ID__c  ,InvolvedAccount__r.Tech_SAP_Id__c)</formula>
    <label>SAP Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vue commerciale client sur la quelle l&#39;opportunité a été créé.</description>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Earliest_Start_Permitted__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Start_Permitted__c</fullName>
    <label>Date Planifiée</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Intf_Synchronisation_Message__c.field-meta.xml
<CustomField>
    <fullName>Intf_Synchronisation_Message__c</fullName>
    <label>Synchronisation Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Organe_controler__c.field-meta.xml
<CustomField>
    <fullName>Organe_controler__c</fullName>
    <label>Organe à contrôler</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cabine</fullName>
            </value>
            <value>
                <fullName>Caisse</fullName>
            </value>
            <value>
                <fullName>Châssis</fullName>
            </value>
            <value>
                <fullName>Electricité</fullName>
            </value>
            <value>
                <fullName>Hayon</fullName>
            </value>
            <value>
                <fullName>Groupe</fullName>
                <label>Groupe frigorifique</label>
            </value>
            <value>
                <fullName>Pneumatiques</fullName>
                <label>Pneumatique</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/TECH_AgenceIntervenante_Name__c.field-meta.xml
<CustomField>
    <fullName>TECH_AgenceIntervenante_Name__c</fullName>
    <formula>Agence_Intervenante__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_AgenceIntervenante_Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Depannage_Vehicule.recordType-meta.xml
<RecordType>
    <fullName>Depannage_Vehicule</fullName>
    <active>true</active>
    <label>Depannage - Véhicule</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tour_de_parc.recordType-meta.xml
<RecordType>
    <fullName>Tour_de_parc</fullName>
    <active>true</active>
    <label>Tour de parc</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tour_de_parc_Chapeau.recordType-meta.xml
<RecordType>
    <fullName>Tour_de_parc_Chapeau</fullName>
    <active>true</active>
    <label>Tour de parc - Chapeau</label>
</RecordType>

unpackaged/main/default/globalValueSets/Intf_InterfaceName.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contract</fullName>
    </customValue>
    <customValue>
        <fullName>Account_Igloo</fullName>
        <label>Account Igloo</label>
    </customValue>
    <customValue>
        <fullName>Account_SAP</fullName>
        <label>Account SAP</label>
    </customValue>
    <customValue>
        <fullName>WorkOrder_SAP</fullName>
        <label>WorkOrder SAP</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
    </customValue>
    <description>Used in interfaces related objects</description>
    <masterLabel>Intf Interface Name</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Intf_Statut_Synchro.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sync</fullName>
        <label>Synchronisé</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <label>En Cours</label>
    </customValue>
    <customValue>
        <fullName>Notsync</fullName>
        <default>true</default>
        <label>Pas Synchro</label>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
        <label>Erreur</label>
    </customValue>
    <customValue>
        <fullName>Resend</fullName>
    </customValue>
    <customValue>
        <fullName>Resync</fullName>
        <isActive>false</isActive>
        <label>Resync</label>
    </customValue>
    <masterLabel>Intf Statut Synchro</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Intf_InterfaceRespTriggerHandler_Test.cls
/**
 * Created by Michael on 05-05-24.
 */

@IsTest
private class Intf_InterfaceRespTriggerHandler_Test {

    @TestSetup
    static void setupData() {

        Intf_Framework_Triggers.handlerBypass('sendWorkOrderToSAP');

        Id acRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();

        Asset asset = new Asset(
                Name = 'PF-123456'
        );
        insert asset;

        SalesArea__c sa = new SalesArea__c(
                Name = 'test'
        );
        insert sa;


        Account account = new Account(
                Name = 'Agence Test',
                RecordTypeId = acRecTypeId
        );
        insert account;

        SalesAreaData__c sad = new SalesAreaData__c(
                Account__c = account.Id,
                SalesArea__c = sa.Id
        );
        insert sad;

        Id coRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Chauffeur').getRecordTypeId();

        Contact contact = new Contact(
                FirstName = 'Monsieur',
                LastName = 'Test',
                MobilePhone = '063456884',
                AccountId = account.Id,
                RecordTypeId = coRecTypeId
        );
        insert contact;

        Id woRecTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get('Tour_de_parc_Chapeau').getRecordTypeId();

        WorkOrder wo = new WorkOrder(
                Organe_controler__c = 'Caisse',
                Earliest_Start_Permitted__c = Datetime.now().addDays(1),
                RecordTypeId = woRecTypeId,
                AccountId = account.Id
        );
        insert wo;

        WorkOrder woChild = new WorkOrder(
                Organe_controler__c = 'Caisse',
                Earliest_Start_Permitted__c = Datetime.now().addDays(1),
                RecordTypeId = woRecTypeId,
                AccountId = account.Id,
                ParentWorkOrderId = wo.Id,
                AssetId = asset.Id
        );
        insert woChild;

        Opportunity oppy = new Opportunity(
                AccountId = account.Id,
                Name = 'Oppy Test',
                CloseDate = Date.today().addDays(5),
                StageName = '1 - Opportunité créée',
                SalesAreaData__c = sad.Id

        );
        insert oppy;

        InvolvedStakeholder__c involvedStakeholder = new InvolvedStakeholder__c(
                InvolvedAccount__c = account.Id,
                Opportunity__c = oppy.Id,
                Role__c = 'Livré'
        );
        insert involvedStakeholder;

    }

    @IsTest
    static void testWorkOrderResponse() {

        WorkOrder wo = [SELECT Id FROM WorkOrder WHERE AssetId = null];

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = wo.Id,
                ERP_Number__c = 'SAP1234',
                Status__c = 'S',
                Interface_Name__c = 'WorkOrder_SAP'
        );

        insert interfaceResponse;

        wo = [SELECT Id, Intf_Sync_Status__c, SAP_ID__c FROM WorkOrder WHERE AssetId = null];
        System.debug('============= TEST TEST TEST wo: ' + wo);

        System.assertEquals('Sync', wo.Intf_Sync_Status__c);
        System.assertEquals('SAP1234', wo.SAP_ID__c);

    }

    @IsTest
    static void testWorkOrderResponseError() {

        WorkOrder wo = [SELECT Id FROM WorkOrder WHERE AssetId = null];

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = wo.Id,
                Response_Message__c = 'Error',
                Status__c = 'E',
                Interface_Name__c = 'WorkOrder_SAP'
        );

        insert interfaceResponse;

        wo = [SELECT Id, Intf_Sync_Status__c, Intf_Synchronisation_Message__c FROM WorkOrder WHERE AssetId = null];
        System.debug('============= TEST TEST TEST wo: ' + wo);

        System.assertEquals('Error', wo.Intf_Sync_Status__c);
        System.assertEquals('Error', wo.Intf_Synchronisation_Message__c);

    }

    @IsTest
    static void testBPResponseError() {

        Account account = [SELECT Id FROM account];

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = account.Id,
                Response_Message__c = 'Error',
                Status__c = 'E',
                Interface_Name__c = 'Account_SAP'
        );

        insert interfaceResponse;

        account = [SELECT Id, Intf_Sync_Status__c, Intf_Synchronisation_Message__c FROM account];

        System.assertEquals('Error', account.Intf_Sync_Status__c);
        System.assertEquals('Error', account.Intf_Synchronisation_Message__c);

    }

    @IsTest
    static void testB2CResponseError() {

        Contact contact = [SELECT Id, Intf_Synchronisation_Message__c, Intf_Sync_Status__c FROM contact LIMIT 1];

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = contact.Id,
                Status__c = 'E',
                Interface_Name__c = 'Account_SAP',
                Response_Message__c = 'ERROR'
        );

        insert interfaceResponse;

        contact = [SELECT Id, Intf_Sync_Status__c, Intf_Synchronisation_Message__c, SAP_ID__c FROM contact];

        System.assertEquals('Error', contact.Intf_Sync_Status__c);
        System.assertEquals('ERROR', contact.Intf_Synchronisation_Message__c);

    }

    @IsTest
    static void testB2CResponse() {

        Contact contact = [SELECT Id FROM contact LIMIT 1];

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = contact.Id,
                ERP_Number__c = 'SAP1234',
                Status__c = 'S',
                Interface_Name__c = 'Account_SAP'
        );

        insert interfaceResponse;

        contact = [SELECT Id, Intf_Sync_Status__c, SAP_ID__c FROM contact];

        System.assertEquals('Sync', contact.Intf_Sync_Status__c);
        System.assertEquals('SAP1234', contact.SAP_ID__c);

    }

    @IsTest
    static void testBPRespons() {

        Account account = [SELECT Id FROM account];
        Contact contact = [SELECT Id FROM contact LIMIT 1];

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = account.Id,
                ERP_Number__c = 'SAP1234',
                Status__c = 'S',
                Interface_Name__c = 'Account_SAP',
                Response_Message__c = '[{"salesforceContactId":"' + contact.Id + '","sapContactId":"291528"}]'
        );

        insert interfaceResponse;

        account = [SELECT Id, Intf_Sync_Status__c, Tech_SAP_Id__c FROM account];

        System.assertEquals('Sync', account.Intf_Sync_Status__c);
        System.assertEquals('SAP1234', account.Tech_SAP_Id__c);

    }

    @IsTest
    static void testNoHandler() {

        Account account = [SELECT Id FROM account];

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = account.Id,
                ERP_Number__c = 'SAP1234',
                Status__c = 'S',
                Interface_Name__c = 'Test'
        );
        insert interfaceResponse;

        interfaceResponse = [SELECT Id, Treatment_Message__c, Treatment_Status__c FROM Interface_Response__c];

        System.assertEquals('No response handler class for this interface', interfaceResponse.Treatment_Message__c);
        System.assertEquals('Error', interfaceResponse.Treatment_Status__c);
    }

    @IsTest
    static void testIncomingNormalWOError() {

        WorkOrder wo = [SELECT Id FROM WorkOrder WHERE AssetId = null];

        String incomingMessage = '{"BasicData":{"sapid":"27284554","type":"Depannage_Vehicule","sapaccountid":"SAP-123454","infocontact":"Chauffeur Test -- 0634567789 -- Adresse: Rue du test 1 34566 TestVile FR","titreordre":"Depannage_Vehicule","statut":"Terminé","priorite":"Moyenne","TECH_AgenceIntervenante_Name__c":"","sfcaseid":""},"parcs":[{"organe":"Caisse","numasset":"PF-123456","notetravaux":"Je suis en panne","realtravaux":"Changement pièces","observations":"Défectueux","daterelisation":"20240325114541"},{"organe":"Caisse","numasset":"PF-123464","notetravaux":"Je suis en panne","realtravaux":"Changement pièces","observations":"Défectueux","daterelisation":"20240326140712"}]}';

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = wo.Id,
                Response_Message__c = incomingMessage,
                Status__c = 'I',
                Interface_Name__c = 'WorkOrder_SAP'
        );

        insert interfaceResponse;

        List<WorkOrder> wos = new List<WorkOrder>([SELECT Id, Intf_Sync_Status__c, Intf_Synchronisation_Message__c FROM WorkOrder WHERE SAP_ID__c = '27284554']);
        System.assert(wos.isEmpty());

        interfaceResponse = [SELECT Id, Treatment_Message__c, Treatment_Status__c FROM Interface_Response__c];
        System.assertEquals('Error', interfaceResponse.Treatment_Status__c);
        System.assert(interfaceResponse.Treatment_Message__c.contains('Pas de compte'));

    }

    @IsTest
    static void testIncomingNormalWO() {

        Account account = [SELECT Id, Tech_SAP_Id__c FROM account];
        account.Tech_SAP_Id__c = 'SAP-123454';
        update account;

        WorkOrder wo = [SELECT Id FROM WorkOrder WHERE AssetId = null];

        String incomingMessage = '{"BasicData":{"sapid":"27284554","type":"Depannage_Vehicule","sapaccountid":"SAP-123454","infocontact":"Chauffeur Test -- 0634567789 -- Adresse: Rue du test 1 34566 TestVile FR","titreordre":"Depannage_Vehicule","statut":"Terminé","priorite":"Moyenne","TECH_AgenceIntervenante_Name__c":"","sfcaseid":""},"parcs":[{"organe":"Caisse","numasset":"PF-123456","notetravaux":"Je suis en panne","realtravaux":"Changement pièces","observations":"Défectueux","daterelisation":"20240325114541"},{"organe":"Caisse","numasset":"PF-123464","notetravaux":"Je suis en panne","realtravaux":"Changement pièces","observations":"Défectueux","daterelisation":"20240326140712"}]}';

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                CRM_Number__c = wo.Id,
                Response_Message__c = incomingMessage,
                Status__c = 'I',
                Interface_Name__c = 'WorkOrder_SAP'
        );

        insert interfaceResponse;

        wo = [SELECT Id, Intf_Sync_Status__c, SAP_ID__c FROM WorkOrder WHERE SAP_ID__c = '27284554'];
        System.assertEquals('27284554', wo.SAP_ID__c);

        interfaceResponse = [SELECT Id, Treatment_Message__c, Treatment_Status__c FROM Interface_Response__c];
        System.assertEquals('Done', interfaceResponse.Treatment_Status__c);

    }

    @IsTest
    static void testIncomingYardCheck() {

        Account account = [SELECT Id, Tech_SAP_Id__c FROM account];
        account.Tech_SAP_Id__c = 'SAP-123454';
        update account;


        String incomingMessage = '{"BasicData":{"sapid":"27284554","type":"Tour_de_parc","sapaccountid":"SAP-123454","infocontact":"Chauffeur Test -- 0634567789 -- Adresse: Rue du test 1 34566 TestVile FR","titreordre":"Tour_de_parc","statut":"Terminé","priorite":"Moyenne","TECH_AgenceIntervenante_Name__c":"","sfcaseid":""},"parcs":[{"organe":"Caisse","numasset":"PF-123456","notetravaux":"Je suis en panne","realtravaux":"Changement pièces","observations":"Défectueux","daterelisation":"20240325114541"}]}';

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                Response_Message__c = incomingMessage,
                Status__c = 'I',
                Interface_Name__c = 'WorkOrder_SAP'
        );

        insert interfaceResponse;

        List<WorkOrder> wos = new List<WorkOrder>([SELECT Id, Intf_Sync_Status__c, SAP_ID__c FROM WorkOrder WHERE SAP_ID__c = '27284554']);
        System.assertEquals('27284554', wos[0].SAP_ID__c);

        List<WorkOrder> woChildren = new List<WorkOrder>([SELECT Id, Intf_Sync_Status__c, ParentWorkOrderId, Asset.Name FROM WorkOrder WHERE ParentWorkOrderId = :wos[0].Id]);
        System.debug('============== TEST TEST TEST woChildren : ' + woChildren);
        System.assertEquals('PF-123456', woChildren[0].Asset.Name);

        interfaceResponse = [SELECT Id, Treatment_Message__c, Treatment_Status__c FROM Interface_Response__c];
        System.assertEquals('Done', interfaceResponse.Treatment_Status__c);

    }

    @IsTest
    static void testIncomingYardCheckUpate() {

        Account account = [SELECT Id, Tech_SAP_Id__c FROM account];
        account.Tech_SAP_Id__c = 'SAP-123454';
        update account;

        WorkOrder wo = [SELECT Id, SAP_ID__c FROM WorkOrder WHERE AssetId = null];
        wo.SAP_ID__c = '27284554';
        update wo;

        String incomingMessage = '{"BasicData":{"sapid":"27284554","type":"Tour_de_parc","sapaccountid":"SAP-123454","infocontact":"Chauffeur Test -- 0634567789 -- Adresse: Rue du test 1 34566 TestVile FR","titreordre":"Tour_de_parc","statut":"Terminé","priorite":"Moyenne","TECH_AgenceIntervenante_Name__c":"","sfcaseid":""},"parcs":[{"organe":"Caisse","numasset":"PF-123456","notetravaux":"Je suis en panne","realtravaux":"Changement pièces","observations":"Défectueux","daterelisation":"20240325114541"}]}';

        Interface_Response__c interfaceResponse = new Interface_Response__c(
                Response_Message__c = incomingMessage,
                Status__c = 'I',
                Interface_Name__c = 'WorkOrder_SAP'
        );

        insert interfaceResponse;

        List<WorkOrder> wos = new List<WorkOrder>([SELECT Id, Intf_Sync_Status__c, SAP_ID__c, Status FROM WorkOrder WHERE SAP_ID__c = '27284554']);
        System.debug('============== TEST TEST TEST wos : ' + wos);
        System.assertEquals('Terminé', wos[0].Status);

        List<WorkOrder> woChildren = new List<WorkOrder>([SELECT Id, Intf_Sync_Status__c, ParentWorkOrderId, Asset.Name, Status  FROM WorkOrder WHERE ParentWorkOrderId = :wos[0].Id]);
        System.debug('============== TEST TEST TEST woChildren : ' + woChildren);
        System.assertEquals('Terminé', woChildren[0].Status);

        interfaceResponse = [SELECT Id, Treatment_Message__c, Treatment_Status__c FROM Interface_Response__c];
        System.debug('============== TEST TEST TEST Treatment_Message__c : ' + interfaceResponse.Treatment_Message__c);
        System.assertEquals('Done', interfaceResponse.Treatment_Status__c);

    }
}