unpackaged/main/default/objects/Account/fields/Intf_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Intf_Sync_Status__c</fullName>
    <label>Statut Synchronisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intf_Statut_Synchro</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_SAP_Id__c</fullName>
    <label>Tech SAP Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Intf_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Intf_Sync_Status__c</fullName>
    <label>Statut Synchronisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intf_Statut_Synchro</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/Interface_Response__c.object-meta.xml
<CustomObject>
    <label>Interface Response</label>
    <nameField>
        <label>Interface Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interface Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interface_Response__c/fields/CRM_Number__c.field-meta.xml
<CustomField>
    <fullName>CRM_Number__c</fullName>
    <label>CRM Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This is the status of the object create/update in the ERP : 
- &quot;S&quot; for the success creation/update in the ERP
- &quot;E&quot; for any error
- &quot;G&quot; to send contract after Price Sync</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Treatment_Message__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Message__c</fullName>
    <label>Treatment Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Treatment_Status__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Status__c</fullName>
    <label>Treatment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Intf_Statut_Synchro.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sync</fullName>
        <label>Synchronisé</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <label>En Cours</label>
    </customValue>
    <customValue>
        <fullName>Notsync</fullName>
        <default>true</default>
        <label>Pas Synchro</label>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
        <label>Erreur</label>
    </customValue>
    <customValue>
        <fullName>Resend</fullName>
    </customValue>
    <customValue>
        <fullName>Resync</fullName>
        <isActive>false</isActive>
        <label>Resync</label>
    </customValue>
    <masterLabel>Intf Statut Synchro</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Intf_BusinessPartnerResponseHandler.cls
/**
 * Created by Michael on 20-03-24.
 */

public with sharing class Intf_BusinessPartnerResponseHandler implements Intf_ResponseHandlerInterface {

    private static final String TREATMENT_OK = 'Done';
    private static final String TREATMENT_ERROR = 'Error';

    public void handleResponses(List<Interface_Response__c> newMessages) {

        List<Interface_Response__c> interfaceResponsesToUpdate = new List<Interface_Response__c>();
        List<Account> accountsToUpdate = new List<Account>();
        List<Contact> contactsToUpdate = new List<Contact>();

        for (Interface_Response__c interfaceResponse : newMessages) {

            Interface_Response__c intRepToUpdate = new Interface_Response__c(
                    Id = interfaceResponse.Id
            );

            String objectAPIName = ((Id)interfaceResponse.CRM_Number__c).getSobjectType().getDescribe().getName();
            System.debug('======= Intf_BusinessPartnerResponseHandler objectAPIName: '+ objectAPIName);
            System.debug('======= Intf_BusinessPartnerResponseHandler interfaceResponse.CRM_Number__c: '+ interfaceResponse.CRM_Number__c);

            switch on interfaceResponse.Status__c {
                when 'S' {
                    // Success

                    try {
                        if (objectAPIName == 'Account') {

                            try {
                                List<MultiContact> contactInfos = (List<MultiContact>)JSON.deserialize(interfaceResponse.Response_Message__c,List<MultiContact>.class);
                                List<Contact> contactsB2BToUpdate =  new List<Contact>();

                                for (MultiContact contactInfo : contactInfos) {
                                    contactsB2BToUpdate.add(new Contact(
                                            Id = contactInfo.salesforceContactId,
                                            SAP_ID__c = contactInfo.sapContactId,
                                            Intf_Sync_Status__c = 'Sync',
                                            Intf_Synchronisation_Message__c = null
                                    ));
                                }
                                update contactsB2BToUpdate;

                            } catch (exception e) {
                                System.debug('======= No contact info returned');
                            }

                            accountsToUpdate.add(new Account(
                                    Id = interfaceResponse.CRM_Number__c,
                                    Intf_Sync_Status__c = 'Sync',
                                    Intf_Synchronisation_Message__c = null,
                                    Tech_SAP_Id__c = interfaceResponse.ERP_Number__c

                            ));

                        } else {
                            contactsToUpdate.add(new Contact(
                                    Id = interfaceResponse.CRM_Number__c,
                                    Intf_Sync_Status__c = 'Sync',
                                    Intf_Synchronisation_Message__c = null,
                                    SAP_ID__c = interfaceResponse.ERP_Number__c
                            ));
                        }

                        intRepToUpdate.Treatment_Status__c = TREATMENT_OK;

                    } catch (Exception e) {
                        intRepToUpdate.Treatment_Status__c = TREATMENT_ERROR;
                        intRepToUpdate.Treatment_Message__c = e.getMessage();
                    }

                }
                when 'E' {
                    // Errors

                    if (objectAPIName == 'Account') {
                        accountsToUpdate.add(new Account(
                                Id = interfaceResponse.CRM_Number__c,
                                Intf_Sync_Status__c = 'Error',
                                Intf_Synchronisation_Message__c = interfaceResponse.Response_Message__c
                        ));

                    } else {

                        contactsToUpdate.add(new Contact(
                                Id = interfaceResponse.CRM_Number__c,
                                Intf_Sync_Status__c = 'Error',
                                Intf_Synchronisation_Message__c = interfaceResponse.Response_Message__c
                        ));
                    }


                    intRepToUpdate.Treatment_Status__c = TREATMENT_OK;
                }
                when else {
                    // Code inconnu

                    intRepToUpdate.Treatment_Status__c = TREATMENT_ERROR;
                    intRepToUpdate.Treatment_Message__c = 'Unknown status code';

                }
            }
            interfaceResponsesToUpdate.add(intRepToUpdate);
        }

        System.debug('======= Intf_BusinessPartnerResponseHandler accountsToUpdate: '+ accountsToUpdate);
        System.debug('======= Intf_BusinessPartnerResponseHandler contactsToUpdate: '+ contactsToUpdate);

        update accountsToUpdate;
        update contactsToUpdate;
        update interfaceResponsesToUpdate;
    }

    public class MultiContact {
        public String salesforceContactId { get; set; }
        public String sapContactId { get; set ;}
    }
}