unpackaged/main/default/objects/Account/fields/Intf_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Intf_Sync_Status__c</fullName>
    <label>Statut Synchronisation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intf_Statut_Synchro</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Agence_PF.recordType-meta.xml
<RecordType>
    <fullName>Agence_PF</fullName>
    <active>true</active>
    <label>Agence PF</label>
</RecordType>

unpackaged/main/default/objects/Asset/fields/Origine__c.field-meta.xml
<CustomField>
    <fullName>Origine__c</fullName>
    <label>Origine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>En propre</fullName>
            </value>
            <value>
                <fullName>Groupe Petit Forestier</fullName>
            </value>
            <value>
                <fullName>Concurrent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/Interface_Response__c.object-meta.xml
<CustomObject>
    <label>Interface Response</label>
    <nameField>
        <label>Interface Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interface Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interface_Response__c/fields/CRM_Number__c.field-meta.xml
<CustomField>
    <fullName>CRM_Number__c</fullName>
    <label>CRM Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This is the status of the object create/update in the ERP : 
- &quot;S&quot; for the success creation/update in the ERP
- &quot;E&quot; for any error
- &quot;G&quot; to send contract after Price Sync</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Treatment_Message__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Message__c</fullName>
    <label>Treatment Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Interface_Response__c/fields/Treatment_Status__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Status__c</fullName>
    <label>Treatment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordres de Travail</relationshipLabel>
    <relationshipName>Ordres_de_Travail</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Anomalie__c.field-meta.xml
<CustomField>
    <fullName>Anomalie__c</fullName>
    <description>anomalie</description>
    <label>Anomalie</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>type_OE__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accastillage</fullName>
            </value>
            <value>
                <fullName>Accessoires (enregistreur, contacteur de porte, sonde piqueuse, etc)</fullName>
            </value>
            <value>
                <fullName>AEBS</fullName>
            </value>
            <value>
                <fullName>Alarme personne enfermée</fullName>
            </value>
            <value>
                <fullName>Alimentation</fullName>
            </value>
            <value>
                <fullName>Alimentation Carburant</fullName>
            </value>
            <value>
                <fullName>Alimentation électrique</fullName>
            </value>
            <value>
                <fullName>Alternateur</fullName>
            </value>
            <value>
                <fullName>Amortisseur</fullName>
            </value>
            <value>
                <fullName>Auvent</fullName>
            </value>
            <value>
                <fullName>Axes grippés</fullName>
            </value>
            <value>
                <fullName>Batterie Déchargée</fullName>
            </value>
            <value>
                <fullName>Batterie De Puissance Groupe Électrique</fullName>
            </value>
            <value>
                <fullName>Batterie De Traction Véhicule Électrique</fullName>
            </value>
            <value>
                <fullName>Batterie Frigo</fullName>
            </value>
            <value>
                <fullName>Batterie Hayon</fullName>
            </value>
            <value>
                <fullName>Bloc Moteur (Trous/Fuite)</fullName>
            </value>
            <value>
                <fullName>Bloque (Serrage Moteur)</fullName>
            </value>
            <value>
                <fullName>Bouteilles d&#39;air</fullName>
            </value>
            <value>
                <fullName>BV bloquée</fullName>
            </value>
            <value>
                <fullName>Cabine / équipements</fullName>
            </value>
            <value>
                <fullName>Cabine / Multimédia</fullName>
            </value>
            <value>
                <fullName>Cadre</fullName>
            </value>
            <value>
                <fullName>Calage</fullName>
            </value>
            <value>
                <fullName>Calandre</fullName>
            </value>
            <value>
                <fullName>Capteur D&#39;usure</fullName>
            </value>
            <value>
                <fullName>Chargeur Hayon</fullName>
            </value>
            <value>
                <fullName>Choc caisse</fullName>
            </value>
            <value>
                <fullName>Choc Carrosserie Ou Pare-brise</fullName>
            </value>
            <value>
                <fullName>Choc Cellule Isotherme (Caisse)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Date_de_realisation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_realisation__c</fullName>
    <label>Date de réalisation</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Date_Heure_Appel_technicien__c.field-meta.xml
<CustomField>
    <fullName>Date_Heure_Appel_technicien__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date / Heure Appel technicien</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Date_Heure_De_transmission__c.field-meta.xml
<CustomField>
    <fullName>Date_Heure_De_transmission__c</fullName>
    <label>Date / Heure De transmission</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Earliest_Start_Permitted__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Start_Permitted__c</fullName>
    <label>Date Planifiée</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Intervenant__c.field-meta.xml
<CustomField>
    <fullName>Intervenant__c</fullName>
    <label>Intervenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interne</fullName>
            </value>
            <value>
                <fullName>Externe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Intf_Synchronisation_Message__c.field-meta.xml
<CustomField>
    <fullName>Intf_Synchronisation_Message__c</fullName>
    <label>Synchronisation Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Lieu_Intervention__c.field-meta.xml
<CustomField>
    <fullName>Lieu_Intervention__c</fullName>
    <label>Lieu d’intervention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atelier</fullName>
            </value>
            <value>
                <fullName>Site client</fullName>
            </value>
            <value>
                <fullName>Autre adresse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Nom_du_technicien__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_technicien__c</fullName>
    <label>Nom du technicien</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Organe_controler__c.field-meta.xml
<CustomField>
    <fullName>Organe_controler__c</fullName>
    <label>Organe à contrôler</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cabine</fullName>
            </value>
            <value>
                <fullName>Caisse</fullName>
            </value>
            <value>
                <fullName>Châssis</fullName>
            </value>
            <value>
                <fullName>Electricité</fullName>
            </value>
            <value>
                <fullName>Hayon</fullName>
            </value>
            <value>
                <fullName>Groupe</fullName>
                <label>Groupe frigorifique</label>
            </value>
            <value>
                <fullName>Pneumatiques</fullName>
                <label>Pneumatique</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Origine__c.field-meta.xml
<CustomField>
    <fullName>Origine__c</fullName>
    <label>Origine</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Technique</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Parc_Assistance__c.field-meta.xml
<CustomField>
    <fullName>Parc_Assistance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parc Assistance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Parc</value>
        </filterItems>
        <infoMessage>Vous ne pouvez sélectionner que les parcs en position &quot;En service&quot;</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ordres de Travail (Parc Assistance)</relationshipLabel>
    <relationshipName>Ordres_de_Travail_Assistance</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Parc_Relais__c.field-meta.xml
<CustomField>
    <fullName>Parc_Relais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parc Relais</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.RecordTypeId</field>
            <operation>equals</operation>
            <value>Parc, Parc - Container</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ordres de Travail (Relais)</relationshipLabel>
    <relationshipName>Ordres_de_Travail_Relais</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Precisions_Long__c.field-meta.xml
<CustomField>
    <fullName>Precisions_Long__c</fullName>
    <label>Travaux Réalisés</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/TECH_MERGE_Observations__c.field-meta.xml
<CustomField>
    <fullName>TECH_MERGE_Observations__c</fullName>
    <label>Observations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Travaux_demandes__c.field-meta.xml
<CustomField>
    <fullName>Travaux_demandes__c</fullName>
    <label>Travaux demandés</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/type_OE__c.field-meta.xml
<CustomField>
    <fullName>type_OE__c</fullName>
    <description>type picklist</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origine__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Boite de vitesse</fullName>
            </value>
            <value>
                <fullName>Cabine</fullName>
            </value>
            <value>
                <fullName>Carrosserie/Cellule Isotherme</fullName>
            </value>
            <value>
                <fullName>Châssis</fullName>
            </value>
            <value>
                <fullName>Mauvaise Utilisation / Négligence</fullName>
            </value>
            <value>
                <fullName>Electricité Véhicule</fullName>
            </value>
            <value>
                <fullName>Freinage</fullName>
            </value>
            <value>
                <fullName>Groupe Froid</fullName>
            </value>
            <value>
                <fullName>Hayon/Portique</fullName>
            </value>
            <value>
                <fullName>Moteur</fullName>
            </value>
            <value>
                <fullName>Pneumatiques</fullName>
            </value>
            <value>
                <fullName>Pont/Essieu/Transmission</fullName>
            </value>
            <value>
                <fullName>Sinistre / Dégâts</fullName>
            </value>
            <value>
                <fullName>Caisse</fullName>
            </value>
            <value>
                <fullName>Electricité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tour_de_parc.recordType-meta.xml
<RecordType>
    <fullName>Tour_de_parc</fullName>
    <active>true</active>
    <label>Tour de parc</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tour_de_parc_Chapeau.recordType-meta.xml
<RecordType>
    <fullName>Tour_de_parc_Chapeau</fullName>
    <active>true</active>
    <label>Tour de parc - Chapeau</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tour_de_parc_Lecture_Seule.recordType-meta.xml
<RecordType>
    <fullName>Tour_de_parc_Lecture_Seule</fullName>
    <active>true</active>
    <label>Tour de parc - Lecture Seule</label>
</RecordType>

unpackaged/main/default/globalValueSets/Intf_Statut_Synchro.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sync</fullName>
        <label>Synchronisé</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <label>En Cours</label>
    </customValue>
    <customValue>
        <fullName>Notsync</fullName>
        <default>true</default>
        <label>Pas Synchro</label>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
        <label>Erreur</label>
    </customValue>
    <customValue>
        <fullName>Resend</fullName>
    </customValue>
    <customValue>
        <fullName>Resync</fullName>
        <isActive>false</isActive>
        <label>Resync</label>
    </customValue>
    <masterLabel>Intf Statut Synchro</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Intf_WorkOrderResponseHandler.cls
/**
 * Created by Michael on 20-03-24.
 */

public with sharing class Intf_WorkOrderResponseHandler implements Intf_ResponseHandlerInterface {

    private static final String OK_SAP_STATUS = 'S';
    private static final String ERROR_SAP_STATUS = 'E';
    private static final String INCOMING_SAP_STATUS = 'I';
    private static final String TREATMENT_OK = 'Done';
    private static final String TREATMENT_ERROR = 'Error';
    private static final String WO_RECTYPE_YARD_CHECK = 'Tour_de_parc';
    private static final String WO_RECTYPE_YARD_CHECK_RO = 'Tour_de_parc_Lecture_Seule';
    private static final String WO_RECTYPE_YARD_CHECK_HAT = 'Tour_de_parc_Chapeau';

    private static Map<String,String> agenceIdsByNames = new Map<String,String>();
    private static Map<String,String> accountIdsBySapAccountIds = new Map<String,String>();
    private static Map<String,String> assetIdsByNames = new Map<String,String>();
    private static Map<String,Workorder> workOrdersBySapIds = new Map<String,Workorder>();
    private static Map<String,Workorder> parentWorkOrdersBySapIds = new Map<String,Workorder>();

    private static Id woRecTypeROId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get(WO_RECTYPE_YARD_CHECK_RO).getRecordTypeId();
    private static Id woRecTypeHATId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get(WO_RECTYPE_YARD_CHECK_HAT).getRecordTypeId();

    public void handleResponses(List<Interface_Response__c> newMessages) {

        //We receive from SAP no need to send it back !!!
        Intf_Framework_Triggers.handlerBypass('sendWorkOrderToSAP');

        List<Interface_Response__c> interfaceResponsesToUpdate = new List<Interface_Response__c>();
        List<WorkOrder> workordersToUpdate = new List<WorkOrder>();

        populateWorkOrderMaps(newMessages);

        for (Interface_Response__c interfaceResponse : newMessages) {

            Interface_Response__c intRepToUpdate = new Interface_Response__c(
                    Id = interfaceResponse.Id
            );

            switch on interfaceResponse.Status__c {
                when 'S' {
                    // Success

                    try {
                        workordersToUpdate.add(new WorkOrder(
                                Id = interfaceResponse.CRM_Number__c,
                                Intf_Sync_Status__c = 'Sync',
                                Intf_Synchronisation_Message__c = null,
                                SAP_ID__c = interfaceResponse.ERP_Number__c

                        ));

                        intRepToUpdate.Treatment_Status__c = TREATMENT_OK;

                    } catch (Exception e) {
                        intRepToUpdate.Treatment_Status__c = TREATMENT_ERROR;
                        intRepToUpdate.Treatment_Message__c = e.getMessage();
                    }

                }
                when 'E' {
                    // Errors

                    workordersToUpdate.add(new WorkOrder(
                            Id = interfaceResponse.CRM_Number__c,
                            Intf_Sync_Status__c = 'Error',
                            Intf_Synchronisation_Message__c = interfaceResponse.Response_Message__c
                    ));

                    intRepToUpdate.Treatment_Status__c = TREATMENT_OK;
                }
                when 'I' {
                    // Tour de parce et changement de status
                    System.debug('===================== Intf_WorkOrderResponseHandler handleResponses Tour de parce et changement de status');

                    try {

                        Intf_WorkOrderSAPMessage workOrderSAPMessage = (Intf_WorkOrderSAPMessage)JSON.deserialize(interfaceResponse.Response_Message__c, Intf_WorkOrderSAPMessage.class);
                        System.debug('===================== Intf_WorkOrderResponseHandler handleResponses workOrderSAPMessage : ' + workOrderSAPMessage);

                        String sapId = workOrderSAPMessage.basicData.sapid;
                        if (String.isBlank(sapId)) { throw new Intf_Exception('Pas de SAP Id pour le workorder '); }

                        if (!accountIdsBySapAccountIds.containsKey(workOrderSAPMessage.basicData.sapaccountId)) { throw new Intf_Exception('Pas de compte correspondant au sap id ' + workOrderSAPMessage.basicData.sapaccountId + ' dans Salesforce'); }

                        if (workOrderSAPMessage.basicData.type == WO_RECTYPE_YARD_CHECK) {
                            System.debug('===================== Intf_WorkOrderResponseHandler handleResponses Tour de parc confirmed');

                            // Check if parent WO exists

                            if (!parentWorkOrdersBySapIds.containsKey(sapId)) {
                                //Create new HAT WO + children WO
                                WorkOrder parentWO = new WorkOrder(
                                        Status = workOrderSAPMessage.basicData.statut,
                                        RecordTypeId = woRecTypeHATId,
                                        AccountId = accountIdsBySapAccountIds.get(workOrderSAPMessage.basicData.sapaccountId),
                                        Agence_Intervenante__c = agenceIdsByNames.containsKey(workOrderSAPMessage.basicData.agenceintervenante) ? agenceIdsByNames.get(workOrderSAPMessage.basicData.agenceintervenante) : null,
                                        SAP_ID__c = sapId,
                                        Intf_Sync_Status__c = 'Sync'
                                );
                                insert parentWO;
                                System.debug('===================== Intf_WorkOrderResponseHandler handleResponses parentWO: ' + parentWO);

                                List<WorkOrder> childrenWOs = new List<WorkOrder>();

                                for (Intf_WorkOrderSAPMessage.Parc parc : workOrderSAPMessage.parcs) {

                                    if (!assetIdsByNames.containsKey(parc.numasset)) { throw new Intf_Exception('Pas d\'asset portant le numéro ' + parc.numasset + ' dans Salesforce'); }

                                    childrenWOs.add(new WorkOrder(
                                            Status = workOrderSAPMessage.basicData.statut,
                                            RecordTypeId = woRecTypeROId,
                                            AccountId = parentWO.AccountId,
                                            ParentWorkOrderId = parentWO.Id,
                                            Agence_Intervenante__c = parentWO.Agence_Intervenante__c,
                                            TECH_MERGE_Observations__c = parc.observations,
                                            AssetId = assetIdsByNames.get(parc.numasset)
                                    ));
                                }
                                insert childrenWOs;


                            } else {
                                //Update on yard check

                                Map<String, WorkOrder> workordersByAssetNames = new Map<String, WorkOrder>();

                                WorkOrder parentWO = parentWorkOrdersBySapIds.get(sapId);
                                for (WorkOrder wo : [SELECT Id, Asset.Name, Status, TECH_MERGE_Observations__c FROM WorkOrder WHERE ParentWorkOrderId = :parentWO.Id]) {
                                    workordersByAssetNames.put(wo.Asset.Name, wo);
                                }

                                for (Intf_WorkOrderSAPMessage.Parc parc : workOrderSAPMessage.parcs) {
                                    WorkOrder wo = workordersByAssetNames.get(parc.numasset);

                                    if (wo != null) {
                                        wo.TECH_MERGE_Observations__c = parc.observations;
                                        wo.Status = workOrderSAPMessage.basicData.statut;
                                    }
                                }

                                parentWO.Status = workOrderSAPMessage.basicData.statut;

                                update parentWO;
                                update workordersByAssetNames.values();

                            }

                        } else {

                            Id woRecordTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get(workOrderSAPMessage.basicData.type).getRecordTypeId();

                            Intf_WorkOrderSAPMessage.Parc parc = workOrderSAPMessage.parcs[0];
                            if (parc == null) { throw new Intf_Exception('Aucune information de Parc dans le message !');}
                            if (!assetIdsByNames.containsKey(parc.numasset)) { throw new Intf_Exception('Pas d\'asset portant le numéro ' + parc.numasset + ' dans Salesforce'); }

                            Datetime datetimeInfo = getDateTimeFromString(parc.daterelisation);
                            WorkOrder wo = new WorkOrder(
                                    Status = workOrderSAPMessage.basicData.statut,
                                    //RecordTypeId = woRecordTypeId,
                                    AccountId = accountIdsBySapAccountIds.get(workOrderSAPMessage.basicData.sapaccountId),
                                    Agence_Intervenante__c = agenceIdsByNames.containsKey(workOrderSAPMessage.basicData.agenceintervenante) ? agenceIdsByNames.get(workOrderSAPMessage.basicData.agenceintervenante) : null,
                                    TECH_MERGE_Observations__c = parc.observations,
                                    AssetId = assetIdsByNames.get(parc.numasset),
                                    Travaux_demandes__c = parc.notetravaux,
                                    Precisions_Long__c = parc.realtravaux,
                                    Organe_controler__c = parc.organe,
                                    Priority = workOrderSAPMessage.basicData.priorite,
                                    SAP_ID__c = sapId,
                                    Date_Heure_De_transmission__c = datetimeInfo,
                                    Date_Heure_Appel_technicien__c = datetimeInfo,
                                    Earliest_Start_Permitted__c = getDateTimeFromString(workOrderSAPMessage.basicData.earliestStartPermitted),
                                    Date_de_realisation__c = getDateTimeFromString(parc.daterelisation),
                                    Description = workOrderSAPMessage.basicData.titreordre,
                                    Lieu_Intervention__c = workOrderSAPMessage.basicData.lieuIntervention,
                                    //TODO Voir avec Roméo comment gérer ces 2 champs
                                    //Parc_Assistance__c = assetIdsByNames.get(parc.numasset),
                                    //Parc_Relais__c = assetIdsByNames.get(parc.numasset),
                                    StartDate = getDateTimeFromString(workOrderSAPMessage.basicData.startDate),
                                    EndDate = getDateTimeFromString(workOrderSAPMessage.basicData.endDate),
                                    Nom_du_technicien__c = workOrderSAPMessage.basicData.nomTechnicien,
                                    Origine__c = workOrderSAPMessage.basicData.origine,
                                    type_OE__c = workOrderSAPMessage.basicData.typeOE,
                                    Anomalie__c = workOrderSAPMessage.basicData.anomalie,
                                    Intervenant__c = workOrderSAPMessage.basicData.intervenant,
                                    Intervenant_Externe_txt__c = workOrderSAPMessage.basicData.intervenantExterne,
                                    Date_Heure_Depart__c = getDateTimeFromString(workOrderSAPMessage.basicData.datetimeDepart),
                                    Date_Heure_Arrivee__c = getDateTimeFromString(workOrderSAPMessage.basicData.datetimeArrivee),
                                    Date_Heure_Fin__c = getDateTimeFromString(workOrderSAPMessage.basicData.datetimeFin),
                                    Date_Heure_Retour__c = getDateTimeFromString(workOrderSAPMessage.basicData.datetimeRetour),
                                    Raison_de_fermeture__c = workOrderSAPMessage.basicData.raisonFermeture
                            );
                            upsert wo SAP_ID__c;
                        }

                        intRepToUpdate.Treatment_Status__c = TREATMENT_OK;


                    } catch (Exception e) {

                        intRepToUpdate.Treatment_Status__c = TREATMENT_ERROR;
                        intRepToUpdate.Treatment_Message__c = e.getMessage();
                        System.debug('===================== Intf_WorkOrderResponseHandler handleResponses Exception: ' + e.getMessage());
                    }

                }
                when else {
                    // Code inconnu

                    intRepToUpdate.Treatment_Status__c = TREATMENT_ERROR;
                    intRepToUpdate.Treatment_Message__c = 'Unknown status code';

                }
            }
            interfaceResponsesToUpdate.add(intRepToUpdate);

        }

        update workordersToUpdate;
        update interfaceResponsesToUpdate;

    }

    private static void populateWorkOrderMaps(List<Interface_Response__c> newMessages) {

        Set<String> accountSAPIds = new Set<String>();
        Set<String> assetNames = new Set<String>();
        Set<String> sapWoIds = new Set<String>();
        Set<String> agencies = new Set<String>();

        for (Interface_Response__c interfaceResponse : newMessages) {
            if (interfaceResponse.Status__c == 'I') {
                try {

                    Intf_WorkOrderSAPMessage workOrderSAPMessage = (Intf_WorkOrderSAPMessage)JSON.deserialize(interfaceResponse.Response_Message__c, Intf_WorkOrderSAPMessage.class);

                    accountSAPIds.add(workOrderSAPMessage.basicData.sapaccountId);
                    sapWoIds.add(workOrderSAPMessage.basicData.sapid);
                    agencies.add(workOrderSAPMessage.basicData.agenceintervenante);

                    for (Intf_WorkOrderSAPMessage.Parc parc : workOrderSAPMessage.parcs) {
                        assetNames.add(parc.numasset);
                    }

                } catch (Exception e) {
                    // Not important just trying to get some Ids from message for bulkification
                    System.debug('===================== Cannot deserialize');
                }
            }
        }

        for (Account agency : [SELECT Id, Name FROM Account WHERE RecordType.DeveloperName = 'Agence_PF' AND Name in :agencies]) {
            agenceIdsByNames.put(agency.Name, agency.Id);
        }

        System.debug('accountSAPIds : ' + accountSAPIds);
        for (Account account : [SELECT Id, Name, Tech_SAP_Id__c FROM Account WHERE Tech_SAP_Id__c in :accountSAPIds]) {
            accountIdsBySapAccountIds.put(account.Tech_SAP_Id__c, account.Id);
        }

        for (WorkOrder parentWO : [SELECT Id, Status, SAP_ID__c FROM WorkOrder WHERE SAP_ID__c in :sapWoIds AND RecordTypeId = :woRecTypeHATId]) {
            parentWorkOrdersBySapIds.put(parentWO.SAP_ID__c, parentWO);
        }

        for (WorkOrder workOrder : [SELECT Id, Status, SAP_ID__c FROM WorkOrder WHERE SAP_ID__c in :sapWoIds AND RecordTypeId <> :woRecTypeHATId]) {
            workOrdersBySapIds.put(workOrder.SAP_ID__c, workOrder);
        }

        for (Asset asset : [SELECT Id, Name FROM Asset WHERE Name in :assetNames]) {
            assetIdsByNames.put(asset.Name, asset.Id);
        }

    }

    private static Datetime getDateTimeFromString(String dateStr) {

        if (String.isBlank(dateStr)) { return null; }

        Integer year;
        Integer month;
        Integer day;
        Integer hour;
        Integer minute;
        Integer second;

        try {

            year = Integer.valueOf(dateStr.substring(0,4));
            month = Integer.valueOf(dateStr.substring(4,6));
            day = Integer.valueOf(dateStr.substring(6,8));
            hour = Integer.valueOf(dateStr.substring(8,10));
            minute = Integer.valueOf(dateStr.substring(10,12));
            second = Integer.valueOf(dateStr.substring(12,14));

//            System.debug ('==== year : ' + year);
//            System.debug ('==== month : ' + month);
//            System.debug ('==== day : ' + day);
//            System.debug ('==== hour : ' + hour);
//            System.debug ('==== minute : ' + minute);
//            System.debug ('==== second : ' + second);

            return Datetime.newInstance(year, month, day, hour, minute, second);

        } catch (Exception e) {
            throw new Intf_Exception('Error invalid date received. Please check date received in JSON. Value received: ' + dateStr);
        }

    }

}