unpackaged/main/default/objects/Account/fields/ListeNoire__c.field-meta.xml
<CustomField>
    <fullName>ListeNoire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refus</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LC_CustomLookUpController_TEST.cls
@isTest
public class LC_CustomLookUpController_TEST {
    @isTest
    public static void TestAccount() {

        Account Account1 = new Account();
        Account1.Name = 'Account Test 1';
        Account1.RecordTypeId = Label.ACC_RT_AgencePF;
        Account1.Statut__c = Label.CPT_Statut_Valide;
        Account1.ListeNoire__c = false;

		insert account1;

        Test.startTest();        
        List<Account> accounts = LC_CustomLookUpController.fetchLookUpValues('Account','Account');
        System.assertEquals(1, accounts.size());
        Test.stopTest();    
    } 

    @isTest
    public static void TestServiceResource() {
        List<Profile> profiles = [SELECT Id, Name
                                    FROM Profile
                                    WHERE Name = 'PF Administrateur Système'
                                    LIMIT 1];
        
        System.assertEquals('PF Administrateur Système', profiles[0].Name);

        User user1 = new User(
            profileID = profiles[0].Id,
            LastName = 'Adi',
            Email = 'puser000@worldwideaz.com',
            Username = 'puser000@worldwideaz.com' + System.currentTimeMillis(),
            CompanyName = 'TEST', 
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Country = 'France'
        );

        insert user1;

        ServiceResource serviceResource1 = new ServiceResource();        
        serviceResource1.Name = 'Service One';
        serviceResource1.RelatedRecordId = user1.Id; 

		insert serviceResource1;

        Test.startTest();        
        List<ServiceResource> serviceResources = LC_CustomLookUpController.fetchLookUpValues('Service','ServiceResource');
        System.assertEquals(1, serviceResources.size());
        Test.stopTest();    
    } 

    
}