unpackaged/main/default/objects/Account/fields/ListeNoire__c.field-meta.xml
<CustomField>
    <fullName>ListeNoire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refus</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Agence__c.field-meta.xml
<CustomField>
    <fullName>Agence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parcs</relationshipLabel>
    <relationshipName>Parcs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ADO</fullName>
            </value>
            <value>
                <fullName>ADO-AN</fullName>
            </value>
            <value>
                <fullName>AFFECTATION</fullName>
            </value>
            <value>
                <fullName>ALD</fullName>
            </value>
            <value>
                <fullName>ALD-AG</fullName>
            </value>
            <value>
                <fullName>ALD-AN</fullName>
            </value>
            <value>
                <fullName>A RETIRER</fullName>
            </value>
            <value>
                <fullName>ATE -AAG</fullName>
            </value>
            <value>
                <fullName>ATE -AAG-AG</fullName>
            </value>
            <value>
                <fullName>ATE -AAG-ATE</fullName>
            </value>
            <value>
                <fullName>ATE CDM</fullName>
            </value>
            <value>
                <fullName>ATE CDM-AAG</fullName>
            </value>
            <value>
                <fullName>ATE CDM-AAG-AG</fullName>
            </value>
            <value>
                <fullName>ATE CDM-AAG-ATE</fullName>
            </value>
            <value>
                <fullName>ATE EXT</fullName>
            </value>
            <value>
                <fullName>ATE EXT CDM</fullName>
            </value>
            <value>
                <fullName>ATE EXT LD</fullName>
            </value>
            <value>
                <fullName>ATE EXT MU</fullName>
            </value>
            <value>
                <fullName>ATE EXT MULET</fullName>
            </value>
            <value>
                <fullName>ATE EXT NEUT</fullName>
            </value>
            <value>
                <fullName>ATE LD</fullName>
            </value>
            <value>
                <fullName>ATE LD-AAG</fullName>
            </value>
            <value>
                <fullName>ATE LD-AAG-AG</fullName>
            </value>
            <value>
                <fullName>ATE LD-AAG-ATE</fullName>
            </value>
            <value>
                <fullName>ATELIER</fullName>
            </value>
            <value>
                <fullName>ATE MU-AAG</fullName>
            </value>
            <value>
                <fullName>ATE MU-AAG-AG</fullName>
            </value>
            <value>
                <fullName>ATE MU-AAG-ATE</fullName>
            </value>
            <value>
                <fullName>ATE MULET</fullName>
            </value>
            <value>
                <fullName>ATE NEUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassAllTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassAllTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass All Triggers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120O0000003cw4QAA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <formula>if
(
OR(
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusSiteAccount,
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusUltimateAccount,
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusClientAccount)
,
IF
(AND(ISPICKVAL(Status,&quot;Nouvelle&quot;), Requete_en_attente__c ==FALSE),IMAGE(&quot;/client/resource/1556207842000/Case_Nouvelle_V2?&quot;,&quot;Nouvelle&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;Nouvelle&quot;), Requete_en_attente__c ==TRUE),IMAGE(&quot;/client/resource/1556207856000/Case_Nouvelle_Attente_V2?&quot;,&quot;Attente&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;En_Cours&quot;), Requete_en_attente__c ==FALSE),IMAGE(&quot;/client/resource/1561547731000/Case_EnCours_V2?&quot;,&quot;En Cours&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;En_Cours&quot;), Requete_en_attente__c == TRUE),IMAGE(&quot;/client/resource/1556207885000/Case_EnCours_Attente_V2?&quot;,&quot;Attente&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;Terminee&quot;),IMAGE(&quot;/client/resource/1556207905000/Case_Ferme_V2?&quot;,&quot;Terminée&quot;,20,130),&#39;&#39;)))))
,
IF
(AND(ISPICKVAL(Status,&quot;Nouvelle&quot;), Requete_en_attente__c ==FALSE),IMAGE(&quot;/resource/1556207842000/Case_Nouvelle_V2?&quot;,&quot;Nouvelle&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;Nouvelle&quot;), Requete_en_attente__c ==TRUE),IMAGE(&quot;/resource/1556207856000/Case_Nouvelle_Attente_V2?&quot;,&quot;Attente&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;En_Cours&quot;), Requete_en_attente__c ==FALSE),IMAGE(&quot;/resource/1561547731000/Case_EnCours_V2?&quot;,&quot;En Cours&quot;,20,130),
IF
(AND(ISPICKVAL(Status,&quot;En_Cours&quot;), Requete_en_attente__c == TRUE),IMAGE(&quot;/resource/1556207885000/Case_EnCours_Attente_V2?&quot;,&quot;Attente&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;Terminee&quot;),IMAGE(&quot;/resource/1556207905000/Case_Ferme_V2?&quot;,&quot;Terminée&quot;,20,130),&#39;&#39;)))))
)</formula>
    <label>Statut</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordres de Travail</relationshipLabel>
    <relationshipName>Ordres_de_Travail</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <formula>if
(
OR(
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusSiteAccount,
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusUltimateAccount,
$User.ProfileId == $Label.USR_ProfileId_PFCommunityPlusClientAccount)
,
IF
(ISPICKVAL(Status,&quot;Nouveau&quot;),IMAGE(&quot;/client/resource/1554898927000/Case_Nouvelle_V2?&quot;,&quot;Nouvelle&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;En cours&quot;),IMAGE(&quot;/client/resource/1555660884000/Case_EnCours_V2?&quot;,&quot;Encours&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;Terminé&quot;),IMAGE(&quot;/client/resource/1555660944000/Case_Ferme_V2?&quot;,&quot;terminé&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;À replanifier&quot;),IMAGE(&quot;/client/resource/1615383328000/Case_Ferme_Orange&quot;,&quot;Orange&quot;,20,130),&#39;&#39;))))
,

IF
(ISPICKVAL(Status,&quot;Nouveau&quot;),IMAGE(&quot;/resource/1554898927000/Case_Nouvelle_V2?&quot;,&quot;Nouvelle&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;En cours&quot;),IMAGE(&quot;/resource/1555660884000/Case_EnCours_V2?&quot;,&quot;Encours&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;Terminé&quot;),IMAGE(&quot;/resource/1555660944000/Case_Ferme_V2?&quot;,&quot;terminé&quot;,20,130),
IF
(ISPICKVAL(Status,&quot;À replanifier&quot;),IMAGE(&quot;/resource/1615383328000/Case_Ferme_Orange&quot;,&quot;Orange&quot;,20,130),&#39;&#39;))))
)</formula>
    <label>Statut</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/RHX_TEST_WorkOrder.cls
@isTest(SeeAllData=true)
public class RHX_TEST_WorkOrder {
	static testMethod void RHX_Testmethod() {

        User testUser1 = Utils_TestMethods.createUser('AP07Opp1','AP07Opp1',Label.USR_ProfileId_PFAdministrateurSysteme);
        insert testUser1;

        System.RunAs(testUser1){
        Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
        MyBypass.BypassValidationRules__c = true;
        MyBypass.BypassTriggers__c = 'AP09Compte,AP03Opportunite,AP01Opportunite';
            MyBypass.BypassAllTriggers__c=true;
            insert MyBypass;

        Account account = Utils_TestMethods.createAccount( 'account', null, null, Label.CPT_RecordTypeId_CompteClient);
        account.statut__c = Label.CPT_TypeIdentifiantNational_Creation;
            //account.Statut__c = Label.CPT_Statut_Valide;
        insert account;

        Account agence1 = new Account();
        agence1.Name = 'Agence Test 1';
        agence1.RecordTypeId = Label.ACC_RT_AgencePF;
        //agence1.Statut__c = Label.CPT_Statut_Valide;
        agence1.ListeNoire__c = false;
        insert agence1;

        Asset asset1 = new Asset();        
        asset1.Name = 'Asset Name 1';  
        asset1.SerialNumber = '123456789';
        asset1.AccountId = account.Id;     
        asset1.Agence__c = agence1.Id;
        asset1.Position__c = 'ALD';
        insert asset1;


        Case C = new Case(Status='En_cours',Agence_Intervenante__c=agence1.Id, AccountId=account.Id, AssetId=asset1.Id );
        insert C;

        WorkOrder wo = new WorkOrder(AccountId=account.Id, caseId=C.Id, WorkTypeId=Label.OT_TypeDeTravail_ID_Depannage);
        insert wo;


        List<sObject> sourceList = [SELECT Id  FROM WorkOrder where LocationId=NULL  LIMIT 1];
        if(sourceList.size() == 0) {
            sourceList.add(
                    new WorkOrder(AccountId=account.Id, caseId=C.Id, RecordTypeId=Label.OT_RecordTypeID_Depannage,WorkTypeId=Label.OT_TypeDeTravail_ID_Depannage)
            );
        }
    	rh2.ParentUtil.UpsertRollupTestRecords( sourceList );  
    
        }
    }
}