unpackaged/main/default/objects/Account/fields/ListeNoire__c.field-meta.xml
<CustomField>
    <fullName>ListeNoire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refus</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TECHDateListeNoire__c.field-meta.xml
<CustomField>
    <fullName>TECHDateListeNoire__c</fullName>
    <description>CPT-RG-021 et CPT-RG-022</description>
    <label>TECH Date Liste Noire</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/VFE07_OpportuniteWarning.cls
public class VFE07_OpportuniteWarning{

    Opportunity opp;
    public boolean spaces{get;set;}
    //public List<Opportunity> accs{get;set;}

    public VFE07_OpportuniteWarning(ApexPages.StandardController controller) {
        this.opp= (Opportunity) controller.getRecord(); 
        opp= [SELECT AccountId,Account.ListeNoire__c, Account.TECHDateListeNoire__c, Account.Statut__c  FROM Opportunity WHERE Id =: opp.Id][0];
        //accs = [SELECT ListeNoire__c,TECHDateListeNoire__c FROM Account WHERE Id =: opp.AccountId];
    }

    public void alert()
    {
        spaces = !Utils_Methods.isSF1();
        if (opp.AccountId!=null)
        {   
            string message = Label.OPP_Info_Compte + ' ';
            boolean warning = false;
            //Account acc = accs[0];
            if(opp.Account.statut__c == Label.CPT_Statut_Inactif){
                warning=true;
                message += Label.MSG_Statut_Inactif;
            }
            else if (opp.Account.statut__c == Label.CPT_Statut_Refuse)
            {
                warning= true;
                message += Label.MSG_Statut_Refuse;
            }
            if (opp.Account.ListeNoire__c) 
            {
                message += (warning?' et ':'') + Label.CPT_ListeNoireDepuis +' '+string.valueof(opp.Account.TECHDateListeNoire__c);
                warning = true;
            }
            if(!warning)
            {
                if(opp.Account.statut__c == Label.CPT_Statut_Draft)
                {
                    message += Label.CPT_EnStatut + ' ' + Label.MSG_Statut_Draft;
                }
                if(opp.Account.statut__c == Label.CPT_Statut_Valide)
                {
                    message += Label.MSG_Statut_Valide;
                }
                if(opp.Account.statut__c == Label.CPT_Statut_ValideCM)
                {
                    message += Label.MSG_Statut_ValideCM;
                }
                if(opp.Account.statut__c == Label.CPT_Statut_Bloque)
                {
                    message += Label.MSG_Statut_Bloque;
                }
            }
            
            ApexPages.Message myMsg = new ApexPages.Message((warning?ApexPages.Severity.WARNING:ApexPages.Severity.INFO),message+'.');
            ApexPages.addMessage(myMsg);
        }
    }
}