unpackaged/main/default/objects/Account/fields/Nombre_de_vehicules__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_vehicules__c</fullName>
    <label>Nombre de véhicules</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Agence__c.field-meta.xml
<CustomField>
    <fullName>Agence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parcs</relationshipLabel>
    <relationshipName>Parcs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Agence_Localisation__c.field-meta.xml
<CustomField>
    <fullName>Agence_Localisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Localisation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parcs (Agence Localisation)</relationshipLabel>
    <relationshipName>Parcs_Localisation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestBatchCountAssets.cls
@isTest
private class TestBatchCountAssets {
    static testMethod void testme(){
        //Create account S
        Account A = New Account();
        A.RecordTypeId = Label.ACC_RecordTypeId_CompteSite;
        A.Name = 'Account test';
		insert A;
        //create Agence
        Account ag = Utils_TestMethods.CreateAgence('Agence Test');
        insert ag;
        //Create Parc
        Asset Parc = Utils_TestMethods.CreateAsset(A.id,Label.Parc_RecordTypeId);
        Parc.Agence__c = ag.id;
        Parc.Agence_Localisation__c = ag.id;
        insert Parc;
        
        
        Test.startTest();
        BatchCountAssets B = new BatchCountAssets();
        //Id jobid = Database.executeBatch(B,5);
        Database.executeBatch(B);
        Test.stopTest();
        Account ACC = [Select id,Nombre_de_vehicules__c from account where id=:A.id];
        system.assertEquals(1,ACC.Nombre_de_vehicules__c);
    }
}