unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_SAP_Id__c</fullName>
    <label>Tech SAP Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville (-Facturation-)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120O0000003cw4QAA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>Contact_Chauffeur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact :
- Type d&#39;enregistrement : Chauffeur 
- Compte du contact = Compte Requête</description>
    <label>Contact - Chauffeur</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Chauffeur</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Description_incident_client__c.field-meta.xml
<CustomField>
    <fullName>Description_incident_client__c</fullName>
    <label>Description incident client</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/N_Tel_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>N_Tel_Chauffeur__c</fullName>
    <label>N° Tel - Chauffeur</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Nom_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>Nom_Chauffeur__c</fullName>
    <label>Nom Chauffeur</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>SLOVAQUIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Rue_Lieu__c.field-meta.xml
<CustomField>
    <fullName>Rue_Lieu__c</fullName>
    <label>Rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Demande_de_service.recordType-meta.xml
<RecordType>
    <fullName>Demande_de_service</fullName>
    <active>true</active>
    <businessProcess>Dépannage</businessProcess>
    <label>Demande de service</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Depannage_Vehicule.recordType-meta.xml
<RecordType>
    <fullName>Depannage_Vehicule</fullName>
    <active>true</active>
    <businessProcess>Dépannage</businessProcess>
    <label>Dépannage - véhicule</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BOLIVIE</fullName>
            </value>
            <value>
                <fullName>BOSNIE HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>BURKINA FASO</fullName>
            </value>
            <value>
                <fullName>CAMBODGE</fullName>
            </value>
            <value>
                <fullName>CAMEROUN</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILI</fullName>
            </value>
            <value>
                <fullName>CHINE</fullName>
            </value>
            <value>
                <fullName>CHYPRE</fullName>
            </value>
            <value>
                <fullName>CISJORDANIE</fullName>
            </value>
            <value>
                <fullName>COLOMBIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact_Chauffeur.recordType-meta.xml
<RecordType>
    <fullName>Contact_Chauffeur</fullName>
    <active>true</active>
    <label>Contact - Chauffeur</label>
</RecordType>

unpackaged/main/default/objects/Interface_monitoring__c/Interface_monitoring__c.object-meta.xml
<CustomObject>
    <label>Interface monitoring</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interfaces monitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interface_monitoring__c/fields/OutgoingMessage__c.field-meta.xml
<CustomField>
    <fullName>OutgoingMessage__c</fullName>
    <label>Outgoing Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Interface_monitoring__c/fields/ResponseMessage__c.field-meta.xml
<CustomField>
    <fullName>ResponseMessage__c</fullName>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordres de Travail</relationshipLabel>
    <relationshipName>Ordres_de_Travail</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Earliest_Start_Permitted__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Start_Permitted__c</fullName>
    <label>Date Planifiée</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Organe_controler__c.field-meta.xml
<CustomField>
    <fullName>Organe_controler__c</fullName>
    <label>Organe à contrôler</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cabine</fullName>
            </value>
            <value>
                <fullName>Caisse</fullName>
            </value>
            <value>
                <fullName>Châssis</fullName>
            </value>
            <value>
                <fullName>Electricité</fullName>
            </value>
            <value>
                <fullName>Hayon</fullName>
            </value>
            <value>
                <fullName>Groupe</fullName>
                <label>Groupe frigorifique</label>
            </value>
            <value>
                <fullName>Pneumatiques</fullName>
                <label>Pneumatique</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Demande_de_service.recordType-meta.xml
<RecordType>
    <fullName>Demande_de_service</fullName>
    <active>true</active>
    <label>Demande de service</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/recordTypes/Depannage_Vehicule.recordType-meta.xml
<RecordType>
    <fullName>Depannage_Vehicule</fullName>
    <active>true</active>
    <label>Depannage - Véhicule</label>
</RecordType>

unpackaged/main/default/classes/Intf_WorkOrderTriggerHandler_Test.cls
/**
 * @description       :
 * @author            : Michaël Cabaraux
 * @group             :
 * @last modified on  : 24-04-2024
 * @last modified by  : Michaël Cabaraux
**/

@IsTest
private class Intf_WorkOrderTriggerHandler_Test {

    @TestSetup
    static void setupData() {

        Asset asset = new Asset(
                Name = 'PF-123456'
        );
        insert asset;

        Account account = new Account(
                Name = 'Agence Test',
                Tech_SAP_Id__c = 'SAP1234'
        );
        insert account;

        Id coRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Chauffeur').getRecordTypeId();

        Contact contact = new Contact(
                FirstName = 'Monsieur',
                LastName = 'Test',
                MobilePhone = '063456884',
                AccountId = account.Id,
                RecordTypeId = coRecTypeId
        );
        insert contact;

        Case caseInfo = new Case(
                Asset = asset,
                Account = account,
                Pays__c = 'France',
                Rue_Lieu__c = 'Rue du test 1',
                Code_postal__c = '34566',
                Ville__c = 'TestVile',
                Nom_Chauffeur__c = 'Chauffeur Test',
                N_Tel_Chauffeur__c = '0634567789',
                Priority = 'Moyenne',
                Description_incident_client__c = 'Je suis en panne',
                Contact_Chauffeur__c = contact.Id
        );
        insert caseInfo;

    }

    @IsTest
    static void testBreakdown() {

        Id woRecTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get('Depannage_Vehicule').getRecordTypeId();

        Case caseInfo = [
                SELECT Id, AssetId, AccountId, Account.Tech_SAP_Id__c, Asset.Name, Pays__c, Rue_Lieu__c, Code_postal__c, Ville__c, Nom_Chauffeur__c, N_Tel_Chauffeur__c, Priority,
                    Description_incident_client__c, Contact_Chauffeur__r.FirstName, Contact_Chauffeur__r.LastName, Contact_Chauffeur__r.Email, Contact_Chauffeur__r.MobilePhone, Contact_Chauffeur__r.Phone
                FROM Case
                ];
        Account account = [SELECT Id FROM Account];

        Test.startTest();
        Intf_WebserviceMock.status = 200;
        Test.setMock(HttpCalloutMock.class, new Intf_WebserviceMock());

        WorkOrder wo = new WorkOrder(
                CaseId = caseInfo.Id,
                Organe_controler__c = 'Caisse',
                Agence_Intervenante__c = account.Id,
                Earliest_Start_Permitted__c = Datetime.now().addDays(1),
                RecordTypeId = woRecTypeId,
                AccountId = account.Id
        );
        insert wo;

        Test.stopTest();

        List<Interface_monitoring__c> interfaceMonitorings = new List<Interface_monitoring__c>([SELECT Id, Status__c, Status_Code__c, OutgoingMessage__c, ResponseMessage__c FROM Interface_monitoring__c]);
        System.assertEquals(1, interfaceMonitorings.size());

    }

    @IsTest
    static void testService() {

        Id woRecTypeId = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName().get('Demande_de_service').getRecordTypeId();

        Case caseInfo = [SELECT Id, AssetId, AccountId, Account.Tech_SAP_Id__c, Asset.Name, Pays__c, Rue_Lieu__c, Code_postal__c, Ville__c, Nom_Chauffeur__c, N_Tel_Chauffeur__c, Priority, Description_incident_client__c FROM Case];
        Account account = [SELECT Id FROM Account];

        Test.startTest();
        Intf_WebserviceMock.status = 200;
        Test.setMock(HttpCalloutMock.class, new Intf_WebserviceMock());

        WorkOrder wo = new WorkOrder(
                CaseId = caseInfo.Id,
                Organe_controler__c = 'Caisse',
                Agence_Intervenante__c = account.Id,
                Earliest_Start_Permitted__c = Datetime.now().addDays(1),
                RecordTypeId = woRecTypeId,
                AccountId = account.Id
        );
        insert wo;

        Test.stopTest();

        List<Interface_monitoring__c> interfaceMonitorings = new List<Interface_monitoring__c>([SELECT Id, Status__c, Status_Code__c, OutgoingMessage__c, ResponseMessage__c FROM Interface_monitoring__c]);
        System.assertEquals(1, interfaceMonitorings.size());

    }

}