unpackaged/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays (-Facturation-)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>DANEMARK</fullName>
                <label>Danemark</label>
            </value>
            <value>
                <fullName>EMIRATS ARABES</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>ETATS UNIS D&#39;AMERIQUE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GRECE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LITUANIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>MAROC</fullName>
            </value>
            <value>
                <fullName>MONACO</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>REUNION</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>RUSSIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
            <value>
                <fullName>TURQUIE</fullName>
            </value>
            <value>
                <fullName>MAURITIUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tech_SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_SAP_Id__c</fullName>
    <label>Tech SAP Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville (-Facturation-)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>Contact_Chauffeur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact :
- Type d&#39;enregistrement : Chauffeur 
- Compte du contact = Compte Requête</description>
    <label>Contact - Chauffeur</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Chauffeur</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Contact_responsable_parc__c.field-meta.xml
<CustomField>
    <fullName>Contact_responsable_parc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact - responsable parc</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) AND 5</booleanFilter>
        <errorMessage>Le type de contact ne correspond pas au type de la requête</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Responsable de parcs</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dépannage - Container</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Commercial, Contact - Chauffeur, Contact - Responsable de parcs</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Demande de service</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Agence_proprietaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requêtes (Contact)</relationshipLabel>
    <relationshipName>Requete</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Description_incident_client__c.field-meta.xml
<CustomField>
    <fullName>Description_incident_client__c</fullName>
    <label>Description incident client</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Fin_Disponibilite_vehicule__c.field-meta.xml
<CustomField>
    <fullName>Fin_Disponibilite_vehicule__c</fullName>
    <label>Fin Disponibilité véhicule</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/N_Tel_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>N_Tel_Chauffeur__c</fullName>
    <label>N° Tel - Chauffeur</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Nom_Chauffeur__c.field-meta.xml
<CustomField>
    <fullName>Nom_Chauffeur__c</fullName>
    <label>Nom Chauffeur</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>ESPAGNE</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>HONGRIE</fullName>
            </value>
            <value>
                <fullName>IRLANDE</fullName>
            </value>
            <value>
                <fullName>ITALIE</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>PAYS - BAS</fullName>
            </value>
            <value>
                <fullName>POLOGNE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>REPUBLIQUE TCHEQUE</fullName>
            </value>
            <value>
                <fullName>ROUMANIE</fullName>
            </value>
            <value>
                <fullName>ROYAUME UNI</fullName>
            </value>
            <value>
                <fullName>SLOVAQUIE</fullName>
            </value>
            <value>
                <fullName>SUISSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Rue_Lieu__c.field-meta.xml
<CustomField>
    <fullName>Rue_Lieu__c</fullName>
    <label>Rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BOLIVIE</fullName>
            </value>
            <value>
                <fullName>BOSNIE HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>BURKINA FASO</fullName>
            </value>
            <value>
                <fullName>CAMBODGE</fullName>
            </value>
            <value>
                <fullName>CAMEROUN</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILI</fullName>
            </value>
            <value>
                <fullName>CHINE</fullName>
            </value>
            <value>
                <fullName>CHYPRE</fullName>
            </value>
            <value>
                <fullName>CISJORDANIE</fullName>
            </value>
            <value>
                <fullName>COLOMBIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Earliest_Start_Permitted__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Start_Permitted__c</fullName>
    <label>Date Planifiée</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Fin_disponibilite_vehicule__c.field-meta.xml
<CustomField>
    <fullName>Fin_disponibilite_vehicule__c</fullName>
    <label>Fin disponibilité véhicule</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Organe_controler__c.field-meta.xml
<CustomField>
    <fullName>Organe_controler__c</fullName>
    <label>Organe à contrôler</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cabine</fullName>
            </value>
            <value>
                <fullName>Caisse</fullName>
            </value>
            <value>
                <fullName>Châssis</fullName>
            </value>
            <value>
                <fullName>Electricité</fullName>
            </value>
            <value>
                <fullName>Hayon</fullName>
            </value>
            <value>
                <fullName>Groupe</fullName>
                <label>Groupe frigorifique</label>
            </value>
            <value>
                <fullName>Pneumatiques</fullName>
                <label>Pneumatique</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Recordtype__c.field-meta.xml
<CustomField>
    <fullName>Recordtype__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <label>Recordtype</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/TECH_AgenceIntervenante_Name__c.field-meta.xml
<CustomField>
    <fullName>TECH_AgenceIntervenante_Name__c</fullName>
    <formula>Agence_Intervenante__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_AgenceIntervenante_Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Travaux_demandes__c.field-meta.xml
<CustomField>
    <fullName>Travaux_demandes__c</fullName>
    <label>Travaux demandés</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Depannage.recordType-meta.xml
<RecordType>
    <fullName>Depannage</fullName>
    <active>true</active>
    <description>Ordre de travail de type Depannage</description>
    <label>Depannage</label>
</RecordType>

unpackaged/main/default/classes/Intf_WorkOrderSchemaBuilder.cls
/**
 * @description       :
 * @author            : Michaël Cabaraux
 * @group             :
 * @last modified on  : 15-02-2024
 * @last modified by  : Michaël Cabaraux
**/

public with sharing class Intf_WorkOrderSchemaBuilder {

    private static WorkOrder workOrder;
    private static Case caseInfo;

    private static final String WO_TYPE_BREAKDOWN = 'Depannage';

    public class WorkOrderMsg {

        public String messid { get; set; }
        public String salesforceId { get; set; }
        public BasicData BasicData;

        public WorkOrderMsg(WorkOrder wo, Case caseInf, String agenceSAP) {

            System.debug('============================== Intf_WorkOrderSchemaBuilder WorkOrderMsg caseInf: ' + caseInf);
            System.debug('============================== Intf_WorkOrderSchemaBuilder WorkOrderMsg wo: ' + wo);

            workOrder = wo;
            caseInfo = caseInf;

            this.messid = Intf_GenerallntService.getUMessageId();
            this.salesforceId = wo.Id;
            this.BasicData = new BasicData(agenceSAP);

            System.debug('============================== Intf_WorkOrderSchemaBuilder WorkOrderMsg workOrder: ' + workOrder);
            System.debug('============================== Intf_WorkOrderSchemaBuilder WorkOrderMsg caseInfo: ' + caseInfo);

        }
    }

    public class BasicData {

        public String type { get; set; }
        public String organe { get; set; }
        public String numasset { get; set; }
        public String sapaccountId { get; set; }
        public String infocontact { get; set; }
        public Datetime datedebut { get; set; }
        public Datetime datefin { get; set; }
        public String titreordre { get; set; }
        public String priorite { get; set; }
        public String notetravaux { get; set; }
        public String sfcaseid { get; set; }
        public String agenceintervenante { get; set; }
        public String organisationservice { get; set; }

        public BasicData(String agenceSAP) {

            this.sfcaseid = workOrder.CaseId;
            this.type = workOrder.Recordtype__c;
            this.organe = workOrder.Organe_controler__c;
            this.titreordre = workOrder.Recordtype__c;
            this.priorite = caseInfo.Priority;

            String infoContact;

            if (workOrder.Recordtype__c.contains(WO_TYPE_BREAKDOWN)) {
                infoContact = caseInfo.Nom_Chauffeur__c + ' -- ' + caseInfo.N_Tel_Chauffeur__c + '-- Adresse: ' + caseInfo.Rue_Lieu__c + ' ';
                infoContact += caseInfo.Code_postal__c + ' ' + caseInfo.Ville__c + ' ' + caseInfo.Pays__c;
                infoContact += ' -- Incident client: ' + caseInfo.Description_incident_client__c;

//                this.notetravaux = caseInfo.Description_incident_client__c;

            } else {
                Contact contact;
                contact = caseInfo.Contact_Chauffeur__c != null ? caseInfo.Contact_Chauffeur__r : caseInfo.Contact_responsable_parc__r;

                infoContact = (String)contact.get('Name') + ' -- ';
                infoContact += (String)contact.get('MobilePhone') + ' -- ';
                infoContact += (String)contact.get('Phone') + ' -- ';
                infoContact += (String)contact.get('Email');

                infoContact += '-- Travaux demandés: ' + workOrder.Travaux_demandes__c;
//                this.notetravaux = workOrder.Travaux_demandes__c;
            }
            this.infocontact = infoContact;
            this.numasset = caseInfo.Asset.Name;
            this.sapaccountId = caseInfo.Account.Tech_SAP_Id__c;
//            this.agenceintervenante = workOrder.TECH_AgenceIntervenante_Name__c;
//            this.organisationservice = workOrder.TECH_AgenceIntervenante_Name__c;
            this.agenceintervenante = agenceSAP;
            this.organisationservice = agenceSAP;
            // this.datedebut = workOrder.Earliest_Start_Permitted__c;
            // this.datefin = workOrder.Fin_disponibilite_vehicule__c;
            this.datedebut = workOrder.Fin_disponibilite_vehicule__c;
            this.datefin = workOrder.Earliest_Start_Permitted__c;
        }
    }
}