unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TypeIdentifiantNational__c</fullName>
    <label>Type d&#39;identifiant national</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CNIE</fullName>
            </value>
            <value>
                <fullName>COC</fullName>
            </value>
            <value>
                <fullName>COCCH</fullName>
            </value>
            <value>
                <fullName>COCCHE</fullName>
            </value>
            <value>
                <fullName>COFIS</fullName>
            </value>
            <value>
                <fullName>CRO</fullName>
            </value>
            <value>
                <fullName>DELTA</fullName>
            </value>
            <value>
                <fullName>HRB</fullName>
            </value>
            <value>
                <fullName>HRM</fullName>
            </value>
            <value>
                <fullName>IBLC</fullName>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
            <value>
                <fullName>KVK</fullName>
            </value>
            <value>
                <fullName>NIPC</fullName>
            </value>
            <value>
                <fullName>P.IVA</fullName>
            </value>
            <value>
                <fullName>RCLU</fullName>
            </value>
            <value>
                <fullName>RNMA</fullName>
            </value>
            <value>
                <fullName>RNPL</fullName>
            </value>
            <value>
                <fullName>RNPT</fullName>
            </value>
            <value>
                <fullName>SIREN</fullName>
            </value>
            <value>
                <fullName>TVABE</fullName>
            </value>
            <value>
                <fullName>TVADE</fullName>
            </value>
            <value>
                <fullName>TVAPL</fullName>
            </value>
            <value>
                <fullName>En création</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>PRISMA</fullName>
            </value>
            <value>
                <fullName>RNHU</fullName>
                <label>RNHU (cégjegyzékszám)</label>
            </value>
            <value>
                <fullName>VATHU</fullName>
                <label>VATHU (Adoszam)</label>
            </value>
            <value>
                <fullName>TVAIT</fullName>
            </value>
            <value>
                <fullName>ICOSK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote from which this Contract was created.</description>
    <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contract</description>
    <label>Contract</label>
</RecordType>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <description>GFC-1687</description>
    <formula>text(SBQQ__Opportunity2__r.PaysRegionPF__c)</formula>
    <label>PaysRegionPF</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TypeIdentifiantNational__c/TypeIdentifiantNational__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Type Identifiant National</label>
</CustomObject>

unpackaged/main/default/classes/GenDocContractsFromQuote_Test.cls
@isTest
public class GenDocContractsFromQuote_Test {
	@isTest
    public static void GenDocContractsFromQuoteTest(){
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;
        Account Acc=new Account(Name='test',PaysRegionPF__c='DO1A',	TypeIdentifiantNational__c='SIREN');
        insert Acc;
        Contract con=new Contract(SBQQ__Quote__c=quote.id,Status='Draft',StartDate=System.today(),ContractTerm=13,AccountId=acc.id);
    	insert con;
        Test.StartTest(); 
        	ApexPages.StandardController sc = new ApexPages.StandardController(quote);
			ApexPages.currentPage().getParameters().put('id', String.valueOf(quote.Id));
			GenDocContractsFromQuote  genDocCon = new GenDocContractsFromQuote(sc);
			genDocCon.quote=quote;
		Test.StopTest();
    }
}