unpackaged/main/default/objects/Account/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TypeIdentifiantNational__c</fullName>
    <label>Type d&#39;identifiant national</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CNIE</fullName>
            </value>
            <value>
                <fullName>COC</fullName>
            </value>
            <value>
                <fullName>COCCH</fullName>
            </value>
            <value>
                <fullName>COCCHE</fullName>
            </value>
            <value>
                <fullName>COFIS</fullName>
            </value>
            <value>
                <fullName>CRO</fullName>
            </value>
            <value>
                <fullName>DELTA</fullName>
            </value>
            <value>
                <fullName>HRB</fullName>
            </value>
            <value>
                <fullName>HRM</fullName>
            </value>
            <value>
                <fullName>IBLC</fullName>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
            <value>
                <fullName>KVK</fullName>
            </value>
            <value>
                <fullName>NIPC</fullName>
            </value>
            <value>
                <fullName>P.IVA</fullName>
            </value>
            <value>
                <fullName>RCLU</fullName>
            </value>
            <value>
                <fullName>RNMA</fullName>
            </value>
            <value>
                <fullName>RNPL</fullName>
            </value>
            <value>
                <fullName>RNPT</fullName>
            </value>
            <value>
                <fullName>SIREN</fullName>
            </value>
            <value>
                <fullName>TVABE</fullName>
            </value>
            <value>
                <fullName>TVADE</fullName>
            </value>
            <value>
                <fullName>TVAPL</fullName>
            </value>
            <value>
                <fullName>En création</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>PRISMA</fullName>
            </value>
            <value>
                <fullName>RNHU</fullName>
                <label>RNHU (cégjegyzékszám)</label>
            </value>
            <value>
                <fullName>VATHU</fullName>
                <label>VATHU (Adoszam)</label>
            </value>
            <value>
                <fullName>TVAIT</fullName>
            </value>
            <value>
                <fullName>ICOSK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/blng__CreditNote__c/blng__CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TypeIdentifiantNational__c/TypeIdentifiantNational__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Type Identifiant National</label>
</CustomObject>

unpackaged/main/default/classes/GenDocCreditNoteFromCreditNote_Test.cls
@isTest
public class GenDocCreditNoteFromCreditNote_Test {
@isTest
    public static void GenDocCreditNoteFromCreditNoteTest(){
        Account acc=new Account(Name='test',PaysRegionPF__c='DO1A',	TypeIdentifiantNational__c='SIREN');
        insert acc;
        blng__CreditNote__c  creditNote=new blng__CreditNote__c (blng__CreditNoteDate__c=system.today(),blng__Account__c=acc.id);
    	insert creditNote;
        Test.StartTest(); 
        	ApexPages.StandardController sc = new ApexPages.StandardController(acc);
			ApexPages.currentPage().getParameters().put('id', String.valueOf(creditNote.Id));
			GenDocCreditNoteFromCreditNote  genDocCreditNote = new GenDocCreditNoteFromCreditNote(sc);
			genDocCreditNote.cr=creditNote;
		Test.StopTest();
    }
}