unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/RoleContact__c.object-meta.xml
<CustomObject>
    <label>Rôle de contact</label>
    <nameField>
        <displayFormat>GF-RCN-{0000000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rôles de contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/VFE13_ContactRole_TEST.cls
/**
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class VFE13_ContactRole_TEST{

    static testMethod void TestContactRole() {

    Bypass__c MyBypass = Utils_TestMethods.createBypass(UserInfo.getUserId());
    MyBypass.BypassValidationRules__c = true;
    MyBypass.BypassTriggers__c = 'AP09Compte';
    insert MyBypass;
    
    Account Account1 = Utils_TestMethods.createAccount('Account1',null,null, Label.CPT_RecordTypeId_CompteClient); 
    Account1.Statut__c = Label.CPT_Statut_Valide;
    insert Account1;
    
    Contact Contact1 = Utils_TestMethods.createContact('Contact1',Account1.Id);
    insert Contact1;
    
    Opportunity Opportunity1= Utils_TestMethods.createOpportunity('OPP1',Label.OPP_StageName_PropositionRemise,system.today(),Account1);
    Opportunity1.AccountId = Account1.Id;
    insert Opportunity1;
    
    RoleContact__c rc = Utils_TestMethods.createRoleContact(Contact1.Id, Opportunity1.Id, Account1.Id);
    
    ApexPages.StandardController controller = new ApexPages.StandardController(rc);
    VFE13_ContactRole r = new VFE13_ContactRole(controller);
    r.selectContact();
    r.saveContact();

    RoleContact__c rc2 = Utils_TestMethods.createRoleContact(Contact1.Id, Opportunity1.Id, Account1.Id);    
    ApexPages.StandardController controller2 = new ApexPages.StandardController(rc2);
    VFE13_ContactRole r2 = new VFE13_ContactRole(controller2);
    r2.selectContact();
    r2.saveAndNewContact();

    RoleContact__c rc3 = Utils_TestMethods.createRoleContact(Contact1.Id, Opportunity1.Id, Account1.Id);    
    insert rc3;    
    ApexPages.StandardController controller3 = new ApexPages.StandardController(rc3);
    VFE13_ContactRole r3 = new VFE13_ContactRole(controller3);
    r3.selectContact();
    r3.saveContact();
    r3.saveAndNewContact();


    }
}