unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Compte_Client.recordType-meta.xml
<RecordType>
    <fullName>Compte_Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact_Commercial.recordType-meta.xml
<RecordType>
    <fullName>Contact_Commercial</fullName>
    <active>true</active>
    <label>Contact - Commercial</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Type_Location__c.field-meta.xml
<CustomField>
    <fullName>Type_Location__c</fullName>
    <description>Indiquez la durée estimée du contrat.</description>
    <inlineHelpText>Il s&#39;agit d&#39;une estimation de la durée du contrat. Elle permet de simplifier les processus selon la durée.</inlineHelpText>
    <label>Type Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/blng__BillingDayOfMonth__c.field-meta.xml
<CustomField>
    <fullName>blng__BillingDayOfMonth__c</fullName>
    <label>Billing Day Of Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunité associée à ce devis.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Type_Location__c.field-meta.xml
<CustomField>
    <fullName>Type_Location__c</fullName>
    <formula>text(SBQQ__Opportunity2__r.Type_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Type_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Courte Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Moyenne Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Longue Durée</fullName>
    </customValue>
    <description>Type de Location (CD, CMD, LD)</description>
    <masterLabel>Type Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/OrderSelectorTest.cls
/**
* @Version: 1.0
* @Author: Remz Grges
* -----------------------------------------------------------------------------------------------
* Description: Test class for OrderSelector class
* Created: 27/08/2021
** -----------------------------------------------------------------------------------------------
*/
@IsTest
public with sharing class OrderSelectorTest {
    @IsTest
    static void testGetOrdersById() {
        Id accountRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Compte_Client').getRecordTypeId();
        Account acc = Utils_TestMethods.createAccount('Test', 'Test', null, accountRTId);
        acc.Statut__c = 'Validé';
        insert acc;

        Id contactRT = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Commercial').getRecordTypeId();

        Contact contact = Utils_TestMethods.createContact('My Contact', acc.Id);
        contact.RecordTypeId = contactRT;
        insert contact;

        Opportunity opportunity = Utils_TestMethods.createOpportunity('Test oppty', '1 - Opportunité créée', Date.today(), acc);
        opportunity.Type_Location__c = 'Courte Durée';
        insert opportunity;


        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        quote.SBQQ__Opportunity2__c = opportunity.Id;
        insert quote;

        Order order = new Order();
        order.AccountId = acc.Id;
        order.EffectiveDate = Date.today();
        order.EndDate = Date.today().addDays(20);
        order.Status = 'Draft';
        order.blng__BillingDayOfMonth__c = '7';
        insert order;

        Test.startTest();

        IOrderSelector orderSelector = new OrderSelector();
        Map<Id, Order> getOrdersByIds = orderSelector.getOrdersByIds(new Set<Id> {order.Id});
        Test.stopTest();
        System.assertEquals(1,getOrdersByIds.size());
    }
}