unpackaged/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>En attente analyse CM</fullName>
            </value>
            <value>
                <fullName>Bloqué CM</fullName>
            </value>
            <value>
                <fullName>Refusé CM</fullName>
            </value>
            <value>
                <fullName>Refusé DC</fullName>
            </value>
            <value>
                <fullName>Validé DC</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Validé CM</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Bloqué</fullName>
            </value>
            <value>
                <fullName>Erreur EH</fullName>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
            <value>
                <fullName>Attente Validation CM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actif</fullName>
                <default>true</default>
                <label>Actif</label>
            </value>
            <value>
                <fullName>Inactif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Date_de_prolongation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_prolongation__c</fullName>
    <label>Date de prolongation</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PF_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>PF_Legal_Entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field has been created to capture the legal entity for which the opportunity has to be created</description>
    <label>Legal Entity</label>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Type_Location__c.field-meta.xml
<CustomField>
    <fullName>Type_Location__c</fullName>
    <description>Indiquez la durée estimée du contrat.</description>
    <inlineHelpText>Il s&#39;agit d&#39;une estimation de la durée du contrat. Elle permet de simplifier les processus selon la durée.</inlineHelpText>
    <label>Type Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
                <color>#0B6FCE</color>
                <label>NCT</label>
            </value>
            <value>
                <fullName>SUP</fullName>
                <color>#A845DC</color>
                <label>SUP</label>
            </value>
            <value>
                <fullName>RNV</fullName>
                <color>#E27001</color>
                <label>RNV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>Objet utilisé pour recueillir les devis SAP CPQ</description>
    <label>Devis SAP CPQ</label>
    <nameField>
        <label>Numéro du devis</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devis SAP CPQ</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Compte associé au devis</description>
    <inlineHelpText>Compte Payeur</inlineHelpText>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Devis</relationshipLabel>
    <relationshipName>Devis</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Date_de_validite_du_devis__c.field-meta.xml
<CustomField>
    <fullName>Date_de_validite_du_devis__c</fullName>
    <label>Date de validité du devis</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Devis SAP CPQ</relationshipLabel>
    <relationshipName>Devis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Devis déclaré comme principal</description>
    <label>Principal</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Quote_Validity_Notification_Sent__c.field-meta.xml
<CustomField>
    <fullName>Quote_Validity_Notification_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Validity Notification</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
            </value>
            <value>
                <fullName>En attente approbation</fullName>
            </value>
            <value>
                <fullName>Autorisé</fullName>
            </value>
            <value>
                <fullName>Non Autorisé</fullName>
            </value>
            <value>
                <fullName>Devis Envoyé</fullName>
            </value>
            <value>
                <fullName>Devis annulé</fullName>
            </value>
            <value>
                <fullName>Devis refusé</fullName>
            </value>
            <value>
                <fullName>Devis validé</fullName>
            </value>
            <value>
                <fullName>Contrat envoyé</fullName>
            </value>
            <value>
                <fullName>Contrat signé</fullName>
            </value>
            <value>
                <fullName>Contrat validé</fullName>
            </value>
            <value>
                <fullName>Devis échu</fullName>
            </value>
            <value>
                <fullName>Brouillon - étude HS en cours</fullName>
            </value>
            <value>
                <fullName>Brouillon - étude HS validée</fullName>
            </value>
            <value>
                <fullName>Création de contrat en cours</fullName>
            </value>
            <value>
                <fullName>Echec de la création du contrat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Type_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Courte Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Moyenne Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Longue Durée</fullName>
    </customValue>
    <description>Type de Location (CD, CMD, LD)</description>
    <masterLabel>Type Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/QuoteTriggerTest.cls
@isTest
public class QuoteTriggerTest {
    
    // Méthodes de création de données de test
    public static List<Account> createClients(Integer nbr, Boolean toInsert){
        List<Account> clients = new List<Account>();
        for(Integer i = 0; i < nbr; i++){
            clients.add(new Account(Name = 'Test' + i, Statut__c = 'Validé'));
        }
        if(toInsert) insert clients;
        return clients;
    }
    
    public static Contact createContact(String ctName, Id accountId) {
        Contact ct = new Contact(LastName = ctName, AccountId = accountId);
        insert ct;
        return ct;
    }
    
    public static Quote__c createQuote(String name, Id opportunityId, Boolean primary, Id accountId, Date startDate, Decimal subsTerm) {
        Quote__c newQuote = new Quote__c(
            Name = name,
            Opportunity__c = opportunityId,
            Primary__c = primary,
            Account__c = accountId,
            Date_de_validite_du_devis__c = Date.today()
        );
        insert newQuote;
        return newQuote;
    }

    public static Opportunity createOpportunity(String name, Id accountId, Date dateProlongation, String stageName, String type, Id legEntId) {
        Opportunity newOpportunity = new Opportunity(
            Name = name,
            AccountId = accountId,
            CloseDate = System.today(),
            StageName = stageName,
            Pricebook2Id = Test.getStandardPricebookId(),
            PF_Legal_Entity__c = legEntId,
            Type_Location__c = 'Longue Durée'
        );
        if (type != null) newOpportunity.TypeOpportunite__c = type;
        if (dateProlongation != null) newOpportunity.Date_de_prolongation__c = dateProlongation;
        insert newOpportunity;
        return newOpportunity;
    }
    
    // Test de la méthode handleDateModification
    @isTest
    static void testHandleDateModification() {
        // Créez vos données de test
        List<Account> acc = createClients(2, true);
        Contact contactRec = createContact('Test Contact', acc[0].Id);
        Opportunity opp = createOpportunity('Test Opportunity', acc[0].Id, null, 'Stage', null, null);

        // Créez vos devis avec des dates de validité différentes
        Quote__c quote1 = createQuote('Test Quote 1', opp.Id, true, acc[0].Id, Date.today(), 12);
        Quote__c quote2 = createQuote('Test Quote 2', opp.Id, true, acc[0].Id, Date.today().addDays(1), 12);
        // Effectuez une mise à jour des devis pour déclencher le trigger
        Test.startTest();
        quote2.Date_de_validite_du_devis__c = Date.today().addDays(6);

        update quote2;
        Test.stopTest();

        // Vérifiez que le champ "Quote_Validity_Notification_Sent__c" est réinitialisé à false pour les devis dont la date de validité a changé
        List<Quote__c> updatedQuotes = [SELECT Id, Quote_Validity_Notification_Sent__c FROM Quote__c WHERE Id IN :new Set<Id>{quote1.Id, quote2.Id}];
        for (Quote__c updatedQuote : updatedQuotes) {
            System.assertEquals(false, updatedQuote.Quote_Validity_Notification_Sent__c);
        }
    }
}