unpackaged/main/default/objects/Account/fields/Tech_SAP_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_SAP_Id__c</fullName>
    <label>Tech SAP Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville (-Facturation-)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Particulier_B2C.recordType-meta.xml
<RecordType>
    <fullName>Particulier_B2C</fullName>
    <active>true</active>
    <label>Particulier (B2C)</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Fonction__c.field-meta.xml
<CustomField>
    <fullName>Fonction__c</fullName>
    <inlineHelpText>Function as defined in the PF qualification</inlineHelpText>
    <label>Fonction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrateur</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Directeur</fullName>
            </value>
            <value>
                <fullName>Employé</fullName>
            </value>
            <value>
                <fullName>Gérant</fullName>
            </value>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Propriétaire</fullName>
            </value>
            <value>
                <fullName>Responsable</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Technicien</fullName>
            </value>
            <value>
                <fullName>Chef d&#39;atelier</fullName>
            </value>
            <value>
                <fullName>DIRECTEUR DE SITE</fullName>
            </value>
            <value>
                <fullName>AGENT D&#39;EXPLOITATION</fullName>
            </value>
            <value>
                <fullName>AIDE EXPLOITANT</fullName>
            </value>
            <value>
                <fullName>APPRENTI CARROSSIER</fullName>
            </value>
            <value>
                <fullName>APPRENTI CARROSSIER PEINTRE</fullName>
            </value>
            <value>
                <fullName>APPRENTI COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>APPRENTI EXPLOITANT</fullName>
            </value>
            <value>
                <fullName>APPRENTI FRIGORISTE</fullName>
            </value>
            <value>
                <fullName>APPRENTI MECANICIEN</fullName>
            </value>
            <value>
                <fullName>APPRENTIE SECRETAIRE</fullName>
            </value>
            <value>
                <fullName>ASSIST REGIONAL ASSURANCE RE</fullName>
            </value>
            <value>
                <fullName>ASSISTANCE DAGENCE</fullName>
            </value>
            <value>
                <fullName>ASSISTANT COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>ASSISTANT EXPLOITATION</fullName>
            </value>
            <value>
                <fullName>ASSISTANT REGIONAL ASSURANCE</fullName>
            </value>
            <value>
                <fullName>ASSISTANT REGIONAL EXPLOITATION</fullName>
            </value>
            <value>
                <fullName>ASSISTANTE ADMINISTRATIVE</fullName>
            </value>
            <value>
                <fullName>ASSISTANTE COMMERCIALE</fullName>
            </value>
            <value>
                <fullName>ASSISTANTE COMMERCIALE REGIONAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Rôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Détracteur</fullName>
            </value>
            <value>
                <fullName>Indifférent</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Particulier_B2C.recordType-meta.xml
<RecordType>
    <fullName>Particulier_B2C</fullName>
    <active>true</active>
    <description>Contact B2C</description>
    <label>Particulier (B2C)</label>
</RecordType>

unpackaged/main/default/objects/Interface_monitoring__c/Interface_monitoring__c.object-meta.xml
<CustomObject>
    <label>Interface monitoring</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interfaces monitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Interface_monitoring__c/fields/OutgoingMessage__c.field-meta.xml
<CustomField>
    <fullName>OutgoingMessage__c</fullName>
    <label>Outgoing Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Interface_monitoring__c/fields/ResponseMessage__c.field-meta.xml
<CustomField>
    <fullName>ResponseMessage__c</fullName>
    <label>Response Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/InvolvedStakeholder__c/InvolvedStakeholder__c.object-meta.xml
<CustomObject>
    <label>Fonction partenaire</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Numéro Partie impliquée</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fonctions partenaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/InvolvedStakeholder__c/fields/Contact_B2C__c.field-meta.xml
<CustomField>
    <fullName>Contact_B2C__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact B2C</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Particulier (B2C)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fonctions partenaires</relationshipLabel>
    <relationshipName>Fonctions_partenaires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/InvolvedStakeholder__c/fields/InvolvedAccount__c.field-meta.xml
<CustomField>
    <fullName>InvolvedAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partenaire</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Prospect, Client, Particulier (B2C)</value>
        </filterItems>
        <filterItems>
            <field>$Source.Role__c</field>
            <operation>equals</operation>
            <value>Donneur d’ordre, Facturé, Payeur, PV</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>$Source.Role__c</field>
            <operation>equals</operation>
            <value>Livré</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fonctions partenaires</relationshipLabel>
    <relationshipName>Parties_impliquees_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/InvolvedStakeholder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Partie_impliquee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/InvolvedStakeholder__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Fonction partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Donneur d’ordre</fullName>
            </value>
            <value>
                <fullName>Facturé</fullName>
            </value>
            <value>
                <fullName>Livré</fullName>
                <default>true</default>
                <label>Livré</label>
            </value>
            <value>
                <fullName>Payeur</fullName>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fonction__c.field-meta.xml
<CustomField>
    <fullName>Fonction__c</fullName>
    <formula>text(Owner.Fonction__c)</formula>
    <label>Fonction</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vue commerciale client sur la quelle l&#39;opportunité a été créé.</description>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/RoleContact__c.object-meta.xml
<CustomObject>
    <label>Rôle de contact</label>
    <nameField>
        <displayFormat>GF-RCN-{0000000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rôles de contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RoleContact__c/fields/CompteOpportunite__c.field-meta.xml
<CustomField>
    <fullName>CompteOpportunite__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte de l&#39;opportunité</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rôles des contacts</relationshipLabel>
    <relationshipName>ContactsOpportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.CompteOpportunite__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Commercial, Contact - Responsable de parcs</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rôles des contacts</relationshipLabel>
    <relationshipName>Opportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rôles des contacts</relationshipLabel>
    <relationshipName>RolesContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Rôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Avis de paiement</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Comptabilité</fullName>
            </value>
            <value>
                <fullName>Donneur d&#39;ordre</fullName>
            </value>
            <value>
                <fullName>Exploitant</fullName>
            </value>
            <value>
                <fullName>Facturation</fullName>
            </value>
            <value>
                <fullName>Facture dématerialisée</fullName>
            </value>
            <value>
                <fullName>Livré</fullName>
            </value>
            <value>
                <fullName>Payeur</fullName>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>Relance KM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/Intf_AccountTriggerHandler_Test.cls
@IsTest
private class Intf_AccountTriggerHandler_Test {
    @TestSetup
    static void setupData() {

        SalesArea__c sa = new SalesArea__c(
          Name = 'test'
        );
        insert sa;

        Id acRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();

        Account account = new Account(
                Name = 'Agence Test',
//                Tech_SAP_Id__c = 'SAP1234',
                RecordTypeId = acRecTypeId
        );
        insert account;

        SalesAreaData__c sad = new SalesAreaData__c(
                Account__c = account.Id,
                SalesArea__c = sa.Id
        );
        insert sad;

        Id coRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Particulier_B2C').getRecordTypeId();

        Contact contact = new Contact(
                FirstName = 'Monsieur',
                LastName = 'Test',
                MobilePhone = '063456884',
                AccountId = account.Id,
                RecordTypeId = coRecTypeId,
                Fonction__c = 'Particulier'
        );
        insert contact;

        Opportunity oppy = new Opportunity(
                AccountId = account.Id,
                Name = 'Oppy Test',
                CloseDate = Date.today().addDays(5),
                StageName = '1 - Opportunité créée',
                SalesAreaData__c = sad.Id

        );
        insert oppy;

        InvolvedStakeholder__c involvedStakeholder = new InvolvedStakeholder__c(
                InvolvedAccount__c = account.Id,
                Opportunity__c = oppy.Id,
                Role__c = 'Livré'
        );
        insert involvedStakeholder;

        RoleContact__c roleContact = new RoleContact__c(
                Contact__c = contact.Id,
                CompteOpportunite__c = account.Id,
                Opportunite__c = oppy.Id,
                Role__c = 'Payeur'

        );
        insert roleContact;

    }

    @IsTest
    static void testB2BBehavior() {

        Test.startTest();
        Intf_WebserviceMock.status = 200;
        Test.setMock(HttpCalloutMock.class, new Intf_WebserviceMock());

        Opportunity oppy = [SELECT Id, StageName FROM Opportunity];
        oppy.StageName = System.Label.Intf_Default_Oppy_BP_Status_Sync;

        update oppy;

        Account acc = [SELECT Id, Ville__c FROM Account];
        acc.Ville__c = 'Test';

        update acc;

        Test.stopTest();

        List<Interface_monitoring__c> interfaceMonitorings = new List<Interface_monitoring__c>([SELECT Id, Status__c, Status_Code__c, OutgoingMessage__c, ResponseMessage__c, CreatedDate FROM Interface_monitoring__c]);
        System.debug('============== TEST TEST TEST interfaceMonitorings: ' + interfaceMonitorings);
        System.assertEquals(2, interfaceMonitorings.size());
    }

    @IsTest
    static void testB2CBehavior() {

        Contact contact = [SELECT FirstName, LastName, MobilePhone, Phone, Salutation FROM Contact];

        Test.startTest();
        Intf_WebserviceMock.status = 200;
        Test.setMock(HttpCalloutMock.class, new Intf_WebserviceMock());

        Opportunity oppy = [SELECT Id, StageName FROM Opportunity];
        oppy.StageName = System.Label.Intf_Default_Oppy_BP_Status_Sync;
        oppy.Contact_B2C__c = contact.Id;

        update oppy;

        Account acc = [SELECT Id, Ville__c FROM Account];
        acc.Ville__c = 'Test';

        update acc;

        Test.stopTest();

        List<Interface_monitoring__c> interfaceMonitorings = new List<Interface_monitoring__c>([SELECT Id, Status__c, Status_Code__c, OutgoingMessage__c, ResponseMessage__c, CreatedDate FROM Interface_monitoring__c]);
        System.debug('============== TEST TEST TEST interfaceMonitorings: ' + interfaceMonitorings);
        System.assertEquals(2, interfaceMonitorings.size());
    }
}