unpackaged/main/default/objects/Account/fields/Territoire__c.field-meta.xml
<CustomField>
    <fullName>Territoire__c</fullName>
    <label>Territoire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANTILLES</fullName>
            </value>
            <value>
                <fullName>DO1A</fullName>
            </value>
            <value>
                <fullName>DO1B</fullName>
            </value>
            <value>
                <fullName>DO2A</fullName>
            </value>
            <value>
                <fullName>DO2B</fullName>
            </value>
            <value>
                <fullName>DO3A</fullName>
            </value>
            <value>
                <fullName>DO3B</fullName>
            </value>
            <value>
                <fullName>DO4A</fullName>
            </value>
            <value>
                <fullName>DO4B</fullName>
            </value>
            <value>
                <fullName>DO5A</fullName>
            </value>
            <value>
                <fullName>DO5B</fullName>
            </value>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>ILE MAURICE</fullName>
            </value>
            <value>
                <fullName>OCEAN INDIEN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesArea__c/SalesArea__c.object-meta.xml
<CustomObject>
    <label>Organisation Commerciale</label>
    <nameField>
        <label>Nom de l&#39;Organisation Commerciale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations Commerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesArea__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <label>Ligne de produit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessLine</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>VuesCommercialesClient_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/BusinessLine__c.field-meta.xml
<CustomField>
    <fullName>BusinessLine__c</fullName>
    <formula>TEXT(SalesArea__r.BusinessLine__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ligne de produit</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/ManagerCommercial__c.field-meta.xml
<CustomField>
    <fullName>ManagerCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vues_Commerciales_Client1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/PFRegion__c.field-meta.xml
<CustomField>
    <fullName>PFRegion__c</fullName>
    <label>Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PIBU</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <formula>Account__r.CodePostal__c</formula>
    <label>PostalCode</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/SalesArea__c.field-meta.xml
<CustomField>
    <fullName>SalesArea__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Secteur__c.field-meta.xml
<CustomField>
    <fullName>Secteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secteur</label>
    <referenceTo>Secteur__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Territoire__c.field-meta.xml
<CustomField>
    <fullName>Territoire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territoire</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>Vues_Commerciales_Client</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/TerritorialCommercial__c.field-meta.xml
<CustomField>
    <fullName>TerritorialCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial / KAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>VuesCommercialesClientUserCommercial</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Secteur__c/Secteur__c.object-meta.xml
<CustomObject>
    <label>Secteur</label>
    <nameField>
        <label>Nom du Secteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Secteur__c/fields/Commercial__c.field-meta.xml
<CustomField>
    <fullName>Commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial / KAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Representants_Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Secteur__c/fields/Manager_Commercial__c.field-meta.xml
<CustomField>
    <fullName>Manager_Commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Secteurs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Secteur__c/fields/Organisation_Commerciale__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Commerciale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipName>Representants_Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <description>Table référentielle pour l&#39;assignation des commerciaux aux S.A.D</description>
    <label>Territoire</label>
    <nameField>
        <displayFormat>TER-{000000000}</displayFormat>
        <label>Numéro de Territoire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territoires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Territory__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <externalId>true</externalId>
    <label>Code Postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Territory__c/fields/Organisation_Commerciale__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Commerciale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation Commerciale</label>
    <referenceTo>SalesArea__c</referenceTo>
    <relationshipLabel>Territoires</relationshipLabel>
    <relationshipName>Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Territory__c/fields/Secteur__c.field-meta.xml
<CustomField>
    <fullName>Secteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secteur</label>
    <referenceTo>Secteur__c</referenceTo>
    <relationshipLabel>Territoire</relationshipLabel>
    <relationshipName>Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/BusinessLine.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Containers</fullName>
    </customValue>
    <customValue>
        <fullName>Meubles</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Frigorifiques</fullName>
    </customValue>
    <customValue>
        <fullName>Véhicules Secs</fullName>
    </customValue>
    <customValue>
        <fullName>Cession</fullName>
    </customValue>
    <customValue>
        <fullName>Vente</fullName>
        <isActive>false</isActive>
        <label>Vente</label>
    </customValue>
    <customValue>
        <fullName>Véhicules</fullName>
        <isActive>false</isActive>
        <label>Véhicules</label>
    </customValue>
    <masterLabel>Business Line</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/UpdateSalesAreaTerritoryDataBatch.cls
global class UpdateSalesAreaTerritoryDataBatch implements Database.Batchable<sObject> {

     private string filterPaysRegionPF;
    
    
    
    public UpdateSalesAreaTerritoryDataBatch(string filterPaysRegionPF)
    {
        this.filterPaysRegionPF = filterPaysRegionPF;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // Query SalesAreaData__c records where Secteur__c and Territory__c are null
        String Query = 'SELECT Id, SalesArea__c, PostalCode__c,Businessline__c,Account__r.OwnerId FROM SalesAreaData__c WHERE Secteur__c = null AND Territoire__c = null AND PostalCode__c <> null';
             if(filterPaysRegionPF!=null && filterPaysRegionPF!=''){
            Query+=' AND PFRegion__c=\''+filterPaysRegionPF+'\' ';
        }
           return Database.getQueryLocator(Query);

    }
    
    global void execute(Database.BatchableContext BC, List<SalesAreaData__c> scope) {
        // Maps to store Territory__c records by PostalCode__c and SalesArea__c
        Map<String, List<Territory__c>> territoireMap = new Map<String, List<Territory__c>>();

        // Query Territory__c records and populate the map
        for (Territory__c ter : [
            SELECT Id, Organisation_Commerciale__c,organisation_Commerciale__r.Businessline__c, Secteur__c, Code_Postal__c, Secteur__r.Commercial__c, Secteur__r.Manager_Commercial__c	
            FROM Territory__c
        ]) {
            String key = ter.Code_Postal__c + '-' + ter.Organisation_Commerciale__c;
            if (!territoireMap.containsKey(key)) {
                territoireMap.put(key, new List<Territory__c>());
            }
            territoireMap.get(key).add(ter);
        }

        // List to hold updates
        List<SalesAreaData__c> updates = new List<SalesAreaData__c>();

        // Process each SalesAreaData__c record
        for (SalesAreaData__c sad : scope) {
            String key = sad.PostalCode__c + '-' + sad.SalesArea__c;
            if (territoireMap.containsKey(key) && !territoireMap.get(key).isEmpty()) {
                // Assuming the first match is the desired one
                Territory__c ter = territoireMap.get(key)[0];
                sad.Territoire__c = ter.Id;
                sad.Secteur__c = ter.Secteur__c;
                if (ter.Secteur__c != null) {
               
                    
                    sad.ManagerCommercial__c = ter.Secteur__r.Manager_Commercial__c;
                    sad.TerritorialCommercial__c = ter.Secteur__r.Commercial__c;
                
                  
                }
                
            }
            else if(sad.BusinessLine__c=='Containers'){sad.TerritorialCommercial__c = sad.Account__r.OwnerId;}
            updates.add(sad);
        }

        // Update the SalesAreaData__c records
        if (!updates.isEmpty()) {
            update updates;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        System.debug('Batch Job Completed Successfully.');
    }
}