unpackaged/main/default/objects/Lead/fields/Code_Agence_PF__c.field-meta.xml
<CustomField>
    <fullName>Code_Agence_PF__c</fullName>
    <description>Code agence du lookup Agence PF dans la piste</description>
    <formula>Agence_PF__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code Agence PF</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Code_prospect_Igloo__c.field-meta.xml
<CustomField>
    <fullName>Code_prospect_Igloo__c</fullName>
    <label>Code prospect Igloo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>- Code Postal -</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Civilité.</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M.</fullName>
            </value>
            <value>
                <fullName>Mme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/IdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantNational__c</fullName>
    <label>Identifiant national</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Particulier_Professionnel__c.field-meta.xml
<CustomField>
    <fullName>Particulier_Professionnel__c</fullName>
    <label>Particulier / Professionnel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
            <value>
                <fullName>Evénementiel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>- Pays -</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BOLIVIE</fullName>
            </value>
            <value>
                <fullName>BOSNIE HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BULGARIE</fullName>
            </value>
            <value>
                <fullName>BURKINA FASO</fullName>
            </value>
            <value>
                <fullName>CAMBODGE</fullName>
            </value>
            <value>
                <fullName>CAMEROUN</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILI</fullName>
            </value>
            <value>
                <fullName>CHINE</fullName>
            </value>
            <value>
                <fullName>CHYPRE</fullName>
            </value>
            <value>
                <fullName>CISJORDANIE</fullName>
            </value>
            <value>
                <fullName>COLOMBIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Produits__c.field-meta.xml
<CustomField>
    <fullName>Produits__c</fullName>
    <label>Produits</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Chambre froide</fullName>
            </value>
            <value>
                <fullName>Containers</fullName>
            </value>
            <value>
                <fullName>Meuble réfrigéré</fullName>
            </value>
            <value>
                <fullName>Meubles</fullName>
            </value>
            <value>
                <fullName>Véhicule frigorifique</fullName>
            </value>
            <value>
                <fullName>Véhicule Sec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Rue__c.field-meta.xml
<CustomField>
    <fullName>Rue__c</fullName>
    <label>- Rue -</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/TypeActivite__c.field-meta.xml
<CustomField>
    <fullName>TypeActivite__c</fullName>
    <label>Type d&#39;activité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Alimentaire Non Frigorifique</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Beurre, Œufs, Fromage</fullName>
            </value>
            <value>
                <fullName>Boulangerie - Pâtisserie</fullName>
            </value>
            <value>
                <fullName>Crèmes Glacées, Surgelés</fullName>
            </value>
            <value>
                <fullName>Cuisine Centrale</fullName>
            </value>
            <value>
                <fullName>Déménagement</fullName>
            </value>
            <value>
                <fullName>Distributeur de boissons</fullName>
            </value>
            <value>
                <fullName>Distributeur de produits frais et surgelés</fullName>
            </value>
            <value>
                <fullName>Evenementiel</fullName>
            </value>
            <value>
                <fullName>Festivités</fullName>
            </value>
            <value>
                <fullName>Fleuriste</fullName>
            </value>
            <value>
                <fullName>Fruits et Légumes</fullName>
            </value>
            <value>
                <fullName>Grandes et Moyennes Surfaces</fullName>
            </value>
            <value>
                <fullName>Home Service</fullName>
            </value>
            <value>
                <fullName>Hôtelier</fullName>
            </value>
            <value>
                <fullName>Hygiène</fullName>
            </value>
            <value>
                <fullName>Loueur﻿</fullName>
            </value>
            <value>
                <fullName>Marée</fullName>
            </value>
            <value>
                <fullName>Médicaments / Laboratoires pharma</fullName>
            </value>
            <value>
                <fullName>Ostréiculteur</fullName>
            </value>
            <value>
                <fullName>Panification (producteur avec distrib. Intégrée)</fullName>
            </value>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Portage de repas (CCAS-CPAS etc…)</fullName>
            </value>
            <value>
                <fullName>Producteur</fullName>
            </value>
            <value>
                <fullName>Producteurs Industriels</fullName>
            </value>
            <value>
                <fullName>Restaurateur</fullName>
            </value>
            <value>
                <fullName>Restauration Collective</fullName>
            </value>
            <value>
                <fullName>Restauration Rapide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/TypeIdentifiantNational__c.field-meta.xml
<CustomField>
    <fullName>TypeIdentifiantNational__c</fullName>
    <label>Type d&#39;identifiant national</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PaysRegionPF__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CNIE</fullName>
            </value>
            <value>
                <fullName>COCCH</fullName>
            </value>
            <value>
                <fullName>CRO</fullName>
            </value>
            <value>
                <fullName>IBLC</fullName>
            </value>
            <value>
                <fullName>ICO</fullName>
            </value>
            <value>
                <fullName>KVK</fullName>
            </value>
            <value>
                <fullName>NIPC</fullName>
            </value>
            <value>
                <fullName>P.IVA</fullName>
            </value>
            <value>
                <fullName>RNMA</fullName>
            </value>
            <value>
                <fullName>SIREN</fullName>
            </value>
            <value>
                <fullName>TVABE</fullName>
            </value>
            <value>
                <fullName>TVADE</fullName>
            </value>
            <value>
                <fullName>TVAPL</fullName>
            </value>
            <value>
                <fullName>En création</fullName>
            </value>
            <value>
                <fullName>FN</fullName>
            </value>
            <value>
                <fullName>PRISMA</fullName>
            </value>
            <value>
                <fullName>RCRO</fullName>
            </value>
            <value>
                <fullName>COC</fullName>
            </value>
            <value>
                <fullName>RNHU</fullName>
            </value>
            <value>
                <fullName>VATHU</fullName>
            </value>
            <value>
                <fullName>COFIS</fullName>
            </value>
            <value>
                <fullName>TVAIT</fullName>
            </value>
            <value>
                <fullName>DUNS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>- Ville -</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>LeadPetitForestier</businessProcess>
    <label>Lead - PF Draft</label>
</RecordType>

unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CreateDevisIgloo.cls
public class CreateDevisIgloo {
   public static String PARAMETERS {get;set;}
   Public static string CreateDevis(Lead led){
       String message = '';
       String Result;
       string Start ='{ "datas" : [';
       string finish = '"]}';
       CreateDevisIgloo.PARAMETERS='WS_Param_007';
       if(led.status == 'Créée'|| led.Status == 'Abandonnée'){
           system.debug('Lead not Qalified');
           Result = 'NotQalified';
           }
       
       else if(led.Code_prospect_Igloo__c != null){
           
           Result = 'ProspectExiste';
       }
       else
        {
            string jsonBody =CreateDevisIgloo.buildJson(led);
            
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        //Setup Call
        string ApplicationName = 'SFCD';
        req.setEndpoint(WSParametreRequete__c.getInstance(CreateDevisIgloo.PARAMETERS).EndPoint__c);
        req.setMethod(WSParametreRequete__c.getInstance(CreateDevisIgloo.PARAMETERS).Methode__c);
        req.setHeader('ApplicationName',ApplicationName);
        req.setHeader('User', WSParametreRequete__c.getInstance(CreateDevisIgloo.PARAMETERS).UserName__c);
        req.setHeader('pwd', WSParametreRequete__c.getInstance(CreateDevisIgloo.PARAMETERS).MotDePasse__c);
        req.setHeader('Content-Type', WSParametreRequete__c.getInstance(CreateDevisIgloo.PARAMETERS).ContentType__c);
        req.setHeader('Authorization', WSParametreRequete__c.getInstance(CreateDevisIgloo.PARAMETERS).Authorization__c);
        req.setBody(jsonBody);
        system.debug('Endpoint'+req.getEndpoint());
        HttpResponse resp= new HttpResponse();
        req.setTimeout(60000);
        resp = http.send(req);
        system.debug(jsonBody);
        system.debug(resp.getStatusCode());
        if(resp.getStatusCode()==404)
        {
         Result = 'Error';
            system.debug('error');
        }
            else if(resp.getStatusCode()==200)
        {
            system.debug('Done');
            JSONParser parser = JSON.createParser(resp.getBody());
            String CodeProspect = '';
            String Doublon = '';
            system.debug(parser);
            while (parser.nextToken() != null){
                if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) &&
                    (parser.getText() == 'ProspectId')){
                        parser.nextToken();
                        CodeProspect = parser.getText() ;
                        system.debug(CodeProspect);
                    }else if((parser.getCurrentToken() == JSONToken.FIELD_NAME) &&
                        (parser.getText() == 'IsDoublon')){
                    parser.nextToken();
                    Doublon = parser.getText() ;
                            system.debug(Doublon);
                }
            }
            
            if(Doublon == '1'){
           
           Result = 'ProspectExiste';
            }else {
                Result = 'Done';
            }
            
            led.Code_prospect_Igloo__c = CodeProspect;
            Database.update(led);
            
        }
            
                    else
       {
           Result = 'Error';
       }
     
            }
       
       return Result;
}
    
    Public static String buildJson(Lead currentLead){
        string json ='{ "datas" : [{';
        json += '"Pays" : "' + currentLead.Pays__c + '",';
        json += '"Region" : "NULL",';
        json += '"TypeProspect" : "' + currentLead.Particulier_Professionnel__c + '",';
        json += '"TypeIdNational" : "' + currentLead.TypeIdentifiantNational__c + '",';
        json += '"IdentifiantNational" : "' + currentLead.IdentifiantNational__c + '",';
		json += '"NomSociete" : "' + currentLead.Company + '",';
		json += '"Agence" : "' + currentLead.Code_Agence_PF__c +'",';
        json += '"Activite" : "' + currentLead.TypeActivite__c + '",';
        json += '"Sourcing" : "' + currentLead.LeadSource + '",';
        json += '"CP" : "' + currentLead.CodePostal__c + '",';
        json += '"Ville" : "' + currentLead.Ville__c + '",';
        json += '"Adresse" : "' + currentLead.Rue__c + '",';
        json += '"Civilite" : "' + currentLead.Gender__c + '",';
        json += '"Nom" : "' + currentLead.Name + '",';
        json += '"Prenom" : "' + currentLead.Name + '",';
		json += '"Telephone" : "' + currentLead.Phone + '",';
        json += '"Mail" : "' + currentLead.Email + '",';
        json += '"ProductName" : "' + currentLead.Produits__c + '",';
		json += '"Service" : "' + currentLead.Fonction__c + '"}]}';
        return json;
    }
}