unpackaged/main/default/objects/Case/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120O0000003cw4QAA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Requete_en_attente__c.field-meta.xml
<CustomField>
    <fullName>Requete_en_attente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requête en attente</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/TECH_Notification_sent__c.field-meta.xml
<CustomField>
    <fullName>TECH_Notification_sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>coché automatiquement quand une notification est envoyé depuis la requête
PB MOON_10_Notifications_Case</description>
    <label>TECH_Notification_sent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CaseClass.cls
public class CaseClass {
	public static void CaseEnAttente(String Id)
    {
            Case C = [SELECT requete_en_attente__c,Status,Agence_Intervenante__c,TECH_Notification_sent__c FROM Case WHERE id=:Id];
       
                C.requete_en_attente__c=false;
        		
    }
    
    public static void CaseNotificationSent(String Id)
    {
                    Case C = [SELECT requete_en_attente__c,Status,Agence_Intervenante__c,TECH_Notification_sent__c FROM Case WHERE id=:Id];
                    C.TECH_Notification_sent__c = false;
        			
    }
   

   
}