unpackaged/main/default/objects/Case/fields/Agence_compte__c.field-meta.xml
<CustomField>
    <fullName>Agence_compte__c</fullName>
    <label>Agence propriétaire /</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Agence_Intervenante__c.field-meta.xml
<CustomField>
    <fullName>Agence_Intervenante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Intervenante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120O0000003cw4QAA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Requetes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Description_incident_client__c.field-meta.xml
<CustomField>
    <fullName>Description_incident_client__c</fullName>
    <label>Description incident client</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Requete_en_attente__c.field-meta.xml
<CustomField>
    <fullName>Requete_en_attente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requête en attente</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/TECH_Notification_sent__c.field-meta.xml
<CustomField>
    <fullName>TECH_Notification_sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>coché automatiquement quand une notification est envoyé depuis la requête
PB MOON_10_Notifications_Case</description>
    <label>TECH_Notification_sent</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TestCaseBeforeUpdate.cls
@isTest
private class TestCaseBeforeUpdate 
{
    Static testMethod void CaseClassTest()
    {
        Case Req = new Case();
        Account ACC = Utils_TestMethods.createAccount('accName', 'accCodeNAF', null, Label.CPT_RecordTypeId_CompteClient);
        Asset Parc = Utils_TestMethods.CreateAsset(ACC.Id,Label.Parc_RecordTypeId);
        Account Agence = Utils_TestMethods.CreateAgence('001 - VILLEPINTE');
        Req.AccountId=ACC.Id;
        Req.AssetId = Parc.id;
        Req.Agence_Intervenante__c=Agence.id;
        //Req.Agence_compte__c='001 - VILLEPINTE';
        Req.Description_incident_client__c=null;
		insert Req;
        Req.requete_en_attente__c=true;
        update Req;
        //EN attente
        CaseClass.CaseEnAttente(Req.Id);
        CaseClass.CaseNotificationSent(Req.Id);
    }
    Static testMethod void CaseClassTrigger1Test()
    {
        Case Req = new Case();
        Account ACC = Utils_TestMethods.createAccount('accName', 'accCodeNAF', null, Label.CPT_RecordTypeId_CompteClient);
        Asset Parc = Utils_TestMethods.CreateAsset(ACC.Id,Label.Parc_RecordTypeId);
        Account Agence = Utils_TestMethods.CreateAgence('001 - VILLEPINTE');
        
        Req.AccountId=ACC.Id;
        Req.AssetId = Parc.id;
        Req.Agence_Intervenante__c=Agence.id;
        Req.Agence_compte__c='001 - VILLEPINTE';
        Req.status = Label.Case_Statut_Nouvelle;
		insert Req;
        //Case En attente 
        Req.requete_en_attente__c=true;
        update Req;
        //Case change de statut
       	Req.Status=Label.Case_Statut_EnCours;
        update Req;
       
    }
    Static testMethod void CaseClassTrigger2Test()
    {
        //Data
        Case Req = new Case();
        Account ACC = Utils_TestMethods.createAccount('accName', 'accCodeNAF', null, Label.CPT_RecordTypeId_CompteClient);
        Asset Parc = Utils_TestMethods.CreateAsset(ACC.Id,Label.Parc_RecordTypeId);
        Account Agence = Utils_TestMethods.CreateAgence('001 - VILLEPINTE');
        Account Agence2 = Utils_TestMethods.CreateAgence('002 - BORDEAUX');
        
        //Affectations
        Req.AccountId=ACC.Id;
        Req.AssetId = Parc.id;
        Req.Agence_Intervenante__c=Agence.id;
        Req.Agence_compte__c='001 - VILLEPINTE';
        Req.status = Label.Case_Statut_Nouvelle;
        Req.Requete_en_attente__c=False;
		insert Req;
       
        //Change Agence
        Req.TECH_Notification_sent__c=true;
       	Req.Agence_Intervenante__c=Agence2.id;
        
        update Req;
    }
    
}