unpackaged/main/default/objects/Derogation__c/Derogation__c.object-meta.xml
<CustomObject>
    <label>Dérogation</label>
    <nameField>
        <displayFormat>DERO-{0000}</displayFormat>
        <label>Num de Dérogation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dérogations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Derogation__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Dérogations</relationshipLabel>
    <relationshipName>Derogations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Derogation__c/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Dérogations</relationshipLabel>
    <relationshipName>Derogations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PaysRegionPF__c.field-meta.xml
<CustomField>
    <fullName>PaysRegionPF__c</fullName>
    <inlineHelpText>Pays ou Région (FR) selon l&#39;implémentation des agences PF</inlineHelpText>
    <label>Pays / Région PF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRO IDF 1</fullName>
            </value>
            <value>
                <fullName>DRO IDF 2</fullName>
            </value>
            <value>
                <fullName>DROM</fullName>
            </value>
            <value>
                <fullName>DRO NORD 1</fullName>
            </value>
            <value>
                <fullName>DRO NORD 2</fullName>
            </value>
            <value>
                <fullName>DRO NORD 3</fullName>
            </value>
            <value>
                <fullName>DRO NORD 4</fullName>
            </value>
            <value>
                <fullName>DRO NORD 5</fullName>
            </value>
            <value>
                <fullName>DRO NORD 6</fullName>
            </value>
            <value>
                <fullName>DRO NORD 7</fullName>
            </value>
            <value>
                <fullName>DRO SUD 1</fullName>
            </value>
            <value>
                <fullName>DRO SUD 2</fullName>
            </value>
            <value>
                <fullName>DRO SUD 3</fullName>
            </value>
            <value>
                <fullName>DRO SUD 4</fullName>
            </value>
            <value>
                <fullName>DRO SUD 5</fullName>
            </value>
            <value>
                <fullName>DRO SUD 6</fullName>
            </value>
            <value>
                <fullName>DRO SUD 7</fullName>
            </value>
            <value>
                <fullName>PFM</fullName>
            </value>
            <value>
                <fullName>PFUK</fullName>
            </value>
            <value>
                <fullName>PIAE</fullName>
            </value>
            <value>
                <fullName>PIAT</fullName>
            </value>
            <value>
                <fullName>PIBE</fullName>
            </value>
            <value>
                <fullName>PICH</fullName>
            </value>
            <value>
                <fullName>PICZ</fullName>
            </value>
            <value>
                <fullName>PIDE</fullName>
            </value>
            <value>
                <fullName>PIES</fullName>
            </value>
            <value>
                <fullName>PIHU</fullName>
            </value>
            <value>
                <fullName>PILU</fullName>
            </value>
            <value>
                <fullName>PIMA</fullName>
            </value>
            <value>
                <fullName>PIND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SalesAreaData__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaData__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vue commerciale client sur la quelle l&#39;opportunité a été créé.</description>
    <label>Vue Commerciale Client</label>
    <referenceTo>SalesAreaData__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/RDD_InitDEROSAD_Batch.cls
public class RDD_InitDEROSAD_Batch implements Database.Batchable<sObject>, Database.Stateful {



    private string filterPaysRegionPF;
    
    
    
    public RDD_InitDEROSAD_Batch(string filterPaysRegionPF)
    {
        this.filterPaysRegionPF = filterPaysRegionPF;
    }
    
	public  Database.queryLocator start(Database.BatchableContext bc)    
    {
        System.Debug('>>>>> RDD_InitDEROSAD_Batch  start <<<<<');
        
        
        string Query = 'Select Id,SalesAreaData__c,Opportunite__c,Opportunite__r.SalesAreaData__c,Opportunite__r.PaysRegionPF__c from Derogation__c where SalesAreaData__c=null and Opportunite__c<>null and Opportunite__r.SalesAreaData__c <>null' ;
         if(filterPaysRegionPF!=null && filterPaysRegionPF!=''){
            Query+=' AND Opportunite__r.PaysRegionPF__c=\''+filterPaysRegionPF+'\' ';
        }
               
        
        return Database.getQueryLocator(Query);
    }
    
    
    
     public void execute(Database.BatchableContext bc, list<sObject> scope){
        System.Debug('>>>> RDD_InitDEROSAD_Batch start execute <<<<');
       list<Derogation__c> ListeDero = (list<Derogation__c>)scope;
       

        RDD_SADController.MigrateDeroSAD(ListeDero);
        
        System.Debug('>>>> RDD_InitDEROSAD_Batch End execute <<<<');
    }
    
    
     public void finish(Database.BatchableContext bc){
        System.Debug('>>>> RDD_InitDEROSAD_Batch Start finish <<<<');
                
       
    }
}