unpackaged/main/default/objects/Asset/fields/Agence_Localisation__c.field-meta.xml
<CustomField>
    <fullName>Agence_Localisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence Localisation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parcs (Agence Localisation)</relationshipLabel>
    <relationshipName>Parcs_Localisation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Date_de_debut_asset__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut_asset__c</fullName>
    <label>Date de debut</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Date_de_fin_asset__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_asset__c</fullName>
    <description>Date de fin servant de filtre conteneur sur l&#39;outil fleet management</description>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Neuf_ou_parc__c.field-meta.xml
<CustomField>
    <fullName>Neuf_ou_parc__c</fullName>
    <label>Neuf ou parc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neuf</fullName>
            </value>
            <value>
                <fullName>Parc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Options installées sur le conteneur.</description>
    <label>Options</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Status_de_location__c.field-meta.xml
<CustomField>
    <fullName>Status_de_location__c</fullName>
    <label>Statut de Réservation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Position_Conteneur__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>En Atelier</fullName>
            </value>
            <value>
                <fullName>En Transport</fullName>
            </value>
            <value>
                <fullName>En Location</fullName>
            </value>
            <value>
                <fullName>Disponible</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Magasin (Service)</fullName>
            </value>
            <value>
                <fullName>En Fabrication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Type_de_parc__c.field-meta.xml
<CustomField>
    <fullName>Type_de_parc__c</fullName>
    <formula>if(
AND(
NOT(ISBLANK( Age_du_vehicule__c ))
,
Age_du_vehicule__c &gt; 1826
)
,
&quot;Parc&quot;
,
&quot;Neuf&quot;
)</formula>
    <label>Type de parc</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <formula>TEXT(SBQQ__Quote__r.Type_de_location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type de location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Exclude_For_Container__c.field-meta.xml
<CustomField>
    <fullName>Exclude_For_Container__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates this product should not be used for container.</inlineHelpText>
    <label>Exclude For Container</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Gamme__c.field-meta.xml
<CustomField>
    <fullName>Gamme__c</fullName>
    <label>Gamme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Maxi-Special</fullName>
            </value>
            <value>
                <fullName>-70ºC</fullName>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Option assemblage</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Hors Standard</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Type_de_Location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_Location__c</fullName>
    <label>Type de Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Containers.recordType-meta.xml
<RecordType>
    <fullName>Containers</fullName>
    <active>true</active>
    <label>Containers</label>
</RecordType>

unpackaged/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objet réservation de containers avec leurs options respectives.</description>
    <label>Réservation</label>
    <nameField>
        <displayFormat>RESA - {0}</displayFormat>
        <label>Numéro de réservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reservation__c/fields/Asset_assigne__c.field-meta.xml
<CustomField>
    <fullName>Asset_assigne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conteneur sélectionné</description>
    <label>Asset assigné</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Réservations</relationshipLabel>
    <relationshipName>R_servations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Réservations (Client)</relationshipLabel>
    <relationshipName>R_servation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Commande__c.field-meta.xml
<CustomField>
    <fullName>Commande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Numéro de commande</description>
    <label>Commande</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Réservations</relationshipLabel>
    <relationshipName>R_servations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de debut</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <description>Date de fin de location</description>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Description_Gantt__c.field-meta.xml
<CustomField>
    <fullName>Description_Gantt__c</fullName>
    <description>Used for Fleet Management Gantt</description>
    <formula>&#39;&lt;p&gt;&#39; &amp;  IF(TEXT(Status__c) != null, TEXT(Status__c), &#39;&#39;) &amp; &#39;&lt;/p&gt;&#39; 
&amp; &#39;&lt;p&gt;&#39; &amp; Type__c &amp; &#39;&lt;/p&gt;&#39;
&amp; &#39;&lt;p&gt;&#39; &amp; IF(Type_de_conteneur__c != null, Type_de_conteneur__r.Name, &#39;&#39;) &amp; &#39;&lt;/p&gt;&#39; 
&amp; &#39;&lt;p&gt;&#39; &amp;  Shipping_City__c &amp; &#39;&lt;/p&gt;&#39;</formula>
    <label>Description (Gantt)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <formula>Commande__r.Compte_de_livraison__r.Ligne1Exploitation__c  + &quot; &quot; +  Commande__r.Compte_de_livraison__r.CodePostalExploitation__c + &quot; &quot; +  Commande__r.Compte_de_livraison__r.VilleExploitation__c + &quot; &quot; +  TEXT(Commande__r.Compte_de_livraison__r.PaysExploitation__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adresse de livraison</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <formula>Commande__r.ShippingPostalCode + &quot; &quot; + Commande__r.ShippingCity</formula>
    <label>Shipping City</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de planification</fullName>
                <default>true</default>
                <label>En attente de planification</label>
            </value>
            <value>
                <fullName>Planifiée</fullName>
            </value>
            <value>
                <fullName>Confirmée</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>RecordType.Name  &amp; 
IF(!ISBLANK(TEXT(Type_Atelier__c)), &#39; - &#39; &amp; TEXT(Type_Atelier__c),
			IF(!ISBLANK(TEXT(Type_de_transport__c)), &#39; - &#39; &amp; TEXT(Type_de_transport__c),
						IF(!ISBLANK(TEXT(Type_de_location__c)), &#39; - &#39; &amp; TEXT(Type_de_location__c),
									&#39;&#39;)
						)
			)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Type_Atelier__c.field-meta.xml
<CustomField>
    <fullName>Type_Atelier__c</fullName>
    <label>Type d&#39;Atelier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avant location</fullName>
                <label>Préparation départ container | PTI</label>
            </value>
            <value>
                <fullName>Apres location</fullName>
                <label>Retour location (Estimation)</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Gros Travaux</fullName>
            </value>
            <value>
                <fullName>Préparation Saison</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Type_de_location__c.field-meta.xml
<CustomField>
    <fullName>Type_de_location__c</fullName>
    <label>Type de location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CD</fullName>
                <label>Courte Durée</label>
            </value>
            <value>
                <fullName>CDM</fullName>
                <label>Moyenne Durée</label>
            </value>
            <value>
                <fullName>Relais</fullName>
            </value>
            <value>
                <fullName>LD</fullName>
                <label>Longue Durée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Type_de_transport__c.field-meta.xml
<CustomField>
    <fullName>Type_de_transport__c</fullName>
    <label>Type de transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transport Aller vers client</fullName>
            </value>
            <value>
                <fullName>Transport Retour vers atelier</fullName>
                <label>Transport Retour vers le dépôt</label>
            </value>
            <value>
                <fullName>Intersites</fullName>
            </value>
            <value>
                <fullName>Fabrication</fullName>
            </value>
            <value>
                <fullName>Echange technique</fullName>
            </value>
            <value>
                <fullName>Déplacement container client</fullName>
            </value>
            <value>
                <fullName>Transport divers</fullName>
            </value>
            <value>
                <fullName>Transport inutile</fullName>
            </value>
            <value>
                <fullName>Transport Amont</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Type_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Courte Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Moyenne Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Longue Durée</fullName>
    </customValue>
    <description>Type de Location (CD, CMD, LD)</description>
    <masterLabel>Type Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/FleetManagementController.cls
public class FleetManagementController {
  
  /************************************* READ *************************************/

  /*********** FIELD SETS  ***********/

  @AuraEnabled
  public static List<Field> getFieldSet(String objectName, String fieldSetName) {
    List<Field> fields = new List<Field>();
    Schema.DescribeSObjectResult obj = Schema.getGlobalDescribe().get(objectName).getDescribe();
    for (Schema.FieldSetMember fsm : obj.FieldSets.getMap().get(fieldSetName).getFields()) {
      if (fsm.getFieldPath() == 'RecordTypeId') {
        fields.add(new Field(fsm.getFieldPath(),
                            fsm.getLabel(),
                            String.valueOf(fsm.getType()),
                            fsm.getRequired(),
                            null,
                            getRecordTypes_bis(objectName)
                            )
                    );
      } 
      else {
        fields.add(new Field(fsm.getFieldPath(),
                            fsm.getLabel(),
                            String.valueOf(fsm.getType()),
                            fsm.getRequired(),
                            (String.valueOf(fsm.getType()) == 'String'
                              ? fsm.getSObjectField().getDescribe().getLength()
                              : null),
                            ((String.valueOf(fsm.getType()) == 'Picklist' ||
                              String.valueOf(fsm.getType()) == 'MultiPicklist')
                              ? getFieldPicklistEntries(
                                  fsm.getSObjectField().getDescribe().getPicklistValues()
                                )
                              : null)
                            )
                    );
      }
    }
    return fields;
  }

  /*********** RECORD TYPES ***********/

  @AuraEnabled
  public static Map<Id, String> getRecordTypes(String objectName) {
    Map<Id, String> recordTypesById = new Map<Id, String>();
    Schema.DescribeSObjectResult obj = Schema.getGlobalDescribe().get(objectName).getDescribe();
    for (Schema.RecordTypeInfo rt : obj.getRecordTypeInfosById().values()) {
      if (!rt.isMaster() && rt.isActive())
        recordTypesById.put(rt.getRecordTypeId(), rt.getName());
    }
    return recordTypesById;
  }

  @AuraEnabled
  public static List<Option> getRecordTypes_bis(String objectName) {
    List<Option> options = new List<Option>();
    Schema.DescribeSObjectResult obj = Schema.getGlobalDescribe().get(objectName).getDescribe();
    for (Schema.RecordTypeInfo rt : obj.getRecordTypeInfosById().values()) {
      if (!rt.isMaster() && rt.isActive())
        options.add(new Option(rt.getRecordTypeId(), rt.getName()));
    }
    return options;
  }

  /*********** PICKLISTS ***********/

  public static List<Option> getFieldPicklistEntries(List<Schema.PicklistEntry> picklistEntries) {
    List<Option> options = new List<Option>();
    for (Schema.PicklistEntry ple : picklistEntries) {
      if (ple.isActive())
        options.add(new Option(ple.getValue(), ple.getLabel(), ple.isDefaultValue()));
    }
    return options;
  }

  /*********** RECORDS ***********/


  /**** HOLIDAYS ****/

  @AuraEnabled
  public static List<Holiday> getHolidayRecords() {
    return [SELECT ActivityDate, Name FROM Holiday];
  }

  /**** RESERVATIONS ****/

  @AuraEnabled
  public static List<Reservation__c> getReservations(List<Field> searchFields, List<Field> resultFields, Id orderId, Reservation__c filter) {
    System.debug('###getReservations');
    System.debug('#searchFields : ' + searchFields);
    System.debug('#resultFields : ' + resultFields);
    System.debug('#orderId : ' + orderId);
    System.debug('#filter : ' + filter);

    //Select
    String query = 'Select Id, Name, Commande__c, ';
    String criteria = '';

    //Search fields
    Object value;
    for (Field field : searchFields) {
      if (!query.contains(field.apiName)) {
        query += field.apiName + ', ';
      }
      if (filter != null) {
        System.debug('##field.apiName : ' + field.apiName);
        System.debug('##field.fieldType : ' + field.fieldType);
        System.debug('##value : ' + filter.get(field.apiName));
        
        value = filter.get(field.apiName);
        if (value != null && value != '') {
          if (field.fieldType == 'String' || field.fieldType == 'TextArea') {
            criteria += field.apiName + ' LIKE \'%' + value + '%\' AND ';
          } 
          else if (field.fieldType == 'Date') {
            if (field.apiName == 'Date_de_debut__c')
              criteria += field.apiName + ' >= ' + ((DateTime) value).format('yyyy-MM-dd') + ' AND ';
            else if (field.apiName == 'Date_de_fin__c')
              criteria += field.apiName + ' <= ' + ((DateTime) value).format('yyyy-MM-dd') + ' AND ';
            else criteria += field.apiName + ' = ' + ((DateTime) value).format('yyyy-MM-dd') + ' AND ';
          } 
          else if (field.fieldType == 'DateTime') {
            criteria += field.apiName + ' = ' + ((DateTime) value).format('yyyy-MM-dd\'T\'hh:mm:ss\'z\'') + ' AND ';
          } 
          else if (field.fieldType == 'Time') {
            criteria += field.apiName + ' = ' + ((DateTime) value).format('\'T\'hh:mm:ss\'z\'') + ' AND ';
          } 
          else if (field.fieldType == 'Picklist' || field.apiName == 'RecordTypeId') {
            criteria += '(';
            for (String option : String.valueOf(value).split(';')) {
              criteria += field.apiName + ' = \'' + String.escapeSingleQuotes(option) + '\' OR ';
            }
            criteria = criteria.SubStringBeforeLast('OR');
            criteria += ') AND ';
          } 
          else if (field.fieldType == 'Currency' || field.fieldType == 'Percent' || field.fieldType == 'Boolean' ||
            field.fieldType == 'Integer' || field.fieldType == 'Double' || field.fieldType == 'Long') {
            criteria += field.apiName + ' = ' + value + ' AND ';
          } 
          else {
            criteria += field.apiName + ' = \'' + value + '\' AND ';
          }
        }
      }
    }

    //Result fields
    for (Field field : resultFields) {
      if (!query.contains(field.apiName)) {
        query += field.apiName + ', ';
      }
    }

    query = query.SubStringBeforeLast(',');

    //FROM
    query += ' FROM Reservation__c';
    System.debug('#query without criteria: ' + query);

    //WHERE
    //if(orderId != null) criteria += ' Commande__c = \'' + orderId + '\'';
    if (!String.isEmpty(criteria)) {
      criteria = criteria.SubStringBeforeLast('AND');
      query += ' WHERE (' + criteria + ')';
    }
    System.debug('#criteria : ' + criteria);
    System.debug('#query with criteria: ' + query);

    //ORDER BY / LIMIT
    query += ' ORDER BY Date_de_debut__c LIMIT 30';

    return Database.query(query);
  }

  @AuraEnabled
  public static List<Reservation__c> getReservationsFSL(String assetIds) {
    List<Reservation__c> reservations = new List<Reservation__c>();
    if (assetIds != '') {
      List<String> assetIdsList = assetIds.split(';');
      reservations = [SELECT Name, Asset_assigne__r.Name, Asset_assigne__r.Account.Name, Asset_assigne__r.Agence_Localisation__r.Name,
                      	Date_de_debut__c, Date_de_fin__c, Status__c,
                        Type_Atelier__c, Type_de_transport__c, Type_de_location__c, Type__c, 
                        Shipping_Address__c, Shipping_City__c,
                        Description_Gantt__c, Record_Type_Name__c, RecordType.DeveloperName
                      FROM Reservation__c
                      WHERE Asset_assigne__c IN :assetIdsList ORDER BY Asset_assigne__r.Name ];
    }
    return reservations;
  }

  private static String getReservationQuery(Id assetId) {
    String queryString;
    if (assetId == null) {
      queryString = 'SELECT Name, Date_de_debut__c, Date_de_fin__c, Client__c, Client__r.Name, Description_Gantt__c, Record_Type_Name__c, RecordType.DeveloperName, Type_Atelier__c, Type_de_transport__c, Status__c FROM Reservation__c where Date_de_debut__c != null and Date_de_fin__c != null and Asset_assigne__c != null';
    } else {
      queryString =
        'SELECT Name, Date_de_debut__c, Date_de_fin__c,Client__c, Client__r.Name, Description_Gantt__c, Record_Type_Name__c, RecordType.DeveloperName,Type_Atelier__c, Type_de_transport__c, Status__c FROM Reservation__c where Date_de_debut__c != null and Date_de_fin__c != null and Asset_assigne__c = \'' +
        assetId +
        '\'';
    }
    queryString += ' ORDER BY Date_de_debut__c DESC LIMIT 5000';
    System.debug('getReservationQuery - queryString: ' + queryString);
    return queryString;
  }

  @AuraEnabled
  public static List<sObject> getReservationSObjects(Id assetId) {
    System.debug('getReservationSObjects - assetId: ' + assetId);
    return Database.query(getReservationQuery(assetId));
  }

  /**** CONTAINERS (ASSETS) ****/

  @AuraEnabled
  public static List<Asset> getAssets(List<Field> searchFields, List<Field> resultFields, Id orderId, Asset filter) {
    System.debug('###getAssets');
    System.debug('#searchFields : ' + searchFields);
    System.debug('#resultFields : ' + resultFields);
    System.debug('#orderId : ' + orderId);
    System.debug('#filter : ' + filter);

    String parcRTID = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Parc_Container').getRecordTypeId();

    //Select
    String query = 'Select Id,  ';
    String criteria = '';
    
     

    //Search fields
    Object value;
    Boolean statusDefined = false;
    for (Field field : searchFields) {
      if (!query.contains(field.apiName)) {
        query += field.apiName + ', ';
      }
      if (filter != null) {
        value = filter.get(field.apiName);
        
        if(field.apiName != 'Date_de_debut_asset__c' && field.apiName != 'Date_de_fin_asset__c') {
          if (value != null && value != '') {
            
            /* START Exception */
            if (field.apiName == 'Name') {
              criteria += field.apiName + ' = \'' + value + '\' AND ';
            } 
             else if ( field.fieldType == 'PICKLIST' && field.apiName == 'Neuf_ou_parc__c') {
              criteria += '(';
              for (String option : String.valueOf(value).split(';')) {
                criteria += ' Type_de_parc__c = \'' + String.escapeSingleQuotes(option) + '\' OR ';
              }
              criteria = criteria.SubStringBeforeLast('OR');
              criteria += ') AND ';
            } 
            else if (field.apiName == 'Parc__c') {
              criteria += ' Id = \'' + value + '\' AND ';
            } 
            else if (field.apiName == 'Options__c') {
              criteria += '(';
              for (String option : ((String) value).split(';')) {
                criteria += field.apiName + ' LIKE \'%' + String.escapeSingleQuotes(option) + '%\' OR ';
              }
              criteria = criteria.SubStringBeforeLast('OR');
              criteria += ') AND ';
            } 
            else if (field.apiName == 'Status_de_location__c') {
              if (filter.get('Date_de_debut_asset__c') == null && filter.get('Date_de_fin_asset__c') == null) {
                criteria += '(';
                for (String option : String.valueOf(value).split(';')) {
                  criteria += field.apiName + ' = \'' + String.escapeSingleQuotes(option) + '\' OR ';
                }
                criteria = criteria.SubStringBeforeLast('OR');
                criteria += ') AND ';
              }
              statusDefined = true;
            } 
            /* END Exception */

            else if ( field.fieldType == 'String' || field.fieldType == 'TextArea') {
              criteria += field.apiName + ' LIKE \'%' + value + '%\' AND ';
            } 
            else if (field.fieldType == 'Date') {
              criteria += field.apiName + ' = ' + ((DateTime) value).format('yyyy-MM-dd') +' AND ';
            } 
            else if (field.fieldType == 'DateTime') {
              criteria += field.apiName + ' = ' + ((DateTime) value).format('yyyy-MM-dd\'T\'hh:mm:ss\'z\'') + ' AND ';
            } 
            else if (field.fieldType == 'Time') {
              criteria += field.apiName + ' = ' + ((DateTime) value).format('\'T\'hh:mm:ss\'z\'') + ' AND ';
            }
            else if ( (field.fieldType == 'Picklist' && field.apiName<>'Neuf_ou_parc__c') || field.apiName == 'RecordTypeId') {
              criteria += '(';
              for (String option : String.valueOf(value).split(';')) {
                criteria += field.apiName + ' = \'' + String.escapeSingleQuotes(option) + '\' OR ';
              }
              criteria = criteria.SubStringBeforeLast('OR');
              criteria += ') AND ';
            } 
            else if (field.fieldType == 'Currency' || field.fieldType == 'Percent' || field.fieldType == 'Boolean' || 
                  field.fieldType == 'Integer' || field.fieldType == 'Double' || field.fieldType == 'Long') {
              criteria += field.apiName + ' = ' + value + ' AND ';
            } 
            else {
              criteria += field.apiName + ' = \'' + value + '\' AND ';
            }
          }
        }
      }
    }

    if (filter != null) {
      Object startDate = filter.get('Date_de_debut_asset__c');
      Object endDate = filter.get('Date_de_fin_asset__c');
      if (startDate != null || endDate != null) {
        if (statusDefined && filter.get('Status_de_location__c') != 'Disponible;') {
          criteria += ' Id IN (SELECT Asset_assigne__c FROM Reservation__c ';
          if(startDate != null && endDate != null){
            criteria += 'WHERE (';
            criteria += '(Date_de_debut__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_debut__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += 'OR ';
            criteria += '(Date_de_fin__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          else if(startDate != null){
            criteria += 'WHERE (';
            criteria += 'Date_de_debut__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          else if(endDate != null){
              
            criteria += 'WHERE (';
            criteria += 'Date_de_fin__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ' ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }

          if (filter.get('Status_de_location__c') != 'Non disponible;') {
            criteria += ' AND (';
            for (String option : ((String) filter.get('Status_de_location__c')).split(';')) {
              criteria += ' RecordType.Name LIKE \'%' + option.replace('En ', '') + '%\' OR ';
            }
            criteria = criteria.SubStringBeforeLast('OR');
            criteria += ')) AND ';
          } 
          else {
            criteria += ') AND ';
          }
        } 
        else {
          criteria += ' Status_de_location__c != \'Cession\' AND ';
          criteria += ' Id NOT IN (SELECT Asset_assigne__c FROM Reservation__c ';
          if(startDate != null && endDate != null){
            criteria += 'WHERE (';
            criteria += '(Date_de_debut__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_debut__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += 'OR ';
            criteria += '(Date_de_fin__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          else if(startDate != null){
            criteria += 'WHERE (';
            criteria += 'Date_de_debut__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          else if(endDate != null){
            criteria += 'WHERE (';
            criteria += 'Date_de_fin__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ' ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          criteria += ') AND ';
        }
      } 
      else if (!statusDefined) {
        criteria += ' Status_de_location__c = \'Disponible\' AND ';
      }
    } 
    else {
      criteria += ' Status_de_location__c = \'Disponible\' AND ';
       
      //criteria += ' Id NOT IN (SELECT Asset_assigne__c FROM Reservation__c) AND ';
    }

    //Result fields
    for (Field field : resultFields) {
      if (!query.contains(field.apiName)) {
        query += field.apiName + ', ';
      }
    }
      
    query += '(SELECT Name FROM ChildAssets WHERE RecordType.DeveloperName = \'Equipement\'), ';
      
    query = query.SubStringBeforeLast(',');

    //FROM
    query += ' FROM Asset';
    System.debug('#query without criteria: ' + query);

    //WHERE
    query += ' WHERE RecordTypeId = \'' + parcRTID + '\'';
    if (!String.isEmpty(criteria)) {
      criteria = criteria.SubStringBeforeLast('AND');
      query += ' AND ' + criteria + '';
    }
      
    System.debug('#criteria : ' + criteria);
    System.debug('#query with criteria: ' + query);

    //ORDER BY / LIMIT
    query += ' ORDER BY Name';
    
    System.debug('##############query : ' + query);
    return Database.query(query);
  }

  @AuraEnabled
  public static List<Asset> getAssetsFSL(List<Field> searchFields, List<Field> resultFields, Id orderId, Asset filter) {
    System.debug('###getAssetsFSL');
    System.debug('#searchFields : ' + searchFields);
    System.debug('#resultFields : ' + resultFields);
    System.debug('#orderId : ' + orderId);
    System.debug('#filter : ' + filter);

    String parcRTID = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Parc_Container').getRecordTypeId();

    //Select
    String query = 'Select Id,  ';
    String criteria = '';

    //Search fields
    Object value;
    Boolean statusDefined = false;
    for (Field field : searchFields) {
      if (!query.contains(field.apiName)) {
        query += field.apiName + ', ';
      }
      if (filter != null) {
        value = filter.get(field.apiName);
        if (
          field.apiName != 'Date_de_debut_asset__c' &&
          field.apiName != 'Date_de_fin_asset__c'
        ) {
          if (value != null && value != '') {
            /* START Exception */
            if (field.apiName == 'Name') {
              criteria += field.apiName + ' = \'' + value + '\' AND ';
            } else if ( field.fieldType == 'PICKLIST' && field.apiName == 'Neuf_ou_parc__c') {
              criteria += '(';
              for (String option : String.valueOf(value).split(';')) {
                criteria += ' Type_de_parc__c = \'' + String.escapeSingleQuotes(option) + '\' OR ';
              }
              criteria = criteria.SubStringBeforeLast('OR');
              criteria += ') AND ';
            } 
              else if (field.apiName == 'Parc__c') {
              criteria += ' Id = \'' + value + '\' AND ';
            } else if (field.apiName == 'Options__c') {
              criteria += '(';
              for (String option : ((String) value).split(';')) {
                criteria += field.apiName + ' LIKE \'%' + String.escapeSingleQuotes(option) + '%\' OR ';
              }
              criteria = criteria.SubStringBeforeLast('OR');
              criteria += ') AND ';
            } else if (field.apiName == 'Status_de_location__c') {
              if (
                filter.get('Date_de_debut_asset__c') == null &&
                filter.get('Date_de_fin_asset__c') == null
              ) {
                criteria += '(';
                for (String option : String.valueOf(value).split(';')) {
                  criteria += field.apiName + ' = \'' + String.escapeSingleQuotes(option) + '\' OR ';
                }
                criteria = criteria.SubStringBeforeLast('OR');
                criteria += ') AND ';
              }
              statusDefined = true;
            } else if (
              field.fieldType == 'String' ||
              field.fieldType == 'TextArea'
            ) {
              /* END Exception */
              criteria += field.apiName + ' LIKE \'%' + value + '%\' AND ';
            } else if (field.fieldType == 'Date') {
              criteria +=
                field.apiName +
                ' = ' +
                ((DateTime) value).format('yyyy-MM-dd') +
                ' AND ';
            } else if (field.fieldType == 'DateTime') {
              criteria +=
                field.apiName +
                ' = ' +
                ((DateTime) value).format('yyyy-MM-dd\'T\'hh:mm:ss\'z\'') +
                ' AND ';
            } else if (field.fieldType == 'Time') {
              criteria +=
                field.apiName +
                ' = ' +
                ((DateTime) value).format('\'T\'hh:mm:ss\'z\'') +
                ' AND ';
            } else if (
              field.fieldType == 'Picklist' ||
              field.apiName == 'RecordTypeId'
            ) {
              criteria += '(';
              for (String option : String.valueOf(value).split(';')) {
                criteria += field.apiName + ' = \'' + String.escapeSingleQuotes(option) + '\' OR ';
              }
              criteria = criteria.SubStringBeforeLast('OR');
              criteria += ') AND ';
            } else if (
              field.fieldType == 'Currency' ||
              field.fieldType == 'Percent' ||
              field.fieldType == 'Boolean' ||
              field.fieldType == 'Integer' ||
              field.fieldType == 'Double' ||
              field.fieldType == 'Long'
            ) {
              criteria += field.apiName + ' = ' + value + ' AND ';
            } else {
              criteria += field.apiName + ' = \'' + value + '\' AND ';
            }
          }
        }
      }
    }

    if (filter != null) {
      Object startDate = filter.get('Date_de_debut_asset__c');
      Object endDate = filter.get('Date_de_fin_asset__c');
      if (startDate != null || endDate != null) {
        if (statusDefined && filter.get('Status_de_location__c') != 'Disponible;') {
          criteria += ' Id IN (SELECT Asset_assigne__c FROM Reservation__c ';
          if(startDate != null && endDate != null){
            criteria += 'WHERE (';
            criteria += '(Date_de_debut__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_debut__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += 'OR ';
            criteria += '(Date_de_fin__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          else if(startDate != null){
            criteria += 'WHERE (';
            criteria += 'Date_de_debut__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          else if(endDate != null){
            criteria += 'WHERE (';
            criteria += 'Date_de_fin__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ' ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          if (filter.get('Status_de_location__c') != 'Non disponible;') {
            criteria += ' AND (';
            for (
              String option : ((String) filter.get('Status_de_location__c'))
                .split(';')
            ) {
              criteria +=
                ' RecordType.Name LIKE \'%' +
                option.replace('En ', '') +
                '%\' OR ';
            }
            criteria = criteria.SubStringBeforeLast('OR');
            criteria += ')) AND ';
          } else {
            criteria += ') AND ';
          }
        } 
        else {
          criteria += ' Status_de_location__c != \'Cession\' AND ';
          criteria += ' Id NOT IN (SELECT Asset_assigne__c FROM Reservation__c ';
          if(startDate != null && endDate != null){
            criteria += 'WHERE (';
            criteria += '(Date_de_debut__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_debut__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += 'OR ';
            criteria += '(Date_de_fin__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          else if(startDate != null){
            criteria += 'WHERE (';
            criteria += 'Date_de_debut__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) startDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          else if(endDate != null){
            criteria += 'WHERE (';
            criteria += 'Date_de_fin__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ' ';
            criteria += 'OR ';
            criteria += '(Date_de_debut__c <= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ' AND Date_de_fin__c >= ' + ((DateTime) endDate).format('yyyy-MM-dd') + ') ';
            criteria += ')';
          }
          criteria += ') AND ';
        }
      } 
      else if (!statusDefined) {
        criteria += ' Status_de_location__c = \'Disponible\' AND ';
      }
    } else {
      criteria += ' Status_de_location__c = \'Disponible\' AND ';
      //criteria += ' Id NOT IN (SELECT Asset_assigne__c FROM Reservation__c) AND ';
    }

    //Result fields
    for (Field field : resultFields) {
      if (!query.contains(field.apiName)) {
        query += field.apiName + ', ';
      }
    }

    query = query.SubStringBeforeLast(',');

    //FROM
    query += ' FROM Asset';
    System.debug('#query without criteria: ' + query);

    //WHERE
    query += ' WHERE RecordTypeId = \'' + parcRTID + '\'';
    if (!String.isEmpty(criteria)) {
      criteria = criteria.SubStringBeforeLast('AND');
      query += ' AND ' + criteria + '';
    }
    System.debug('#criteria : ' + criteria);
    System.debug('#query with criteria: ' + query);

    //ORDER BY / LIMIT
    // query += ' ORDER BY Name LIMIT 30';

    return Database.query(query);
  }

  /**** PRODUCTS ****/

  @AuraEnabled
  public static List<Product2> getOptionProducts() {
      if(!Test.isRunningTest()){
          return [SELECT Id, Name, ProductCode
                  FROM Product2
                  WHERE Gamme__c LIKE 'Option%' 
                  AND Exclude_For_Container__c = false
                  AND isActive = true
                  ORDER BY Name];
      }
      else{
           return [SELECT Id, Name, ProductCode
                  FROM Product2
                  WHERE Gamme__c LIKE 'Option%'
                  AND Exclude_For_Container__c = false
                  ORDER BY Name];
      }
      
  }

  /**** ORDERS ****/

  @AuraEnabled
  public static Order getOrder(Id orderId) {
    return [SELECT Id, OrderNumber, AccountId, StartDate__c, EndDate__c, Type_de_location__c
            FROM Order
            WHERE Id = :orderId];      
  }

  /************************************* CREATE/UPDATE/DELETE *************************************/

  /*********** RESERVATION - GANTT ***********/

  @AuraEnabled
  public static Reservation__c updateReservationSObjects(EventCalendar eventCalendar, Id assetId) {
    System.debug('updateReservationSObjects - assetId: ' + assetId);
    System.debug('updateReservationSObjects - eventCalendar: ' + eventCalendar);

    Reservation__c reservation = new Reservation__c();
    System.debug('updateReservationSObjects - reservations: ' + reservation);
    reservation.Id = eventCalendar.eventId;
    reservation.Status__c = 'Planifiée';
    reservation.Date_de_debut__c = date.valueof(eventCalendar.Date_de_debut);
    reservation.Date_de_fin__c = date.valueof(eventCalendar.Date_de_fin);
    if (assetId != null) {
      reservation.Asset_assigne__c = assetId;
    }
    update reservation;
    return reservation;
  }

  @AuraEnabled
  public static void scheduleReservations(Id assetId, List<Id> reservationsId) {
    try {
      List<Reservation__c> reservations = new List<Reservation__c>();
      for (Id reservationId : reservationsId) {
        reservations.add(new Reservation__c(Id = reservationId, Asset_assigne__c = assetId, Status__c = 'Planifiée'));
      }
      update reservations;
    } 
    catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }



  /************************************* WRAPPER CLASSES *************************************/

  public class Field {
    @AuraEnabled
    public String apiName { get; set; }
    @AuraEnabled
    public String label { get; set; }
    @AuraEnabled
    public String fieldType { get; set; }
    @AuraEnabled
    public Boolean required { get; set; }
    @AuraEnabled
    public Integer length { get; set; }
    @AuraEnabled
    public List<Option> options { get; set; }
    @AuraEnabled
    public Object value { get; set; }
    @AuraEnabled
    public Boolean selected { get; set; }

    public Field(){}

    public Field(
      String apiName,
      String label,
      String fieldType,
      Boolean required,
      Integer length
    ) {
      this.apiName = apiName;
      this.label = label;
      this.fieldType = fieldType;
      this.required = required;
      this.length = length;
      this.selected = false;
    }

    public Field(
      String apiName,
      String label,
      String fieldType,
      Boolean required,
      Integer length,
      List<Option> options
    ) {
      this.apiName = apiName;
      this.label = label;
      this.fieldType = fieldType;
      this.required = required;
      this.length = length;
      this.options = options;
      this.selected = false;
    }
  }

  public class Option {
    @AuraEnabled
    public String value { get; set; }
    @AuraEnabled
    public String label { get; set; }
    @AuraEnabled
    public Boolean isDefault { get; set; }

    public Option(){}
    
    public Option(String value, String label) {
      this.value = value;
      this.label = label;
    }

    public Option(String value, String label, Boolean isDefault) {
      this.value = value;
      this.label = label;
      this.isDefault = isDefault;
    }
  }

  public class EventCalendar {
    @AuraEnabled
    public String eventId { get; set; }
    @AuraEnabled
    public String Date_de_debut { get; set; }
    @AuraEnabled
    public String Date_de_fin { get; set; }

    public EventCalendar(){}

    public EventCalendar(
      String eventId,
      String Date_de_debut,
      String fieldType
    ) {
      this.eventId = eventId;
      this.Date_de_debut = Date_de_debut;
      this.Date_de_fin = fieldType;
    }
  }


}