unpackaged/main/default/objects/Asset/fields/Agence__c.field-meta.xml
<CustomField>
    <fullName>Agence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parcs</relationshipLabel>
    <relationshipName>Parcs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Agence_proprietaire__c.field-meta.xml
<CustomField>
    <fullName>Agence_proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence propriétaire</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requêtes (Agence propriétaire)</relationshipLabel>
    <relationshipName>Requetes_agenceproprietaire</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FicheDepannageRIVController_TEST.cls
@isTest
private class FicheDepannageRIVController_TEST {
	static testMethod void testRedirectToWorkOrderItem()
    {
        //Mock
        Test.setMock(HttpCalloutMock.class, new FicheDepannageMock_TEST());
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_003',
                                                                   EndPoint__c = 'https://api-test.petitforestier.fr/api/services/SFDC/Report/RIV/v2.0/GetRIVReport',
                                                                   Methode__c = 'POST',
                                                                   UserName__c = 'mdm_sfdc',
                                                                   MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                                   ContentType__c = 'application/jsonl',
                                                                   ApplicationName__c = 'SFCD',
                                                                   Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr1;
        //DATA
        Account Account1 = Utils_TestMethods.createAccount('Account1',null,null, Label.CPT_RecordTypeId_CompteSite);
        insert Account1;
        Account Agence1 = Utils_TestMethods.CreateAgence('AgenceTEST');
        insert Agence1;
        Asset Parc1 = Utils_TestMethods.CreateAsset(Account1.id,Label.Parc_RecordTypeId);
        Parc1.Agence__c=Agence1.id;
        insert Parc1;
        Case Req1 = Utils_TestMethods.CreateCase_Depannage(Account1.id,Parc1.id,Agence1.id,Label.Case_RecordTypeID_Depannage_Vehicule);
        Req1.Agence_proprietaire__c=Agence1.id;
        insert Req1;
        WorkOrder WO1 = Utils_TestMethods.CreateWorkOrder_Depannage(Account1.id,Parc1.id,Agence1.id,Req1.id,Label.OT_RecordTypeId_Depannage_Vehicule);
        insert WO1;
        
        
        PageReference pref = Page.FicheDepannageRIV;
        pref.getParameters().put('id',WO1.Id);
        Test.setCurrentPage(pref);
        Test.startTest();
        ApexPages.StandardController con = new ApexPages.StandardController(WO1);
        FicheDepannageRIVController MyCon = new FicheDepannageRIVController(con);
        MyCon.RedirectToWorkOrderItem();
        Test.stopTest();
    }
}