unpackaged/main/default/objects/Asset/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Options installées sur le conteneur.</description>
    <label>Options</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Exclude_For_Container__c.field-meta.xml
<CustomField>
    <fullName>Exclude_For_Container__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates this product should not be used for container.</inlineHelpText>
    <label>Exclude For Container</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Gamme__c.field-meta.xml
<CustomField>
    <fullName>Gamme__c</fullName>
    <label>Gamme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Maxi-Special</fullName>
            </value>
            <value>
                <fullName>-70ºC</fullName>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Option assemblage</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Hors Standard</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OptionsPickerController.cls
public class OptionsPickerController {

    /************************************* READ *************************************/ 

    
    /*********** RECORDS  ***********/


    /**** PRODUCTS ****/

    @AuraEnabled
    public static List<Product2> getOptionProducts(){
        if(!Test.isRunningTest()){
            return [SELECT Id, Name, ProductCode
                    FROM Product2 
                    WHERE Gamme__c LIKE 'Option%' 
                    AND Exclude_For_Container__c = false
                    AND isActive = true
                    ORDER BY Name];
        }
        else{
            return [SELECT Id, Name, ProductCode
                    FROM Product2 
                    WHERE Gamme__c LIKE 'Option%'
                    AND Exclude_For_Container__c = false
                    ORDER BY Name];
        }
    }

    /**** ASSETS ****/

    @AuraEnabled
    public static Asset getOptionInstallees(Id assetId){
        return [SELECT Options__c
                FROM Asset 
                WHERE Id =: assetId];
    }


    /************************************* CREATE/UPDATE/DELETE *************************************/ 

    
    /***********  ***********/




}