unpackaged/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>Objet utilisé pour recueillir les devis SAP CPQ</description>
    <label>Devis SAP CPQ</label>
    <nameField>
        <label>Numéro du devis</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devis SAP CPQ</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Quote__c/fields/Date_de_validite_du_devis__c.field-meta.xml
<CustomField>
    <fullName>Date_de_validite_du_devis__c</fullName>
    <label>Date de validité du devis</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Quote__c/fields/Quote_Validity_Notification_Sent__c.field-meta.xml
<CustomField>
    <fullName>Quote_Validity_Notification_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Validity Notification</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/DateModificationHandler.cls
public class DateModificationHandler {
    public static void handleDateModification(List<Quote__c> newQuotes, Map<Id, Quote__c> oldMap) {
        List<Quote__c> quotesToUpdateWithNotification = new List<Quote__c>();
        
        for (Quote__c newQuote : newQuotes) {
            Quote__c oldQuote = oldMap.get(newQuote.Id);
            if (newQuote.Date_de_validite_du_devis__c != oldQuote.Date_de_validite_du_devis__c) {
                // Ajouter les enregistrements nécessitant une mise à jour à la liste
                newQuote.Quote_Validity_Notification_Sent__c = false;
                quotesToUpdateWithNotification.add(newQuote);
            }
        }
        
        // Effectuer l'update des enregistrements avec la notification
        if (!quotesToUpdateWithNotification.isEmpty()) {
            update quotesToUpdateWithNotification;
        }
    }
}