unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteDocument__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this Quote Document belongs.</description>
    <inlineHelpText>Devis auquel ce document de devis appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Documents</relationshipLabel>
    <relationshipName>R00N70000001lX7YEAU</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteDocument__c/fields/SBQQ__QuoteTemplate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote Template that generated this document.</description>
    <inlineHelpText>Modèle de devis qui a généré ce document.</inlineHelpText>
    <label>Quote Template</label>
    <referenceTo>SBQQ__QuoteTemplate__c</referenceTo>
    <relationshipLabel>Quote Documents</relationshipLabel>
    <relationshipName>Quote_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this group belongs.</description>
    <inlineHelpText>Devis auquel ce groupe appartient.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Line Groups</relationshipLabel>
    <relationshipName>LineItemGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/SBQQ__DocumentGeneratorController.cls
/*
Ce fichier est généré ne correspond pas au code source de cette
classe globale gérée.
Ce fichier en lecture seule affiche les constructeurs globaux,
les méthodes, les variables et les propriétés de la classe.
Pour activer le code à compiler, toutes les méthodes renvoient null.
*/
global class DocumentGeneratorController {
    global List<String> dimensionTables {
        get;
        set;
    }
    global List<SBQQ__QuoteLineGroup__c> dynamicGroupList {
        get;
        set;
    }
    global List<SBQQ__QuoteLineGroup__c> dynamicGroups {
        get;
        set;
    }
    global Boolean hasQuote {
        get;
    }
    global String language {
        get;
        set;
    }
    global Boolean lineItemsGrouped {
        get;
    }
    global Boolean lineItemsPrinted {
        get;
    }
    global String pageNumber {
        get;
        set;
    }
    global String pageNumberText {
        get;
        set;
    }
    global SBQQ__Quote__c quote {
        get;
        set;
    }
    global SObject quote2 {
        get;
        set;
    }
    global SBQQ__QuoteDocument__c quoteDocument {
        get;
        set;
    }
    global SObject quoteObject {
        get;
        set;
    }
    global SBQQ__Quote__c quoteRecord {
        get;
        set;
    }
    global Boolean quoteTotalsPrinted {
        get;
    }
    global SBQQ__TemplateSection__c section {
        get;
    }
    global String sectionIds {
        get;
    }
    global List<SBQQ__QuoteLineGroup__c> staticGroupList {
        get;
        set;
    }
    global List<SBQQ__QuoteLineGroup__c> staticGroups {
        get;
        set;
    }
    global SBQQ__QuoteTemplate__c template {
        get;
        set;
    }
    global SBQQ__QuoteTemplate__c templateRecord {
        get;
        set;
    }
    global String vfLanguage {
        get;
        set;
    }
    global DocumentGeneratorController() {

    }
    global String getCurrencyFormatPattern() {
        return null;
    }
    global String getFontFamily() {
        return null;
    }
    global Decimal getFontSize() {
        return null;
    }
    global List<SBQQ__QuoteLineGroup__c> getGroups() {
        return null;
    }
    global String getTableStyle() {
        return null;
    }
    global String getTextColor() {
        return null;
    }
    global List<SBQQ__QuoteLineGroup__c> getVisibleGroups() {
        return null;
    }
    global Map<String,Integer> getVisibleLineCountsByGroupName() {
        return null;
    }
}