unpackaged/main/default/objects/Contact/fields/InfluenceAchat__c.field-meta.xml
<CustomField>
    <fullName>InfluenceAchat__c</fullName>
    <label>Influence d&#39;achat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Décideur économique</fullName>
            </value>
            <value>
                <fullName>Décideur technique</fullName>
            </value>
            <value>
                <fullName>Sans influence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Rôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Détracteur</fullName>
            </value>
            <value>
                <fullName>Indifférent</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ServiceDepartement__c.field-meta.xml
<CustomField>
    <fullName>ServiceDepartement__c</fullName>
    <label>Service/département</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fonction__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Achat</fullName>
            </value>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Comptabilité</fullName>
            </value>
            <value>
                <fullName>Cuisine</fullName>
            </value>
            <value>
                <fullName>Direction générale</fullName>
            </value>
            <value>
                <fullName>Exploitation</fullName>
            </value>
            <value>
                <fullName>Financier</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technique</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/RoleContact__c.object-meta.xml
<CustomObject>
    <label>Rôle de contact</label>
    <nameField>
        <displayFormat>GF-RCN-{0000000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rôles de contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RoleContact__c/fields/CompteOpportunite__c.field-meta.xml
<CustomField>
    <fullName>CompteOpportunite__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte de l&#39;opportunité</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rôles des contacts</relationshipLabel>
    <relationshipName>ContactsOpportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.CompteOpportunite__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contact - Commercial, Contact - Responsable de parcs</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rôles des contacts</relationshipLabel>
    <relationshipName>Opportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/fields/InfluenceAchat__c.field-meta.xml
<CustomField>
    <fullName>InfluenceAchat__c</fullName>
    <label>Influence d&#39;achat</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Décideur économique</fullName>
            </value>
            <value>
                <fullName>Décideur technique</fullName>
            </value>
            <value>
                <fullName>Sans influence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rôles des contacts</relationshipLabel>
    <relationshipName>RolesContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Rôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Avis de paiement</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Comptabilité</fullName>
            </value>
            <value>
                <fullName>Donneur d&#39;ordre</fullName>
            </value>
            <value>
                <fullName>Exploitant</fullName>
            </value>
            <value>
                <fullName>Facturation</fullName>
            </value>
            <value>
                <fullName>Facture dématerialisée</fullName>
            </value>
            <value>
                <fullName>Livré</fullName>
            </value>
            <value>
                <fullName>Payeur</fullName>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>Relance KM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/fields/ServiceDepartement__c.field-meta.xml
<CustomField>
    <fullName>ServiceDepartement__c</fullName>
    <label>Service/département</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Achat</fullName>
            </value>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Comptabilité</fullName>
            </value>
            <value>
                <fullName>Cuisine</fullName>
            </value>
            <value>
                <fullName>Direction générale</fullName>
            </value>
            <value>
                <fullName>Exploitation</fullName>
            </value>
            <value>
                <fullName>Financier</fullName>
            </value>
            <value>
                <fullName>Logistique</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technique</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/VFE13_ContactRole.cls
public with sharing class VFE13_ContactRole {
    
    public RoleContact__c rc {get; set;}
    public list<Contact> c {get; set;}
    public string subtitle {get; set;}
    
    public VFE13_ContactRole(ApexPages.StandardController controller) {
        rc=(RoleContact__c)controller.getRecord();
        if(rc.Id!=null){
            rc=[select Name, Opportunite__c, CompteOpportunite__c, Contact__c, ServiceDepartement__c, InfluenceAchat__c, Role__c, Commentaires__c
                from RoleContact__c
                where Id=:rc.Id];
            subtitle=rc.Name;
        }
        else{
            rc.CompteOpportunite__c=[select AccountId from Opportunity where Id=:rc.Opportunite__c].AccountId;
            subtitle=Label.RDC_VFPSubtitle_NouveauRoleContact;
        }
    }
    
    public void selectContact(){
        c=[select ServiceDepartement__c, InfluenceAchat__c, Role__c
           from Contact
           where Id=:rc.Contact__c];
        if(c.size()>0){
            rc.ServiceDepartement__c=c[0].ServiceDepartement__c;
            rc.InfluenceAchat__c=c[0].InfluenceAchat__c;
            rc.Role__c=c[0].Role__c;
        }
    }
    
    public PageReference saveContact(){
        try{
            if(rc.Id==null){
                insert rc;
            }
            else{
                update rc;
            }
            PageReference p=new PageReference('/'+rc.Id);
            p.setRedirect(true);
            return p;
        }catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').substringBeforeLast(':'));
            if(ApexPages.getMessages().size()==0)
            {    ApexPages.addmessage(myMsg);    }
        }
        return null;
    }
    
    public PageReference saveAndNewContact(){
        try{
            if(rc.Id==null){
                insert rc;
            }
            else{
                update rc;
            }
            
            PageReference p=new PageReference('/apex/VFP13_ContactRole?'+Label.RCN_OppId_Id+'='+rc.Opportunite__c+'&scontrolCaching=1&retURL=%2F'+rc.Opportunite__c+'&sfdc.override=1');
            p.setRedirect(true);
            return p;
        }catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').substringBeforeLast(':'));
            if(ApexPages.getMessages().size()==0)
            {    ApexPages.addmessage(myMsg);    }
        }
        return null;
    }
    
}