unpackaged/main/default/objects/Google_Callr_Services_Params__c/Google_Callr_Services_Params__c.object-meta.xml
<CustomObject>
    <label>Google Callr Services Params</label>
    <nameField>
        <label>Nom de Google_Callr_Services_Param</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Callr Services Params</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/Destination_Param__c.field-meta.xml
<CustomField>
    <fullName>Destination_Param__c</fullName>
    <label>Destination Param</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/EstimatedTravelTime_Sec__c.field-meta.xml
<CustomField>
    <fullName>EstimatedTravelTime_Sec__c</fullName>
    <label>EstimatedTravelTime Sec</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/Origine_Param__c.field-meta.xml
<CustomField>
    <fullName>Origine_Param__c</fullName>
    <label>Origine_Param</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/Recipient_Phone__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Phone__c</fullName>
    <label>Recipient_Phone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/RecordId_1__c.field-meta.xml
<CustomField>
    <fullName>RecordId_1__c</fullName>
    <label>RecordId_1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/RecordId_2__c.field-meta.xml
<CustomField>
    <fullName>RecordId_2__c</fullName>
    <label>RecordId_2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/SMS_Message__c.field-meta.xml
<CustomField>
    <fullName>SMS_Message__c</fullName>
    <label>SMS_Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/SMS_Sender__c.field-meta.xml
<CustomField>
    <fullName>SMS_Sender__c</fullName>
    <label>SMS_Sender</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Google_Callr_Services_Params__c/fields/SMSType__c.field-meta.xml
<CustomField>
    <fullName>SMSType__c</fullName>
    <label>SMSType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/EstimatedTravelTime_TEST.cls
@isTest
public class EstimatedTravelTime_TEST 
{
	// Test the success (200) case of the the Post request
	static testMethod void sendSMSWithSuccess()
    {
        //Mock
        Test.setMock(HttpCalloutMock.class, new EstimatedTravelTimeMock_TEST(200));
        List<Google_Callr_Services_Params__c> GoogleCallrServicesParamsRecords = Test.loadData(Google_Callr_Services_Params__c.sObjectType, 'GoogleCallrServicesParamsRecordsFile');
        List<Case> CaseRecords = Test.loadData(Case.sObjectType, 'CaseRecordFile');
        Test.startTest();
     	EstimatedTravelTime.getEstimatedTravelTime(GoogleCallrServicesParamsRecords[0].Origine_Param__c, GoogleCallrServicesParamsRecords[0].Origine_Param__c, GoogleCallrServicesParamsRecords[0].RecordId_1__c, GoogleCallrServicesParamsRecords[0].RecordId_2__c, CaseRecords[0].Id, GoogleCallrServicesParamsRecords[0].Recipient_Phone__c, GoogleCallrServicesParamsRecords[0].SMS_Sender__c, GoogleCallrServicesParamsRecords[0].SMS_Message__c, GoogleCallrServicesParamsRecords[0].SMSType__c);
        Test.stopTest();    
    }
    
    // Test the unsuccess (404 or other Status) case of the the Post request
    static testMethod void sendSMSWithUnsuccess()
    {
       //Mock
        Test.setMock(HttpCalloutMock.class, new EstimatedTravelTimeMock_TEST(404));
        List<Google_Callr_Services_Params__c> GoogleCallrServicesParamsRecords = Test.loadData(Google_Callr_Services_Params__c.sObjectType, 'GoogleCallrServicesParamsRecordsFile');
        List<Case> CaseRecords = Test.loadData(Case.sObjectType, 'CaseRecordFile');
        Test.startTest();
        EstimatedTravelTime.getEstimatedTravelTime(GoogleCallrServicesParamsRecords[0].Origine_Param__c, GoogleCallrServicesParamsRecords[0].Origine_Param__c, GoogleCallrServicesParamsRecords[0].RecordId_1__c, GoogleCallrServicesParamsRecords[0].RecordId_2__c, CaseRecords[0].Id, GoogleCallrServicesParamsRecords[0].Recipient_Phone__c, GoogleCallrServicesParamsRecords[0].SMS_Sender__c, GoogleCallrServicesParamsRecords[0].SMS_Message__c, GoogleCallrServicesParamsRecords[0].SMSType__c);
        Test.stopTest();
    }
    
    @IsTest(SeeAllData=true)
    private static void testSchedulable() 
    {        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EstimatedTravelTimeMock_TEST(200));
        List<Case> CaseRecords = Test.loadData(Case.sObjectType, 'CaseRecordFile');
        List<Google_Callr_Services_Params__c> GoogleCallrServicesParamsRecords = Test.loadData(Google_Callr_Services_Params__c.sObjectType, 'GoogleCallrServicesParamsRecordsFile');
		String name1 = EstimatedTravelTime.getUUID();
		String name2 = EstimatedTravelTime.getUUID();
        EstimatedTravelTime.scheduleThis ( GoogleCallrServicesParamsRecords[0].EstimatedTravelTime_Sec__c.intValue(),  GoogleCallrServicesParamsRecords[0].RecordId_1__c,  GoogleCallrServicesParamsRecords[0].RecordId_2__c, CaseRecords[0].Id, GoogleCallrServicesParamsRecords[0].Origine_Param__c, GoogleCallrServicesParamsRecords[0].Destination_Param__c, '10min', name1, 40, GoogleCallrServicesParamsRecords[0].Recipient_Phone__c, GoogleCallrServicesParamsRecords[0].SMS_Sender__c, GoogleCallrServicesParamsRecords[0].SMS_Message__c, GoogleCallrServicesParamsRecords[0].SMSType__c);
        Test.stopTest();
    }  
}