unpackaged/main/default/objects/SalesAreaData__c/SalesAreaData__c.object-meta.xml
<CustomObject>
    <label>Vue Commerciale Client</label>
    <nameField>
        <label>Nom de la Vue Commerciale Client</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vues Commerciales Client</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SalesAreaData__c/fields/ManagerCommercial__c.field-meta.xml
<CustomField>
    <fullName>ManagerCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vues_Commerciales_Client1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/Secteur__c.field-meta.xml
<CustomField>
    <fullName>Secteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secteur</label>
    <referenceTo>Secteur__c</referenceTo>
    <relationshipLabel>Vues Commerciales Client</relationshipLabel>
    <relationshipName>SalesAreaData</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SalesAreaData__c/fields/TerritorialCommercial__c.field-meta.xml
<CustomField>
    <fullName>TerritorialCommercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial / KAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>VuesCommercialesClientUserCommercial</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Secteur__c/Secteur__c.object-meta.xml
<CustomObject>
    <label>Secteur</label>
    <nameField>
        <label>Nom du Secteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Secteur__c/fields/Commercial__c.field-meta.xml
<CustomField>
    <fullName>Commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial / KAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Representants_Territoires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Secteur__c/fields/Manager_Commercial__c.field-meta.xml
<CustomField>
    <fullName>Manager_Commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Secteurs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchUpdateSalesAreaData.cls
public class BatchUpdateSalesAreaData implements Database.Batchable<SObject>, Database.Stateful {
    private Set<Id> secteurIds;
    private Map<Id, Secteur__c> secteurMap;

    // Constructor to initialize the Secteur IDs
    public BatchUpdateSalesAreaData(Set<Id> secteurIds) {
        this.secteurIds = secteurIds;
    }

    // Start method to query SalesAreaData__c records
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Query and cache Secteur__c records
        secteurMap = new Map<Id, Secteur__c>([
            SELECT Id, Commercial__c, Manager_Commercial__c
            FROM Secteur__c
            WHERE Id IN :secteurIds
        ]);

        // Query related SalesAreaData__c records
        return Database.getQueryLocator([
            SELECT Id, Secteur__c
            FROM SalesAreaData__c
            WHERE Secteur__c IN :secteurIds
        ]);
    }

    // Execute method to process each batch of records
    public void execute(Database.BatchableContext bc, List<SalesAreaData__c> scope) {
        List<SalesAreaData__c> recordsToUpdate = new List<SalesAreaData__c>();

        for (SalesAreaData__c salesData : scope) {
            Secteur__c secteur = secteurMap.get(salesData.Secteur__c);
            if (secteur != null) {
                salesData.TerritorialCommercial__c = secteur.Commercial__c;
                salesData.ManagerCommercial__c = secteur.Manager_Commercial__c;
                recordsToUpdate.add(salesData);
            }
        }

        if (!recordsToUpdate.isEmpty()) {
            update recordsToUpdate;
        }
    }

    // Finish method (optional)
    public void finish(Database.BatchableContext bc) {
        // Send email when Batch finish
         // Préparer et envoyer l'email
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {'mhassouni@petitforestier.fr'}; 
            mail.setToAddresses(toAddresses);
            mail.setSubject('Batch Process Completed: BatchUpdateSalesAreaData');
            
            // Construire le corps de l'email
            String emailBody = 'The batch BatchUpdateSalesAreaData has finished:\n\n';
    
            mail.setPlainTextBody(emailBody);
            
            // Envoyer l'email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}