unpackaged/main/default/objects/Facture_vehicule__c/Facture_vehicule__c.object-meta.xml
<CustomObject>
    <label>Facture véhicule</label>
    <nameField>
        <displayFormat>FV-{0000}</displayFormat>
        <label>Numéro de Facture véhicule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factures véhicule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Facture_vehicule__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factures véhicule</relationshipLabel>
    <relationshipName>Factures_vehicule</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Facture_vehicule__c/fields/Numero_de_facture_IGLOO__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_facture_IGLOO__c</fullName>
    <label>Numéro de facture IGLOO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FactureVehiculeToDownloadController_TEST.cls
@isTest
public class FactureVehiculeToDownloadController_TEST {

    // Test the success (200) case of the the GET request
    
	static testMethod void GetFactureVehiculeWithSuccess()
    {
        //Mock
        Test.setMock(HttpCalloutMock.class, new FactureVehiculeToDownloadMock_TEST(200));
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_010',
                                                                   EndPoint__c = 'https://api.petitforestier.fr/api/services/SFDC/IGLOOPDFCommunity/GetFacture/',
                                                                   Methode__c = 'GET',
                                                                   UserName__c = 'mdm_sfdc',
                                                                   MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                                   ContentType__c = 'application/xml',
                                                                   ApplicationName__c = 'SFCD',
                                                                   Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr1;
		PageReference pref = Page.FactureVehiculeToDownload;
        
        //data
        Account AC = Utils_TestMethods.createAccount('Test','test',null,Label.CPT_RecordTypeId_CompteClient);
        insert AC;
        Facture_vehicule__c FV = new Facture_vehicule__c();
        FV.Numero_de_facture_IGLOO__c = '123456789';
        FV.Compte__c=AC.id;
        insert FV;
        pref.getParameters().put('id',FV.Id);
        Test.setCurrentPage(pref);
        Test.startTest();
        FactureVehiculeToDownloadController MyCon = new FactureVehiculeToDownloadController();
        MyCon.getDocument();
        Test.stopTest();
    }
    
    // Test the unsuccess (404 or other Status) case of the the GET request
    
    static testMethod void GetFactureVehiculeWithUnsuccess()
    {
        //Mock
		Test.setMock(HttpCalloutMock.class, new FactureVehiculeToDownloadMock_TEST(404));
        WSParametreRequete__c wspr1 = new WSParametreRequete__c(Name='WS_Param_010',
                                                                   EndPoint__c = 'https://api.petitforestier.fr/api/services/SFDC/IGLOOPDFCommunity/GetFacture/	',
                                                                   Methode__c = 'GET',
                                                                   UserName__c = 'mdm_sfdc',
                                                                   MotDePasse__c = '5:?MWWE6-tm9fcW4',
                                                                   ContentType__c = 'application/xml',
                                                                   ApplicationName__c = 'SFCD',
                                                                   Authorization__c = 'Basic bWRtX3NmZGM6NTo/TVdXRTYtdG05ZmNXNA==');
        insert wspr1;
       
        PageReference pref = Page.FactureVehiculeToDownload;
        
        //data
        Account AC = Utils_TestMethods.createAccount('Test','test',null,Label.CPT_RecordTypeId_CompteClient);
        insert AC;
        Facture_vehicule__c FV = new Facture_vehicule__c();
        FV.Numero_de_facture_IGLOO__c = '123456789';
        FV.Compte__c=AC.id;
        insert FV;
        pref.getParameters().put('id',FV.Id);
        Test.setCurrentPage(pref);
        
        
        Test.startTest();
        FactureVehiculeToDownloadController MyCon = new FactureVehiculeToDownloadController();
        MyCon.getDocument();
        Test.stopTest();
    }
}