unpackaged/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Objet réservation de containers avec leurs options respectives.</description>
    <label>Réservation</label>
    <nameField>
        <displayFormat>RESA - {0}</displayFormat>
        <label>Numéro de réservation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reservation__c/fields/Asset_assigne__c.field-meta.xml
<CustomField>
    <fullName>Asset_assigne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conteneur sélectionné</description>
    <label>Asset assigné</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Réservations</relationshipLabel>
    <relationshipName>R_servations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Réservations (Client)</relationshipLabel>
    <relationshipName>R_servation</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de debut</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <description>Date de fin de location</description>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Description_Gantt__c.field-meta.xml
<CustomField>
    <fullName>Description_Gantt__c</fullName>
    <description>Used for Fleet Management Gantt</description>
    <formula>&#39;&lt;p&gt;&#39; &amp;  IF(TEXT(Status__c) != null, TEXT(Status__c), &#39;&#39;) &amp; &#39;&lt;/p&gt;&#39; 
&amp; &#39;&lt;p&gt;&#39; &amp; Type__c &amp; &#39;&lt;/p&gt;&#39;
&amp; &#39;&lt;p&gt;&#39; &amp; IF(Type_de_conteneur__c != null, Type_de_conteneur__r.Name, &#39;&#39;) &amp; &#39;&lt;/p&gt;&#39; 
&amp; &#39;&lt;p&gt;&#39; &amp;  Shipping_City__c &amp; &#39;&lt;/p&gt;&#39;</formula>
    <label>Description (Gantt)</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de planification</fullName>
                <default>true</default>
                <label>En attente de planification</label>
            </value>
            <value>
                <fullName>Planifiée</fullName>
            </value>
            <value>
                <fullName>Confirmée</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Type_Atelier__c.field-meta.xml
<CustomField>
    <fullName>Type_Atelier__c</fullName>
    <label>Type d&#39;Atelier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avant location</fullName>
                <label>Préparation départ container | PTI</label>
            </value>
            <value>
                <fullName>Apres location</fullName>
                <label>Retour location (Estimation)</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
            <value>
                <fullName>Gros Travaux</fullName>
            </value>
            <value>
                <fullName>Préparation Saison</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reservation__c/fields/Type_de_transport__c.field-meta.xml
<CustomField>
    <fullName>Type_de_transport__c</fullName>
    <label>Type de transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transport Aller vers client</fullName>
            </value>
            <value>
                <fullName>Transport Retour vers atelier</fullName>
                <label>Transport Retour vers le dépôt</label>
            </value>
            <value>
                <fullName>Intersites</fullName>
            </value>
            <value>
                <fullName>Fabrication</fullName>
            </value>
            <value>
                <fullName>Echange technique</fullName>
            </value>
            <value>
                <fullName>Déplacement container client</fullName>
            </value>
            <value>
                <fullName>Transport divers</fullName>
            </value>
            <value>
                <fullName>Transport inutile</fullName>
            </value>
            <value>
                <fullName>Transport Amont</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AssetCalendarController.cls
public class AssetCalendarController {
  
  @AuraEnabled
  public static List<Reservation__c> getReservations(Id assetId) {
    return [
      SELECT
        Id,
        Name,
        Client__c,
        Client__r.Name,
        Date_de_debut__c,
        Date_de_fin__c,
        Description_Gantt__c,
        RecordType.Name,
        RecordType.DeveloperName,
        Type_Atelier__c,
        Type_de_transport__c,
        Status__c
      FROM Reservation__c
      WHERE Asset_Assigne__c = :assetId
      LIMIT 5000
    ];
  }
    
  @AuraEnabled
  public static List<Holiday> getHolidays() {
    return [SELECT ActivityDate, Name FROM Holiday];
  }
}