unpackaged/main/default/objects/blng__CreditNote__c/blng__CreditNote__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/blng__CreditNote__c/fields/Facture_Genere__c.field-meta.xml
<CustomField>
    <fullName>Facture_Genere__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facture Générée</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/blng__CreditNote__c/fields/templateId__c.field-meta.xml
<CustomField>
    <fullName>templateId__c</fullName>
    <formula>&#39;a2D7T000000TN81UAG&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>templateId</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GenDocCreditNotesFromAccount.cls
public class GenDocCreditNotesFromAccount {
	public Account acc { get; set; }
    public List<blng__CreditNote__c> creditNotes { get; set; }
    public Boolean allDocsAlreadyGenerated { get; set; }
    public GenDocCreditNotesFromAccount(ApexPages.StandardController stdController) {
        allDocsAlreadyGenerated=false;
        String id = ApexPages.currentPage().getParameters().get('id');
        creditNotes = [SELECT id,blng__Account__c,templateId__c,Facture_Genere__c   FROM blng__CreditNote__c where blng__Account__c=:id];
        integer nombreTotalDesFactureGenere=0;
        for(blng__CreditNote__c creditNote:creditNotes){
            system.debug('before condition');
            if(creditNote.Facture_Genere__c){
                nombreTotalDesFactureGenere++;
            }
        }
        if(nombreTotalDesFactureGenere==creditNotes.size()){
            allDocsAlreadyGenerated=true;
        }
    }
}