unpackaged/main/default/objects/Calendrier_Astreinte__c/Calendrier_Astreinte__c.object-meta.xml
<CustomObject>
    <label>Calendrier Astreinte</label>
    <nameField>
        <label>Calendrier Astreinte Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendriers Astreintes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Calendrier_Astreinte__c/fields/Agence_PF__c.field-meta.xml
<CustomField>
    <fullName>Agence_PF__c</fullName>
    <label>Agence PF</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agence PF</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calendriers Astreintes</relationshipLabel>
    <relationshipName>Calendriers_Astreintes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Calendrier_Astreinte__c/fields/Numero_semaine_dates__c.field-meta.xml
<CustomField>
    <fullName>Numero_semaine_dates__c</fullName>
    <formula>&quot;Semaine &quot; &amp; text(N_semaine__c)&amp; &quot;&quot; 
&amp; &quot; - &quot; &amp;&quot;Du &quot;&amp; Text(Day(Date_de_debut__c)) &amp; &quot;/&quot; &amp; text(month(Date_de_debut__c)) &amp; &quot;/&quot; &amp; text(YEAR(Date_de_debut__c))
&amp;&quot; Au &quot; &amp; text(Day(Date_de_fin__c)) &amp; &quot;/&quot; &amp; text(month(Date_de_fin__c)) &amp; &quot;/&quot; &amp; text(YEAR(Date_de_fin__c))</formula>
    <label>Numéro semaine - dates</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Agence_PF__c.field-meta.xml
<CustomField>
    <fullName>Agence_PF__c</fullName>
    <description>Agence PF de l&#39;opportunité 
GFC-489</description>
    <formula>text( Opportunity.AgencePF__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agence PF</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/RCSC_GetCalendrierAstreinte.cls
public with sharing class RCSC_GetCalendrierAstreinte {

    @AuraEnabled
    
    public static List<Calendrier_Astreinte__c> listWeeks(String Id){
        List<Calendrier_Astreinte__c> result = [SELECT Id, Numero_semaine_dates__c
        FROM Calendrier_Astreinte__c
        WHERE Agence_PF__c =: Id AND Date_de_fin__c >= TODAY ORDER BY Date_de_debut__c,Date_de_fin__c ASC];
        return result;
    }
}