unpackaged/main/default/objects/ActeurOpportunite__c/ActeurOpportunite__c.object-meta.xml
<CustomObject>
    <label>Acteur de l&#39;opportunité</label>
    <nameField>
        <displayFormat>GF-ACT-{0000000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acteurs de l&#39;opportunité</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ActeurOpportunite__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Acteurs de l&#39;opportunité</relationshipLabel>
    <relationshipName>Acteurs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ActeurOpportunite__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Rôle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Concurrent</fullName>
            </value>
            <value>
                <fullName>Fournisseur</fullName>
            </value>
            <value>
                <fullName>Partenaire</fullName>
            </value>
            <value>
                <fullName>Utilisateur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bypass__c/Bypass__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass</label>
</CustomObject>

unpackaged/main/default/objects/Bypass__c/fields/BypassTriggers__c.field-meta.xml
<CustomField>
    <fullName>BypassTriggers__c</fullName>
    <inlineHelpText>Saisissez les noms des classes que vous voulez désactiver, séparés par un point-virgule.</inlineHelpText>
    <label>Bypass Triggers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bypass__c/fields/OldBypassTriggersValidationRules__c.field-meta.xml
<CustomField>
    <fullName>OldBypassTriggersValidationRules__c</fullName>
    <label>TECHOld Bypass Triggers Validation Rules</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sans_Activites_En_Cours__c.field-meta.xml
<CustomField>
    <fullName>Sans_Activites_En_Cours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sans Activités en cours</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Sans_Activites_Terminees__c.field-meta.xml
<CustomField>
    <fullName>Sans_Activites_Terminees__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sans Activités terminées</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Batch_Flags_Opp.cls
//Batch Nocturne
//Permet de marquer les flags suivants:
//Opportunités Sans Activités en cours
//Opportunités Sans Activités Terminées



global class Batch_Flags_Opp implements Database.Batchable<sObject>{
    //Lists finals
   
    
    List<Opportunity> Opp_S_Act_Encours = new List<Opportunity>();//Opportunités sans activités en cours
    List<Opportunity> Opp_S_Act_Terminees = new List<Opportunity>();//Opportunités sans activités terminées
    //List<Opportunity> Opp_S_Concurrent =  new List<Opportunity>();//Opportunités sans concurrent
    //List<Opportunity> Opp_A_Concurrent =  new List<Opportunity>();//Opportunités avec concurrent
    
    //start
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        //Bypass Validation Rules on Running User////////////////////////////
        Bypass__c bypassSetting=Bypass__c.getInstance(UserInfo.getUserId());
        if (bypassSetting==null){
            bypassSetting=new Bypass__c();
            bypassSetting.OldBypassTriggersValidationRules__c = 'false:';
        }
        else{
            if(bypassSetting.BypassTriggers__c != 'Batch_Flags_Opp' || bypassSetting.BypassValidationRules__c != true)
            {
                bypassSetting.OldBypassTriggersValidationRules__c = bypassSetting.BypassValidationRules__c+':'+bypassSetting.BypassTriggers__c;
            }
        }
        bypassSetting.BypassTriggers__c = 'Batch_Flags_Opp';
        bypassSetting.BypassValidationRules__c = true;
        upsert bypassSetting;
        
        //////////////////////////////
        //Queries
       ///////////////////////////////
        //Opp_S_Concurrent = [SELECT ID FROM opportunity WHERE ID NOT IN(SELECT Opportunite__c FROM ActeurOpportunite__c where Role__c='Concurrent')];
        //Opp_A_Concurrent = [SELECT ID FROM opportunity WHERE ID IN(SELECT Opportunite__c FROM ActeurOpportunite__c where Role__c='Concurrent')];
        
        return database.getQueryLocator([SELECT Id, (SELECT Id FROM OpenActivities),(SELECT Id FROM ActivityHistories)FROM Opportunity]);
       
  
    }
    //execute
    global void execute(database.BatchableContext BC,List<Opportunity> scope)
    {
        System.Debug('>>>> Batch_Flags Start execute <<<<');
          
        //////////////////////////////
        //Execution
       ///////////////////////////////
       
        
//treatement of Opportunities activities
////
        for(Opportunity Opp: scope)
        { 
            //Opportunités:Activités en cours
            if(Opp.OpenActivities.size()==0)
            {
                Opp.Sans_Activites_En_Cours__c =true;
            }
            else
            {
                Opp.Sans_Activites_En_Cours__c =false;                
            }
            //opportunités:Activités terminées
            if(Opp.ActivityHistories.size()==0)
            {
                Opp.Sans_Activites_Terminees__c=true;
            }
            else
            {
                 Opp.Sans_Activites_Terminees__c=false;
            }
        }


                
        //////////////////////////
        //Updates
       ///////////////////////////////

         try{
        update scope;
        }catch(exception e){System.debug(e);}
       
  
       
    }

    //finish 
    global void finish(Database.BatchableContext BC){
         Bypass__c bypassSetting=Bypass__c.getInstance(UserInfo.getUserId());
            if (bypassSetting!=null && bypassSetting.OldBypassTriggersValidationRules__c!=null){
                bypassSetting.BypassTriggers__c = bypassSetting.OldBypassTriggersValidationRules__c.split(':')[1];
                if(bypassSetting.BypassTriggers__c=='null')
                {
                    bypassSetting.BypassTriggers__c = null;
                }
                bypassSetting.BypassValidationRules__c = boolean.valueof(bypassSetting.OldBypassTriggersValidationRules__c.split(':')[0]);
                bypassSetting.OldBypassTriggersValidationRules__c=null;
                upsert bypassSetting;
            }
         System.Debug('>>>> Batch_Flags End execute <<<<');
    }






















}