unpackaged/main/default/objects/Opportunity/fields/CodePF__c.field-meta.xml
<CustomField>
    <fullName>CodePF__c</fullName>
    <label>Code PF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Quantite__c.field-meta.xml
<CustomField>
    <fullName>Quantite__c</fullName>
    <label>Quantité</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SousCategorie__c.field-meta.xml
<CustomField>
    <fullName>SousCategorie__c</fullName>
    <label>Sous-catégorie</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Categorie__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>V1M</fullName>
            </value>
            <value>
                <fullName>V3M</fullName>
            </value>
            <value>
                <fullName>V3X</fullName>
            </value>
            <value>
                <fullName>V3E</fullName>
            </value>
            <value>
                <fullName>V3P</fullName>
            </value>
            <value>
                <fullName>V3I</fullName>
            </value>
            <value>
                <fullName>V3S</fullName>
            </value>
            <value>
                <fullName>V5M</fullName>
            </value>
            <value>
                <fullName>V5E</fullName>
            </value>
            <value>
                <fullName>V5X</fullName>
            </value>
            <value>
                <fullName>V5P</fullName>
            </value>
            <value>
                <fullName>V5I</fullName>
            </value>
            <value>
                <fullName>V5S</fullName>
            </value>
            <value>
                <fullName>V9M</fullName>
            </value>
            <value>
                <fullName>V9MH</fullName>
            </value>
            <value>
                <fullName>V9X</fullName>
            </value>
            <value>
                <fullName>V9XH</fullName>
            </value>
            <value>
                <fullName>V9E</fullName>
            </value>
            <value>
                <fullName>V9P</fullName>
            </value>
            <value>
                <fullName>V9I</fullName>
            </value>
            <value>
                <fullName>V9IH</fullName>
            </value>
            <value>
                <fullName>V9S</fullName>
            </value>
            <value>
                <fullName>V11M</fullName>
            </value>
            <value>
                <fullName>V11MH</fullName>
            </value>
            <value>
                <fullName>V11X</fullName>
            </value>
            <value>
                <fullName>V11XH</fullName>
            </value>
            <value>
                <fullName>V11E</fullName>
            </value>
            <value>
                <fullName>V11P</fullName>
            </value>
            <value>
                <fullName>V11PH</fullName>
            </value>
            <value>
                <fullName>V11I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SousFamille__c.field-meta.xml
<CustomField>
    <fullName>SousFamille__c</fullName>
    <label>Sous-famille</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TypeProduits__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>N/A (Carrosseries)</fullName>
            </value>
            <value>
                <fullName>BAC</fullName>
            </value>
            <value>
                <fullName>SALON</fullName>
            </value>
            <value>
                <fullName>VITRINE</fullName>
            </value>
            <value>
                <fullName>CF</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P (Frigo)</fullName>
            </value>
            <value>
                <fullName>S (Frigo)</fullName>
            </value>
            <value>
                <fullName>T (Frigo)</fullName>
            </value>
            <value>
                <fullName>V (Frigo)</fullName>
            </value>
            <value>
                <fullName>P (Sec)</fullName>
            </value>
            <value>
                <fullName>T (Sec)</fullName>
            </value>
            <value>
                <fullName>V (Sec)</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>V (Dry)</fullName>
            </value>
            <value>
                <fullName>L (Dry)</fullName>
            </value>
            <value>
                <fullName>C (Dry)</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>S (Dry)</fullName>
            </value>
            <value>
                <fullName>MEDFOOD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Type_Location__c.field-meta.xml
<CustomField>
    <fullName>Type_Location__c</fullName>
    <description>Indiquez la durée estimée du contrat.</description>
    <inlineHelpText>Il s&#39;agit d&#39;une estimation de la durée du contrat. Elle permet de simplifier les processus selon la durée.</inlineHelpText>
    <label>Type Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_Location</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <label>Type de contrat</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TypeProduits__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>LD</fullName>
                <default>true</default>
                <label>LD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TypeOpportunite__c.field-meta.xml
<CustomField>
    <fullName>TypeOpportunite__c</fullName>
    <label>Type d&#39;opportunité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCT</fullName>
                <color>#0B6FCE</color>
                <label>NCT</label>
            </value>
            <value>
                <fullName>SUP</fullName>
                <color>#A845DC</color>
                <label>SUP</label>
            </value>
            <value>
                <fullName>RNV</fullName>
                <color>#E27001</color>
                <label>RNV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Type_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Courte Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Moyenne Durée</fullName>
    </customValue>
    <customValue>
        <fullName>Longue Durée</fullName>
    </customValue>
    <description>Type de Location (CD, CMD, LD)</description>
    <masterLabel>Type Location</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AP04Opportunite.cls
/*
*le nomde l'opportunite de type mono doit etre genere en combinant 4 champs
* @Author Ali Naji
* @TestClass AP04Opportunite_TEST
* @CodeCoverage 100%
*/

public class AP04Opportunite
{
    public static void GenerateOppName(list<opportunity> opportunities)
    {
        set<string> AccountIDs = new set<string>();

        for(Opportunity o : opportunities)
        {
            AccountIDs.add(o.AccountId);
        }
        map<string,Account> AccountsMap =new map<string,Account>([  SELECT Name 
                                                                    FROM Account 
                                                                    WHERE Id in: AccountIDs ]);
                
        for(opportunity o : opportunities)
        {
            string s1='';
            
            if(AccountsMap.get(o.AccountId)!=null)
            {
                s1= AccountsMap.get(o.AccountId).Name;
            }
            s1 = s1.replaceAll('[ \\\\\t\r\n\f0-9!"#$%&\'()*+,./:;<=>?@\\^_`{|}~-]','');
            s1 = s1.left(10);
            
            string comb;
            if(o.TypeOpportunite__c!=null && o.Quantite__c!=null && AccountsMap.get(o.accountid).name!=null )
            {
                if(o.CodePF__c!=null)
                {
                    comb = String.valueOf(o.TypeOpportunite__c)+'_' + String.valueOf(o.Quantite__c)+'_'+String.valueOf(o.CodePF__c)+'_'+s1;
                    o.Name=comb;
                }
                else if(o.SousCategorie__c!=null)
                {
                    comb = String.valueOf(o.TypeOpportunite__c)+'_' + String.valueOf(o.Quantite__c)+'_'+String.valueOf(o.SousCategorie__c)+'_'+s1;
                    o.Name=comb;
                }
            }
        }
    }   
    
    
    public static void GenerateOppName_Container(list<opportunity> opportunities)
    {
        set<string> AccountIDs = new set<string>();

        for(Opportunity o : opportunities)
        {
            AccountIDs.add(o.AccountId);
        }
        map<string,Account> AccountsMap =new map<string,Account>([  SELECT Name 
                                                                    FROM Account 
                                                                    WHERE Id in: AccountIDs ]);
                
        for(opportunity o : opportunities)
        {
            string s1='';
            string s2='';
            if(AccountsMap.get(o.AccountId)!=null)
            {
                s1= AccountsMap.get(o.AccountId).Name;
            }
            s1 = s1.replaceAll('[ \\\\\t\r\n\f0-9!"#$%&\'()*+,./:;<=>?@\\^_`{|}~-]','');
            s1 = s1.left(10);
            
            string comb;
            if(o.TypeOpportunite__c!=null && o.Type_Location__c!=null && AccountsMap.get(o.accountid).name!=null )
            {
               s2 = String.valueOf(o.Type_Location__c);
               s2 = s2.replaceAll('[ \\\\\t\r\n\f0-9!"#$%&\'()*+,./:;<=>?@\\^_`{|}~-]','');
                
                    comb = String.valueOf(o.TypeOpportunite__c)+ '_' + s2 +'_'+s1;
                    o.Name=comb;
                
               
            }
        }
    }
    public static void GenerateOppName_SAPCPQ(list<opportunity> opportunities)
    {
        set<string> AccountIDs = new set<string>();

        for(Opportunity o : opportunities)
        {
            AccountIDs.add(o.AccountId);
        }
        map<string,Account> AccountsMap =new map<string,Account>([  SELECT Name 
                                                                    FROM Account 
                                                                    WHERE Id in: AccountIDs ]);
        for(opportunity o : opportunities)
        {
             string AccountName='';
            if(AccountsMap.get(o.AccountId)!=null)
            {
                AccountName= AccountsMap.get(o.AccountId).Name;
            }
            AccountName = AccountName.replaceAll('[ \\\\\t\r\n\f0-9!"#$%&\'()*+,./:;<=>?@\\^_`{|}~-]','');
            AccountName = AccountName.left(10);
            
          
            if(o.TypeContrat__c !=null  &&  AccountName !=null && o.CreatedDate<>null)
            {
                String day = String.valueOf(o.CreatedDate.day());
        		String month = String.valueOf(o.CreatedDate.month());
        		String year = String.valueOf(o.CreatedDate.year());
          
                    o.Name= day+'/'+month+'/'+year+' - '+o.TypeContrat__c+' - '+AccountName;
                }
               else if(o.TypeContrat__c !=null  && AccountName!=null && o.CreatedDate==null)
            {
				Date Todays = Date.today();
                String day = String.valueOf(Todays.day());
        		String month = String.valueOf(Todays.month());
        		String year = String.valueOf(Todays.year());
          
                    o.Name= day+'/'+month+'/'+year+' - '+o.TypeContrat__c+' - '+AccountName;
            }
            }
        	
        }
 
    public static void GenerateOppName_Reways(list<opportunity> opportunities)
    {
        set<string> AccountIDs = new set<string>();

        for(Opportunity o : opportunities)
        {
            AccountIDs.add(o.AccountId);
        }
        map<string,Account> AccountsMap =new map<string,Account>([  SELECT Name 
                                                                    FROM Account 
                                                                    WHERE Id in: AccountIDs ]);
                
        for(opportunity o : opportunities)
        {
            string s1='';
            
            if(AccountsMap.get(o.AccountId)!=null)
            {
                s1= AccountsMap.get(o.AccountId).Name;
            }
            s1 = s1.replaceAll('[ \\\\\t\r\n\f0-9!"#$%&\'()*+,./:;<=>?@\\^_`{|}~-]','');
            s1 = s1.left(10);
            
            string comb;
            if(o.Quantite__c!=null && o.SousFamille__c !=null && AccountsMap.get(o.accountid).name!=null )
            {
                if(o.SousFamille__c!=null)
                {
                    comb = 'Cession_' + String.valueOf(o.Quantite__c)+'_'+String.valueOf(o.SousFamille__c)+'_'+s1;
                    o.Name=comb;
                }
               
            }
        }
    }   
}