unpackaged/main/default/objects/Opportunity/fields/OpportuniteParent__c.field-meta.xml
<CustomField>
    <fullName>OpportuniteParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunité parent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND 4 AND 5)</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.PaysRegionPF__c</field>
            <operation>equals</operation>
            <valueField>Opportunity.PaysRegionPF__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.AgencePF__c</field>
            <operation>equals</operation>
            <valueField>Opportunity.AgencePF__c</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opportunité Multi-Produits, Opportunité Multi-Produits (en cours), Opportunité Multi-Produits (clôturée)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Opportunité Mono-Produit, Opportunité Mono-Produit (en cours), Opportunité Mono-Produit (clôturée)</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunités enfants</relationshipLabel>
    <relationshipName>OpportunitesEnfants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TECHNombreDeRoles__c.field-meta.xml
<CustomField>
    <fullName>TECHNombreDeRoles__c</fullName>
    <label>TECH Nombre de roles</label>
    <summaryForeignKey>RoleContact__c.Opportunite__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/RoleContact__c/RoleContact__c.object-meta.xml
<CustomObject>
    <label>Rôle de contact</label>
    <nameField>
        <displayFormat>GF-RCN-{0000000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rôles de contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RoleContact__c/fields/Opportunite__c.field-meta.xml
<CustomField>
    <fullName>Opportunite__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Rôles des contacts</relationshipLabel>
    <relationshipName>RolesContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/AP01RoleDeContact.cls
public class AP01RoleDeContact {
	
	public static void PreventDeletion(list<RoleContact__c> roles)
	{
		set<string> ParentOppIDs = new set<string>();
		for(RoleContact__c rc : roles)
		{
			ParentOppIDs.add(rc.Opportunite__c);
		}
		
		list<AggregateResult> ChildrenAgg = [	SELECT COUNT(CreatedDate) c, OpportuniteParent__c
												FROM Opportunity
												WHERE OpportuniteParent__c in: ParentOppIDs
													AND (NOT StageName =: Label.OPP_StageName_OpportuniteCreee)
													AND TECHNombreDeRoles__c <= 0
													AND OpportuniteParent__r.TECHNombreDeRoles__c = 1
												GROUP BY OpportuniteParent__c];
											
		map<string,integer> ParentNoContactChildrenMap = new map<string,integer>();
		for(AggregateResult ar : ChildrenAgg)
		{
			ParentNoContactChildrenMap.put(string.valueof(ar.get('OpportuniteParent__c')),integer.valueof(ar.get('c')));
		}
										
		for(RoleContact__c rc : roles)
		{
			if(ParentNoContactChildrenMap.get(rc.Opportunite__c)!=null)
			{
				rc.addError(Label.OPP_ErrorMessage_CantDeleteRole);
			}
		}
		
	}
    
}