unpackaged/main/default/objects/Quote/fields/Amenagements_Caisse__c.field-meta.xml
<CustomField>
    <fullName>Amenagements_Caisse__c</fullName>
    <label>Aménagements standard Caisse</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Amenagements_Chassis__c.field-meta.xml
<CustomField>
    <fullName>Amenagements_Chassis__c</fullName>
    <label>Aménagements standard Châssis</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Amenagements_Groupe__c.field-meta.xml
<CustomField>
    <fullName>Amenagements_Groupe__c</fullName>
    <label>Aménagements standard Groupe</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Amenagements_Hayon__c.field-meta.xml
<CustomField>
    <fullName>Amenagements_Hayon__c</fullName>
    <label>Aménagements standard Hayon</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Charge_utile_Kg__c.field-meta.xml
<CustomField>
    <fullName>Charge_utile_Kg__c</fullName>
    <label>Charge utile (Kg ± 5%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Chassis_hauteur_seuil__c.field-meta.xml
<CustomField>
    <fullName>Chassis_hauteur_seuil__c</fullName>
    <label>Hauteur sol plancher</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Chassis_largeur__c.field-meta.xml
<CustomField>
    <fullName>Chassis_largeur__c</fullName>
    <label>Largeur ext. hors rétroviseurs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Chassis_longueur__c.field-meta.xml
<CustomField>
    <fullName>Chassis_longueur__c</fullName>
    <label>Longueur ext. hors tout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Chassis_Porte_faux_arriere__c.field-meta.xml
<CustomField>
    <fullName>Chassis_Porte_faux_arriere__c</fullName>
    <label>Porte-à-faux arrière</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Code_PF__c.field-meta.xml
<CustomField>
    <fullName>Code_PF__c</fullName>
    <label>Code PF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Désignation</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Empattement__c.field-meta.xml
<CustomField>
    <fullName>Empattement__c</fullName>
    <label>Empattement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Energie__c.field-meta.xml
<CustomField>
    <fullName>Energie__c</fullName>
    <label>Energie</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B100</fullName>
            </value>
            <value>
                <fullName>DIESEL</fullName>
            </value>
            <value>
                <fullName>ELECTRIQUE</fullName>
            </value>
            <value>
                <fullName>ESSENCE</fullName>
            </value>
            <value>
                <fullName>GNC</fullName>
            </value>
            <value>
                <fullName>GNL</fullName>
            </value>
            <value>
                <fullName>GNV</fullName>
            </value>
            <value>
                <fullName>HYBRIDE</fullName>
            </value>
            <value>
                <fullName>AUTRE -  voir Equipements chassis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Hauteur_Interieur__c.field-meta.xml
<CustomField>
    <fullName>Hauteur_Interieur__c</fullName>
    <label>Hauteur Intérieur</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Hauteur_maxi_Hors_tout__c.field-meta.xml
<CustomField>
    <fullName>Hauteur_maxi_Hors_tout__c</fullName>
    <label>Hauteur maxi Hors tout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Hauteur_passage_arriere_mm__c.field-meta.xml
<CustomField>
    <fullName>Hauteur_passage_arriere_mm__c</fullName>
    <label>Hauteur passage arrière</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Largeur_Interieur__c.field-meta.xml
<CustomField>
    <fullName>Largeur_Interieur__c</fullName>
    <label>Largeur int. utile sur plinthe</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Longueur_Interieur__c.field-meta.xml
<CustomField>
    <fullName>Longueur_Interieur__c</fullName>
    <label>Longueur int. utile sur plinthe</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Marque__c.field-meta.xml
<CustomField>
    <fullName>Marque__c</fullName>
    <label>Marque</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALFA ROMEO</fullName>
            </value>
            <value>
                <fullName>ANCY FACTORY</fullName>
            </value>
            <value>
                <fullName>ASCA</fullName>
            </value>
            <value>
                <fullName>AUDI</fullName>
            </value>
            <value>
                <fullName>BENALU</fullName>
            </value>
            <value>
                <fullName>BENTLEY</fullName>
            </value>
            <value>
                <fullName>BERLIET</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>CADILLAC</fullName>
            </value>
            <value>
                <fullName>CHEREAU</fullName>
            </value>
            <value>
                <fullName>CITROEN</fullName>
            </value>
            <value>
                <fullName>CODER</fullName>
            </value>
            <value>
                <fullName>CROSSLAND</fullName>
            </value>
            <value>
                <fullName>DAF</fullName>
            </value>
            <value>
                <fullName>DESOT</fullName>
            </value>
            <value>
                <fullName>EUROCOOLER</fullName>
            </value>
            <value>
                <fullName>FENWICK</fullName>
            </value>
            <value>
                <fullName>FIAT</fullName>
            </value>
            <value>
                <fullName>FLURY AL 52-21</fullName>
            </value>
            <value>
                <fullName>FOIMA</fullName>
            </value>
            <value>
                <fullName>FORD</fullName>
            </value>
            <value>
                <fullName>FRAPPA</fullName>
            </value>
            <value>
                <fullName>FREEGONES</fullName>
            </value>
            <value>
                <fullName>FREIGHTLINER</fullName>
            </value>
            <value>
                <fullName>FRUEHAUF</fullName>
            </value>
            <value>
                <fullName>FUSO</fullName>
            </value>
            <value>
                <fullName>GOUPIL</fullName>
            </value>
            <value>
                <fullName>GROSSE EQUIPEMENT</fullName>
            </value>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>HINO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Mod_le__c.field-meta.xml
<CustomField>
    <fullName>Mod_le__c</fullName>
    <label>Modèle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Marque__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>159</fullName>
            </value>
            <value>
                <fullName>159 SW</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>205</fullName>
            </value>
            <value>
                <fullName>206</fullName>
            </value>
            <value>
                <fullName>220 E</fullName>
            </value>
            <value>
                <fullName>300E</fullName>
            </value>
            <value>
                <fullName>306</fullName>
            </value>
            <value>
                <fullName>307</fullName>
            </value>
            <value>
                <fullName>320D</fullName>
            </value>
            <value>
                <fullName>320E</fullName>
            </value>
            <value>
                <fullName>320S</fullName>
            </value>
            <value>
                <fullName>405</fullName>
            </value>
            <value>
                <fullName>406</fullName>
            </value>
            <value>
                <fullName>407</fullName>
            </value>
            <value>
                <fullName>420E</fullName>
            </value>
            <value>
                <fullName>5008</fullName>
            </value>
            <value>
                <fullName>500S</fullName>
            </value>
            <value>
                <fullName>530D</fullName>
            </value>
            <value>
                <fullName>600SL</fullName>
            </value>
            <value>
                <fullName>605</fullName>
            </value>
            <value>
                <fullName>607</fullName>
            </value>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A5</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A8</fullName>
            </value>
            <value>
                <fullName>ACTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Poids_vide_Kg_5__c.field-meta.xml
<CustomField>
    <fullName>Poids_vide_Kg_5__c</fullName>
    <label>Poids à vide (Kg ± 5%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/PTAC_kgs__c.field-meta.xml
<CustomField>
    <fullName>PTAC_kgs__c</fullName>
    <label>PTAC (kgs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/PTRA_Kg__c.field-meta.xml
<CustomField>
    <fullName>PTRA_Kg__c</fullName>
    <label>PTRA (Kg)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/STANDARD__c.field-meta.xml
<CustomField>
    <fullName>STANDARD__c</fullName>
    <label>STANDARD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>H00</fullName>
            </value>
            <value>
                <fullName>H01</fullName>
            </value>
            <value>
                <fullName>H02</fullName>
            </value>
            <value>
                <fullName>H03</fullName>
            </value>
            <value>
                <fullName>H04</fullName>
            </value>
            <value>
                <fullName>H05</fullName>
            </value>
            <value>
                <fullName>H06</fullName>
            </value>
            <value>
                <fullName>H07</fullName>
            </value>
            <value>
                <fullName>H08</fullName>
            </value>
            <value>
                <fullName>H09</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Volume_Palettes__c.field-meta.xml
<CustomField>
    <fullName>Volume_Palettes__c</fullName>
    <label>Volume (m3) / Nombre de palettes (euro)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/WSParametreRequete__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>WS Paramètres Requête</label>
</CustomObject>

unpackaged/main/default/objects/WSParametreRequete__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/Methode__c.field-meta.xml
<CustomField>
    <fullName>Methode__c</fullName>
    <label>Méthode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WSParametreRequete__c/fields/MotDePasse__c.field-meta.xml
<CustomField>
    <fullName>MotDePasse__c</fullName>
    <label>Mot de Passe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CatalogueAPI.cls
public class CatalogueAPI{
public static String PARAMETERS {get;set;}
    
@AuraEnabled
    public static String WSCallCatalogue(String CodePaysParam, String CodePFParam, String CatalogueParam, String StandardPFParam,String currentQuote,String MarqueParam,String ModeleParam)
    {
       //Init
       String message = '';
       Quote Q =[SELECT id, Energie__c, Status,PTRA_Kg__c,Hauteur_passage_arriere_mm__c	,Poids_vide_Kg_5__c,Code_PF__c,Charge_utile_Kg__c,STANDARD__c,Marque__c,PTAC_kgs__c,Mod_le__c,Amenagements_Caisse__c,Amenagements_Chassis__c,
                      Amenagements_Groupe__c,Amenagements_Hayon__c,Longueur_Interieur__c,Largeur_Interieur__c,Hauteur_Interieur__c,Hauteur_maxi_Hors_tout__c,
                      Chassis_largeur__c,Chassis_longueur__c,Chassis_Porte_faux_arriere__c,Chassis_hauteur_seuil__c,Empattement__c,Volume_Palettes__c
                      from Quote where Id=:currentQuote];
//Check status and return error if status <> Draft        
if(Q.Status == 'Draft') 
{		CatalogueAPI.PARAMETERS='WS_Param_006';
		//Check for empty fields
        if(CodePaysParam == '-' || CodePFParam == '-' || CatalogueParam == '-'||StandardPFParam == '-' )
        {
            message = 'ErreurDM';
        }
        else
        {
         Catalogue_JSON CatalogueJSON;
           
			//WS Call
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        //Clean params
        String CodePaysParamClean = CodePaysParam.replaceAll(' ', '%20');
        String CodePFParamClean = CodePFParam.replaceAll(' ', '%20');
        String CatalogueParamClean = CatalogueParam.replaceAll(' ', '%20');
        String StandardPFParamClean = StandardPFParam.replaceAll(' ', '%20');
        String endpoint=WSParametreRequete__c.getInstance(CatalogueAPI.PARAMETERS).EndPoint__c+'/'+CodePaysParamClean+'/'+CodePFParamClean+'/'+StandardPFParam+'/'+CatalogueParamClean;
        //Setup Call
        req.setEndpoint(endpoint);
        req.setMethod(WSParametreRequete__c.getInstance(CatalogueAPI.PARAMETERS).Methode__c);
        req.setHeader('User', WSParametreRequete__c.getInstance(CatalogueAPI.PARAMETERS).UserName__c);
        req.setHeader('Password', WSParametreRequete__c.getInstance(CatalogueAPI.PARAMETERS).MotDePasse__c);
        req.setHeader('Content-Type', WSParametreRequete__c.getInstance(CatalogueAPI.PARAMETERS).ContentType__c);
        req.setHeader('Authorization', WSParametreRequete__c.getInstance(CatalogueAPI.PARAMETERS).Authorization__c);
        //Setup response
        HttpResponse resp= new HttpResponse();
        req.setTimeout(60000);
        resp = http.send(req);
        system.debug('resp.getStatusCode'+resp.getStatusCode());
       
        //Response = pas de catalogue
        if(resp.getStatusCode()==404)
        {
         message = 'null';
            
        }
        //Response OK
        else if(resp.getStatusCode()==200)
        {
            message = 'OK';
            
               CatalogueJSON = (Catalogue_JSON) System.JSON.deserialize(resp.getBody(),Catalogue_JSON.class); 
         
            
             //Parsing the response and updating the Quote   
            Q.Code_PF__c = CatalogueJSON.body.produit.code_pf;
            
            if(CatalogueJSON.body.produit.charge_utile <> '' && CatalogueJSON.body.produit.charge_utile <> null)
            {Q.Charge_utile_Kg__c = integer.valueof(CatalogueJSON.body.produit.charge_utile);}
            else
            {Q.Charge_utile_Kg__c=null;}
            
            Q.STANDARD__c = CatalogueJSON.body.produit.standard_pf;
            Q.Marque__c = CatalogueJSON.body.produit.marque;
            
            
             if(CatalogueJSON.body.produit.ptac <> '' && CatalogueJSON.body.produit.ptac <> null)
            {Q.PTAC_kgs__c = integer.valueof(CatalogueJSON.body.produit.ptac);}
            else
            {Q.PTAC_kgs__c=null;}
            
            Q.Mod_le__c = CatalogueJSON.body.produit.modele;
            
            if(CatalogueJSON.body.produit.longueur_interieur <> '' && CatalogueJSON.body.produit.longueur_interieur <> null)
            {Q.Longueur_Interieur__c = integer.valueof(CatalogueJSON.body.produit.longueur_interieur);}
            else
            {Q.Longueur_Interieur__c=null;}
            
            if(CatalogueJSON.body.produit.largeur_interieur <> '' && CatalogueJSON.body.produit.largeur_interieur <> null)
            {Q.Largeur_Interieur__c = integer.valueof(CatalogueJSON.body.produit.largeur_interieur);}
            else
            {Q.Largeur_Interieur__c=null;}
            
            if(CatalogueJSON.body.produit.hauteur_interieur <> '' && CatalogueJSON.body.produit.hauteur_interieur <> null)
            {Q.Hauteur_Interieur__c = integer.valueof(CatalogueJSON.body.produit.hauteur_interieur);}
            else
            {Q.Hauteur_Interieur__c=null;}
            
            if(CatalogueJSON.body.produit.hauteur_maxi_hors_tout <> '' && CatalogueJSON.body.produit.hauteur_maxi_hors_tout <> null)
            {Q.Hauteur_maxi_Hors_tout__c = integer.valueof(CatalogueJSON.body.produit.hauteur_maxi_hors_tout);}
            else
            {Q.Hauteur_maxi_Hors_tout__c=null;}
            
            if(CatalogueJSON.body.produit.largeur <> '' && CatalogueJSON.body.produit.largeur <> null)
            {Q.Chassis_largeur__c = integer.valueof(CatalogueJSON.body.produit.largeur);}
            else
            {Q.Chassis_largeur__c=null;}
            
         	if(CatalogueJSON.body.produit.longueur <> '' && CatalogueJSON.body.produit.longueur <> null)
            {Q.Chassis_longueur__c = integer.valueof(CatalogueJSON.body.produit.longueur);}
            else
            {Q.Chassis_longueur__c=null;}
            
            if(CatalogueJSON.body.produit.porte_a_faux_arr <> '' && CatalogueJSON.body.produit.porte_a_faux_arr <> null)
            {Q.Chassis_Porte_faux_arriere__c = integer.valueof(CatalogueJSON.body.produit.porte_a_faux_arr);}
            else
            {Q.Chassis_Porte_faux_arriere__c=null;}
            
             if(CatalogueJSON.body.produit.hauteur_seuil <> '' && CatalogueJSON.body.produit.hauteur_seuil <> null)
            {Q.Chassis_hauteur_seuil__c = integer.valueof(CatalogueJSON.body.produit.hauteur_seuil);}
            else
            {Q.Chassis_hauteur_seuil__c=null;}
            
            if(CatalogueJSON.body.produit.empattement <> '' && CatalogueJSON.body.produit.empattement <> null)
            {Q.Empattement__c = integer.valueof(CatalogueJSON.body.produit.empattement);}
            else
            {Q.Empattement__c=null;}
             
             
            if(CatalogueJSON.body.produit.Energie <> '' && CatalogueJSON.body.produit.Energie <> null)
            {Q.Energie__c = CatalogueJSON.body.produit.Energie;} else {Q.energie__c = NULL;}
             
            Q.Volume_Palettes__c = CatalogueJSON.body.produit.volume_palettes.replaceall(',','\n');
            Q.Amenagements_Caisse__c = CatalogueJSON.body.produit.amenagement_caisse.replaceall(',','\n');
            Q.Amenagements_Chassis__c = CatalogueJSON.body.produit.amenagement_chassis.replaceall(',','\n');
            Q.Amenagements_Groupe__c = CatalogueJSON.body.produit.amenagement_groupe.replaceall(',','\n');
            Q.Amenagements_Hayon__c = CatalogueJSON.body.produit.amenagement_hayon.replaceall(',','\n');
            
            ///
            if(CatalogueJSON.body.produit.poids_a_vide <> '' && CatalogueJSON.body.produit.poids_a_vide <> null )
            {Q.Poids_vide_Kg_5__c = integer.valueof(CatalogueJSON.body.produit.poids_a_vide);}
            else
            {Q.Poids_vide_Kg_5__c =null;}
            
            if(CatalogueJSON.body.produit.hauteur_passage_arriere <> '' && CatalogueJSON.body.produit.hauteur_passage_arriere <> null)
            {Q.Hauteur_passage_arriere_mm__c = integer.valueof(CatalogueJSON.body.produit.hauteur_passage_arriere);}
            else
            {Q.Hauteur_passage_arriere_mm__c =null;}
            
            if(CatalogueJSON.body.produit.ptra <> ''  && CatalogueJSON.body.produit.ptra <> null)
            {Q.PTRA_Kg__c = integer.valueof(CatalogueJSON.body.produit.ptra);}
            else
            {Q.PTRA_Kg__c =null;}
            
			Q.designation__c = CatalogueJSON.body.produit.libelle_descriptif;
            //Stock params values
            Q.Code_Pays_Catalogue__c = CodePaysParam;
            Q.Code_PF_Catalogue__c = CodePFParam;
            Q.Standard_PF_Catalogue__c	= StandardPFParam;
          	Q.Catalogue_PF_Catalogue__c = CatalogueParam;
            Q.Marque_Catalogue__c = MarqueParam;
            Q.Modele_Catalogue__c= ModeleParam;
            update Q; 
            
            
        }
        //Erreur WS    
        else{
            message = 'Erreur';
        }
        
        
        
        }
}
else
{
 message = 'NOT_ALLOWED';   
}
		
    return message;    
    }
}//END