unpackaged/main/default/objects/Quote/fields/Devis__c.field-meta.xml
<CustomField>
    <fullName>Devis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Devis modèle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Modele_de_devis__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Devis</relationshipLabel>
    <relationshipName>Devis</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Duree__c.field-meta.xml
<CustomField>
    <fullName>Duree__c</fullName>
    <label>Durée</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Duree_de_location__c.field-meta.xml
<CustomField>
    <fullName>Duree_de_location__c</fullName>
    <inlineHelpText>(Mois)</inlineHelpText>
    <label>Durée de location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>72</fullName>
            </value>
            <value>
                <fullName>84</fullName>
            </value>
            <value>
                <fullName>96</fullName>
            </value>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Kilom_trage__c.field-meta.xml
<CustomField>
    <fullName>Kilom_trage__c</fullName>
    <label>Kilométrage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Quote/fields/Synchronise__c.field-meta.xml
<CustomField>
    <fullName>Synchronise__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Synchronisation Devis/Opportunité</description>
    <label>Synchronisé</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Tarification__c/Tarification__c.object-meta.xml
<CustomObject>
    <label>Tarification</label>
    <nameField>
        <displayFormat>TAR-{00000}</displayFormat>
        <label>Numéro de Tarification Loyer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tarifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tarification__c/fields/Devis__c.field-meta.xml
<CustomField>
    <fullName>Devis__c</fullName>
    <label>Devis</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Tarifications</relationshipLabel>
    <relationshipName>Tarifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Tarification__c/fields/Duree__c.field-meta.xml
<CustomField>
    <fullName>Duree__c</fullName>
    <label>Durée</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Tarification__c/fields/Kilometrage__c.field-meta.xml
<CustomField>
    <fullName>Kilometrage__c</fullName>
    <label>Kilométrage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Tarification__c/fields/Synchronise__c.field-meta.xml
<CustomField>
    <fullName>Synchronise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synchronisé</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/QuoteClass.cls
public class QuoteClass {
 
    //Générer les lignes de tarifications en fonctions des champs Duree_de_location__c 
    public static void generateTarifications(String Devis_ID,string CurrencyIsoCode)
    {
        //Quote
        Quote Q = [SELECT Duree_de_location__c,Kilom_trage__c  FROM Quote where Id=:Devis_ID];
         string[] LesDurees = Q.Duree_de_location__c.split(';');
        
     for(String D : LesDurees)
        {            
            Tarification__c T = new Tarification__c();
            T.Duree__c =integer.valueof(D);
            T.Kilometrage__c = Q.Kilom_trage__c;
            T.Devis__c = Devis_ID;
            T.CurrencyIsoCode= CurrencyIsoCode;
            Insert T;   
        }   
    }
    //En cas d'update,supprimer les anciennes lignes de tarifications.
    public static void deleteTarifications(String DEVIS_ID)
    {
         List<Tarification__c> OldTarifications = new List<Tarification__c>(); 
        OldTarifications = [SELECT id from Tarification__c where devis__c =:DEVIS_ID];
        Delete OldTarifications;
        
    }
    
    //En cas de synchronisation du devis,désynchroniser les autres devis associés à la même opportunité
    public static void Synchronisation(String DEVIS_ID)
    {
        List<Quote> QuoteToDesync = new List<Quote>();
        Quote Q = [SELECT synchronise__c,OpportunityId from quote where id=:DEVIS_ID];
        
        for(Quote Qt : [SELECT Id,synchronise__c from Quote where synchronise__c=true AND OpportunityId =:Q.OpportunityId])
          {
               if(Q.Id<>Qt.Id)
                {
                Qt.Synchronise__c=false;
                QuoteToDesync.add(Qt); 
                }
          }
        IF(QuoteToDesync.size()!=0){update QuoteToDesync;}
    }
    
    //Modifier les tarifications suite à la modification du KM sur devis
    public static void updateTarifications(String DEVIS_ID,decimal KM)
    {
        List<Tarification__c> Tarifications = [SELECT id,Kilometrage__c from Tarification__c where devis__c=:DEVIS_ID];
        
        for(Tarification__c T : Tarifications)
        {
            T.Kilometrage__c = KM;
        }
        if(Tarifications.size()>0){update Tarifications;}
    }
}