unpackaged/main/default/objects/SFCPQ_Fields_Mapping_Settings__mdt/SFCPQ_Fields_Mapping_Settings__mdt.object-meta.xml
<CustomObject>
    <label>SFCPQ Fields Mapping Settings</label>
    <pluralLabel>SFCPQ Fields Mapping Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SFCPQ_Fields_Mapping_Settings__mdt/fields/CPQ_Owner_ID_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Owner_ID_Field_API_Name__c</fullName>
    <label>CPQ Owner ID Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Fields_Mapping_Settings__mdt/fields/Opportunity_ID_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID_Field_API_Name__c</fullName>
    <label>Opportunity ID Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Fields_Mapping_Settings__mdt/fields/Quote_ID_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_ID_Field_API_Name__c</fullName>
    <label>Quote ID Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Fields_Mapping_Settings__mdt/fields/SF_SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SF_SObject_API_Name__c</fullName>
    <label>SF SObject API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/SFCPQ_Integration_Settings__mdt.object-meta.xml
<CustomObject>
    <label>SFCPQ Integration Settings</label>
    <pluralLabel>SFCPQ Integration Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/fields/Client_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Client_Identifier__c</fullName>
    <label>Client Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/fields/CPQ_Environment__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Environment__c</fullName>
    <label>CPQ Environment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/fields/CPQ_Environment_URL__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Environment_URL__c</fullName>
    <label>CPQ Environment URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/fields/FSSO__c.field-meta.xml
<CustomField>
    <fullName>FSSO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FSSO</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/fields/IDP_Route__c.field-meta.xml
<CustomField>
    <fullName>IDP_Route__c</fullName>
    <label>IDP Route</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/fields/JWT_Token_Signing_Key__c.field-meta.xml
<CustomField>
    <fullName>JWT_Token_Signing_Key__c</fullName>
    <label>JWT Token Signing Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/fields/SF_Environment_URL__c.field-meta.xml
<CustomField>
    <fullName>SF_Environment_URL__c</fullName>
    <label>SF Environment URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Integration_Settings__mdt/fields/Use_SFCPQ_Usernames_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Use_SFCPQ_Usernames_Mapping__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use SFCPQ Usernames Mapping</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Usernames_Mapping_Settings__c/SFCPQ_Usernames_Mapping_Settings__c.object-meta.xml
<CustomObject>
    <label>SFCPQ Usernames Mapping Settings</label>
    <nameField>
        <displayFormat>UMS-{00000}</displayFormat>
        <label>SFCPQ Usernames Mapping Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFCPQ Usernames Mapping Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SFCPQ_Usernames_Mapping_Settings__c/fields/CPQ_Username__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Username__c</fullName>
    <label>CPQ Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SFCPQ_Usernames_Mapping_Settings__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SFCPQ_Usernames_Mapping_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/QuoteDocumentController.cls
public class QuoteDocumentController { 
    public String url { get; set; } 
    private static List<SFCPQ_Integration_Settings__mdt> integrationSettingsList = SFCPQ_Integration_Settings__mdt.getAll().values();
    private static List<SFCPQ_Fields_Mapping_Settings__mdt> fieldsMappingSettingsList = SFCPQ_Fields_Mapping_Settings__mdt.getAll().values();
  
    public QuoteDocumentController() { 
        String recordid = ApexPages.currentPage().getParameters().get('recordid'); 
        String accessToken = ApexPages.currentPage().getParameters().get('token'); 
        String action = ApexPages.currentPage().getParameters().get('action'); 
  
        SFCPQ_Integration_Settings__mdt integrationSettings = integrationSettingsList[0];
        String routerParameter = isFSSOEnabled(integrationSettings) ? '/fed/' + integrationSettings.IDP_Route__c + '/integrations' : '/integrations';
        String authTokenParameter = isFSSOEnabled(integrationSettings) ? '' : '&authtoken=' + accessToken; 
        if (action == 'create') { 
            this.url = integrationSettings.CPQ_Environment_URL__c + routerParameter + '/crm/landing?action=create' + 
                                '&opportunityid=' + recordid + 
                                '&apisessionid=' + UserInfo.getSessionId() + 
                                authTokenParameter; 
        } else {
             //action = 'edit', 'view', 'new'
            List<SFCPQ_Fields_Mapping_Settings__mdt> fieldsMappingSettingsList = SFCPQ_Fields_Mapping_Settings__mdt.getAll().values(); 
            if (! fieldsMappingSettingsList.isEmpty()) { 
                SFCPQ_Fields_Mapping_Settings__mdt fieldsMappingSettings = fieldsMappingSettingsList[0]; 
                String query = 'SELECT Name, ' + fieldsMappingSettings.Quote_ID_Field_API_Name__c + ', ' + 
                                        fieldsMappingSettings.CPQ_Owner_ID_Field_API_Name__c + ', ' + 
                                        fieldsMappingSettings.Opportunity_ID_Field_API_Name__c + ' ' + 
                                'FROM ' + fieldsMappingSettings.SF_SObject_API_Name__c + ' ' + 
                                'WHERE Id = \'' + recordid + '\' ' + 
                                'LIMIT 1'; 
                system.debug('recordid mo recordid:'+recordid);system.debug('debug mo action '+action);
                SObject sobj = Database.query(query); 
                this.url = integrationSettings.CPQ_Environment_URL__c + routerParameter + '/crm/landing?action=' + action + '&quotenumber=' + sobj.get('Name') + 
                                '&quoteid=' + sobj.get(fieldsMappingSettings.Quote_ID_Field_API_Name__c) + 
                                '&ownerid=' + sobj.get(fieldsMappingSettings.CPQ_Owner_ID_Field_API_Name__c) + 
                                '&opportunityid=' + sobj.get(fieldsMappingSettings.Opportunity_ID_Field_API_Name__c) + 
                                '&apisessionid=' + UserInfo.getSessionId() + 
                                authTokenParameter; 
                system.debug('debug mo URL '+url);
            } 
        }
    } 
    
  
    @AuraEnabled 
    public static String getAccessToken() { 
        SFCPQ_Integration_Settings__mdt integrationSettings = integrationSettingsList[0];
        String username = returnAuthUsername(integrationSettings);
        validateUsername(username);
        String accessToken;
        if (! isFSSOEnabled(integrationSettings)) {
            String jwtToken = SecurityService.generateJWT('HS256',
                                    username,
                                    integrationSettings.SF_Environment_URL__c, 
                                    integrationSettings.CPQ_Environment_URL__c, 
                                    5, 
                                    integrationSettings.JWT_Token_Signing_Key__c); 
            accessToken = generateAccessToken(jwtToken, integrationSettings);
            validateAccessToken(accessToken);
        }
        return accessToken; 
    } 
  
  
    private static String generateAccessToken(String jwtToken, SFCPQ_Integration_Settings__mdt integrationSettings) { 
        String accessToken; 
        HttpRequest req = new HttpRequest(); 
        req.setMethod('POST'); 
        req.setHeader('Content-Type','application/x-www-form-urlencoded'); 
        req.setEndpoint(integrationSettings.CPQ_Environment_URL__c + '/oauth2/token'); 
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(integrationSettings.Client_Identifier__c + ':' + integrationSettings.Client_Secret__c))); 
        req.setBody('grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer' + 
                    '&assertion=' + jwtToken + 
                    '&domain=' + integrationSettings.CPQ_Environment__c); 
        Http http = new Http(); 
        HTTPResponse response = http.send(req); 
                     
        if (response.getStatusCode() == 200) { 
            Map<String,Object> responseMap = (Map<String,Object>) JSON.deserializeUntyped(response.getBody()); 
            accessToken = responseMap.containsKey('access_token') ? String.valueOf(responseMap.get('access_token')) : null; 
        } 
        system.debug('Mo debug response :'+response);system.debug('Mo debug token:'+accessToken);
        return accessToken; 
    }
    
    
    private static String returnAuthUsername(SFCPQ_Integration_Settings__mdt integrationSettings) {
        String username = UserInfo.getUserName();
        if (integrationSettings.Use_SFCPQ_Usernames_Mapping__c == true) {
            List<SFCPQ_Usernames_Mapping_Settings__c> usernamesMapping = [
                SELECT SF_User__r.Username, CPQ_Username__c
                FROM SFCPQ_Usernames_Mapping_Settings__c 
                WHERE SF_User__r.Username = :username
                LIMIT 1];
            username = ! usernamesMapping.isEmpty() ? usernamesMapping[0].CPQ_Username__c : null;
            if (Test.isRunningTest()) { username = UserInfo.getUserName(); }
        }
        return username;
    }


    private static Boolean isFSSOEnabled(SFCPQ_Integration_Settings__mdt integrationSettings) {
        return (integrationSettings.FSSO__c && String.isNotBlank(integrationSettings.IDP_Route__c));
    }


    private static void validateUsername(String username) {
        username = Test.isRunningTest() ? UserInfo.getUserName() : username;
        if (username == null) {
            throw new AuraHandledException('Please contact Admin to add "' + UserInfo.getUserName() + '" to the User Mappings table.');
        }
    }


    private static void validateAccessToken(String accessToken) {
        if (accessToken == null) {
            throw new AuraHandledException('Please contact Admin to verify authentication setup in SAP CPQ and Salesforce.');
        }
    }
}