unpackaged/main/default/objects/Alerte__c/Alerte__c.object-meta.xml
<CustomObject>
    <label>Alerte</label>
    <nameField>
        <displayFormat>Alerte-{0000}</displayFormat>
        <label>N° Alerte</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Alerte__c/fields/Charge_Alternateur_Update__c.field-meta.xml
<CustomField>
    <fullName>Charge_Alternateur_Update__c</fullName>
    <label>Charge_Alternateur Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Code_defaut_alternateur_update__c.field-meta.xml
<CustomField>
    <fullName>Code_defaut_alternateur_update__c</fullName>
    <label>Code Defaut Alternateur Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Date_Dernier_Etat_Moteur_Update__c.field-meta.xml
<CustomField>
    <fullName>Date_Dernier_Etat_Moteur_Update__c</fullName>
    <label>Le Update</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/DateTime_Alerte__c.field-meta.xml
<CustomField>
    <fullName>DateTime_Alerte__c</fullName>
    <label>DateTime Alerte</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Dernier_Etat_Moteur__c.field-meta.xml
<CustomField>
    <fullName>Dernier_Etat_Moteur__c</fullName>
    <label>Moteur</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Dernier_Etat_Moteur_Update__c.field-meta.xml
<CustomField>
    <fullName>Dernier_Etat_Moteur_Update__c</fullName>
    <label>Moteur Update</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Description_Update__c.field-meta.xml
<CustomField>
    <fullName>Description_Update__c</fullName>
    <label>Description Update</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Location_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Location_Latitude__c</fullName>
    <label>Location Latitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Location_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Location_Longitude__c</fullName>
    <label>Location Longitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Nb_Demarrages_12H_Update__c.field-meta.xml
<CustomField>
    <fullName>Nb_Demarrages_12H_Update__c</fullName>
    <label>Nb Démarrages 12H Update</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Nb_Kilometres_12H_Update__c.field-meta.xml
<CustomField>
    <fullName>Nb_Kilometres_12H_Update__c</fullName>
    <label>Nb Kilometres 12H Update</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Niveau_Batterie_Actuel_Update__c.field-meta.xml
<CustomField>
    <fullName>Niveau_Batterie_Actuel_Update__c</fullName>
    <label>Niveau Batterie Actuel Update</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Occurrences__c.field-meta.xml
<CustomField>
    <fullName>Occurrences__c</fullName>
    <label>Occurrences</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Parc__c.field-meta.xml
<CustomField>
    <fullName>Parc__c</fullName>
    <label>Parc</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Alertes</relationshipLabel>
    <relationshipName>Alerte</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Parc_Id__c.field-meta.xml
<CustomField>
    <fullName>Parc_Id__c</fullName>
    <label>Parc_Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Sujet__c.field-meta.xml
<CustomField>
    <fullName>Sujet__c</fullName>
    <label>Sujet</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Sujet_Update__c.field-meta.xml
<CustomField>
    <fullName>Sujet_Update__c</fullName>
    <label>Sujet Update</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Temperature_Exterieure_Update__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Exterieure_Update__c</fullName>
    <label>Temperature Exterieure Update</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Tension_Batterie_2H_Update__c.field-meta.xml
<CustomField>
    <fullName>Tension_Batterie_2H_Update__c</fullName>
    <label>Tension Batterie 2H Update</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Type_Alerte__c.field-meta.xml
<CustomField>
    <fullName>Type_Alerte__c</fullName>
    <label>Type Alerte</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tension batterie basse</fullName>
            </value>
            <value>
                <fullName>Voyant moteur</fullName>
            </value>
            <value>
                <fullName>Coupure basse pression A01</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Vitesse_Du_Vehicule_Update__c.field-meta.xml
<CustomField>
    <fullName>Vitesse_Du_Vehicule_Update__c</fullName>
    <label>Vitesse du véhicule Update</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Voyant_moteur_allume_depuis__c.field-meta.xml
<CustomField>
    <fullName>Voyant_moteur_allume_depuis__c</fullName>
    <label>Allumé depuis</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Voyant_moteur_allume_depuis_update__c.field-meta.xml
<CustomField>
    <fullName>Voyant_moteur_allume_depuis_update__c</fullName>
    <label>Allumé depuis Update</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Voyant_moteur_description__c.field-meta.xml
<CustomField>
    <fullName>Voyant_moteur_description__c</fullName>
    <label>Description</label>
    <length>35000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Voyant_moteur_description_Update__c.field-meta.xml
<CustomField>
    <fullName>Voyant_moteur_description_Update__c</fullName>
    <label>Description Update</label>
    <length>35000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Voyant_moteur_protocole__c.field-meta.xml
<CustomField>
    <fullName>Voyant_moteur_protocole__c</fullName>
    <label>Protocole</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Voyant_moteur_protocole_Update__c.field-meta.xml
<CustomField>
    <fullName>Voyant_moteur_protocole_Update__c</fullName>
    <label>Protocole Update</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Voyant_moteur_sujet__c.field-meta.xml
<CustomField>
    <fullName>Voyant_moteur_sujet__c</fullName>
    <label>Sujet</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Voyant_moteur_sujet_update__c.field-meta.xml
<CustomField>
    <fullName>Voyant_moteur_sujet_update__c</fullName>
    <label>Sujet Update</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Alerte__c.field-meta.xml
<CustomField>
    <fullName>Alerte__c</fullName>
    <formula>if( Date_alerte_tension_batterie__c = today()
,
true,
false)</formula>
    <label>Alerte</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WebserviceTelematicsData__c/WebserviceTelematicsData__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Webservices données telematics sur Google Cloud Platform</description>
    <label>WebserviceTelematicsData</label>
</CustomObject>

unpackaged/main/default/objects/WebserviceTelematicsData__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Authorization</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WebserviceTelematicsData__c/fields/Environnement__c.field-meta.xml
<CustomField>
    <fullName>Environnement__c</fullName>
    <label>Environnement</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WebserviceTelematicsData__c/fields/Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Sandbox__c</fullName>
    <label>Sandbox</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PRG_AlertGoogleController.cls
public class PRG_AlertGoogleController {

public static JSONLowBattery JSonLOwBat {get; set;}    

    public  class location{
       //string  Street {get;set;}
       //string  City{get;set;}
       //string  State{get;set;}
       string Latitude {get;set;}
       string Longitude {get;set;}
       string LastLatitude {get;set;}
       string LastLongitude {get;set;} 
    }
    
    @AuraEnabled
    public static string  CurrentLocation(string precord){

       Alerte__c alert =[SELECT  id, Parc_Id__c ,Location_Latitude__c,Location_Longitude__c, parc__r.name 
                         FROM alerte__c where id= :precord LIMIT 1 ];
        location l = new  Location();
        l.Latitude =     string.valueof(alert.Location_Latitude__c);
        l.Longitude =    string.valueof(alert.Location_Longitude__c);
        //System.debug(l);
        
        String parcId = alert.parc__r.name;   
        String AlertVehiculeName =EncodingUtil.urlEncode(parcId,'UTF-8');
        
        String message = ' vide';
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        
        String sbx = UserInfo.getUserName().substringAfterLast('.');        
		System.debug(LoggingLevel.info, 'sandbox : ' + sbx);

		WebserviceTelematicsData__c ws = [Select name, Endpoint__c, Authorization__c, Environnement__c, Sandbox__c 
                                  FROM WebserviceTelematicsData__c limit 1];
        if(Test.isRunningTest()) {
            ws = [Select name, Endpoint__c, Authorization__c, Environnement__c, Sandbox__c 
                                  FROM WebserviceTelematicsData__c WHERE Sandbox__c = 'infra' limit 1];
        }
        
        string urlEndpoint = ws.Endpoint__c + '/gps/lastPosition?vehicleId=';
        req.setEndpoint(urlEndpoint+AlertVehiculeName+'');
        req.setMethod('GET');
        
        req.setHeader('Authorization', ws.Authorization__c);
       
        System.debug(LoggingLevel.info, 'urlEndpoint : ' + urlEndpoint);
        System.debug(LoggingLevel.info, 'PRGDebug : Envoi requête...');
        
        HttpResponse resp= new HttpResponse();
        req.setTimeout(30000);
        resp = http.send(req);
        System.debug(LoggingLevel.info, 'PRGDebug : resp.getStatusCode() : ' + resp.getStatusCode());
        
        if(resp.getStatusCode()==200)
        {
           system.debug(LoggingLevel.info, resp.getBody());
            message= 'ok ! '+ string.valueof(resp.getBody());
            
            JsonGPS gpsData = JsonGPS.parse(resp.getBody());
            if(gpsData != null){
                l.LastLatitude = string.valueof(gpsData.latitude);
                l.LastLongitude = string.valueof(gpsData.longitude);
                System.debug(LoggingLevel.info, 'LastLatitude : ' + l.LastLatitude);
                System.debug(LoggingLevel.info, 'LastLongitude : ' + l.LastLongitude);             
            }
        }
        
        return JSON.serialize(l); 
    }
        
    
    @AuraEnabled
    public static string RefreshLowBattery(string precord){

        Alerte__c alert = [SELECT  id, Parc_Id__c ,
                            Tension_Batterie_2H_Update__c,
                            Nb_Demarrages_12H_Update__c ,
                            Nb_Kilometres_12H_Update__c ,
                            Niveau_Batterie_Actuel_Update__c,
                            Temperature_Exterieure_Update__c,
                            Charge_Alternateur_Update__c,
                          	Dernier_Etat_Moteur__c,
                            Date_Dernier_Etat_Moteur_Update__c,
                          	Code_defaut_alternateur_update__c,
                          	Vitesse_Du_Vehicule_Update__c,
                            voyant_moteur_protocole__c, 
                            voyant_moteur_sujet__c, 
                            voyant_moteur_description__c,
                          	voyant_moteur_protocole_Update__c, 
                            voyant_moteur_sujet_Update__c, 
                            voyant_moteur_description_Update__c,
                          	Voyant_moteur_allume_depuis__c,
                            Voyant_moteur_allume_depuis_update__c,
                           	Occurrences__c,
                          	CreatedDate,
                           	parc__r.name,
                           	recordTypeId,
                           	DateTime_Alerte__c,
                           	Sujet__c,
                           	Description__c,
                           	Sujet_Update__c,
                           	Description_Update__c
                          	//Type_Alerte__c
                            FROM alerte__c where id= :precord LIMIT 1 ];
        
        String parcId = alert.parc__r.name;        
        System.debug(LoggingLevel.info, 'Asset name  : ' + parcId);  
        
        RecordType RecordType = [select Id, name from RecordType where id =: alert.recordTypeId ];
        String typeAlerte = RecordType.name;
        System.debug(LoggingLevel.info, 'typeAlerte  : ' + typeAlerte);  
        
        String AlertVehiculeName =EncodingUtil.urlEncode(parcId,'UTF-8');
        String AlerteDate= string.valueof((Datetime.now().formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')));
        System.debug('PRGDebug : AlerteDate : ' + AlerteDate);
        AlerteDate= EncodingUtil.urlEncode(AlerteDate,'UTF-8');
      
        
        String message = ' vide';
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        
        //BON REQUETE 
        //string urlEndpoint = 'https://data-iot-mcs-5unavwdk4q-ew.a.run.app/lowBattery?vehicleName=';
        //string urlEndpoint = 'https://data-iot-mcs-5unavwdk4q-ew.a.run.app/secured/basic/lowBattery?vehicleName=';
        String sbx = UserInfo.getUserName().substringAfterLast('.');        
		System.debug(LoggingLevel.info, 'sandbox : ' + sbx);

		WebserviceTelematicsData__c ws = [Select name, Endpoint__c, Authorization__c, Environnement__c, Sandbox__c 
                                  FROM WebserviceTelematicsData__c limit 1];
        if(Test.isRunningTest()) {
            ws = [Select name, Endpoint__c, Authorization__c, Environnement__c, Sandbox__c 
                                  FROM WebserviceTelematicsData__c WHERE Sandbox__c = 'infra' limit 1];
        }
        
        string urlEndpoint = ws.Endpoint__c + '/lowBattery?vehicleName=';
        
        if(typeAlerte == 'Voyant moteur'){
            urlEndpoint = ws.Endpoint__c + '/engineLight?vehicleName=';
        }else if(typeAlerte == 'Coupure basse pression'){
            urlEndpoint = ws.Endpoint__c + '/lowPressureCutOffA01?vehicleName=';
        }
        
        req.setEndpoint(urlEndpoint+AlertVehiculeName+'&dateTime='+AlerteDate+'');
        req.setMethod('GET');
        
        req.setHeader('Authorization', ws.Authorization__c);
       
        System.debug(LoggingLevel.info, 'urlEndpoint : ' + urlEndpoint);
        System.debug(LoggingLevel.info, 'PRGDebug : Envoi requête...');
        
        HttpResponse resp= new HttpResponse();
        req.setTimeout(60000);
        resp = http.send(req);
        System.debug(LoggingLevel.info, 'PRGDebug : resp.getStatusCode() : ' + resp.getStatusCode());
        
        if(resp.getStatusCode()==200)
        {
           system.debug(LoggingLevel.info, 'BodyDebug :' + resp.getBody());
            message= 'ok ! '+ string.valueof(resp.getBody());
            if(typeAlerte == 'Tension batterie basse'){
                JSonLOwBat = JSONLowBattery.parse(resp.getBody());
                //JSONLowBattery r = JSONLowBattery.parse(resp.getBody());
                //system.debug('PRGDebug :' + JSonLOwBat.batteryMilliVolts.value_Z );
                //system.debug('PRGDebug :' + JSonLOwBat);
                alert.Tension_Batterie_2H_Update__c    = JSonLOwBat.tensionBatterie2H; 
                alert.Nb_Demarrages_12H_Update__c      = JSonLOwBat.nbDemarrage12H;
                alert.Charge_Alternateur_Update__c      = JSonLOwBat.chargeAlternateur;
                //alert.Dernier_Etat_Moteur_Update__c		= JSonLOwBat.engineStates.value;  
                
				if ('On'.equalsIgnoreCase(JSonLOwBat.engineStates.value)) {
					alert.Dernier_Etat_Moteur_Update__c		= 'Allumé';
				} else if ('Off'.equalsIgnoreCase(JSonLOwBat.engineStates.value)) {
					alert.Dernier_Etat_Moteur_Update__c		= 'Eteint';
				}
                
                alert.Date_Dernier_Etat_Moteur_Update__c= JSonLOwBat.engineStates.dateTime_Z;        
                alert.Niveau_Batterie_Actuel_Update__c =   JSonLOwBat.batteryMilliVolts.value_Z /1000 ; 
                alert.Temperature_Exterieure_Update__c =  JSonLOwBat.temperatureExterieure;
                alert.Nb_Kilometres_12H_Update__c = JSonLOwBat.nbKilometres12H;
                alert.Code_defaut_alternateur_update__c = JSonLOwBat.codeDefautAlternateur;
                alert.Vitesse_Du_Vehicule_Update__c = JSonLOwBat.vitesseKmh;
                alert.Occurrences__c = JSonLOwBat.occurrences;
                System.debug(LoggingLevel.info, 'nbOccurrences : ' + JSonLOwBat.occurrences);
                UPDATE alert; 
                
            } else if(typeAlerte == 'Voyant moteur'){
                System.debug(LoggingLevel.info,'Res Body : ' + resp.getBody());
                JSONEngineLightData lightData = JSONEngineLightData.parse(resp.getBody());                
                
                if(lightData != null) {
                    alert.voyant_moteur_sujet_Update__c = lightData.subject; 
                	alert.voyant_moteur_description_Update__c = lightData.description;
                    //alert.Occurrences__c = lightData.occurrences;
                    DateTime startDate = alert.DateTime_Alerte__c;
                    if(alert.DateTime_Alerte__c == null){                        
                        startDate = alert.CreatedDate;
                    }
                    // DateTime endDate = DateTime.now();
                    // calculer le nombre de jours/heures/minutes entre startDate & endDate
                    String dateDiff = dateDifference(startDate);
                    System.debug(LoggingLevel.info, 'dateDiff : ' + dateDiff);
                    
                    alert.Voyant_moteur_allume_depuis__c = dateDiff;                    
                	if(lightData.faultCodes != null){
                	 	alert.voyant_moteur_protocole_Update__c = lightData.faultCodes.protocol;
                        if(lightData.faultCodes.checkEngineLightIsOn != null && lightData.faultCodes.checkEngineLightIsOn){                            
                            alert.Voyant_moteur_allume_depuis_update__c = dateDiff;
                        }else if(lightData.faultCodes.stopIsOn != null && lightData.faultCodes.stopIsOn){
                            alert.Voyant_moteur_allume_depuis_update__c = dateDiff;
                        }else{
                            alert.Voyant_moteur_allume_depuis_update__c = 'Voyant éteint'; 
                        }
            		}
                    alert.Occurrences__c = lightData.occurrences;
                	System.debug(LoggingLevel.info, 'light occurrences : ' + lightData.occurrences);
                	UPDATE alert;
                }                
            }else if(typeAlerte == 'Coupure basse pression'){
                System.debug(LoggingLevel.info,'Res Body : ' + resp.getBody());
                JSONLowPressureCutOffA01 lowPressureData = JSONLowPressureCutOffA01.parse(resp.getBody());                
                
                if(lowPressureData != null) {
                    alert.sujet_Update__c = lowPressureData.subject; 
                	alert.description_Update__c = lowPressureData.description;                    
                    alert.Occurrences__c = lowPressureData.occurrences;
                	System.debug(LoggingLevel.info, 'low pressure occurrences : ' + lowPressureData.occurrences);
                	UPDATE alert;
                }                     
        	}
              
        } 
        else {
            system.debug(LoggingLevel.info, 'PRGDebug : Error response code different de 200' );
            message= string.valueof(resp.getStatusCode()); 
        }
                
        return  message;
    }
    
    public static String dateDifference(DateTime startDate){
        
        String result = '';
        
        DateTime endDate = DateTime.now();
        Long dt1Long = startDate.getTime();
        Long dt2Long = endDate.getTime();
        Long milliseconds = dt2Long - dt1Long;
        
        Long nbDays = milliseconds / (24*60*60*1000);
        if(nbDays > 0){
            result += nbDays + 'j ';
        }
        
        dt1Long = startDate.addDays((Integer)nbDays).getTime();
        milliseconds = dt2Long - dt1Long;
        
        Long nbHours = milliseconds / (60*60*1000);
        if(nbHours > 0){
            result += nbHours + 'h ';
        }
        
        dt1Long = startDate.addDays((Integer)nbDays).addHours((Integer)nbHours).getTime();
        milliseconds = dt2Long - dt1Long;
        
        Long nbMinutes = milliseconds / (60*1000);
        if(nbMinutes > 0){
            result += ' ' + nbMinutes + 'mn';
        }else if(milliseconds > 0 ){
            result += ' ' + 1 + 'mn';
        }
        
        return result;
    }
    
}