unpackaged/main/default/objects/Alerte__c/Alerte__c.object-meta.xml
<CustomObject>
    <label>Alerte</label>
    <nameField>
        <displayFormat>Alerte-{0000}</displayFormat>
        <label>N° Alerte</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerte</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Alerte__c/fields/Code_Alarme__c.field-meta.xml
<CustomField>
    <fullName>Code_Alarme__c</fullName>
    <label>Code Alarme</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/DateTime_Alerte__c.field-meta.xml
<CustomField>
    <fullName>DateTime_Alerte__c</fullName>
    <label>DateTime Alerte</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Location_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Location_Latitude__c</fullName>
    <label>Location Latitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Location_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Location_Longitude__c</fullName>
    <label>Location Longitude</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Parc__c.field-meta.xml
<CustomField>
    <fullName>Parc__c</fullName>
    <label>Parc</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Alertes</relationshipLabel>
    <relationshipName>Alerte</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Parc_Id__c.field-meta.xml
<CustomField>
    <fullName>Parc_Id__c</fullName>
    <label>Parc_Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Statut_du_vehicule__c.field-meta.xml
<CustomField>
    <fullName>Statut_du_vehicule__c</fullName>
    <label>Statut du vehicule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOTEUR_NON_TOURNANT</fullName>
                <default>true</default>
                <label>MOTEUR_NON_TOURNANT</label>
            </value>
            <value>
                <fullName>MOTEUR_TOURNANT_VEHICULE_NON_ROULANT</fullName>
            </value>
            <value>
                <fullName>MOTEUR_TOURNANT_VEHICULE_ROULANT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Type_Alerte__c.field-meta.xml
<CustomField>
    <fullName>Type_Alerte__c</fullName>
    <label>Type Alerte</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tension batterie basse</fullName>
            </value>
            <value>
                <fullName>Voyant moteur</fullName>
            </value>
            <value>
                <fullName>Coupure basse pression A01</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Alerte__c/fields/Type_De_Batterie__c.field-meta.xml
<CustomField>
    <fullName>Type_De_Batterie__c</fullName>
    <label>Type De Batterie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Alerte__c.field-meta.xml
<CustomField>
    <fullName>Alerte__c</fullName>
    <formula>if( Date_alerte_tension_batterie__c = today()
,
true,
false)</formula>
    <label>Alerte</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WebserviceTelematicsData__c/WebserviceTelematicsData__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Webservices données telematics sur Google Cloud Platform</description>
    <label>WebserviceTelematicsData</label>
</CustomObject>

unpackaged/main/default/objects/WebserviceTelematicsData__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Authorization</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WebserviceTelematicsData__c/fields/Environnement__c.field-meta.xml
<CustomField>
    <fullName>Environnement__c</fullName>
    <label>Environnement</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WebserviceTelematicsData__c/fields/Sandbox__c.field-meta.xml
<CustomField>
    <fullName>Sandbox__c</fullName>
    <label>Sandbox</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PRG_AlertGoogleControllerTest.cls
@isTest
private class PRG_AlertGoogleControllerTest {
   @isTest
    static   void CurrentLocation_Test(){
        //creation d'une alerte
        Asset asset = new asset();
        asset.Name = 'Name-Asset-XXXX';
        Insert asset;
        
        Alerte__c a = getAlerte(asset, 'Tension batterie basse'); 
        INSERT  a;
        
        WebserviceTelematicsData__c ws = getWebserviceTelematicsData();
        insert ws;
        
        Test.setMock(HttpCalloutMock.class, new MockAlertHttpResponseGenerator());        
        test.startTest();
        PRG_AlertGoogleController.CurrentLocation(string.valueof(a.id)); 
        test.stopTest();
    } 

    @isTest static  void RefreshLowBattery_Test(){

        Asset asset = new asset();
        asset.Name = 'Name-Asset-XXXX';
        Insert asset;
        
        WebserviceTelematicsData__c ws = getWebserviceTelematicsData();
        insert ws;
        
        Alerte__c a = getAlerte(asset, 'Tension batterie basse'); 
        INSERT  a;
        
        Test.setMock(HttpCalloutMock.class, new MockAlertHttpResponseGenerator());        
        Test.startTest();
        PRG_AlertGoogleController.JSonLOwBat = null;
        PRG_AlertGoogleController.RefreshLowBattery(string.valueof(a.id)); 
        Test.stopTest();
    }
    
    @isTest static  void RefreshVoyantMoteur_Test(){

        Asset asset = new asset();
        asset.Name = 'Name-Asset-XXXX';
        Insert asset;
        
        WebserviceTelematicsData__c ws = getWebserviceTelematicsData();
        insert ws;
        
        Alerte__c a = getAlerte(asset, 'Voyant moteur');
        INSERT  a;
        
        Test.setMock(HttpCalloutMock.class, new MockAlertHttpResponseGenerator());        
        test.startTest();
        PRG_AlertGoogleController.JSonLOwBat = null;
        PRG_AlertGoogleController.RefreshLowBattery(string.valueof(a.id)); 
        test.stopTest();
    }
    
    @isTest static  void RefreshCoupureBassePression_Test(){

        Asset asset = new asset();
        asset.Name = 'Name-Asset-XXXX';
        Insert asset;
        
        WebserviceTelematicsData__c ws = getWebserviceTelematicsData();
        insert ws;
        
        Alerte__c a = getAlerte(asset, 'Coupure basse pression');
        a.DateTime_Alerte__c = DateTime.now();
        INSERT  a;
        
        Test.setMock(HttpCalloutMock.class, new MockAlertHttpResponseGenerator());        
        test.startTest();
        PRG_AlertGoogleController.JSonLOwBat = null;
        PRG_AlertGoogleController.RefreshLowBattery(string.valueof(a.id)); 
        test.stopTest();
    }
    
    @isTest static  void LBGraphEvolution_Test(){

        Asset asset = new asset();
        asset.Name = 'Name-Asset-XXXX';
        Insert asset;
        
        WebserviceTelematicsData__c ws = getWebserviceTelematicsData();
        insert ws;
        
        Alerte__c a = getAlerte(asset, 'Tension batterie basse');
		a.DateTime_Alerte__c = DateTime.now();        
        INSERT  a;
        
        Test.setMock(HttpCalloutMock.class, new MockBatteryEvolutionHttpResponse());
        test.startTest();
        List<GraphController.LineChartVar> myLineChartVarList = new List<GraphController.LineChartVar>();
        myLineChartVarList.add(new GraphController.LineChartVar('', 1));
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), 'live'); 
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), '12h'); 
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), '6h'); 
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), '3h'); 
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), ''); 
        test.stopTest();
    }
    
    @isTest static  void LB24GraphEvolution_Test(){

        Asset asset = new asset();
        asset.Name = 'Name-Asset-XXXX';
        Insert asset;
        
        WebserviceTelematicsData__c ws = getWebserviceTelematicsData();
        insert ws;
        
        Alerte__c a = getAlerte(asset, 'Tension batterie basse');
        a.Type_De_Batterie__c = '24 Volts';
        INSERT  a;
        
        Test.setMock(HttpCalloutMock.class, new MockBatteryEvolutionHttpResponse());
        test.startTest();
        List<GraphController.LineChartVar> myLineChartVarList = new List<GraphController.LineChartVar>();
        myLineChartVarList.add(new GraphController.LineChartVar('', 1));
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), 'live'); 
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), '12h'); 
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), '6h'); 
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), '3h'); 
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), ''); 
        test.stopTest();
    }
    
    @isTest static  void VMGraphEvolution_Test(){

        Asset asset = new asset();
        asset.Name = 'Name-Asset-XXXX';
        Insert asset;
        
        WebserviceTelematicsData__c ws = getWebserviceTelematicsData();
        insert ws;
        
        Alerte__c a = getAlerte(asset, 'Voyant moteur');
        INSERT  a;
        
        Test.setMock(HttpCalloutMock.class, new MockVoyantMoteurEvolutionHttpResponse());
        test.startTest();
        //List<GraphController.LineChartVar> myLineChartVarList = new List<GraphController.LineChartVar>();
        //myLineChartVarList.add(new GraphController.LineChartVar('', 1));
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), ''); 
        test.stopTest();
    }
    
    @isTest static  void CBPGraphEvolution_Test(){

        Asset asset = new asset();
        asset.Name = 'Name-Asset-XXXX';
        Insert asset;
        
        WebserviceTelematicsData__c ws = getWebserviceTelematicsData();
        insert ws;
        
        Alerte__c a = getAlerte(asset, 'Coupure basse pression');
        a.Code_Alarme__c = 'A01/P01';
        INSERT  a;
        
        Test.setMock(HttpCalloutMock.class, new MockVoyantMoteurEvolutionHttpResponse());
        test.startTest();
        GraphController.NewRefreshLowBatteryEvolution(string.valueof(a.id), ''); 
        test.stopTest();
    }

    
    @isTest static void dateDiff_Test(){
        DateTime startDate = DateTime.now();
        PRG_AlertGoogleController.dateDifference(startDate.addDays(-1));
        PRG_AlertGoogleController.dateDifference(startDate.addHours(-1));
        PRG_AlertGoogleController.dateDifference(startDate.addMinutes(-10));
            
    	//PRG_AlertGoogleController.dateDifference(startDate);
    }

    static Alerte__c getAlerte(Asset asset, String typeAlerte){
        Alerte__c a =new Alerte__c();
        a.Type_Alerte__c = typeAlerte;        
        a.Statut_du_vehicule__c = 'MOTEUR_TOURNANT_VEHICULE_ROULANT';
        a.Parc__c = asset.id;
        a.Parc_Id__c ='XXXXXX';
        a.Location_Latitude__c  =10.0;
        a.Location_Longitude__c = 10.0 ;        
        return a;
    }
    
    static WebserviceTelematicsData__c getWebserviceTelematicsData(){
        WebserviceTelematicsData__c ws = new WebserviceTelematicsData__c();
        ws.name = 'sandbox-infra-dev';
        ws.Endpoint__c= 'https://data-iot-mcs-5unavwdk4q-ew.a.run.app/secured/basic';
        ws.Authorization__c= 'Basic VXNlclJlc3Q6akFaU1dINFJoUzNrZU1qRThNS055WjZFbWdNWDlXaFo='; 
        ws.Environnement__c= 'dev'; 
        ws.Sandbox__c= 'infra';
        return ws;
    }
        
}